DECL|function|pthread_exit
DECL|function|pthread_getspecific
DECL|function|pthread_key_create
DECL|function|pthread_key_delete
DECL|function|pthread_setspecific
DECL|macro|PTHREAD_H
DECL|macro|PTHREAD_MUTEX_RECURSIVE
DECL|macro|WIN32_LEAN_AND_MEAN
DECL|macro|pthread_equal
DECL|macro|pthread_join
DECL|macro|pthread_mutex_destroy
DECL|macro|pthread_mutex_init
DECL|macro|pthread_mutex_lock
DECL|macro|pthread_mutex_t
DECL|macro|pthread_mutex_unlock
DECL|macro|pthread_mutexattr_destroy
DECL|macro|pthread_mutexattr_init
DECL|macro|pthread_mutexattr_settype
DECL|member|arg
DECL|member|continue_broadcast
DECL|member|handle
DECL|member|sema
DECL|member|start_routine
DECL|member|tid
DECL|member|waiters
DECL|member|waiters_lock
DECL|member|was_broadcast
DECL|typedef|pthread_cond_t
DECL|typedef|pthread_key_t
DECL|typedef|pthread_mutexattr_t
DECL|typedef|pthread_t
