DECL|function|blk_SHA1_Block
DECL|function|blk_SHA1_Final
DECL|function|blk_SHA1_Init
DECL|function|blk_SHA1_Update
DECL|macro|SHA_ASM
DECL|macro|SHA_MIX
DECL|macro|SHA_ROL
DECL|macro|SHA_ROL
DECL|macro|SHA_ROR
DECL|macro|SHA_ROR
DECL|macro|SHA_ROT
DECL|macro|SHA_ROUND
DECL|macro|SHA_SRC
DECL|macro|T_0_15
DECL|macro|T_16_19
DECL|macro|T_20_39
DECL|macro|T_40_59
DECL|macro|T_60_79
DECL|macro|W
DECL|macro|get_be32
DECL|macro|get_be32
DECL|macro|put_be32
DECL|macro|put_be32
DECL|macro|setW
DECL|macro|setW
DECL|macro|setW
