DECL|function|alias_lookup
DECL|function|split_cmdline
DECL|function|split_cmdline_strerror
DECL|macro|SPLIT_CMDLINE_BAD_ENDING
DECL|macro|SPLIT_CMDLINE_UNCLOSED_QUOTE
DECL|variable|split_cmdline_errors
