DECL|function|apply_chunk
DECL|function|apply_fragment
DECL|function|apply_patch
DECL|function|apply_single_patch
DECL|function|find_header
DECL|function|find_name
DECL|function|gitdiff_copydst
DECL|function|gitdiff_copysrc
DECL|function|gitdiff_delete
DECL|function|gitdiff_hdrend
DECL|function|gitdiff_newfile
DECL|function|gitdiff_newmode
DECL|function|gitdiff_newname
DECL|function|gitdiff_oldmode
DECL|function|gitdiff_oldname
DECL|function|gitdiff_renamedst
DECL|function|gitdiff_renamesrc
DECL|function|gitdiff_similarity
DECL|function|is_dev_null
DECL|function|linelen
DECL|function|main
DECL|function|parse_fragment_header
DECL|function|parse_git_header
DECL|function|parse_num
DECL|function|parse_traditional_patch
DECL|function|read_patch_file
DECL|macro|CHUNKSIZE
DECL|macro|SLOP
DECL|variable|apply_usage
DECL|variable|def_name
DECL|variable|is_copy
DECL|variable|is_delete
DECL|variable|is_new
DECL|variable|is_rename
DECL|variable|linenr
DECL|variable|merge_patch
DECL|variable|new_mode
DECL|variable|new_name
DECL|variable|old_mode
DECL|variable|old_name
