DECL|function|apply_patch
DECL|function|apply_patch_list
DECL|function|check_patch
DECL|function|find_header
DECL|function|find_name
DECL|function|gitdiff_copydst
DECL|function|gitdiff_copysrc
DECL|function|gitdiff_delete
DECL|function|gitdiff_hdrend
DECL|function|gitdiff_newfile
DECL|function|gitdiff_newmode
DECL|function|gitdiff_newname
DECL|function|gitdiff_oldmode
DECL|function|gitdiff_oldname
DECL|function|gitdiff_renamedst
DECL|function|gitdiff_renamesrc
DECL|function|gitdiff_similarity
DECL|function|gitdiff_unrecognized
DECL|function|gitdiff_verify_name
DECL|function|is_dev_null
DECL|function|linelen
DECL|function|main
DECL|function|name_terminate
DECL|function|parse_chunk
DECL|function|parse_fragment
DECL|function|parse_fragment_header
DECL|function|parse_git_header
DECL|function|parse_num
DECL|function|parse_range
DECL|function|parse_single_patch
DECL|function|parse_traditional_patch
DECL|function|patch_stats
DECL|function|read_patch_file
DECL|function|show_stats
DECL|macro|CHUNKSIZE
DECL|macro|SLOP
DECL|macro|TERM_EXIST
DECL|macro|TERM_SPACE
DECL|macro|TERM_TAB
DECL|member|fragments
DECL|member|is_copy
DECL|member|is_delete
DECL|member|is_new
DECL|member|is_rename
DECL|member|lines_added
DECL|member|lines_deleted
DECL|member|new_mode
DECL|member|new_name
DECL|member|newlines
DECL|member|newpos
DECL|member|next
DECL|member|next
DECL|member|old_mode
DECL|member|old_name
DECL|member|oldlines
DECL|member|oldpos
DECL|member|patch
DECL|member|size
DECL|struct|fragment
DECL|struct|patch
DECL|variable|apply_usage
DECL|variable|check
DECL|variable|def_name
DECL|variable|diffstat
DECL|variable|linenr
DECL|variable|max_change
DECL|variable|max_len
DECL|variable|merge_patch
DECL|variable|minuses
DECL|variable|pluses
