DECL|function|get_path_prefix
DECL|function|git_tar_config
DECL|function|strbuf_append_ext_header
DECL|function|ustar_header_chksum
DECL|function|write_blocked
DECL|function|write_global_extended_header
DECL|function|write_if_needed
DECL|function|write_tar_archive
DECL|function|write_tar_entry
DECL|function|write_trailer
DECL|macro|BLOCKSIZE
DECL|macro|RECORDSIZE
DECL|variable|block
DECL|variable|offset
DECL|variable|tar_umask
