DECL|macro|ARCHIVE_H
DECL|macro|MAX_ARGS
DECL|macro|MAX_EXTRA_ARGS
DECL|member|base
DECL|member|baselen
DECL|member|commit
DECL|member|commit_sha1
DECL|member|compression_level
DECL|member|flags
DECL|member|name
DECL|member|pathspec
DECL|member|time
DECL|member|tree
DECL|member|verbose
DECL|member|write_archive
DECL|struct|archiver
DECL|struct|archiver_args
DECL|typedef|write_archive_entry_fn_t
DECL|typedef|write_archive_fn_t
