DECL|macro|ARCHIVER_WANT_COMPRESSION_LEVELS
DECL|macro|ARCHIVE_H
DECL|member|base
DECL|member|baselen
DECL|member|commit
DECL|member|commit_sha1
DECL|member|compression_level
DECL|member|data
DECL|member|flags
DECL|member|name
DECL|member|pathspec
DECL|member|time
DECL|member|tree
DECL|member|verbose
DECL|member|worktree_attributes
DECL|member|write_archive
DECL|struct|archiver
DECL|struct|archiver_args
DECL|typedef|write_archive_entry_fn_t
