DECL|function|copy_le16
DECL|function|copy_le32
DECL|function|dos_time
DECL|function|write_zip_archive
DECL|function|write_zip_entry
DECL|function|write_zip_trailer
DECL|function|zlib_deflate
DECL|macro|ZIP_DIRECTORY_MIN_SIZE
DECL|macro|ZIP_DIR_HEADER_SIZE
DECL|macro|ZIP_DIR_TRAILER_SIZE
DECL|macro|ZIP_LOCAL_HEADER_SIZE
DECL|member|_end
DECL|member|_end
DECL|member|_end
DECL|member|attr1
DECL|member|attr2
DECL|member|comment_length
DECL|member|comment_length
DECL|member|compressed_size
DECL|member|compressed_size
DECL|member|compression_method
DECL|member|compression_method
DECL|member|crc32
DECL|member|crc32
DECL|member|creator_version
DECL|member|directory_start_disk
DECL|member|disk
DECL|member|disk
DECL|member|entries
DECL|member|entries_on_this_disk
DECL|member|extra_length
DECL|member|extra_length
DECL|member|filename_length
DECL|member|filename_length
DECL|member|flags
DECL|member|flags
DECL|member|magic
DECL|member|magic
DECL|member|magic
DECL|member|mdate
DECL|member|mdate
DECL|member|mtime
DECL|member|mtime
DECL|member|offset
DECL|member|offset
DECL|member|size
DECL|member|size
DECL|member|size
DECL|member|version
DECL|member|version
DECL|struct|zip_dir_header
DECL|struct|zip_dir_trailer
DECL|struct|zip_local_header
DECL|variable|zip_date
DECL|variable|zip_dir
DECL|variable|zip_dir_entries
DECL|variable|zip_dir_offset
DECL|variable|zip_dir_size
DECL|variable|zip_offset
DECL|variable|zip_time
