DECL|macro|ARCHIVE_H
DECL|macro|MAX_ARGS
DECL|macro|MAX_EXTRA_ARGS
DECL|member|args
DECL|member|base
DECL|member|commit_sha1
DECL|member|extra
DECL|member|name
DECL|member|parse_extra
DECL|member|pathspec
DECL|member|time
DECL|member|tree
DECL|member|write_archive
DECL|struct|archiver
DECL|struct|archiver_args
DECL|typedef|parse_extra_args_fn_t
DECL|typedef|write_archive_fn_t
