DECL|function|argv_array_clear
DECL|function|argv_array_init
DECL|function|argv_array_push
DECL|function|argv_array_push_nodup
DECL|function|argv_array_pushf
DECL|variable|empty_argv
DECL|variable|empty_argv_storage
