DECL|enumerator|GIT_ATTR_CHECKIN
DECL|enumerator|GIT_ATTR_CHECKOUT
DECL|enumerator|GIT_ATTR_INDEX
DECL|enum|git_attr_direction
DECL|macro|ATTR_FALSE
DECL|macro|ATTR_H
DECL|macro|ATTR_TRUE
DECL|macro|ATTR_UNSET
DECL|member|attr
DECL|member|value
DECL|struct|git_attr_check
