DECL|function|bootstrap_attr_stack
DECL|function|debug_info
DECL|function|debug_set
DECL|function|drop_attr_stack
DECL|function|fill
DECL|function|fill_one
DECL|function|free_attr_elem
DECL|function|git_attr
DECL|function|git_attr_internal
DECL|function|git_attr_set_direction
DECL|function|git_checkattr
DECL|function|handle_attr_line
DECL|function|hash_name
DECL|function|invalid_attr_name
DECL|function|macroexpand
DECL|function|parse_attr
DECL|function|parse_attr_line
DECL|function|path_matches
DECL|function|prepare_attr_stack
DECL|function|read_attr
DECL|function|read_attr_from_array
DECL|function|read_attr_from_file
DECL|function|read_attr_from_index
DECL|function|read_index_data
DECL|macro|ATTR__FALSE
DECL|macro|ATTR__TRUE
DECL|macro|ATTR__UNKNOWN
DECL|macro|ATTR__UNSET
DECL|macro|DEBUG_ATTR
DECL|macro|HASHSIZE
DECL|macro|NO_THE_INDEX_COMPATIBILITY_MACROS
DECL|macro|debug_pop
DECL|macro|debug_pop
DECL|macro|debug_push
DECL|macro|debug_push
DECL|macro|debug_set
DECL|member|alloc
DECL|member|attr
DECL|member|attr
DECL|member|attr_nr
DECL|member|attrs
DECL|member|h
DECL|member|is_macro
DECL|member|name
DECL|member|next
DECL|member|num_attr
DECL|member|num_matches
DECL|member|origin
DECL|member|pattern
DECL|member|prev
DECL|member|setto
DECL|member|state
DECL|member|u
DECL|struct|attr_stack
DECL|struct|attr_state
DECL|struct|git_attr
DECL|struct|match_attr
DECL|variable|attr_nr
DECL|variable|attr_stack
DECL|variable|blank
DECL|variable|builtin_attr
DECL|variable|check_all_attr
DECL|variable|direction
DECL|variable|git_attr__false
DECL|variable|git_attr__true
DECL|variable|git_attr__unknown
DECL|variable|git_attr_hash
DECL|variable|use_index
