DECL|function|bootstrap_attr_stack
DECL|function|debug_info
DECL|function|debug_set
DECL|function|fill
DECL|function|free_attr_elem
DECL|function|git_attr
DECL|function|git_checkattr
DECL|function|hash_name
DECL|function|macroexpand
DECL|function|parse_attr_line
DECL|function|path_matches
DECL|function|prepare_attr_stack
DECL|function|read_attr_from_array
DECL|function|read_attr_from_file
DECL|macro|DEBUG_ATTR
DECL|macro|HASHSIZE
DECL|macro|debug_pop
DECL|macro|debug_pop
DECL|macro|debug_push
DECL|macro|debug_push
DECL|macro|debug_set
DECL|member|attr
DECL|member|attr
DECL|member|attr_nr
DECL|member|attrs
DECL|member|h
DECL|member|is_macro
DECL|member|name
DECL|member|next
DECL|member|num_attr
DECL|member|num_matches
DECL|member|origin
DECL|member|pattern
DECL|member|prev
DECL|member|state
DECL|member|u
DECL|member|unset
DECL|struct|attr_stack
DECL|struct|attr_state
DECL|struct|git_attr
DECL|struct|match_attr
DECL|variable|attr_nr
DECL|variable|attr_stack
DECL|variable|blank
DECL|variable|builtin_attr
DECL|variable|check_all_attr
DECL|variable|git_attr_hash
