DECL|macro|BISECT_H
DECL|macro|BISECT_SHOW_ALL
DECL|macro|REV_LIST_QUIET
DECL|member|flags
DECL|member|hdr_termination
DECL|member|header_prefix
DECL|member|revs
DECL|member|show_timestamp
DECL|struct|rev_list_info
