DECL|function|argv_array_push
DECL|function|argv_array_push_sha1
DECL|function|best_bisection
DECL|function|best_bisection_sorted
DECL|function|bisect_checkout
DECL|function|bisect_common
DECL|function|bisect_next_all
DECL|function|bisect_rev_setup
DECL|function|check_ancestors
DECL|function|check_good_are_ancestors_of_bad
DECL|function|check_merge_bases
DECL|function|clear_distance
DECL|function|compare_commit_dist
DECL|function|count_distance
DECL|function|count_interesting_parents
DECL|function|do_find_bisection
DECL|function|exit_if_skipped_commits
DECL|function|filter_skipped
DECL|function|find_bisection
DECL|function|get_bad_and_good_commits
DECL|function|get_commit_reference
DECL|function|get_prn
DECL|function|halfway
DECL|function|handle_bad_merge_base
DECL|function|handle_skipped_merge_base
DECL|function|is_expected_rev
DECL|function|join_sha1_array_hex
DECL|function|managed_skipped
DECL|function|mark_expected_rev
DECL|function|read_bisect_paths
DECL|function|read_bisect_refs
DECL|function|register_ref
DECL|function|show_diff_tree
DECL|function|show_list
DECL|function|skip_away
DECL|function|sqrti
DECL|function|weight
DECL|function|weight_set
DECL|macro|COUNTED
DECL|macro|DEBUG_BISECT
DECL|macro|PRN_MODULO
DECL|macro|show_list
DECL|member|argv
DECL|member|argv_alloc
DECL|member|argv_nr
DECL|member|commit
DECL|member|distance
DECL|struct|argv_array
DECL|struct|commit_dist
DECL|variable|argv_checkout
DECL|variable|argv_show_branch
DECL|variable|argv_update_ref
DECL|variable|current_bad_sha1
DECL|variable|good_revs
DECL|variable|skipped_revs
