DECL|function|best_bisection
DECL|function|best_bisection_sorted
DECL|function|bisect_next_vars
DECL|function|bisect_rev_setup
DECL|function|clear_distance
DECL|function|compare_commit_dist
DECL|function|count_distance
DECL|function|count_interesting_parents
DECL|function|do_find_bisection
DECL|function|filter_skipped
DECL|function|find_bisection
DECL|function|halfway
DECL|function|lookup_skipped
DECL|function|prepare_skipped
DECL|function|read_bisect_paths
DECL|function|read_bisect_refs
DECL|function|register_ref
DECL|function|show_list
DECL|function|skipcmp
DECL|function|skipped_sha1_access
DECL|function|weight
DECL|function|weight_set
DECL|macro|COUNTED
DECL|macro|DEBUG_BISECT
DECL|macro|show_list
DECL|member|commit
DECL|member|distance
DECL|struct|commit_dist
DECL|variable|rev_argv
DECL|variable|rev_argv_alloc
DECL|variable|rev_argv_nr
DECL|variable|skipped_sha1
DECL|variable|skipped_sha1_alloc
DECL|variable|skipped_sha1_nr
