DECL|function|alloc_line_map
DECL|function|compare_tree_path
DECL|function|fill_line_map
DECL|function|fill_util_info
DECL|function|find_orig_linenum
DECL|function|find_rename
DECL|function|format_time
DECL|function|free_patch
DECL|function|get_blob
DECL|function|get_blob_sha1
DECL|function|get_blob_sha1_internal
DECL|function|get_commit_info
DECL|function|get_patch
DECL|function|get_util
DECL|function|init_first_commit
DECL|function|lineno_width
DECL|function|main
DECL|function|map_line
DECL|function|print_map
DECL|function|print_patch
DECL|function|process_commits
DECL|function|process_u0_diff
DECL|function|read_ancestry
DECL|function|same_tree_as_empty_path
DECL|function|simplify_commit
DECL|function|topo_getter
DECL|function|topo_setter
DECL|macro|DEBUG
DECL|member|author
DECL|member|author_mail
DECL|member|author_time
DECL|member|author_tz
DECL|member|buf
DECL|member|chunks
DECL|member|len1
DECL|member|len2
DECL|member|line_map
DECL|member|num
DECL|member|num_lines
DECL|member|off1
DECL|member|off2
DECL|member|pathname
DECL|member|ret
DECL|member|sha1
DECL|member|size
DECL|member|topo_data
DECL|member|xm
DECL|struct|blame_diff_state
DECL|struct|chunk
DECL|struct|commit_info
DECL|struct|patch
DECL|struct|util_info
DECL|variable|blame_contents
DECL|variable|blame_file
DECL|variable|blame_len
DECL|variable|blame_lines
DECL|variable|blame_usage
DECL|variable|blob_sha1
DECL|variable|num_blame_lines
DECL|variable|num_commits
DECL|variable|num_get_patch
DECL|variable|patch_time
