DECL|function|alloc_line_map
DECL|function|copy_line_map
DECL|function|fill_line_map
DECL|function|fill_util_info
DECL|function|free_patch
DECL|function|get_blob
DECL|function|get_blob_sha1
DECL|function|get_blob_sha1_internal
DECL|function|get_commit_list
DECL|function|get_patch
DECL|function|main
DECL|function|map_line
DECL|function|print_patch
DECL|function|process_commits
DECL|macro|DEBUG
DECL|macro|SEEN
DECL|member|buf
DECL|member|chunks
DECL|member|len1
DECL|member|len2
DECL|member|line_map
DECL|member|num
DECL|member|num_lines
DECL|member|off1
DECL|member|off2
DECL|member|sha1
DECL|member|size
DECL|struct|chunk
DECL|struct|patch
DECL|struct|util_info
DECL|variable|blame_lines
DECL|variable|blob_sha1
DECL|variable|num_blame_lines
DECL|variable|num_commits
DECL|variable|num_get_patch
