DECL|function|create_branch
DECL|function|find_tracked_branch
DECL|function|install_branch_config
DECL|function|remove_branch_state
DECL|function|setup_tracking
DECL|function|should_setup_rebase
DECL|member|matches
DECL|member|remote
DECL|member|spec
DECL|member|src
DECL|struct|tracking
