DECL|function|check_tracking_branch
DECL|function|create_branch
DECL|function|find_tracked_branch
DECL|function|install_branch_config
DECL|function|read_branch_desc
DECL|function|remove_branch_state
DECL|function|setup_tracking
DECL|function|should_setup_rebase
DECL|function|validate_new_branchname
DECL|function|validate_remote_tracking_branch
DECL|member|matches
DECL|member|remote
DECL|member|spec
DECL|member|src
DECL|struct|tracking
DECL|variable|upstream_advice
DECL|variable|upstream_missing
DECL|variable|upstream_not_branch
