DECL|function|add
DECL|function|add_branch_for_removal
DECL|function|cmd_remote
DECL|function|config_read_branches
DECL|function|fetch_remote
DECL|function|get_one_entry
DECL|function|get_ref_states
DECL|function|handle_one_branch
DECL|function|opt_parse_track
DECL|function|postfixcmp
DECL|function|read_branches
DECL|function|remove_branches
DECL|function|rm
DECL|function|show_all
DECL|function|show_list
DECL|function|show_or_prune
DECL|function|skip_prefix
DECL|function|update
DECL|function|update_one
DECL|member|branches
DECL|member|merge
DECL|member|new
DECL|member|prefix
DECL|member|remote
DECL|member|remote
DECL|member|remote_prefix
DECL|member|stale
DECL|member|tracked
DECL|struct|branch_info
DECL|struct|branches_for_remote
DECL|struct|ref_states
DECL|variable|branch_list
DECL|variable|builtin_remote_usage
DECL|variable|verbose
