DECL|enumerator|COLOR_BRANCH_CURRENT
DECL|enumerator|COLOR_BRANCH_LOCAL
DECL|enumerator|COLOR_BRANCH_PLAIN
DECL|enumerator|COLOR_BRANCH_REMOTE
DECL|enumerator|COLOR_BRANCH_RESET
DECL|enumerator|NO_FILTER
DECL|enumerator|SHOW_MERGED
DECL|enumerator|SHOW_NOT_MERGED
DECL|enum|color_branch
DECL|enum|merge_filter
DECL|function|append_ref
DECL|function|branch_get_color
DECL|function|calc_maxwidth
DECL|function|cmd_branch
DECL|function|delete_branches
DECL|function|fill_tracking_info
DECL|function|free_ref_list
DECL|function|git_branch_config
DECL|function|has_commit
DECL|function|matches_merge_filter
DECL|function|opt_parse_merge_filter
DECL|function|opt_parse_with_commit
DECL|function|parse_branch_color_slot
DECL|function|print_ref_item
DECL|function|print_ref_list
DECL|function|ref_cmp
DECL|function|rename_branch
DECL|macro|REF_LOCAL_BRANCH
DECL|macro|REF_REMOTE_BRANCH
DECL|member|alloc
DECL|member|commit
DECL|member|index
DECL|member|kind
DECL|member|kinds
DECL|member|list
DECL|member|maxwidth
DECL|member|name
DECL|member|revs
DECL|member|with_commit
DECL|struct|ref_item
DECL|struct|ref_list
DECL|variable|branch_colors
DECL|variable|branch_use_color
DECL|variable|builtin_branch_usage
DECL|variable|head
DECL|variable|head_sha1
DECL|variable|merge_filter
DECL|variable|merge_filter_ref
