DECL|function|add_object_entry
DECL|function|add_pbase_object
DECL|function|add_preferred_base
DECL|function|add_preferred_base_object
DECL|function|check_delta_limit
DECL|function|check_inflate
DECL|function|check_object
DECL|function|check_pbase_path
DECL|function|cmd_pack_objects
DECL|function|cmp_offset
DECL|function|create_final_object_list
DECL|function|create_sorted_list
DECL|function|delta_against
DECL|function|done_pbase_path_pos
DECL|function|encode_header
DECL|function|find_deltas
DECL|function|find_packed_object
DECL|function|find_packed_object_name
DECL|function|find_packed_object_size
DECL|function|get_object_details
DECL|function|get_object_list
DECL|function|git_pack_config
DECL|function|locate_object_entry
DECL|function|locate_object_entry_hash
DECL|function|name_cmp_len
DECL|function|name_hash
DECL|function|pack_revindex_ix
DECL|function|pbase_tree_cache_ix
DECL|function|pbase_tree_cache_ix_incr
DECL|function|pbase_tree_get
DECL|function|pbase_tree_put
DECL|function|prepare_pack
DECL|function|prepare_pack_ix
DECL|function|prepare_pack_revindex
DECL|function|progress_interval
DECL|function|read_object_list_from_stdin
DECL|function|rehash_objects
DECL|function|reuse_cached_pack
DECL|function|revalidate_loose_object
DECL|function|setup_progress_signal
DECL|function|sha1_sort
DECL|function|show_commit
DECL|function|show_edge
DECL|function|show_object
DECL|function|sort_comparator
DECL|function|try_delta
DECL|function|type_size_sort
DECL|function|write_index_file
DECL|function|write_object
DECL|function|write_one
DECL|function|write_pack_file
DECL|macro|in_pack_header_size
DECL|member|data
DECL|member|delta
DECL|member|delta_child
DECL|member|delta_limit
DECL|member|delta_sibling
DECL|member|delta_size
DECL|member|depth
DECL|member|entry
DECL|member|hash
DECL|member|in_pack
DECL|member|in_pack_offset
DECL|member|in_pack_type
DECL|member|index
DECL|member|next
DECL|member|nr
DECL|member|offset
DECL|member|offset
DECL|member|p
DECL|member|pcache
DECL|member|preferred_base
DECL|member|ref
DECL|member|revindex
DECL|member|sha1
DECL|member|sha1
DECL|member|size
DECL|member|temporary
DECL|member|tree_data
DECL|member|tree_size
DECL|member|type
DECL|struct|object_entry
DECL|struct|pack_revindex
DECL|struct|pbase_tree
DECL|struct|pbase_tree_cache
DECL|struct|revindex_entry
DECL|struct|unpacked
DECL|typedef|entry_sort_t
DECL|variable|allow_ofs_delta
DECL|variable|base_name
DECL|variable|current_sort
DECL|variable|done_pbase_paths
DECL|variable|done_pbase_paths_alloc
DECL|variable|done_pbase_paths_num
DECL|variable|incremental
DECL|variable|local
DECL|variable|no_reuse_delta
DECL|variable|non_empty
DECL|variable|nr_alloc
DECL|variable|nr_objects
DECL|variable|nr_result
DECL|variable|num_preferred_base
DECL|variable|object_ix
DECL|variable|object_ix_hashsz
DECL|variable|object_list_sha1
DECL|variable|objects
DECL|variable|pack_file_sha1
DECL|variable|pack_revindex
DECL|variable|pack_revindex_hashsz
DECL|variable|pack_to_stdout
DECL|variable|pack_usage
DECL|variable|pbase_tree
DECL|variable|pbase_tree_cache
DECL|variable|progress
DECL|variable|progress_update
DECL|variable|reused
DECL|variable|reused_delta
DECL|variable|sorted_by_sha
DECL|variable|sorted_by_type
DECL|variable|window
DECL|variable|written
DECL|variable|written_delta
