DECL|function|cmd_reflog
DECL|function|cmd_reflog_expire
DECL|function|expire_reflog
DECL|function|expire_reflog_ent
DECL|function|keep_entry
DECL|member|dry_run
DECL|member|expire_total
DECL|member|expire_total
DECL|member|expire_unreachable
DECL|member|expire_unreachable
DECL|member|newlog
DECL|member|ref
DECL|member|ref_commit
DECL|struct|cmd_reflog_expire_cb
DECL|struct|expire_reflog_cb
DECL|variable|reflog_expire_usage
DECL|variable|reflog_usage
