DECL|enumerator|T_BOOL
DECL|enumerator|T_INT
DECL|enumerator|T_RAW
DECL|function|cmd_repo_config
DECL|function|get_value
DECL|function|show_all_config
DECL|function|show_config
DECL|variable|do_all
DECL|variable|do_not_match
DECL|variable|git_config_set_usage
DECL|variable|key
DECL|variable|key_regexp
DECL|variable|regexp
DECL|variable|seen
DECL|variable|show_keys
DECL|variable|type
DECL|variable|use_key_regexp
