DECL|function|cmd_notes
DECL|function|commit_notes
DECL|function|copy_note_for_rewrite
DECL|function|create_note
DECL|function|finish_copy_notes_for_rewrite
DECL|function|init_copy_notes_for_rewrite
DECL|function|list_each_note
DECL|function|notes_copy_from_stdin
DECL|function|notes_rewrite_config
DECL|function|parse_combine_notes_fn
DECL|function|parse_file_arg
DECL|function|parse_msg_arg
DECL|function|parse_reedit_arg
DECL|function|parse_reuse_arg
DECL|function|write_commented_object
DECL|function|write_note_data
DECL|member|buf
DECL|member|given
DECL|member|use_editor
DECL|struct|msg_arg
DECL|variable|git_notes_usage
DECL|variable|note_template
