DECL|enumerator|HARD
DECL|enumerator|MIXED
DECL|enumerator|NONE
DECL|enumerator|SOFT
DECL|enum|reset_type
DECL|function|args_to_str
DECL|function|cmd_reset
DECL|function|is_merge
DECL|function|prepend_reflog_action
DECL|function|print_new_head_line
DECL|function|read_from_tree
DECL|function|reset_index_file
DECL|function|unmerged_files
DECL|function|update_index_from_diff
DECL|function|update_index_refresh
DECL|member|exit_code
DECL|member|index_fd
DECL|member|lock
DECL|struct|update_cb_data
DECL|variable|builtin_reset_usage
DECL|variable|reset_type_names
