DECL|function|append_fetch_head
DECL|function|cmd_fetch__tool
DECL|function|expand_refs_wildcard
DECL|function|fetch_native_store
DECL|function|find_local_name
DECL|function|parse_reflist
DECL|function|remove_keep
DECL|function|remove_keep_on_signal
DECL|function|show_new
DECL|function|update_local_ref
DECL|function|update_ref
DECL|variable|keep
