DECL|function|cmd_rev_parse
DECL|function|is_rev_argument
DECL|function|show
DECL|function|show_datestring
DECL|function|show_default
DECL|function|show_file
DECL|function|show_flag
DECL|function|show_reference
DECL|function|show_rev
DECL|function|try_difference
DECL|macro|DO_FLAGS
DECL|macro|DO_NONFLAGS
DECL|macro|DO_NOREV
DECL|macro|DO_REVS
DECL|macro|NORMAL
DECL|macro|REVERSED
DECL|variable|abbrev
DECL|variable|def
DECL|variable|filter
DECL|variable|output_sq
DECL|variable|revs_count
DECL|variable|show_type
DECL|variable|symbolic
