DECL|function|cmd_reflog
DECL|function|cmd_reflog_delete
DECL|function|cmd_reflog_expire
DECL|function|collect_reflog
DECL|function|commit_is_complete
DECL|function|count_reflog_ent
DECL|function|expire_reflog
DECL|function|expire_reflog_ent
DECL|function|find_cfg_ent
DECL|function|keep_entry
DECL|function|mark_reachable
DECL|function|parse_expire_cfg_value
DECL|function|reflog_expire_config
DECL|function|set_reflog_expiry_param
DECL|function|tree_is_complete
DECL|function|unreachable
DECL|macro|EXPIRE_TOTAL
DECL|macro|EXPIRE_UNREACH
DECL|macro|INCOMPLETE
DECL|macro|REACHABLE
DECL|macro|STUDYING
DECL|member|alloc
DECL|member|cmd
DECL|member|dry_run
DECL|member|e
DECL|member|expire_total
DECL|member|expire_total
DECL|member|expire_unreachable
DECL|member|expire_unreachable
DECL|member|last_kept_sha1
DECL|member|len
DECL|member|newlog
DECL|member|next
DECL|member|nr
DECL|member|pattern
DECL|member|recno
DECL|member|ref
DECL|member|ref_commit
DECL|member|reflog
DECL|member|revs
DECL|member|rewrite
DECL|member|sha1
DECL|member|stalefix
DECL|member|updateref
DECL|member|verbose
DECL|struct|cmd_reflog_expire_cb
DECL|struct|collect_reflog_cb
DECL|struct|collected_reflog
DECL|struct|expire_reflog_cb
DECL|struct|reflog_expire_cfg
DECL|variable|default_reflog_expire
DECL|variable|default_reflog_expire_unreachable
DECL|variable|reflog_delete_usage
DECL|variable|reflog_expire_cfg
DECL|variable|reflog_expire_cfg_tail
DECL|variable|reflog_expire_usage
DECL|variable|reflog_usage
