DECL|function|checkout_all
DECL|function|checkout_file
DECL|function|cmd_checkout_index
DECL|function|write_tempfile_record
DECL|macro|CHECKOUT_ALL
DECL|variable|checkout_cache_usage
DECL|variable|checkout_stage
DECL|variable|line_termination
DECL|variable|lock_file
DECL|variable|state
DECL|variable|to_tempfile
DECL|variable|topath
