DECL|function|add_blame_entry
DECL|function|assign_blame
DECL|function|blame_chunk
DECL|function|blame_overlap
DECL|function|cmd_pickaxe
DECL|function|cmp_suspect
DECL|function|coalesce
DECL|function|compare_buffer
DECL|function|copy_split_if_better
DECL|function|decref_split
DECL|function|dup_entry
DECL|function|emit_other
DECL|function|emit_porcelain
DECL|function|ent_score
DECL|function|fill_blob_sha1
DECL|function|find_alignment
DECL|function|find_copy_in_blob
DECL|function|find_copy_in_parent
DECL|function|find_last_in_target
DECL|function|find_move_in_parent
DECL|function|find_origin
DECL|function|find_rename
DECL|function|format_time
DECL|function|free_patch
DECL|function|get_ac_line
DECL|function|get_commit_info
DECL|function|get_origin
DECL|function|get_patch
DECL|function|has_path_in_work_tree
DECL|function|lineno_width
DECL|function|nth_line
DECL|function|origin_decref
DECL|function|origin_incref
DECL|function|output
DECL|function|parse_score
DECL|function|pass_blame
DECL|function|pass_blame_to_parent
DECL|function|prepare_lines
DECL|function|process_u_diff
DECL|function|read_ancestry
DECL|function|sanity_check_refcnt
DECL|function|split_blame
DECL|function|split_overlap
DECL|macro|BLAME_DEFAULT_COPY_SCORE
DECL|macro|BLAME_DEFAULT_MOVE_SCORE
DECL|macro|DEBUG
DECL|macro|MAXPARENT
DECL|macro|METAINFO_SHOWN
DECL|macro|MORE_THAN_ONE_PATH
DECL|macro|OUTPUT_ANNOTATE_COMPAT
DECL|macro|OUTPUT_LONG_OBJECT_NAME
DECL|macro|OUTPUT_PORCELAIN
DECL|macro|OUTPUT_RAW_TIMESTAMP
DECL|macro|OUTPUT_SHOW_NAME
DECL|macro|OUTPUT_SHOW_NUMBER
DECL|macro|OUTPUT_SHOW_SCORE
DECL|macro|PICKAXE_BLAME_COPY
DECL|macro|PICKAXE_BLAME_COPY_HARDER
DECL|macro|PICKAXE_BLAME_MOVE
DECL|macro|cmp_suspect
DECL|member|author
DECL|member|author_mail
DECL|member|author_time
DECL|member|author_tz
DECL|member|blob_sha1
DECL|member|chunks
DECL|member|commit
DECL|member|committer
DECL|member|committer_mail
DECL|member|committer_time
DECL|member|committer_tz
DECL|member|ent
DECL|member|final
DECL|member|final_buf
DECL|member|final_buf_size
DECL|member|guilty
DECL|member|hunk_in_pre_context
DECL|member|hunk_post_context
DECL|member|lineno
DECL|member|lno
DECL|member|next
DECL|member|num
DECL|member|num_lines
DECL|member|num_lines
DECL|member|p_next
DECL|member|path
DECL|member|path
DECL|member|prev
DECL|member|refcnt
DECL|member|ret
DECL|member|s_lno
DECL|member|same
DECL|member|score
DECL|member|summary
DECL|member|suspect
DECL|member|t_next
DECL|member|xm
DECL|struct|blame_diff_state
DECL|struct|blame_entry
DECL|struct|chunk
DECL|struct|commit_info
DECL|struct|origin
DECL|struct|patch
DECL|struct|scoreboard
DECL|variable|blame_copy_score
DECL|variable|blame_move_score
DECL|variable|longest_author
DECL|variable|longest_file
DECL|variable|max_digits
DECL|variable|max_orig_digits
DECL|variable|max_score_digits
DECL|variable|pickaxe_usage
