DECL|function|add_cmdname
DECL|function|cmd_help
DECL|function|cmd_usage
DECL|function|cmd_version
DECL|function|cmdname_compare
DECL|function|list_commands
DECL|function|list_common_cmds_help
DECL|function|mput_char
DECL|function|oom
DECL|function|pretty_print_string_list
DECL|function|show_man_page
DECL|function|term_columns
DECL|member|len
DECL|member|name
DECL|struct|cmdname
DECL|variable|cmdname
DECL|variable|cmdname_alloc
DECL|variable|cmdname_cnt
DECL|variable|git_usage
