DECL|function|cmd_notes
DECL|function|commit_notes
DECL|function|create_note
DECL|function|parse_msg_arg
DECL|function|write_commented_object
DECL|function|write_note_data
DECL|member|buf
DECL|member|given
DECL|struct|msg_arg
DECL|variable|git_notes_usage
DECL|variable|note_template
