DECL|function|add_pattern
DECL|function|buffer_is_binary
DECL|function|cmd_grep
DECL|function|compile_patterns
DECL|function|end_of_line
DECL|function|grep_buffer
DECL|function|grep_cache
DECL|function|grep_file
DECL|function|grep_object
DECL|function|grep_sha1
DECL|function|grep_tree
DECL|function|pathspec_matches
DECL|function|show_line
DECL|function|word_char
DECL|macro|FIRST_FEW_BYTES
DECL|macro|GREP_BINARY_DEFAULT
DECL|macro|GREP_BINARY_NOMATCH
DECL|macro|GREP_BINARY_TEXT
DECL|member|binary
DECL|member|count
DECL|member|invert
DECL|member|linenum
DECL|member|name_only
DECL|member|next
DECL|member|pattern
DECL|member|pattern_list
DECL|member|pattern_tail
DECL|member|post_context
DECL|member|pre_context
DECL|member|regexp
DECL|member|regexp
DECL|member|regflags
DECL|member|unmatch_name_only
DECL|member|word_regexp
DECL|struct|grep_opt
DECL|struct|grep_pat
DECL|variable|builtin_grep_usage
