DECL|function|add_to_known_names
DECL|function|cmd_describe
DECL|function|compare_names
DECL|function|describe
DECL|function|get_name
DECL|function|match
DECL|macro|SEEN
DECL|member|commit
DECL|member|path
DECL|member|prio
DECL|struct|commit_name
DECL|variable|abbrev
DECL|variable|all
DECL|variable|allocs
DECL|variable|describe_usage
DECL|variable|name_array
DECL|variable|names
DECL|variable|tags
