DECL|function|append_line
DECL|function|cmd_rerere
DECL|function|copy_file
DECL|function|diff_two
DECL|function|do_plain_rerere
DECL|function|find_conflict
DECL|function|garbage_collect
DECL|function|git_rerere_config
DECL|function|handle_file
DECL|function|merge
DECL|function|outf
DECL|function|read_rr
DECL|function|rr_path
DECL|function|unlink_rr_item
DECL|function|write_rr
DECL|member|alloc
DECL|member|nr
DECL|member|ptr
DECL|struct|buffer
DECL|variable|cutoff_noresolve
DECL|variable|cutoff_resolve
DECL|variable|git_rerere_usage
DECL|variable|merge_rr_path
DECL|variable|write_lock
