DECL|function|cmd_send_pack
DECL|function|feed_object
DECL|function|pack_objects
DECL|function|print_helper_status
DECL|function|receive_status
DECL|function|send_pack
DECL|function|sideband_demux
DECL|variable|args
DECL|variable|send_pack_usage
