DECL|enumerator|TAGS_DEFAULT
DECL|enumerator|TAGS_SET
DECL|enumerator|TAGS_UNSET
DECL|function|add_existing
DECL|function|add_merge_config
DECL|function|cmd_fetch
DECL|function|do_fetch
DECL|function|fetch_refs
DECL|function|find_non_local_tags
DECL|function|get_ref_map
DECL|function|quickfetch
DECL|function|s_update_ref
DECL|function|set_option
DECL|function|store_updated_refs
DECL|function|unlock_pack
DECL|function|unlock_pack_on_signal
DECL|function|update_local_ref
DECL|function|will_fetch
DECL|macro|REFCOL_WIDTH
DECL|macro|SUMMARY_WIDTH
DECL|variable|append
DECL|variable|builtin_fetch_options
DECL|variable|builtin_fetch_usage
DECL|variable|default_rla
DECL|variable|depth
DECL|variable|force
DECL|variable|keep
DECL|variable|quiet
DECL|variable|tags
DECL|variable|transport
DECL|variable|update_head_ok
DECL|variable|upload_pack
DECL|variable|verbose
