DECL|function|cmd_tag
DECL|function|create_tag
DECL|function|delete_tag
DECL|function|do_sign
DECL|function|for_each_tag_name
DECL|function|git_tag_config
DECL|function|launch_editor
DECL|function|list_tags
DECL|function|show_reference
DECL|function|verify_tag
DECL|macro|MAX_SIGNATURE_LENGTH
DECL|macro|PGP_SIGNATURE
DECL|member|lines
DECL|member|pattern
DECL|struct|tag_filter
DECL|typedef|each_tag_name_fn
DECL|variable|builtin_tag_usage
DECL|variable|signingkey
DECL|variable|tag_template
