DECL|function|add_existing
DECL|function|add_merge_config
DECL|function|cmd_fetch
DECL|function|do_fetch
DECL|function|fetch_refs
DECL|function|find_non_local_tags
DECL|function|get_ref_map
DECL|function|s_update_ref
DECL|function|show_new
DECL|function|store_updated_refs
DECL|function|unlock_pack
DECL|function|unlock_pack_on_signal
DECL|function|update_local_ref
DECL|variable|append
DECL|variable|default_rla
DECL|variable|fetch_usage
DECL|variable|force
DECL|variable|no_tags
DECL|variable|quiet
DECL|variable|tags
DECL|variable|transport
DECL|variable|update_head_ok
DECL|variable|verbose
