DECL|enumerator|PUSH_STATUS_CREATE
DECL|enumerator|PUSH_STATUS_DELETE
DECL|enumerator|PUSH_STATUS_FASTFORWARD
DECL|enumerator|PUSH_STATUS_NOTQUERIED
DECL|enumerator|PUSH_STATUS_OUTOFDATE
DECL|enumerator|PUSH_STATUS_UPTODATE
DECL|function|abbrev_ref
DECL|function|add
DECL|function|add_branch_for_removal
DECL|function|add_known_remote
DECL|function|add_local_to_show_info
DECL|function|add_push_to_show_info
DECL|function|add_remote_to_show_info
DECL|function|append_ref_to_tracked_list
DECL|function|clear_push_info
DECL|function|cmd_remote
DECL|function|cmp_string_with_push
DECL|function|config_read_branches
DECL|function|fetch_remote
DECL|function|free_remote_ref_states
DECL|function|get_head_names
DECL|function|get_one_entry
DECL|function|get_one_remote_for_update
DECL|function|get_push_ref_states
DECL|function|get_push_ref_states_noquery
DECL|function|get_ref_states
DECL|function|get_remote_group
DECL|function|get_remote_ref_states
DECL|function|handle_one_branch
DECL|function|migrate_file
DECL|function|mv
DECL|function|opt_parse_track
DECL|function|postfixcmp
DECL|function|prune
DECL|function|prune_remote
DECL|function|read_branches
DECL|function|read_remote_branches
DECL|function|remove_branches
DECL|function|rm
DECL|function|set_head
DECL|function|show
DECL|function|show_all
DECL|function|show_local_info_item
DECL|function|show_push_info_item
DECL|function|show_remote_info_item
DECL|function|update
DECL|macro|GET_HEAD_NAMES
DECL|macro|GET_PUSH_REF_STATES
DECL|macro|GET_REF_STATES
DECL|macro|abbrev_branch
DECL|member|any_rebase
DECL|member|branches
DECL|member|dest
DECL|member|forced
DECL|member|heads
DECL|member|keep
DECL|member|list
DECL|member|list
DECL|member|list
DECL|member|merge
DECL|member|name
DECL|member|new
DECL|member|new
DECL|member|next
DECL|member|old
DECL|member|push
DECL|member|queried
DECL|member|rebase
DECL|member|remote
DECL|member|remote
DECL|member|remote
DECL|member|remote_branches
DECL|member|remote_name
DECL|member|skipped
DECL|member|stale
DECL|member|states
DECL|member|status
DECL|member|to_delete
DECL|member|tracked
DECL|member|width
DECL|member|width2
DECL|struct|branch_info
DECL|struct|branches_for_remote
DECL|struct|known_remote
DECL|struct|known_remotes
DECL|struct|push_info
DECL|struct|ref_states
DECL|struct|remote_group
DECL|struct|rename_info
DECL|struct|show_info
DECL|variable|branch_list
DECL|variable|builtin_remote_usage
DECL|variable|remote_group
DECL|variable|verbose
