DECL|function|clone_local
DECL|function|cmd_clone
DECL|function|copy_or_link_directory
DECL|function|get_repo_path
DECL|function|guess_dir_name
DECL|function|is_directory
DECL|function|locate_head
DECL|function|remove_junk
DECL|function|remove_junk_on_signal
DECL|function|setup_reference
DECL|function|write_remote_refs
DECL|variable|builtin_clone_options
DECL|variable|builtin_clone_usage
DECL|variable|junk_git_dir
DECL|variable|junk_pid
DECL|variable|junk_work_tree
DECL|variable|option_bare
DECL|variable|option_depth
DECL|variable|option_local
DECL|variable|option_mirror
DECL|variable|option_no_checkout
DECL|variable|option_no_hardlinks
DECL|variable|option_origin
DECL|variable|option_quiet
DECL|variable|option_reference
DECL|variable|option_shared
DECL|variable|option_template
DECL|variable|option_upload_pack
