DECL|function|add_delta_to_list
DECL|function|added_object
DECL|function|cmd_unpack_objects
DECL|function|fill
DECL|function|get_data
DECL|function|resolve_delta
DECL|function|unpack_all
DECL|function|unpack_delta_entry
DECL|function|unpack_non_delta_entry
DECL|function|unpack_one
DECL|function|use
DECL|function|write_object
DECL|member|base_offset
DECL|member|base_sha1
DECL|member|delta
DECL|member|next
DECL|member|nr
DECL|member|offset
DECL|member|sha1
DECL|member|size
DECL|struct|delta_info
DECL|struct|obj_info
DECL|variable|buffer
DECL|variable|consumed_bytes
DECL|variable|ctx
DECL|variable|delta_list
DECL|variable|dry_run
DECL|variable|has_errors
DECL|variable|len
DECL|variable|obj_list
DECL|variable|offset
DECL|variable|quiet
DECL|variable|recover
DECL|variable|unpack_usage
