DECL|function|check_argc
DECL|function|cmd_config
DECL|function|get_color
DECL|function|get_colorbool
DECL|function|get_value
DECL|function|git_get_color_config
DECL|function|git_get_colorbool_config
DECL|function|normalize_value
DECL|function|show_all_config
DECL|function|show_config
DECL|macro|ACTION_ADD
DECL|macro|ACTION_EDIT
DECL|macro|ACTION_GET
DECL|macro|ACTION_GET_ALL
DECL|macro|ACTION_GET_COLOR
DECL|macro|ACTION_GET_COLORBOOL
DECL|macro|ACTION_GET_REGEXP
DECL|macro|ACTION_LIST
DECL|macro|ACTION_REMOVE_SECTION
DECL|macro|ACTION_RENAME_SECTION
DECL|macro|ACTION_REPLACE_ALL
DECL|macro|ACTION_SET
DECL|macro|ACTION_SET_ALL
DECL|macro|ACTION_UNSET
DECL|macro|ACTION_UNSET_ALL
DECL|macro|TYPE_BOOL
DECL|macro|TYPE_BOOL_OR_INT
DECL|macro|TYPE_INT
DECL|variable|actions
DECL|variable|builtin_config_options
DECL|variable|builtin_config_usage
DECL|variable|delim
DECL|variable|do_all
DECL|variable|do_not_match
DECL|variable|end_null
DECL|variable|get_color_found
DECL|variable|get_color_slot
DECL|variable|get_color_slot
DECL|variable|get_colorbool_found
DECL|variable|get_colorbool_slot
DECL|variable|get_colorbool_slot
DECL|variable|get_diff_color_found
DECL|variable|given_config_file
DECL|variable|key
DECL|variable|key_delim
DECL|variable|key_regexp
DECL|variable|parsed_color
DECL|variable|regexp
DECL|variable|seen
DECL|variable|show_keys
DECL|variable|stdout_is_tty
DECL|variable|term
DECL|variable|types
DECL|variable|use_global_config
DECL|variable|use_key_regexp
DECL|variable|use_system_config
