DECL|macro|BUILTIN_H
DECL|macro|DEFAULT_MERGE_LOG_LEN
DECL|member|cmd
DECL|member|combine
DECL|member|enabled
DECL|member|mode_from_env
DECL|member|refs
DECL|member|refs_from_env
DECL|member|trees
DECL|struct|notes_rewrite_cfg
