DECL|enumerator|T_BOOL
DECL|enumerator|T_BOOL_OR_INT
DECL|enumerator|T_INT
DECL|enumerator|T_RAW
DECL|function|cmd_config
DECL|function|get_color
DECL|function|get_colorbool
DECL|function|get_value
DECL|function|git_get_color_config
DECL|function|git_get_colorbool_config
DECL|function|normalize_value
DECL|function|show_all_config
DECL|function|show_config
DECL|variable|delim
DECL|variable|do_all
DECL|variable|do_not_match
DECL|variable|get_color_found
DECL|variable|get_color_slot
DECL|variable|get_colorbool_found
DECL|variable|get_diff_color_found
DECL|variable|git_config_set_usage
DECL|variable|key
DECL|variable|key_delim
DECL|variable|key_regexp
DECL|variable|parsed_color
DECL|variable|regexp
DECL|variable|seen
DECL|variable|show_keys
DECL|variable|stdout_is_tty
DECL|variable|term
DECL|variable|type
DECL|variable|use_key_regexp
