DECL|function|cmd_show_ref
DECL|function|show_ref
DECL|variable|abbrev
DECL|variable|deref_tags
DECL|variable|found_match
DECL|variable|hash_only
DECL|variable|heads_only
DECL|variable|pattern
DECL|variable|quiet
DECL|variable|show_head
DECL|variable|show_ref_usage
DECL|variable|tags_only
DECL|variable|verify
