DECL|enumerator|correct_ws_error
DECL|enumerator|die_on_ws_error
DECL|enumerator|nowarn_ws_error
DECL|enumerator|warn_on_ws_error
DECL|enum|ws_error_action
DECL|function|add_index_file
DECL|function|add_line_info
DECL|function|add_to_fn_table
DECL|function|apply_binary
DECL|function|apply_binary_fragment
DECL|function|apply_data
DECL|function|apply_fragments
DECL|function|apply_one_fragment
DECL|function|apply_patch
DECL|function|build_fake_ancestor
DECL|function|check_patch
DECL|function|check_patch_list
DECL|function|check_preimage
DECL|function|check_to_create_blob
DECL|function|check_whitespace
DECL|function|clear_image
DECL|function|cmd_apply
DECL|function|count_slashes
DECL|function|create_file
DECL|function|create_one_file
DECL|function|find_header
DECL|function|find_name
DECL|function|find_pos
DECL|function|get_current_sha1
DECL|function|git_apply_config
DECL|function|git_header_name
DECL|function|gitdiff_copydst
DECL|function|gitdiff_copysrc
DECL|function|gitdiff_delete
DECL|function|gitdiff_dissimilarity
DECL|function|gitdiff_hdrend
DECL|function|gitdiff_index
DECL|function|gitdiff_newfile
DECL|function|gitdiff_newmode
DECL|function|gitdiff_newname
DECL|function|gitdiff_oldmode
DECL|function|gitdiff_oldname
DECL|function|gitdiff_renamedst
DECL|function|gitdiff_renamesrc
DECL|function|gitdiff_similarity
DECL|function|gitdiff_unrecognized
DECL|function|gitdiff_verify_name
DECL|function|guess_p_value
DECL|function|hash_line
DECL|function|in_fn_table
DECL|function|inflate_it
DECL|function|is_dev_null
DECL|function|linelen
DECL|function|match_fragment
DECL|function|metadata_changes
DECL|function|name_terminate
DECL|function|numstat_patch_list
DECL|function|parse_binary
DECL|function|parse_binary_hunk
DECL|function|parse_chunk
DECL|function|parse_fragment
DECL|function|parse_fragment_header
DECL|function|parse_git_header
DECL|function|parse_num
DECL|function|parse_range
DECL|function|parse_single_patch
DECL|function|parse_traditional_patch
DECL|function|parse_whitespace_option
DECL|function|patch_stats
DECL|function|prefix_one
DECL|function|prefix_patches
DECL|function|prepare_image
DECL|function|read_file_or_gitlink
DECL|function|read_old_data
DECL|function|read_patch_file
DECL|function|recount_diff
DECL|function|remove_file
DECL|function|remove_first_line
DECL|function|remove_last_line
DECL|function|reverse_patches
DECL|function|say_patch_name
DECL|function|set_default_whitespace_mode
DECL|function|show_file_mode_name
DECL|function|show_mode_change
DECL|function|show_rename_copy
DECL|function|show_stats
DECL|function|stat_patch_list
DECL|function|stop_at_slash
DECL|function|summary_patch_list
DECL|function|try_create_file
DECL|function|update_image
DECL|function|update_pre_post_images
DECL|function|use_patch
DECL|function|verify_index_match
DECL|function|write_out_one_reject
DECL|function|write_out_one_result
DECL|function|write_out_results
DECL|macro|BINARY_DELTA_DEFLATED
DECL|macro|BINARY_LITERAL_DEFLATED
DECL|macro|CHUNKSIZE
DECL|macro|INACCURATE_EOF
DECL|macro|LINE_COMMON
DECL|macro|RECOUNT
DECL|macro|SLOP
DECL|macro|TERM_SPACE
DECL|macro|TERM_TAB
DECL|macro|binary_patch_method
DECL|macro|myswap
DECL|macro|swap
DECL|member|alloc
DECL|member|buf
DECL|member|def_name
DECL|member|deflate_origlen
DECL|member|flag
DECL|member|fragments
DECL|member|hash
DECL|member|inaccurate_eof
DECL|member|is_binary
DECL|member|is_copy
DECL|member|is_delete
DECL|member|is_new
DECL|member|is_rename
DECL|member|is_toplevel_relative
DECL|member|leading
DECL|member|len
DECL|member|len
DECL|member|line
DECL|member|line_allocated
DECL|member|lines_added
DECL|member|lines_deleted
DECL|member|new_mode
DECL|member|new_name
DECL|member|new_sha1_prefix
DECL|member|newlines
DECL|member|newpos
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|nr
DECL|member|old_mode
DECL|member|old_name
DECL|member|old_sha1_prefix
DECL|member|oldlines
DECL|member|oldpos
DECL|member|patch
DECL|member|path
DECL|member|recount
DECL|member|rejected
DECL|member|rejected
DECL|member|result
DECL|member|resultsize
DECL|member|score
DECL|member|size
DECL|member|trailing
DECL|member|ws_rule
DECL|struct|excludes
DECL|struct|fragment
DECL|struct|image
DECL|struct|line
DECL|struct|patch
DECL|variable|applied_after_fixing_ws
DECL|variable|apply
DECL|variable|apply_in_reverse
DECL|variable|apply_usage
DECL|variable|apply_verbosely
DECL|variable|apply_with_reject
DECL|variable|cached
DECL|variable|check
DECL|variable|check_index
DECL|variable|diffstat
DECL|variable|excludes
DECL|variable|fake_ancestor
DECL|variable|fn_table
DECL|variable|line_termination
DECL|variable|linenr
DECL|variable|lock_file
DECL|variable|max_change
DECL|variable|max_len
DECL|variable|minuses
DECL|variable|newfd
DECL|variable|no_add
DECL|variable|numstat
DECL|variable|p_context
DECL|variable|p_value
DECL|variable|p_value_known
DECL|variable|patch_input_file
DECL|variable|pluses
DECL|variable|prefix
DECL|variable|prefix_length
DECL|variable|root
DECL|variable|root_len
DECL|variable|squelch_whitespace_errors
DECL|variable|summary
DECL|variable|unidiff_zero
DECL|variable|update_index
DECL|variable|whitespace_error
DECL|variable|ws_error_action
