DECL|function|clear_distance
DECL|function|cmd_rev_list
DECL|function|count_distance
DECL|function|find_bisection
DECL|function|read_revisions_from_stdin
DECL|function|show_commit
DECL|function|show_edge
DECL|function|show_object
DECL|macro|COUNTED
DECL|variable|bisect_list
DECL|variable|hdr_termination
DECL|variable|header_prefix
DECL|variable|rev_list_usage
DECL|variable|revs
DECL|variable|show_left_right
DECL|variable|show_timestamp
