DECL|enumerator|TE_BASE64
DECL|enumerator|TE_DONTCARE
DECL|enumerator|TE_QP
DECL|function|bogus_from
DECL|function|check_header
DECL|function|check_header_line
DECL|function|check_subheader_line
DECL|function|cleanup_space
DECL|function|cleanup_subject
DECL|function|cmd_mailinfo
DECL|function|convert_to_utf8
DECL|function|decode_b_segment
DECL|function|decode_header
DECL|function|decode_header_bq
DECL|function|decode_q_segment
DECL|function|decode_transfer_encoding
DECL|function|eatspace
DECL|function|handle_body
DECL|function|handle_commit_msg
DECL|function|handle_content_transfer_encoding
DECL|function|handle_content_type
DECL|function|handle_date
DECL|function|handle_from
DECL|function|handle_inbody_header
DECL|function|handle_info
DECL|function|handle_multipart_body
DECL|function|handle_multipart_one_part
DECL|function|handle_patch
DECL|function|handle_subcontent_type
DECL|function|handle_subject
DECL|function|is_multipart_boundary
DECL|function|is_rfc2822_header
DECL|function|mailinfo
DECL|function|read_one_header_line
DECL|function|sanity_check
DECL|function|slurp_attr
DECL|macro|SEEN_BOGUS_UNIX_FROM
DECL|macro|SEEN_DATE
DECL|macro|SEEN_FROM
DECL|macro|SEEN_PREFIX
DECL|macro|SEEN_SUBJECT
DECL|member|func
DECL|member|name
DECL|member|namelen
DECL|struct|header_def
DECL|typedef|header_fn_t
DECL|variable|charset
DECL|variable|cmitmsg
DECL|variable|date
DECL|variable|email
DECL|variable|fin
DECL|variable|fout
DECL|variable|keep_subject
DECL|variable|line
DECL|variable|mailinfo_usage
DECL|variable|metainfo_charset
DECL|variable|multipart_boundary
DECL|variable|multipart_boundary_len
DECL|variable|name
DECL|variable|patch_lines
DECL|variable|patchfile
DECL|variable|subject
DECL|variable|transfer_encoding
