DECL|function|bind_merge
DECL|function|cmd_read_tree
DECL|function|deleted_entry
DECL|function|invalidate_ce_path
DECL|function|keep_entry
DECL|function|list_tree
DECL|function|merged_entry
DECL|function|oneway_merge
DECL|function|prime_cache_tree
DECL|function|prime_cache_tree_rec
DECL|function|read_cache_unmerged
DECL|function|reject_merge
DECL|function|same
DECL|function|show_stage_entry
DECL|function|threeway_merge
DECL|function|twoway_merge
DECL|function|verify_absent
DECL|function|verify_uptodate
DECL|macro|DBRT_DEBUG
DECL|variable|lock_file
DECL|variable|read_tree_usage
DECL|variable|trees
