DECL|function|cmd_ls_files
DECL|function|match
DECL|function|prune_cache
DECL|function|show_ce_entry
DECL|function|show_dir_entry
DECL|function|show_files
DECL|function|show_killed_files
DECL|function|show_other_files
DECL|function|verify_pathspec
DECL|variable|abbrev
DECL|variable|error_unmatch
DECL|variable|line_terminator
DECL|variable|ls_files_usage
DECL|variable|pathspec
DECL|variable|prefix_len
DECL|variable|prefix_offset
DECL|variable|ps_matched
DECL|variable|show_cached
DECL|variable|show_deleted
DECL|variable|show_killed
DECL|variable|show_modified
DECL|variable|show_others
DECL|variable|show_stage
DECL|variable|show_unmerged
DECL|variable|show_valid_bit
DECL|variable|tag_cached
DECL|variable|tag_killed
DECL|variable|tag_modified
DECL|variable|tag_other
DECL|variable|tag_removed
DECL|variable|tag_unmerged
