DECL|enumerator|CLEANUP_ALL
DECL|enumerator|CLEANUP_NONE
DECL|enumerator|CLEANUP_SPACE
DECL|enumerator|COMMIT_AS_IS
DECL|enumerator|COMMIT_NORMAL
DECL|enumerator|COMMIT_PARTIAL
DECL|function|add_remove_files
DECL|function|cmd_commit
DECL|function|cmd_status
DECL|function|commit_index_files
DECL|function|create_base_index
DECL|function|determine_author_info
DECL|function|find_author_by_nickname
DECL|function|git_commit_config
DECL|function|is_a_merge
DECL|function|list_paths
DECL|function|message_is_empty
DECL|function|opt_parse_m
DECL|function|parse_and_validate_options
DECL|function|prepare_index
DECL|function|prepare_to_commit
DECL|function|print_summary
DECL|function|rollback_index_files
DECL|function|run_status
DECL|variable|all
DECL|variable|allow_empty
DECL|variable|also
DECL|variable|amend
DECL|variable|author_date
DECL|variable|author_email
DECL|variable|author_name
DECL|variable|builtin_commit_options
DECL|variable|builtin_commit_usage
DECL|variable|builtin_status_usage
DECL|variable|cleanup_arg
DECL|variable|cleanup_mode
DECL|variable|commit_editmsg
DECL|variable|commit_style
DECL|variable|edit_flag
DECL|variable|edit_message
DECL|variable|false_lock
DECL|variable|force_author
DECL|variable|head_sha1
DECL|variable|in_merge
DECL|variable|index_lock
DECL|variable|initial_commit
DECL|variable|interactive
DECL|variable|logfile
DECL|variable|merge_head_sha1
DECL|variable|message
DECL|variable|no_verify
DECL|variable|only
DECL|variable|only_include_assumed
DECL|variable|quiet
DECL|variable|sign_off_header
DECL|variable|signoff
DECL|variable|template_file
DECL|variable|untracked_files_arg
DECL|variable|use_editor
DECL|variable|use_message
DECL|variable|use_message_buffer
DECL|variable|verbose
