DECL|function|add_refspec
DECL|function|cmd_push
DECL|function|do_push
DECL|function|expand_one_ref
DECL|function|expand_refspecs
DECL|function|get_branches_uri
DECL|function|get_remotes_uri
DECL|function|get_uri
DECL|function|set_refspecs
DECL|macro|BUF_SIZE
DECL|macro|MAX_REFSPECS
DECL|macro|MAX_URI
DECL|variable|all
DECL|variable|buffer
DECL|variable|current_refspec
DECL|variable|execute
DECL|variable|force
DECL|variable|push_usage
DECL|variable|refspec
DECL|variable|refspec_nr
DECL|variable|refspecs_
DECL|variable|tags
DECL|variable|thin
