DECL|function|add_to_known_names
DECL|function|cmd_describe
DECL|function|compare_pt
DECL|function|describe
DECL|function|display_name
DECL|function|finish_depth_computation
DECL|function|get_name
DECL|function|show_suffix
DECL|macro|MAX_TAGS
DECL|macro|SEEN
DECL|member|depth
DECL|member|flag_within
DECL|member|found_order
DECL|member|name
DECL|member|path
DECL|member|prio
DECL|member|sha1
DECL|member|tag
DECL|struct|commit_name
DECL|struct|possible_tag
DECL|variable|abbrev
DECL|variable|all
DECL|variable|always
DECL|variable|debug
DECL|variable|describe_usage
DECL|variable|longformat
DECL|variable|max_candidates
DECL|variable|pattern
DECL|variable|prio_names
DECL|variable|tags
