DECL|function|cmd_var
DECL|function|editor
DECL|function|list_vars
DECL|function|pager
DECL|function|read_var
DECL|function|show_config
DECL|member|name
DECL|member|read
DECL|struct|git_var
DECL|variable|git_vars
DECL|variable|var_usage
