DECL|function|append_head_ref
DECL|function|append_matching_ref
DECL|function|append_one_rev
DECL|function|append_ref
DECL|function|append_remote_ref
DECL|function|append_tag_ref
DECL|function|cmd_show_branch
DECL|function|compare_ref_name
DECL|function|count_slash
DECL|function|find_digit_prefix
DECL|function|get_color_code
DECL|function|get_color_reset_code
DECL|function|git_show_branch_config
DECL|function|interesting
DECL|function|join_revs
DECL|function|mark_seen
DECL|function|name_commit
DECL|function|name_commits
DECL|function|name_first_parent_chain
DECL|function|name_parent
DECL|function|omit_in_dense
DECL|function|parse_reflog_param
DECL|function|pop_one_commit
DECL|function|rev_is_head
DECL|function|show_independent
DECL|function|show_merge_base
DECL|function|show_one_commit
DECL|function|snarf_refs
DECL|function|sort_ref_range
DECL|function|version_cmp
DECL|macro|COLUMN_COLORS_MAX
DECL|macro|DEFAULT_REFLOG
DECL|macro|MAX_REVS
DECL|macro|REV_SHIFT
DECL|macro|UNINTERESTING
DECL|member|generation
DECL|member|head_name
DECL|struct|commit_name
DECL|variable|column_colors
DECL|variable|default_alloc
DECL|variable|default_arg
DECL|variable|default_num
DECL|variable|match_ref_pattern
DECL|variable|match_ref_slash
DECL|variable|ref_name
DECL|variable|ref_name_cnt
DECL|variable|reflog
DECL|variable|show_branch_usage
DECL|variable|showbranch_use_color
