DECL|function|cmd_reflog
DECL|function|cmd_reflog_delete
DECL|function|cmd_reflog_expire
DECL|function|collect_reflog
DECL|function|commit_is_complete
DECL|function|count_reflog_ent
DECL|function|expire_reflog
DECL|function|expire_reflog_ent
DECL|function|keep_entry
DECL|function|reflog_expire_config
DECL|function|tree_is_complete
DECL|macro|INCOMPLETE
DECL|macro|STUDYING
DECL|member|alloc
DECL|member|cmd
DECL|member|dry_run
DECL|member|e
DECL|member|expire_total
DECL|member|expire_unreachable
DECL|member|newlog
DECL|member|nr
DECL|member|recno
DECL|member|ref
DECL|member|ref_commit
DECL|member|reflog
DECL|member|revs
DECL|member|sha1
DECL|member|stalefix
DECL|member|verbose
DECL|struct|cmd_reflog_expire_cb
DECL|struct|collect_reflog_cb
DECL|struct|collected_reflog
DECL|struct|expire_reflog_cb
DECL|variable|default_reflog_expire
DECL|variable|default_reflog_expire_unreachable
DECL|variable|reflog_expire_usage
DECL|variable|reflog_usage
