DECL|function|append_ref
DECL|function|cmd_branch
DECL|function|create_branch
DECL|function|delete_branches
DECL|function|free_ref_list
DECL|function|in_merge_bases
DECL|function|print_ref_list
DECL|function|ref_cmp
DECL|macro|REF_LOCAL_BRANCH
DECL|macro|REF_REMOTE_BRANCH
DECL|macro|REF_TAG
DECL|macro|REF_UNKNOWN_TYPE
DECL|member|alloc
DECL|member|index
DECL|member|kind
DECL|member|kinds
DECL|member|list
DECL|member|name
DECL|struct|ref_item
DECL|struct|ref_list
DECL|variable|builtin_branch_usage
DECL|variable|head
DECL|variable|head_sha1
