DECL|enumerator|FIELD_STR
DECL|enumerator|FIELD_TIME
DECL|enumerator|FIELD_ULONG
DECL|function|cmd_for_each_ref
DECL|function|cmp_ref_sort
DECL|function|compare_refs
DECL|function|copy_email
DECL|function|copy_line
DECL|function|copy_name
DECL|function|default_sort
DECL|function|emit
DECL|function|fill_missing_values
DECL|function|find_next
DECL|function|find_subpos
DECL|function|find_wholine
DECL|function|get_obj
DECL|function|get_value
DECL|function|grab_commit_values
DECL|function|grab_common_values
DECL|function|grab_date
DECL|function|grab_person
DECL|function|grab_single_ref
DECL|function|grab_sub_body_contents
DECL|function|grab_tag_values
DECL|function|grab_values
DECL|function|hex1
DECL|function|hex2
DECL|function|num_parents
DECL|function|opt_parse_sort
DECL|function|parse_atom
DECL|function|populate_value
DECL|function|print_value
DECL|function|show_ref
DECL|function|sort_refs
DECL|function|verify_format
DECL|macro|QUOTE_NONE
DECL|macro|QUOTE_PERL
DECL|macro|QUOTE_PYTHON
DECL|macro|QUOTE_SHELL
DECL|macro|QUOTE_TCL
DECL|member|atom
DECL|member|cmp_type
DECL|member|grab_array
DECL|member|grab_cnt
DECL|member|grab_pattern
DECL|member|name
DECL|member|next
DECL|member|objectname
DECL|member|refname
DECL|member|reverse
DECL|member|s
DECL|member|ul
DECL|member|value
DECL|struct|atom_value
DECL|struct|grab_ref_cbdata
DECL|struct|ref_sort
DECL|struct|refinfo
DECL|typedef|cmp_type
DECL|variable|for_each_ref_usage
DECL|variable|need_tagged
DECL|variable|ref_sort
DECL|variable|sort_atom_limit
DECL|variable|used_atom
DECL|variable|used_atom_cnt
DECL|variable|used_atom_type
DECL|variable|valid_atom
