DECL|function|cmd_tag
DECL|function|create_tag
DECL|function|delete_tag
DECL|function|do_sign
DECL|function|for_each_tag_name
DECL|function|git_tag_config
DECL|function|list_tags
DECL|function|parse_msg_arg
DECL|function|set_signingkey
DECL|function|show_reference
DECL|function|verify_tag
DECL|function|write_tag_body
DECL|macro|PGP_SIGNATURE
DECL|member|buf
DECL|member|given
DECL|member|lines
DECL|member|pattern
DECL|struct|msg_arg
DECL|struct|tag_filter
DECL|typedef|each_tag_name_fn
DECL|variable|git_tag_usage
DECL|variable|signingkey
DECL|variable|tag_template
