DECL|function|cmd_send_pack
DECL|function|feed_object
DECL|function|pack_objects
DECL|function|print_ok_ref_status
DECL|function|print_one_push_status
DECL|function|print_push_status
DECL|function|print_ref_status
DECL|function|receive_status
DECL|function|refs_pushed
DECL|function|send_pack
DECL|function|status_abbrev
DECL|function|update_tracking_ref
DECL|function|verify_remote_names
DECL|macro|SUMMARY_WIDTH
DECL|variable|args
DECL|variable|send_pack_usage
