DECL|function|add_to_ref_list
DECL|function|cmd_bundle
DECL|function|create_bundle
DECL|function|list_heads
DECL|function|list_refs
DECL|function|read_header
DECL|function|unbundle
DECL|function|verify_bundle
DECL|macro|PREREQ_MARK
DECL|member|alloc
DECL|member|list
DECL|member|name
DECL|member|nr
DECL|member|prerequisites
DECL|member|references
DECL|member|sha1
DECL|struct|bundle_header
DECL|struct|ref_list
DECL|struct|ref_list_entry
DECL|variable|bundle_signature
DECL|variable|bundle_usage
