DECL|enumerator|TAGS_DEFAULT
DECL|enumerator|TAGS_SET
DECL|enumerator|TAGS_UNSET
DECL|function|add_existing
DECL|function|add_merge_config
DECL|function|add_remote_or_group
DECL|function|add_to_tail
DECL|function|check_not_current_branch
DECL|function|cmd_fetch
DECL|function|do_fetch
DECL|function|fetch_multiple
DECL|function|fetch_one
DECL|function|fetch_refs
DECL|function|find_non_local_tags
DECL|function|get_one_remote_for_fetch
DECL|function|get_ref_map
DECL|function|get_remote_group
DECL|function|prune_refs
DECL|function|quickfetch
DECL|function|s_update_ref
DECL|function|set_option
DECL|function|store_updated_refs
DECL|function|unlock_pack
DECL|function|unlock_pack_on_signal
DECL|function|update_local_ref
DECL|function|will_fetch
DECL|macro|REFCOL_WIDTH
DECL|macro|STORE_REF_ERROR_DF_CONFLICT
DECL|macro|STORE_REF_ERROR_OTHER
DECL|macro|SUMMARY_WIDTH
DECL|member|head
DECL|member|list
DECL|member|name
DECL|member|tail
DECL|struct|remote_group_data
DECL|struct|tag_data
DECL|variable|all
DECL|variable|append
DECL|variable|builtin_fetch_options
DECL|variable|builtin_fetch_usage
DECL|variable|default_rla
DECL|variable|depth
DECL|variable|dry_run
DECL|variable|force
DECL|variable|keep
DECL|variable|multiple
DECL|variable|prune
DECL|variable|tags
DECL|variable|transport
DECL|variable|update_head_ok
DECL|variable|upload_pack
DECL|variable|verbosity
