DECL|function|cmd_format_patch
DECL|function|cmd_log
DECL|function|cmd_log_init
DECL|function|cmd_log_walk
DECL|function|cmd_show
DECL|function|cmd_whatchanged
DECL|function|gen_message_id
DECL|function|get_patch_id
DECL|function|get_patch_ids
DECL|function|git_format_config
DECL|function|istitlechar
DECL|function|reopen_stdout
DECL|variable|extra_headers
DECL|variable|extra_headers_size
DECL|variable|output_directory
DECL|variable|realstdout
