DECL|function|cmd_shortlog
DECL|function|compare_by_number
DECL|function|get_from_rev
DECL|function|insert_one_record
DECL|function|parse_uint
DECL|function|parse_wrap_args
DECL|function|read_from_stdin
DECL|function|shortlog_add_commit
DECL|function|shortlog_init
DECL|function|shortlog_output
DECL|macro|DEFAULT_INDENT1
DECL|macro|DEFAULT_INDENT2
DECL|macro|DEFAULT_WRAPLEN
DECL|variable|shortlog_usage
DECL|variable|wrap_arg_usage
