DECL|function|add_buffer
DECL|function|check_valid
DECL|function|cmd_commit_tree
DECL|function|init_buffer
DECL|function|new_parent
DECL|macro|BLOCKING
DECL|macro|MAXPARENT
DECL|variable|commit_tree_usage
DECL|variable|commit_utf8_warn
DECL|variable|parent_sha1
