DECL|function|builtin_diff_b_f
DECL|function|builtin_diff_blobs
DECL|function|builtin_diff_combined
DECL|function|builtin_diff_files
DECL|function|builtin_diff_index
DECL|function|builtin_diff_tree
DECL|function|cmd_diff
DECL|function|refresh_index_quietly
DECL|function|stuff_change
DECL|member|mode
DECL|member|name
DECL|member|sha1
DECL|struct|blobinfo
DECL|variable|builtin_diff_usage
