DECL|function|cmd_name_rev
DECL|function|get_rev_name
DECL|function|name_ref
DECL|function|name_rev
DECL|macro|ishex
DECL|member|generation
DECL|member|merge_traversals
DECL|member|tip_name
DECL|struct|rev_name
DECL|typedef|rev_name
DECL|variable|cutoff
DECL|variable|name_rev_usage
