DECL|function|add_refspec
DECL|function|cmd_push
DECL|function|do_push
DECL|function|expand_one_ref
DECL|function|expand_refspecs
DECL|function|expand_wildcard_ref
DECL|function|set_refspecs
DECL|function|wildcard_ref
DECL|member|force
DECL|member|from_prefix
DECL|member|from_prefix_len
DECL|member|to_prefix
DECL|member|to_prefix_len
DECL|struct|wildcard_cb
DECL|variable|all
DECL|variable|force
DECL|variable|push_usage
DECL|variable|receivepack
DECL|variable|refspec
DECL|variable|refspec_nr
DECL|variable|tags
DECL|variable|thin
DECL|variable|verbose
