DECL|function|cmd_mailsplit
DECL|function|is_from_line
DECL|function|populate_maildir_list
DECL|function|read_line_with_nul
DECL|function|split_maildir
DECL|function|split_mbox
DECL|function|split_one
DECL|variable|buf
DECL|variable|git_mailsplit_usage
