DECL|function|cmd_format_patch
DECL|function|cmd_log
DECL|function|cmd_log_wc
DECL|function|cmd_show
DECL|function|cmd_whatchanged
DECL|function|istitlechar
DECL|function|reopen_stdout
DECL|variable|output_directory
DECL|variable|realstdout
