DECL|function|already_written
DECL|function|deflate_to_pack
DECL|function|finish_bulk_checkin
DECL|function|index_bulk_checkin
DECL|function|plug_bulk_checkin
DECL|function|prepare_to_stream
DECL|function|stream_to_pack
DECL|function|unplug_bulk_checkin
DECL|member|alloc_written
DECL|member|f
DECL|member|nr_written
DECL|member|offset
DECL|member|pack_idx_opts
DECL|member|pack_tmp_name
DECL|member|plugged
DECL|member|written
DECL|struct|bulk_checkin_state
DECL|variable|pack_compression_level
DECL|variable|state
