DECL|macro|BUNDLE_H
DECL|member|alloc
DECL|member|list
DECL|member|name
DECL|member|nr
DECL|member|prerequisites
DECL|member|references
DECL|member|sha1
DECL|struct|bundle_header
DECL|struct|ref_list
DECL|struct|ref_list_entry
