DECL|function|add_to_ref_list
DECL|function|create_bundle
DECL|function|is_bundle
DECL|function|is_tag_in_date_range
DECL|function|list_bundle_refs
DECL|function|list_refs
DECL|function|parse_bundle_header
DECL|function|read_bundle_header
DECL|function|unbundle
DECL|function|verify_bundle
DECL|macro|PREREQ_MARK
DECL|variable|bundle_signature
