DECL|function|create_ce_mode
DECL|function|xcalloc
DECL|function|xmalloc
DECL|function|xrealloc
DECL|macro|ADD_CACHE_OK_TO_ADD
DECL|macro|ADD_CACHE_OK_TO_REPLACE
DECL|macro|ALTERNATE_DB_ENVIRONMENT
DECL|macro|CACHE_H
DECL|macro|CACHE_SIGNATURE
DECL|macro|CE_NAMEMASK
DECL|macro|CE_STAGEMASK
DECL|macro|CE_STAGESHIFT
DECL|macro|CE_UPDATE
DECL|macro|CTIME_CHANGED
DECL|macro|DATA_CHANGED
DECL|macro|DB_ENVIRONMENT
DECL|macro|DEFAULT_GIT_DIR_ENVIRONMENT
DECL|macro|DTYPE
DECL|macro|DTYPE
DECL|macro|DT_DIR
DECL|macro|DT_LNK
DECL|macro|DT_REG
DECL|macro|DT_UNKNOWN
DECL|macro|GIT_DIR_ENVIRONMENT
DECL|macro|INDEX_ENVIRONMENT
DECL|macro|INODE_CHANGED
DECL|macro|MODE_CHANGED
DECL|macro|MTIME_CHANGED
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|OWNER_CHANGED
DECL|macro|TYPE_CHANGED
DECL|macro|alloc_nr
DECL|macro|cache_entry_size
DECL|macro|ce_namelen
DECL|macro|ce_permissions
DECL|macro|ce_size
DECL|macro|ce_stage
DECL|macro|create_ce_flags
DECL|macro|deflateBound
DECL|macro|gitenv
DECL|member|base_dir
DECL|member|base_dir_len
DECL|member|ce_ctime
DECL|member|ce_dev
DECL|member|ce_flags
DECL|member|ce_gid
DECL|member|ce_ino
DECL|member|ce_mode
DECL|member|ce_mtime
DECL|member|ce_size
DECL|member|ce_uid
DECL|member|force
DECL|member|hdr_entries
DECL|member|hdr_signature
DECL|member|hdr_version
DECL|member|lockfile
DECL|member|name
DECL|member|next
DECL|member|not_new
DECL|member|nsec
DECL|member|quiet
DECL|member|refresh_cache
DECL|member|sec
DECL|member|sha1
DECL|struct|cache_entry
DECL|struct|cache_file
DECL|struct|cache_header
DECL|struct|cache_time
DECL|struct|checkout
