DECL|macro|CACHE_H
DECL|macro|CACHE_SIGNATURE
DECL|macro|CE_NAMEMASK
DECL|macro|CE_STAGEMASK
DECL|macro|CE_STAGESHIFT
DECL|macro|CTIME_CHANGED
DECL|macro|DATA_CHANGED
DECL|macro|DB_ENVIRONMENT
DECL|macro|DEFAULT_DB_ENVIRONMENT
DECL|macro|INODE_CHANGED
DECL|macro|MODE_CHANGED
DECL|macro|MTIME_CHANGED
DECL|macro|OWNER_CHANGED
DECL|macro|alloc_nr
DECL|macro|cache_entry_size
DECL|macro|ce_namelen
DECL|macro|ce_size
DECL|macro|ce_stage
DECL|macro|create_ce_flags
DECL|member|ce_ctime
DECL|member|ce_dev
DECL|member|ce_flags
DECL|member|ce_gid
DECL|member|ce_ino
DECL|member|ce_mode
DECL|member|ce_mtime
DECL|member|ce_size
DECL|member|ce_uid
DECL|member|hdr_entries
DECL|member|hdr_signature
DECL|member|hdr_version
DECL|member|name
DECL|member|nsec
DECL|member|sec
DECL|member|sha1
DECL|member|sha1
DECL|struct|cache_entry
DECL|struct|cache_header
DECL|struct|cache_time
DECL|variable|active_alloc
DECL|variable|active_cache
DECL|variable|active_nr
DECL|variable|sha1_file_directory
