DECL|function|checkout_all
DECL|function|checkout_file
DECL|function|main
DECL|function|write_tempfile_record
DECL|macro|CHECKOUT_ALL
DECL|variable|cache_file
DECL|variable|checkout_cache_usage
DECL|variable|checkout_stage
DECL|variable|line_termination
DECL|variable|prefix
DECL|variable|prefix_length
DECL|variable|state
DECL|variable|to_tempfile
DECL|variable|topath
