DECL|function|clone_handshake
DECL|function|clone_pack
DECL|function|is_master
DECL|function|main
DECL|function|write_one_ref
DECL|function|write_refs
DECL|variable|clone_pack_usage
DECL|variable|exec
DECL|variable|quiet
