DECL|enumerator|COLOR_256
DECL|enumerator|COLOR_ANSI
DECL|enumerator|COLOR_NORMAL
DECL|enumerator|COLOR_UNSPECIFIED
DECL|function|check_auto_color
DECL|function|color_empty
DECL|function|color_fprintf
DECL|function|color_fprintf_ln
DECL|function|color_is_nil
DECL|function|color_output
DECL|function|color_parse
DECL|function|color_parse_mem
DECL|function|color_print_strbuf
DECL|function|color_vfprintf
DECL|function|git_color_config
DECL|function|git_color_default_config
DECL|function|git_config_colorbool
DECL|function|match_word
DECL|function|parse_attr
DECL|function|parse_color
DECL|function|want_color
DECL|macro|COLOR_BACKGROUND
DECL|macro|COLOR_FOREGROUND
DECL|member|type
DECL|member|value
DECL|struct|color
DECL|variable|color_stdout_is_tty
DECL|variable|column_colors_ansi
DECL|variable|column_colors_ansi_max
DECL|variable|git_use_color_default
