DECL|function|color_fprintf
DECL|function|color_fprintf_ln
DECL|function|color_parse
DECL|function|color_vfprintf
DECL|function|git_color_default_config
DECL|function|git_config_colorbool
DECL|function|parse_attr
DECL|function|parse_color
DECL|macro|COLOR_RESET
DECL|variable|git_use_color_default
