DECL|function|column_config
DECL|function|display_cell
DECL|function|display_plain
DECL|function|display_table
DECL|function|finalize_colopts
DECL|function|git_column_config
DECL|function|item_length
DECL|function|layout
DECL|function|parse_config
DECL|function|parse_option
DECL|function|parseopt_column_callback
DECL|function|print_columns
DECL|macro|ENABLE_SET
DECL|macro|LAYOUT_SET
DECL|macro|XY2LINEAR
DECL|member|colopts
DECL|member|cols
DECL|member|len
DECL|member|list
DECL|member|mask
DECL|member|name
DECL|member|opts
DECL|member|rows
DECL|member|value
DECL|struct|colopt
DECL|struct|column_data
