DECL|enumerator|CMIT_FMT_DEFAULT
DECL|enumerator|CMIT_FMT_EMAIL
DECL|enumerator|CMIT_FMT_FULL
DECL|enumerator|CMIT_FMT_FULLER
DECL|enumerator|CMIT_FMT_MEDIUM
DECL|enumerator|CMIT_FMT_ONELINE
DECL|enumerator|CMIT_FMT_RAW
DECL|enumerator|CMIT_FMT_SHORT
DECL|enumerator|CMIT_FMT_UNSPECIFIED
DECL|enumerator|CMIT_FMT_USERFORMAT
DECL|enum|cmit_fmt
DECL|function|single_parent
DECL|macro|COMMIT_H
DECL|member|buffer
DECL|member|date
DECL|member|indegree
DECL|member|item
DECL|member|name
DECL|member|next
DECL|member|next
DECL|member|nr_parent
DECL|member|object
DECL|member|parent
DECL|member|parents
DECL|member|sha1
DECL|member|tree
DECL|member|util
DECL|struct|commit
DECL|struct|commit_graft
DECL|struct|commit_list
DECL|struct|name_decoration
