DECL|function|add_parent_info
DECL|function|add_user_info
DECL|function|check_commit
DECL|function|clear_commit_marks
DECL|function|commit_graft_pos
DECL|function|commit_list_insert
DECL|function|count_parents
DECL|function|free_commit_list
DECL|function|get_commit_format
DECL|function|get_one_line
DECL|function|insert_by_date
DECL|function|is_empty_line
DECL|function|lookup_commit
DECL|function|lookup_commit_graft
DECL|function|lookup_commit_reference
DECL|function|lookup_commit_reference_gently
DECL|function|parse_commit
DECL|function|parse_commit_buffer
DECL|function|parse_commit_date
DECL|function|pop_commit
DECL|function|pop_most_recent_commit
DECL|function|prepare_commit_graft
DECL|function|pretty_print_commit
DECL|function|sort_by_date
DECL|function|sort_in_topological_order
DECL|member|indegree
DECL|member|list_item
DECL|member|nr_parent
DECL|member|parent
DECL|member|sha1
DECL|struct|commit_graft
DECL|struct|sort_node
DECL|variable|commit_graft
DECL|variable|commit_graft_alloc
DECL|variable|commit_graft_nr
DECL|variable|commit_type
DECL|variable|save_commit_buffer
