DECL|function|add_parent_info
DECL|function|add_user_info
DECL|function|check_commit
DECL|function|commit_list_insert
DECL|function|count_parents
DECL|function|free_commit_list
DECL|function|get_commit_format
DECL|function|get_one_line
DECL|function|insert_by_date
DECL|function|is_empty_line
DECL|function|lookup_commit
DECL|function|lookup_commit_reference
DECL|function|parse_commit
DECL|function|parse_commit_buffer
DECL|function|parse_commit_date
DECL|function|pop_commit
DECL|function|pop_most_recent_commit
DECL|function|pretty_print_commit
DECL|function|sort_by_date
DECL|function|sort_in_topological_order
DECL|member|indegree
DECL|member|list_item
DECL|struct|sort_node
DECL|variable|commit_type
