DECL|enumerator|CMIT_FMT_DEFAULT
DECL|enumerator|CMIT_FMT_FULL
DECL|enumerator|CMIT_FMT_FULLER
DECL|enumerator|CMIT_FMT_MEDIUM
DECL|enumerator|CMIT_FMT_ONELINE
DECL|enumerator|CMIT_FMT_RAW
DECL|enumerator|CMIT_FMT_SHORT
DECL|enum|cmit_fmt
DECL|macro|COMMIT_H
DECL|member|buffer
DECL|member|date
DECL|member|item
DECL|member|next
DECL|member|nr_parent
DECL|member|object
DECL|member|parent
DECL|member|parents
DECL|member|sha1
DECL|member|tree
DECL|struct|commit
DECL|struct|commit_graft
DECL|struct|commit_list
DECL|typedef|topo_sort_get_fn_t
DECL|typedef|topo_sort_set_fn_t
