DECL|function|add_merge_info
DECL|function|add_rfc2047
DECL|function|add_user_info
DECL|function|check_commit
DECL|function|clear_commit_marks
DECL|function|commit_graft_pos
DECL|function|commit_list_insert
DECL|function|count_parents
DECL|function|free_commit_list
DECL|function|get_commit_format
DECL|function|get_merge_bases
DECL|function|get_one_line
DECL|function|insert_by_date
DECL|function|interesting
DECL|function|is_empty_line
DECL|function|is_rfc2047_special
DECL|function|lookup_commit
DECL|function|lookup_commit_graft
DECL|function|lookup_commit_reference
DECL|function|lookup_commit_reference_gently
DECL|function|mark_reachable_commits
DECL|function|parse_commit
DECL|function|parse_commit_buffer
DECL|function|parse_commit_date
DECL|function|pop_commit
DECL|function|pop_most_recent_commit
DECL|function|prepare_commit_graft
DECL|function|pretty_print_commit
DECL|function|read_graft_file
DECL|function|read_graft_line
DECL|function|register_commit_graft
DECL|function|sort_by_date
DECL|function|sort_in_topological_order
DECL|function|sort_in_topological_order_fn
DECL|function|topo_sort_default_getter
DECL|function|topo_sort_default_setter
DECL|macro|PARENT1
DECL|macro|PARENT2
DECL|macro|UNINTERESTING
DECL|member|cmp_len
DECL|member|indegree
DECL|member|list_item
DECL|member|n
DECL|member|v
DECL|struct|cmt_fmt_map
DECL|struct|sort_node
DECL|variable|cmt_fmts
DECL|variable|commit_graft
DECL|variable|commit_graft_alloc
DECL|variable|commit_graft_nr
DECL|variable|commit_type
DECL|variable|save_commit_buffer
