DECL|function|add_buffer
DECL|function|check_valid
DECL|function|git_author_info
DECL|function|git_committer_info
DECL|function|init_buffer
DECL|function|main
DECL|function|new_parent
DECL|macro|BLOCKING
DECL|macro|MAXPARENT
DECL|variable|commit_tree_usage
DECL|variable|parent_sha1
