DECL|enumerator|CMIT_FMT_DEFAULT
DECL|enumerator|CMIT_FMT_EMAIL
DECL|enumerator|CMIT_FMT_FULL
DECL|enumerator|CMIT_FMT_FULLER
DECL|enumerator|CMIT_FMT_MEDIUM
DECL|enumerator|CMIT_FMT_ONELINE
DECL|enumerator|CMIT_FMT_RAW
DECL|enumerator|CMIT_FMT_SHORT
DECL|enumerator|CMIT_FMT_UNSPECIFIED
DECL|enumerator|CMIT_FMT_USERFORMAT
DECL|enumerator|REV_SORT_BY_AUTHOR_DATE
DECL|enumerator|REV_SORT_BY_COMMIT_DATE
DECL|enumerator|REV_SORT_IN_GRAPH_ORDER
DECL|enum|cmit_fmt
DECL|enum|rev_sort_order
DECL|function|single_parent
DECL|macro|COMMIT_H
DECL|macro|INFINITE_DEPTH
DECL|macro|merge_remote_util
DECL|member|abbrev
DECL|member|after_subject
DECL|member|color
DECL|member|commits
DECL|member|date
DECL|member|date_mode
DECL|member|date_mode_explicit
DECL|member|fmt
DECL|member|from_ident
DECL|member|in_body_headers
DECL|member|index
DECL|member|item
DECL|member|key
DECL|member|len
DECL|member|mailmap
DECL|member|name
DECL|member|name
DECL|member|need_8bit_cte
DECL|member|need_reachability_test
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|notes
DECL|member|notes_message
DECL|member|nr_commits
DECL|member|nr_ours
DECL|member|nr_parent
DECL|member|nr_theirs
DECL|member|obj
DECL|member|object
DECL|member|ours
DECL|member|output_encoding
DECL|member|parent
DECL|member|parents
DECL|member|preserve_subject
DECL|member|reachable
DECL|member|ref
DECL|member|reflog_info
DECL|member|sha1
DECL|member|shallow
DECL|member|shallow_ref
DECL|member|subject
DECL|member|theirs
DECL|member|tree
DECL|member|type
DECL|member|used_shallow
DECL|member|util
DECL|member|value
DECL|struct|commit
DECL|struct|commit_extra_header
DECL|struct|commit_graft
DECL|struct|commit_list
DECL|struct|merge_remote_desc
DECL|struct|name_decoration
DECL|struct|pretty_print_context
DECL|struct|shallow_info
DECL|struct|userformat_want
DECL|typedef|each_commit_graft_fn
