DECL|enumerator|KEY_SEEN
DECL|enumerator|SECTION_END_SEEN
DECL|enumerator|SECTION_SEEN
DECL|enumerator|START
DECL|function|find_beginning_of_line
DECL|function|get_base_var
DECL|function|get_extended_base_var
DECL|function|get_next_char
DECL|function|get_value
DECL|function|git_config
DECL|function|git_config_bool
DECL|function|git_config_from_file
DECL|function|git_config_int
DECL|function|git_config_set
DECL|function|git_config_set_multivar
DECL|function|git_default_config
DECL|function|git_parse_file
DECL|function|matches
DECL|function|parse_value
DECL|function|store_aux
DECL|function|store_write_pair
DECL|function|store_write_section
DECL|macro|MAXNAME
DECL|macro|MAX_MATCHES
DECL|member|baselen
DECL|member|do_not_match
DECL|member|key
DECL|member|multi_replace
DECL|member|offset
DECL|member|seen
DECL|member|state
DECL|member|value_regex
DECL|variable|config_file
DECL|variable|config_file_name
DECL|variable|config_linenr
DECL|variable|store
