DECL|enumerator|KEY_SEEN
DECL|enumerator|SECTION_END_SEEN
DECL|enumerator|SECTION_SEEN
DECL|enumerator|START
DECL|function|config_buf_fgetc
DECL|function|config_buf_ftell
DECL|function|config_buf_ungetc
DECL|function|config_error_nonbool
DECL|function|config_file_fgetc
DECL|function|config_file_ftell
DECL|function|config_file_ungetc
DECL|function|die_bad_number
DECL|function|do_config_from
DECL|function|do_config_from_file
DECL|function|find_beginning_of_line
DECL|function|get_base_var
DECL|function|get_extended_base_var
DECL|function|get_next_char
DECL|function|get_value
DECL|function|git_config
DECL|function|git_config_bool
DECL|function|git_config_bool_or_int
DECL|function|git_config_early
DECL|function|git_config_from_blob_ref
DECL|function|git_config_from_blob_sha1
DECL|function|git_config_from_buf
DECL|function|git_config_from_file
DECL|function|git_config_from_parameters
DECL|function|git_config_from_stdin
DECL|function|git_config_include
DECL|function|git_config_int
DECL|function|git_config_int64
DECL|function|git_config_maybe_bool
DECL|function|git_config_maybe_bool_text
DECL|function|git_config_parse_key
DECL|function|git_config_parse_parameter
DECL|function|git_config_pathname
DECL|function|git_config_push_parameter
DECL|function|git_config_rename_section
DECL|function|git_config_rename_section_in_file
DECL|function|git_config_set
DECL|function|git_config_set_in_file
DECL|function|git_config_set_multivar
DECL|function|git_config_set_multivar_in_file
DECL|function|git_config_string
DECL|function|git_config_system
DECL|function|git_config_ulong
DECL|function|git_config_with_options
DECL|function|git_default_branch_config
DECL|function|git_default_config
DECL|function|git_default_core_config
DECL|function|git_default_i18n_config
DECL|function|git_default_mailmap_config
DECL|function|git_default_push_config
DECL|function|git_env_bool
DECL|function|git_etc_gitconfig
DECL|function|git_parse_int
DECL|function|git_parse_int64
DECL|function|git_parse_signed
DECL|function|git_parse_source
DECL|function|git_parse_ulong
DECL|function|git_parse_unsigned
DECL|function|handle_path_include
DECL|function|iskeychar
DECL|function|lowercase
DECL|function|matches
DECL|function|parse_config_key
DECL|function|parse_unit_factor
DECL|function|parse_value
DECL|function|section_name_is_ok
DECL|function|section_name_match
DECL|function|store_aux
DECL|function|store_write_pair
DECL|function|store_write_section
DECL|function|write_error
DECL|macro|MAX_INCLUDE_DEPTH
DECL|macro|config_error_nonbool
DECL|member|baselen
DECL|member|buf
DECL|member|buf
DECL|member|die_on_error
DECL|member|do_fgetc
DECL|member|do_ftell
DECL|member|do_not_match
DECL|member|do_ungetc
DECL|member|eof
DECL|member|file
DECL|member|key
DECL|member|len
DECL|member|linenr
DECL|member|multi_replace
DECL|member|name
DECL|member|offset
DECL|member|offset_alloc
DECL|member|path
DECL|member|pos
DECL|member|prev
DECL|member|seen
DECL|member|state
DECL|member|u
DECL|member|value
DECL|member|value_regex
DECL|member|var
DECL|struct|config_buf
DECL|struct|config_source
DECL|variable|cf
DECL|variable|include_depth_advice
DECL|variable|store
DECL|variable|zlib_compression_seen
