DECL|enumerator|PROTO_GIT
DECL|enumerator|PROTO_LOCAL
DECL|enumerator|PROTO_SSH
DECL|enum|protocol
DECL|function|finish_connect
DECL|function|get_ack
DECL|function|get_protocol
DECL|function|get_remote_heads
DECL|function|git_connect
DECL|function|git_tcp_connect
DECL|function|path_match
DECL|macro|STR
DECL|macro|STR_
