DECL|enumerator|PROTO_GIT
DECL|enumerator|PROTO_LOCAL
DECL|enumerator|PROTO_SSH
DECL|enum|protocol
DECL|function|ai_name
DECL|function|check_ref
DECL|function|check_ref_type
DECL|function|finish_connect
DECL|function|get_ack
DECL|function|get_port
DECL|function|get_protocol
DECL|function|get_remote_heads
DECL|function|git_connect
DECL|function|git_proxy_command_options
DECL|function|git_proxy_connect
DECL|function|git_tcp_connect
DECL|function|git_tcp_connect_sock
DECL|function|git_tcp_connect_sock
DECL|function|git_use_proxy
DECL|function|path_match
DECL|function|server_supports
DECL|macro|MAX_CMD_LEN
DECL|macro|STR
DECL|macro|STR_
DECL|variable|git_proxy_command
DECL|variable|no_fork
DECL|variable|rhost_len
DECL|variable|rhost_name
DECL|variable|server_capabilities
