DECL|enumerator|CRLF_AUTO
DECL|enumerator|CRLF_BINARY
DECL|enumerator|CRLF_CRLF
DECL|enumerator|CRLF_GUESS
DECL|enumerator|CRLF_INPUT
DECL|enumerator|CRLF_TEXT
DECL|enum|crlf_action
DECL|function|apply_filter
DECL|function|check_safe_crlf
DECL|function|convert_attrs
DECL|function|convert_to_git
DECL|function|convert_to_working_tree
DECL|function|convert_to_working_tree_internal
DECL|function|count_ident
DECL|function|crlf_to_git
DECL|function|crlf_to_worktree
DECL|function|filter_buffer
DECL|function|gather_stats
DECL|function|git_path_check_convert
DECL|function|git_path_check_crlf
DECL|function|git_path_check_eol
DECL|function|git_path_check_ident
DECL|function|has_cr_in_index
DECL|function|ident_to_git
DECL|function|ident_to_worktree
DECL|function|input_crlf_action
DECL|function|is_binary
DECL|function|output_eol
DECL|function|read_convert_config
DECL|function|renormalize_buffer
DECL|macro|NUM_CONV_ATTRS
DECL|member|clean
DECL|member|cmd
DECL|member|cr
DECL|member|crlf
DECL|member|crlf_action
DECL|member|drv
DECL|member|eol_attr
DECL|member|ident
DECL|member|lf
DECL|member|name
DECL|member|next
DECL|member|nonprintable
DECL|member|nul
DECL|member|path
DECL|member|printable
DECL|member|size
DECL|member|smudge
DECL|member|src
DECL|struct|conv_attrs
DECL|struct|convert_driver
DECL|struct|filter_params
DECL|struct|text_stat
DECL|variable|conv_attr_name
DECL|variable|user_convert
DECL|variable|user_convert_tail
