DECL|enumerator|CRLF_AUTO
DECL|enumerator|CRLF_BINARY
DECL|enumerator|CRLF_CRLF
DECL|enumerator|CRLF_GUESS
DECL|enumerator|CRLF_INPUT
DECL|enumerator|CRLF_TEXT
DECL|enum|crlf_action
DECL|function|apply_filter
DECL|function|cascade_filter
DECL|function|cascade_filter_fn
DECL|function|cascade_free_fn
DECL|function|check_safe_crlf
DECL|function|convert_attrs
DECL|function|convert_to_git
DECL|function|convert_to_working_tree
DECL|function|convert_to_working_tree_internal
DECL|function|count_ident
DECL|function|crlf_to_git
DECL|function|crlf_to_worktree
DECL|function|filter_buffer
DECL|function|free_stream_filter
DECL|function|gather_stats
DECL|function|get_stream_filter
DECL|function|git_path_check_convert
DECL|function|git_path_check_crlf
DECL|function|git_path_check_eol
DECL|function|git_path_check_ident
DECL|function|has_cr_in_index
DECL|function|ident_drain
DECL|function|ident_filter
DECL|function|ident_filter_fn
DECL|function|ident_free_fn
DECL|function|ident_to_git
DECL|function|ident_to_worktree
DECL|function|input_crlf_action
DECL|function|is_binary
DECL|function|is_foreign_ident
DECL|function|is_null_stream_filter
DECL|function|lf_to_crlf_filter
DECL|function|lf_to_crlf_filter_fn
DECL|function|lf_to_crlf_free_fn
DECL|function|null_filter_fn
DECL|function|null_free_fn
DECL|function|output_eol
DECL|function|read_convert_config
DECL|function|renormalize_buffer
DECL|function|stream_filter
DECL|macro|FILTER_BUFFER
DECL|macro|IDENT_DRAINING
DECL|macro|IDENT_SKIPPING
DECL|macro|NUM_CONV_ATTRS
DECL|member|buf
DECL|member|clean
DECL|member|cmd
DECL|member|cr
DECL|member|crlf
DECL|member|crlf_action
DECL|member|drv
DECL|member|end
DECL|member|eol_attr
DECL|member|filter
DECL|member|filter
DECL|member|filter
DECL|member|filter
DECL|member|free
DECL|member|has_held
DECL|member|held
DECL|member|ident
DECL|member|ident
DECL|member|left
DECL|member|lf
DECL|member|name
DECL|member|next
DECL|member|nonprintable
DECL|member|nul
DECL|member|one
DECL|member|path
DECL|member|printable
DECL|member|ptr
DECL|member|size
DECL|member|smudge
DECL|member|src
DECL|member|state
DECL|member|two
DECL|member|vtbl
DECL|struct|cascade_filter
DECL|struct|conv_attrs
DECL|struct|convert_driver
DECL|struct|filter_params
DECL|struct|ident_filter
DECL|struct|lf_to_crlf_filter
DECL|struct|stream_filter
DECL|struct|stream_filter_vtbl
DECL|struct|text_stat
DECL|typedef|filter_fn
DECL|typedef|free_fn
DECL|variable|cascade_vtbl
DECL|variable|conv_attr_name
DECL|variable|ident_vtbl
DECL|variable|lf_to_crlf_vtbl
DECL|variable|null_filter_singleton
DECL|variable|null_vtbl
DECL|variable|user_convert
DECL|variable|user_convert_tail
