DECL|function|cache_credential
DECL|function|check_expirations
DECL|function|check_socket_directory
DECL|function|cleanup_socket
DECL|function|cleanup_socket_on_signal
DECL|function|lookup_credential
DECL|function|main
DECL|function|read_request
DECL|function|remove_credential
DECL|function|serve_cache
DECL|function|serve_cache_loop
DECL|function|serve_one_client
DECL|member|expiration
DECL|member|item
DECL|struct|credential_cache_entry
DECL|variable|entries
DECL|variable|entries_alloc
DECL|variable|entries_nr
DECL|variable|permissions_advice
DECL|variable|socket_path
