DECL|macro|CREDENTIAL_H
DECL|macro|CREDENTIAL_INIT
DECL|member|approved
DECL|member|configured
DECL|member|helpers
DECL|member|host
DECL|member|password
DECL|member|path
DECL|member|protocol
DECL|member|use_http_path
DECL|member|username
DECL|struct|credential
