DECL|macro|CSUM_FILE_H
DECL|member|buffer
DECL|member|crc32
DECL|member|ctx
DECL|member|do_crc
DECL|member|error
DECL|member|fd
DECL|member|name
DECL|member|namelen
DECL|member|offset
DECL|member|tp
DECL|struct|sha1file
