DECL|enumerator|Header
DECL|enumerator|Log
DECL|enumerator|Members
DECL|enum|state
DECL|function|commit
DECL|function|lookup_author
DECL|function|main
DECL|function|prepare_commit
DECL|function|update_file
DECL|member|dest
DECL|member|name
DECL|struct|hdrentry
DECL|variable|ancestor
DECL|variable|author
DECL|variable|branch
DECL|variable|cvsmodule
DECL|variable|cvsroot
DECL|variable|date
DECL|variable|hdrs
DECL|variable|initial_commit
DECL|variable|log
DECL|variable|loglen
DECL|variable|tag
DECL|variable|verbose
