DECL|function|add_child
DECL|function|check_max_connections
DECL|function|child_handler
DECL|function|execute
DECL|function|handle
DECL|function|kill_some_children
DECL|function|logerror
DECL|function|loginfo
DECL|function|logreport
DECL|function|main
DECL|function|path_ok
DECL|function|remove_child
DECL|function|serve
DECL|function|set_dir
DECL|function|upload
DECL|macro|MAX_CHILDREN
DECL|member|address
DECL|member|addrlen
DECL|member|pid
DECL|struct|child
DECL|variable|children_deleted
DECL|variable|children_reaped
DECL|variable|children_spawned
DECL|variable|daemon_usage
DECL|variable|dead_child
DECL|variable|export_all_trees
DECL|variable|init_timeout
DECL|variable|live_child
DECL|variable|log_syslog
DECL|variable|max_connections
DECL|variable|ok_paths
DECL|variable|timeout
DECL|variable|verbose
