DECL|function|add_child
DECL|function|addrcmp
DECL|function|check_dead_children
DECL|function|child_handler
DECL|function|copy_to_log
DECL|function|daemon_die
DECL|function|daemon_error
DECL|function|daemonize
DECL|function|daemonize
DECL|function|drop_privileges
DECL|function|drop_privileges
DECL|function|enable_service
DECL|function|execute
DECL|function|git_daemon_config
DECL|function|handle
DECL|function|ip2str
DECL|function|kill_some_child
DECL|function|logerror
DECL|function|loginfo
DECL|function|logreport
DECL|function|main
DECL|function|make_service_overridable
DECL|function|parse_host_and_port
DECL|function|parse_host_arg
DECL|function|path_ok
DECL|function|prepare_credentials
DECL|function|prepare_credentials
DECL|function|receive_pack
DECL|function|run_service
DECL|function|run_service_command
DECL|function|sanitize_stdfds
DECL|function|serve
DECL|function|service_loop
DECL|function|set_reuse_addr
DECL|function|setup_named_sock
DECL|function|setup_named_sock
DECL|function|socksetup
DECL|function|store_pid
DECL|function|upload_archive
DECL|function|upload_pack
DECL|function|xstrdup_tolower
DECL|macro|HOST_NAME_MAX
DECL|macro|NI_MAXSERV
DECL|macro|initgroups
DECL|member|address
DECL|member|alloc
DECL|member|cld
DECL|member|config_name
DECL|member|enabled
DECL|member|fn
DECL|member|gid
DECL|member|list
DECL|member|name
DECL|member|next
DECL|member|nr
DECL|member|overridable
DECL|member|pass
DECL|struct|child
DECL|struct|credentials
DECL|struct|daemon_service
DECL|struct|socketlist
DECL|typedef|daemon_service_fn
DECL|variable|base_path
DECL|variable|base_path_relaxed
DECL|variable|canon_hostname
DECL|variable|cld_argv
DECL|variable|daemon_service
DECL|variable|daemon_usage
DECL|variable|export_all_trees
DECL|variable|firstborn
DECL|variable|hostname
DECL|variable|informative_errors
DECL|variable|init_timeout
DECL|variable|interpolated_path
DECL|variable|ip_address
DECL|variable|live_children
DECL|variable|log_syslog
DECL|variable|max_connections
DECL|variable|ok_paths
DECL|variable|reuseaddr
DECL|variable|saw_extended_args
DECL|variable|service_enabled
DECL|variable|service_looking_at
DECL|variable|strict_paths
DECL|variable|tcp_port
DECL|variable|timeout
DECL|variable|user_path
DECL|variable|verbose
