DECL|function|add_child
DECL|function|avoid_alias
DECL|function|check_dead_children
DECL|function|check_max_connections
DECL|function|child_handler
DECL|function|daemon_die
DECL|function|daemonize
DECL|function|enable_service
DECL|function|execute
DECL|function|fill_in_extra_table_entries
DECL|function|git_daemon_config
DECL|function|handle
DECL|function|kill_some_children
DECL|function|logerror
DECL|function|loginfo
DECL|function|logreport
DECL|function|main
DECL|function|make_service_overridable
DECL|function|parse_extra_args
DECL|function|path_ok
DECL|function|receive_pack
DECL|function|remove_child
DECL|function|run_service
DECL|function|sanitize_stdfds
DECL|function|serve
DECL|function|service_loop
DECL|function|set_reuse_addr
DECL|function|socksetup
DECL|function|socksetup
DECL|function|store_pid
DECL|function|upload_archive
DECL|function|upload_pack
DECL|macro|HOST_NAME_MAX
DECL|macro|INTERP_SLOT_CANON_HOST
DECL|macro|INTERP_SLOT_DIR
DECL|macro|INTERP_SLOT_HOST
DECL|macro|INTERP_SLOT_IP
DECL|macro|INTERP_SLOT_PERCENT
DECL|macro|INTERP_SLOT_PORT
DECL|macro|MAX_CHILDREN
DECL|macro|NI_MAXSERV
DECL|member|address
DECL|member|addrlen
DECL|member|config_name
DECL|member|enabled
DECL|member|fn
DECL|member|name
DECL|member|overridable
DECL|member|pid
DECL|struct|child
DECL|struct|daemon_service
DECL|typedef|daemon_service_fn
DECL|variable|base_path
DECL|variable|base_path_relaxed
DECL|variable|child_handler_pipe
DECL|variable|children_deleted
DECL|variable|children_reaped
DECL|variable|children_spawned
DECL|variable|daemon_service
DECL|variable|daemon_usage
DECL|variable|dead_child
DECL|variable|export_all_trees
DECL|variable|init_timeout
DECL|variable|interp_table
DECL|variable|interpolated_path
DECL|variable|live_child
DECL|variable|log_syslog
DECL|variable|max_connections
DECL|variable|ok_paths
DECL|variable|reuseaddr
DECL|variable|saw_extended_args
DECL|variable|service_enabled
DECL|variable|service_looking_at
DECL|variable|strict_paths
DECL|variable|timeout
DECL|variable|user_path
DECL|variable|verbose
