DECL|function|approxidate_alpha
DECL|function|approxidate_careful
DECL|function|approxidate_digit
DECL|function|approxidate_relative
DECL|function|approxidate_str
DECL|function|date_am
DECL|function|date_midnight
DECL|function|date_never
DECL|function|date_noon
DECL|function|date_now
DECL|function|date_pm
DECL|function|date_string
DECL|function|date_tea
DECL|function|date_time
DECL|function|date_yesterday
DECL|function|datestamp
DECL|function|gm_time_t
DECL|function|is_date
DECL|function|local_tzoffset
DECL|function|match_alpha
DECL|function|match_digit
DECL|function|match_multi_number
DECL|function|match_object_header_date
DECL|function|match_string
DECL|function|match_tz
DECL|function|nodate
DECL|function|parse_date
DECL|function|parse_date_basic
DECL|function|parse_date_format
DECL|function|pending_number
DECL|function|show_date
DECL|function|show_date_relative
DECL|function|skip_alpha
DECL|function|time_to_tm
DECL|function|tm_to_time_t
DECL|function|update_tm
DECL|member|dst
DECL|member|fn
DECL|member|length
DECL|member|name
DECL|member|name
DECL|member|offset
DECL|member|type
DECL|struct|special
DECL|struct|typelen
DECL|variable|month_names
DECL|variable|number_name
DECL|variable|special
DECL|variable|timezone_names
DECL|variable|typelen
DECL|variable|weekday_names
