DECL|function|datestamp
DECL|function|is_date
DECL|function|match_alpha
DECL|function|match_digit
DECL|function|match_multi_number
DECL|function|match_string
DECL|function|match_tz
DECL|function|my_mktime
DECL|function|parse_date
DECL|function|show_date
DECL|function|skip_alpha
DECL|macro|NR_TZ
DECL|member|dst
DECL|member|name
DECL|member|offset
DECL|variable|month_names
DECL|variable|timezone_names
DECL|variable|weekday_names
