DECL|function|datestamp
DECL|function|match_alpha
DECL|function|match_digit
DECL|function|match_string
DECL|function|match_tz
DECL|function|my_mktime
DECL|function|parse_date
DECL|macro|NR_TZ
DECL|member|name
DECL|member|offset
DECL|variable|month_names
DECL|variable|timezone_names
DECL|variable|weekday_names
