DECL|function|lookup_delta
DECL|function|parse_delta_buffer
DECL|function|process_deltas
DECL|member|blob
DECL|member|commit
DECL|member|object
DECL|member|tag
DECL|member|tree
DECL|member|u
DECL|struct|delta
