DECL|function|main
DECL|function|show_file
DECL|function|show_modified
DECL|function|show_unmerge
DECL|variable|combine_merges
DECL|variable|dense_combined_merges
DECL|variable|diff_files_usage
DECL|variable|diff_unmerged_stage
DECL|variable|rev
DECL|variable|silent
