DECL|function|diff_cache
DECL|function|diff_index_show_file
DECL|function|do_diff_cache
DECL|function|get_stat_data
DECL|function|handle_diff_files_args
DECL|function|is_in_index
DECL|function|mark_merge_entries
DECL|function|queue_diff
DECL|function|read_directory
DECL|function|run_diff_files
DECL|function|run_diff_files_cmd
DECL|function|run_diff_index
DECL|function|show_modified
DECL|function|show_new_file
