DECL|macro|DEFAULT_MINIMUM_SCORE
DECL|macro|DIFF_FILE_VALID
DECL|macro|DIFF_PAIR_UNMERGED
DECL|macro|MAX_SCORE
DECL|macro|RENAME_DST_MATCHED
DECL|macro|RENAME_SCORE_SHIFT
DECL|macro|RENAME_SRC_GONE
DECL|macro|_DIFFCORE_H_
DECL|member|alloc
DECL|member|data
DECL|member|mode
DECL|member|nr
DECL|member|one
DECL|member|orig_order
DECL|member|path
DECL|member|queue
DECL|member|rename_rank
DECL|member|score
DECL|member|sha1
DECL|member|sha1_valid
DECL|member|should_free
DECL|member|should_munmap
DECL|member|size
DECL|member|status
DECL|member|two
DECL|member|xfrm_flags
DECL|struct|diff_filepair
DECL|struct|diff_filespec
DECL|struct|diff_queue_struct
