DECL|function|diff_cache
DECL|function|get_stat_data
DECL|function|main
DECL|function|mark_merge_entries
DECL|function|show_file
DECL|function|show_modified
DECL|function|show_new_file
DECL|variable|cached_only
DECL|variable|diff_cache_usage
DECL|variable|generate_patch
DECL|variable|line_termination
