DECL|macro|DEFAULT_BREAK_SCORE
DECL|macro|DEFAULT_MERGE_SCORE
DECL|macro|DEFAULT_RENAME_SCORE
DECL|macro|DIFFCORE_H
DECL|macro|DIFF_DEBUG
DECL|macro|DIFF_FILE_VALID
DECL|macro|DIFF_PAIR_BROKEN
DECL|macro|DIFF_PAIR_MODE_CHANGED
DECL|macro|DIFF_PAIR_RENAME
DECL|macro|DIFF_PAIR_TYPE_CHANGED
DECL|macro|DIFF_PAIR_UNMERGED
DECL|macro|DIFF_QUEUE_CLEAR
DECL|macro|DIRTY_SUBMODULE_MODIFIED
DECL|macro|DIRTY_SUBMODULE_UNTRACKED
DECL|macro|MAX_SCORE
DECL|macro|MINIMUM_BREAK_SIZE
DECL|macro|diff_debug_filepair
DECL|macro|diff_debug_filespec
DECL|macro|diff_debug_queue
DECL|member|alloc
DECL|member|broken_pair
DECL|member|cnt_data
DECL|member|count
DECL|member|data
DECL|member|dirty_submodule
DECL|member|driver
DECL|member|funcname_pattern_ident
DECL|member|is_binary
DECL|member|is_stdin
DECL|member|is_unmerged
DECL|member|mode
DECL|member|nr
DECL|member|one
DECL|member|path
DECL|member|queue
DECL|member|rename_used
DECL|member|renamed_pair
DECL|member|score
DECL|member|sha1
DECL|member|sha1_valid
DECL|member|should_free
DECL|member|should_munmap
DECL|member|size
DECL|member|status
DECL|member|two
DECL|member|xfrm_flags
DECL|struct|diff_filepair
DECL|struct|diff_filespec
DECL|struct|diff_queue_struct
