DECL|enumerator|DIFF_COMMIT
DECL|enumerator|DIFF_FILE_NEW
DECL|enumerator|DIFF_FILE_OLD
DECL|enumerator|DIFF_FRAGINFO
DECL|enumerator|DIFF_METAINFO
DECL|enumerator|DIFF_PLAIN
DECL|enumerator|DIFF_RESET
DECL|enumerator|DIFF_WHITESPACE
DECL|enum|color_diff
DECL|macro|COMMON_DIFF_OPTIONS_HELP
DECL|macro|DIFF_DETECT_COPY
DECL|macro|DIFF_DETECT_RENAME
DECL|macro|DIFF_FORMAT_CALLBACK
DECL|macro|DIFF_FORMAT_CHECKDIFF
DECL|macro|DIFF_FORMAT_DIFFSTAT
DECL|macro|DIFF_FORMAT_DIRSTAT
DECL|macro|DIFF_FORMAT_NAME
DECL|macro|DIFF_FORMAT_NAME_STATUS
DECL|macro|DIFF_FORMAT_NO_OUTPUT
DECL|macro|DIFF_FORMAT_NUMSTAT
DECL|macro|DIFF_FORMAT_PATCH
DECL|macro|DIFF_FORMAT_RAW
DECL|macro|DIFF_FORMAT_SHORTSTAT
DECL|macro|DIFF_FORMAT_SUMMARY
DECL|macro|DIFF_H
DECL|macro|DIFF_OPT_ALLOW_EXTERNAL
DECL|macro|DIFF_OPT_ALLOW_TEXTCONV
DECL|macro|DIFF_OPT_BINARY
DECL|macro|DIFF_OPT_CHECK_FAILED
DECL|macro|DIFF_OPT_CLR
DECL|macro|DIFF_OPT_COLOR_DIFF
DECL|macro|DIFF_OPT_COLOR_DIFF_WORDS
DECL|macro|DIFF_OPT_DIRSTAT_BY_FILE
DECL|macro|DIFF_OPT_DIRSTAT_CUMULATIVE
DECL|macro|DIFF_OPT_EXIT_WITH_STATUS
DECL|macro|DIFF_OPT_FIND_COPIES_HARDER
DECL|macro|DIFF_OPT_FOLLOW_RENAMES
DECL|macro|DIFF_OPT_FULL_INDEX
DECL|macro|DIFF_OPT_HAS_CHANGES
DECL|macro|DIFF_OPT_IGNORE_SUBMODULES
DECL|macro|DIFF_OPT_NO_INDEX
DECL|macro|DIFF_OPT_QUIET
DECL|macro|DIFF_OPT_RECURSIVE
DECL|macro|DIFF_OPT_RELATIVE_NAME
DECL|macro|DIFF_OPT_REVERSE_DIFF
DECL|macro|DIFF_OPT_SET
DECL|macro|DIFF_OPT_SILENT_ON_REMOVE
DECL|macro|DIFF_OPT_TEXT
DECL|macro|DIFF_OPT_TREE_IN_RECURSIVE
DECL|macro|DIFF_OPT_TST
DECL|macro|DIFF_PICKAXE_ALL
DECL|macro|DIFF_PICKAXE_REGEX
DECL|macro|DIFF_RACY_IS_MODIFIED
DECL|macro|DIFF_SETUP_REVERSE
DECL|macro|DIFF_SETUP_USE_CACHE
DECL|macro|DIFF_SETUP_USE_SIZE_CACHE
DECL|macro|DIFF_SILENT_ON_REMOVED
DECL|macro|DIFF_STATUS_ADDED
DECL|macro|DIFF_STATUS_COPIED
DECL|macro|DIFF_STATUS_DELETED
DECL|macro|DIFF_STATUS_FILTER_AON
DECL|macro|DIFF_STATUS_FILTER_BROKEN
DECL|macro|DIFF_STATUS_MODIFIED
DECL|macro|DIFF_STATUS_RENAMED
DECL|macro|DIFF_STATUS_TYPE_CHANGED
DECL|macro|DIFF_STATUS_UNKNOWN
DECL|macro|DIFF_STATUS_UNMERGED
DECL|macro|DIFF_XDL_CLR
DECL|macro|DIFF_XDL_SET
DECL|macro|DIFF_XDL_TST
DECL|macro|combine_diff_path_size
DECL|macro|diff_get_color_opt
DECL|member|a_prefix
DECL|member|abbrev
DECL|member|add_remove
DECL|member|b_prefix
DECL|member|break_opt
DECL|member|change
DECL|member|close_file
DECL|member|context
DECL|member|detect_rename
DECL|member|dirstat_percent
DECL|member|file
DECL|member|filter
DECL|member|flags
DECL|member|format_callback
DECL|member|format_callback_data
DECL|member|found_changes
DECL|member|interhunkcontext
DECL|member|len
DECL|member|line_termination
DECL|member|mode
DECL|member|mode
DECL|member|next
DECL|member|nr_paths
DECL|member|orderfile
DECL|member|output_format
DECL|member|parent
DECL|member|path
DECL|member|pathlens
DECL|member|paths
DECL|member|pickaxe
DECL|member|pickaxe_opts
DECL|member|prefix
DECL|member|prefix_length
DECL|member|rename_limit
DECL|member|rename_score
DECL|member|setup
DECL|member|sha1
DECL|member|sha1
DECL|member|single_follow
DECL|member|skip_stat_unmatch
DECL|member|stat_name_width
DECL|member|stat_sep
DECL|member|stat_width
DECL|member|status
DECL|member|warn_on_too_large_rename
DECL|member|word_regex
DECL|member|xdl_opts
DECL|struct|combine_diff_parent
DECL|struct|combine_diff_path
DECL|struct|diff_options
DECL|typedef|add_remove_fn_t
DECL|typedef|change_fn_t
DECL|typedef|diff_format_fn_t
