DECL|function|builtin_diff
DECL|function|diff_addremove
DECL|function|diff_change
DECL|function|diff_flush
DECL|function|diff_setup
DECL|function|diff_unmerge
DECL|function|estimate_similarity
DECL|function|external_diff
DECL|function|flush_remaining_diff
DECL|function|flush_rename_pair
DECL|function|free_data
DECL|function|free_held_diff
DECL|function|hold_diff
DECL|function|is_exact_match
DECL|function|matches_pathspec
DECL|function|populate_data
DECL|function|prep_temp_blob
DECL|function|prepare_temp_file
DECL|function|remove_tempfile
DECL|function|remove_tempfile_on_signal
DECL|function|run_external_diff
DECL|function|score_compare
DECL|function|sq_expand
DECL|function|work_tree_matches
DECL|macro|MATCHED
DECL|macro|MINIMUM_SCORE
DECL|macro|SHOULD_FREE
DECL|macro|SHOULD_MUNMAP
DECL|member|blob_sha1
DECL|member|data
DECL|member|dst
DECL|member|file_valid
DECL|member|flags
DECL|member|hex
DECL|member|it
DECL|member|mode
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|path
DECL|member|score
DECL|member|sha1_valid
DECL|member|size
DECL|member|src
DECL|member|tmp_path
DECL|struct|diff_score
DECL|struct|diff_spec
DECL|struct|diff_spec_hold
DECL|struct|diff_tempfile
DECL|variable|createdfile
DECL|variable|deletedfile
DECL|variable|detect_rename
DECL|variable|diff_opts
DECL|variable|diff_rename_minimum_score
DECL|variable|diff_temp
DECL|variable|null_sha1
DECL|variable|pathspec
DECL|variable|reverse_diff
DECL|variable|speccnt
