DECL|function|estimate_similarity
DECL|function|flush_renames
DECL|function|hold_spec
DECL|function|main
DECL|function|matches_pathspec
DECL|function|parse_diff_raw_output
DECL|function|parse_oneside_change
DECL|macro|MINIMUM_SCORE
DECL|member|matched
DECL|member|new
DECL|member|next
DECL|member|old
DECL|member|path
DECL|struct|diff_spec_hold
DECL|variable|createdfile
DECL|variable|deletedfile
DECL|variable|detect_rename
DECL|variable|diff_helper_usage
