DECL|function|call_diff_flush
DECL|function|diff_root_tree
DECL|function|diff_tree_commit
DECL|function|diff_tree_sha1_top
DECL|function|diff_tree_stdin
DECL|function|generate_header
DECL|function|main
DECL|variable|always_show_header
DECL|variable|combine_merges
DECL|variable|commit_format
DECL|variable|dense_combined_merges
DECL|variable|diff_options
DECL|variable|diff_tree_usage
DECL|variable|header
DECL|variable|header_prefix
DECL|variable|ignore_merges
DECL|variable|no_commit_id
DECL|variable|read_stdin
DECL|variable|show_root_diff
DECL|variable|verbose_header
