DECL|function|compare_pair_order
DECL|function|diffcore_order
DECL|function|match_order
DECL|function|prepare_order
DECL|member|order
DECL|member|orig_order
DECL|member|pair
DECL|struct|pair_order
DECL|variable|order
DECL|variable|order_cnt
