DECL|function|diff_rename_pool_add
DECL|function|diff_rename_pool_clear
DECL|function|diff_scoreopt_parse
DECL|function|diffcore_rename
DECL|function|estimate_similarity
DECL|function|is_exact_match
DECL|function|rank_compare
DECL|function|record_rename_pair
DECL|function|score_compare
DECL|macro|debug_queue
DECL|member|alloc
DECL|member|dst
DECL|member|nr
DECL|member|rank
DECL|member|s
DECL|member|score
DECL|member|src
DECL|struct|diff_rename_pool
DECL|struct|diff_score
