DECL|function|cha_alloc
DECL|function|cha_free
DECL|function|cha_init
DECL|function|delta_cleanup
DECL|function|delta_prepare
DECL|function|diff_delta
DECL|function|hashbits
DECL|macro|BLK_SIZE
DECL|macro|COPYOP_SIZE
DECL|macro|GR_PRIME
DECL|macro|HASH
DECL|macro|MIN
DECL|member|ancur
DECL|member|cha
DECL|member|fp
DECL|member|fphash
DECL|member|fphbits
DECL|member|icurr
DECL|member|isize
DECL|member|next
DECL|member|next
DECL|member|nsize
DECL|member|ptr
DECL|struct|s_bdfile
DECL|struct|s_bdrecord
DECL|struct|s_chanode
DECL|struct|s_chastore
DECL|typedef|bdfile_t
DECL|typedef|bdrecord_t
DECL|typedef|chanode_t
DECL|typedef|chastore_t
