DECL|function|compute_stays
DECL|function|diffcore_rename
DECL|function|estimate_similarity
DECL|function|is_exact_match
DECL|function|locate_rename_dst
DECL|function|record_rename_pair
DECL|function|register_rename_src
DECL|function|score_compare
DECL|member|dst
DECL|member|one
DECL|member|pair
DECL|member|score
DECL|member|score
DECL|member|src
DECL|member|src_path_left
DECL|member|two
DECL|struct|diff_rename_dst
DECL|struct|diff_rename_src
DECL|struct|diff_score
DECL|variable|rename_dst
DECL|variable|rename_dst_alloc
DECL|variable|rename_dst_nr
DECL|variable|rename_src
DECL|variable|rename_src_alloc
DECL|variable|rename_src_nr
