DECL|function|main
DECL|function|matches_pathspec
DECL|function|show_file
DECL|function|show_modified
DECL|function|show_unmerge
DECL|variable|detect_rename
DECL|variable|diff_files_usage
DECL|variable|generate_patch
DECL|variable|line_termination
DECL|variable|silent
