DECL|function|diff_no_index
DECL|function|get_mode
DECL|function|noindex_filespec
DECL|function|path_outside_repo
DECL|function|populate_from_stdin
DECL|function|queue_diff
DECL|function|read_directory
DECL|variable|file_from_standard_input
