DECL|function|call_diff_flush
DECL|function|call_diff_setup
DECL|function|compare_tree_entry
DECL|function|diff_root_tree
DECL|function|diff_tree
DECL|function|diff_tree_commit
DECL|function|diff_tree_sha1
DECL|function|diff_tree_sha1_top
DECL|function|diff_tree_stdin
DECL|function|extract
DECL|function|generate_header
DECL|function|get_commit_format
DECL|function|interesting
DECL|function|main
DECL|function|malloc_base
DECL|function|show_file
DECL|function|show_tree
DECL|function|update_tree_entry
DECL|variable|commit_format
DECL|variable|detect_rename
DECL|variable|diff_break_opt
DECL|variable|diff_filter
DECL|variable|diff_output_format
DECL|variable|diff_score_opt
DECL|variable|diff_setup_opt
DECL|variable|diff_tree_usage
DECL|variable|find_copies_harder
DECL|variable|header
DECL|variable|header_prefix
DECL|variable|ignore_merges
DECL|variable|nr_paths
DECL|variable|orderfile
DECL|variable|pathlens
DECL|variable|paths
DECL|variable|pickaxe
DECL|variable|pickaxe_opts
DECL|variable|read_stdin
DECL|variable|recursive
DECL|variable|show_root_diff
DECL|variable|show_tree_entry_in_recursive
DECL|variable|verbose_header
