DECL|function|diff_index_show_file
DECL|function|do_diff_cache
DECL|function|do_oneway_diff
DECL|function|get_mode
DECL|function|get_stat_data
DECL|function|handle_diff_files_args
DECL|function|is_in_index
DECL|function|is_outside_repo
DECL|function|mark_merge_entries
DECL|function|oneway_diff
DECL|function|queue_diff
DECL|function|read_directory
DECL|function|run_diff_files
DECL|function|run_diff_files_cmd
DECL|function|run_diff_index
DECL|function|setup_diff_no_index
DECL|function|show_modified
DECL|function|show_new_file
