DECL|function|main
DECL|function|show_file
DECL|function|show_modified
DECL|function|show_unmerge
DECL|variable|detect_rename
DECL|variable|diff_break_opt
DECL|variable|diff_files_usage
DECL|variable|diff_filter
DECL|variable|diff_output_format
DECL|variable|diff_score_opt
DECL|variable|diff_setup_opt
DECL|variable|orderfile
DECL|variable|pickaxe
DECL|variable|pickaxe_opts
DECL|variable|silent
