DECL|function|basename_same
DECL|function|diffcore_rename
DECL|function|estimate_similarity
DECL|function|find_exact_renames
DECL|function|find_identical_files
DECL|function|find_renames
DECL|function|find_same_files
DECL|function|free_similarity_list
DECL|function|hash_filespec
DECL|function|insert_file_table
DECL|function|locate_rename_dst
DECL|function|record_if_better
DECL|function|record_rename_pair
DECL|function|register_rename_src
DECL|function|score_compare
DECL|function|too_many_rename_candidates
DECL|macro|NUM_CANDIDATE_PER_DST
DECL|member|dst
DECL|member|filespec
DECL|member|index
DECL|member|name_score
DECL|member|next
DECL|member|one
DECL|member|pair
DECL|member|score
DECL|member|score
DECL|member|src
DECL|member|src_dst
DECL|member|two
DECL|struct|diff_rename_dst
DECL|struct|diff_rename_src
DECL|struct|diff_score
DECL|struct|file_similarity
DECL|variable|rename_dst
DECL|variable|rename_dst_alloc
DECL|variable|rename_dst_nr
DECL|variable|rename_src
DECL|variable|rename_src_alloc
DECL|variable|rename_src_nr
