DECL|function|check_removed
DECL|function|diff_index_show_file
DECL|function|do_diff_cache
DECL|function|do_oneway_diff
DECL|function|get_stat_data
DECL|function|mark_merge_entries
DECL|function|oneway_diff
DECL|function|run_diff_files
DECL|function|run_diff_index
DECL|function|show_modified
DECL|function|show_new_file
DECL|function|skip_same_name
DECL|member|revs
DECL|member|symcache
DECL|struct|oneway_unpack_data
