DECL|function|builtin_diff
DECL|function|diff_addremove
DECL|function|diff_change
DECL|function|diff_unmerge
DECL|function|external_diff
DECL|function|prep_temp_blob
DECL|function|prepare_temp_file
DECL|function|remove_tempfile
DECL|function|remove_tempfile_on_signal
DECL|function|run_external_diff
DECL|function|sq_expand
DECL|function|work_tree_matches
DECL|member|hex
DECL|member|mode
DECL|member|name
DECL|member|tmp_path
DECL|struct|diff_tempfile
DECL|variable|diff_opts
DECL|variable|diff_temp
