DECL|enumerator|DIFF_COMMIT
DECL|enumerator|DIFF_FILE_NEW
DECL|enumerator|DIFF_FILE_OLD
DECL|enumerator|DIFF_FRAGINFO
DECL|enumerator|DIFF_METAINFO
DECL|enumerator|DIFF_PLAIN
DECL|enumerator|DIFF_RESET
DECL|enum|color_diff
DECL|macro|COMMON_DIFF_OPTIONS_HELP
DECL|macro|DIFF_DETECT_COPY
DECL|macro|DIFF_DETECT_RENAME
DECL|macro|DIFF_FORMAT_CALLBACK
DECL|macro|DIFF_FORMAT_CHECKDIFF
DECL|macro|DIFF_FORMAT_DIFFSTAT
DECL|macro|DIFF_FORMAT_NAME
DECL|macro|DIFF_FORMAT_NAME_STATUS
DECL|macro|DIFF_FORMAT_NO_OUTPUT
DECL|macro|DIFF_FORMAT_PATCH
DECL|macro|DIFF_FORMAT_RAW
DECL|macro|DIFF_FORMAT_SUMMARY
DECL|macro|DIFF_H
DECL|macro|DIFF_PICKAXE_ALL
DECL|macro|DIFF_PICKAXE_REGEX
DECL|macro|DIFF_SETUP_REVERSE
DECL|macro|DIFF_SETUP_USE_CACHE
DECL|macro|DIFF_SETUP_USE_SIZE_CACHE
DECL|macro|DIFF_STATUS_ADDED
DECL|macro|DIFF_STATUS_COPIED
DECL|macro|DIFF_STATUS_DELETED
DECL|macro|DIFF_STATUS_FILTER_AON
DECL|macro|DIFF_STATUS_FILTER_BROKEN
DECL|macro|DIFF_STATUS_MODIFIED
DECL|macro|DIFF_STATUS_RENAMED
DECL|macro|DIFF_STATUS_TYPE_CHANGED
DECL|macro|DIFF_STATUS_UNKNOWN
DECL|macro|DIFF_STATUS_UNMERGED
DECL|macro|combine_diff_path_size
DECL|member|abbrev
DECL|member|add_remove
DECL|member|binary
DECL|member|break_opt
DECL|member|change
DECL|member|color_diff
DECL|member|color_diff_words
DECL|member|context
DECL|member|detect_rename
DECL|member|filter
DECL|member|find_copies_harder
DECL|member|format_callback
DECL|member|format_callback_data
DECL|member|full_index
DECL|member|len
DECL|member|line_termination
DECL|member|mode
DECL|member|mode
DECL|member|msg_sep
DECL|member|next
DECL|member|nr_paths
DECL|member|orderfile
DECL|member|output_format
DECL|member|parent
DECL|member|path
DECL|member|pathlens
DECL|member|paths
DECL|member|pickaxe
DECL|member|pickaxe_opts
DECL|member|recursive
DECL|member|rename_limit
DECL|member|rename_score
DECL|member|reverse_diff
DECL|member|setup
DECL|member|sha1
DECL|member|sha1
DECL|member|silent_on_remove
DECL|member|stat_name_width
DECL|member|stat_sep
DECL|member|stat_width
DECL|member|status
DECL|member|text
DECL|member|tree_in_recursive
DECL|member|xdl_opts
DECL|struct|combine_diff_parent
DECL|struct|combine_diff_path
DECL|struct|diff_options
DECL|typedef|add_remove_fn_t
DECL|typedef|change_fn_t
DECL|typedef|diff_format_fn_t
