DECL|function|create_delta
DECL|function|create_delta_index
DECL|function|free_delta_index
DECL|macro|BLK_SIZE
DECL|macro|COPYOP_SIZE
DECL|macro|GR_PRIME
DECL|macro|HASH
DECL|macro|HASH_LIMIT
DECL|macro|MAX_OP_SIZE
DECL|member|hash
DECL|member|hash_shift
DECL|member|next
DECL|member|ptr
DECL|member|src_buf
DECL|member|src_size
DECL|member|val
DECL|struct|delta_index
DECL|struct|index_entry
