DECL|enumerator|DIR_COLLECT_IGNORED
DECL|enumerator|DIR_COLLECT_KILLED_ONLY
DECL|enumerator|DIR_HIDE_EMPTY_DIRECTORIES
DECL|enumerator|DIR_NO_GITLINKS
DECL|enumerator|DIR_SHOW_IGNORED
DECL|enumerator|DIR_SHOW_IGNORED_TOO
DECL|enumerator|DIR_SHOW_OTHER_DIRECTORIES
DECL|function|ce_path_match
DECL|function|dir_path_match
DECL|function|is_dot_or_dotdot
DECL|macro|DIR_H
DECL|macro|EXC_CMDL
DECL|macro|EXC_DIRS
DECL|macro|EXC_FILE
DECL|macro|EXC_FLAG_ENDSWITH
DECL|macro|EXC_FLAG_MUSTBEDIR
DECL|macro|EXC_FLAG_NEGATIVE
DECL|macro|EXC_FLAG_NODIR
DECL|macro|MATCHED_EXACTLY
DECL|macro|MATCHED_FNMATCH
DECL|macro|MATCHED_RECURSIVELY
DECL|macro|REMOVE_DIR_EMPTY_ONLY
DECL|macro|REMOVE_DIR_KEEP_NESTED_GIT
DECL|macro|REMOVE_DIR_KEEP_TOPLEVEL
DECL|member|alloc
DECL|member|alloc
DECL|member|alloc
DECL|member|base
DECL|member|basebuf
DECL|member|baselen
DECL|member|baselen
DECL|member|check_only
DECL|member|dir_created
DECL|member|dir_flags
DECL|member|dir_invalidated
DECL|member|dir_opened
DECL|member|dirs
DECL|member|dirs_alloc
DECL|member|dirs_nr
DECL|member|el
DECL|member|el
DECL|member|entries
DECL|member|exclude
DECL|member|exclude_ix
DECL|member|exclude_list_group
DECL|member|exclude_per_dir
DECL|member|exclude_per_dir
DECL|member|exclude_sha1
DECL|member|exclude_stack
DECL|member|excludes
DECL|member|filebuf
DECL|member|flags
DECL|member|flags
DECL|member|gitignore_invalidated
DECL|member|ignored
DECL|member|ignored_alloc
DECL|member|ignored_nr
DECL|member|len
DECL|member|name
DECL|member|name
DECL|member|nowildcardlen
DECL|member|nr
DECL|member|nr
DECL|member|nr
DECL|member|pattern
DECL|member|patternlen
DECL|member|prev
DECL|member|recurse
DECL|member|root
DECL|member|sha1
DECL|member|src
DECL|member|srcpos
DECL|member|ss_excludes_file
DECL|member|ss_excludes_file
DECL|member|ss_info_exclude
DECL|member|ss_info_exclude
DECL|member|stat
DECL|member|stat_data
DECL|member|ucd
DECL|member|unmanaged_exclude_files
DECL|member|untracked
DECL|member|untracked
DECL|member|untracked_alloc
DECL|member|untracked_nr
DECL|member|valid
DECL|member|valid
DECL|struct|dir_entry
DECL|struct|dir_struct
DECL|struct|exclude
DECL|struct|exclude_list
DECL|struct|exclude_list_group
DECL|struct|exclude_stack
DECL|struct|sha1_stat
DECL|struct|untracked_cache
DECL|struct|untracked_cache_dir
