DECL|enumerator|index_directory
DECL|enumerator|index_gitdir
DECL|enumerator|index_nonexistent
DECL|enumerator|path_excluded
DECL|enumerator|path_none
DECL|enumerator|path_recurse
DECL|enumerator|path_untracked
DECL|enum|exist_status
DECL|enum|path_treatment
DECL|function|add_exclude
DECL|function|add_exclude_list
DECL|function|add_excludes
DECL|function|add_excludes_from_file
DECL|function|add_excludes_from_file_1
DECL|function|add_excludes_from_file_to_list
DECL|function|add_untracked
DECL|function|add_untracked_ident
DECL|function|clear_directory
DECL|function|clear_exclude_list
DECL|function|close_cached_dir
DECL|function|cmp_name
DECL|function|common_prefix
DECL|function|common_prefix_len
DECL|function|create_simplify
DECL|function|dir_add_ignored
DECL|function|dir_add_name
DECL|function|dir_entry_new
DECL|function|dir_inside_of
DECL|function|directory_exists_in_index
DECL|function|directory_exists_in_index_icase
DECL|function|do_invalidate_gitignore
DECL|function|do_match_pathspec
DECL|function|exclude_matches_pathspec
DECL|function|file_exists
DECL|function|fill_directory
DECL|function|fnmatch_icase
DECL|function|fnmatch_icase_mem
DECL|function|free_simplify
DECL|function|free_untracked
DECL|function|free_untracked_cache
DECL|function|get_dtype
DECL|function|get_ident_string
DECL|function|get_index_dtype
DECL|function|git_fnmatch
DECL|function|ident_in_untracked
DECL|function|invalidate_directory
DECL|function|invalidate_gitignore
DECL|function|is_empty_dir
DECL|function|is_excluded
DECL|function|is_excluded_from_list
DECL|function|is_inside_dir
DECL|function|last_exclude_matching
DECL|function|last_exclude_matching_from_list
DECL|function|last_exclude_matching_from_lists
DECL|function|load_sha1_stat
DECL|function|lookup_untracked
DECL|function|match_basename
DECL|function|match_pathname
DECL|function|match_pathspec
DECL|function|match_pathspec_item
DECL|function|no_wildcard
DECL|function|open_cached_dir
DECL|function|parse_exclude_pattern
DECL|function|prep_exclude
DECL|function|read_cached_dir
DECL|function|read_directory
DECL|function|read_directory_recursive
DECL|function|read_one_dir
DECL|function|read_sha1
DECL|function|read_skip_worktree_file_from_index
DECL|function|read_stat
DECL|function|read_untracked_extension
DECL|function|remove_dir_recurse
DECL|function|remove_dir_recursively
DECL|function|remove_path
DECL|function|set_check_only
DECL|function|setup_standard_excludes
DECL|function|simple_length
DECL|function|simplify_away
DECL|function|stat_data_from_disk
DECL|function|stat_data_to_disk
DECL|function|strcmp_icase
DECL|function|strncmp_icase
DECL|function|treat_directory
DECL|function|treat_leading_path
DECL|function|treat_one_path
DECL|function|treat_path
DECL|function|treat_path_fast
DECL|function|trim_trailing_spaces
DECL|function|untracked_cache_add_to_index
DECL|function|untracked_cache_invalidate_path
DECL|function|untracked_cache_remove_from_index
DECL|function|valid_cached_dir
DECL|function|validate_untracked_cache
DECL|function|within_depth
DECL|function|write_one_dir
DECL|function|write_untracked_extension
DECL|macro|DO_MATCH_DIRECTORY
DECL|macro|DO_MATCH_EXCLUDE
DECL|macro|ouc_size
DECL|member|check_only
DECL|member|check_only
DECL|member|data
DECL|member|de
DECL|member|dir_flags
DECL|member|end
DECL|member|exclude_per_dir
DECL|member|excludes_file_sha1
DECL|member|excludes_file_stat
DECL|member|fdir
DECL|member|file
DECL|member|index
DECL|member|index
DECL|member|info_exclude_sha1
DECL|member|info_exclude_stat
DECL|member|len
DECL|member|nr_dirs
DECL|member|nr_files
DECL|member|out
DECL|member|path
DECL|member|sb_sha1
DECL|member|sb_stat
DECL|member|sha1_valid
DECL|member|sha1_valid
DECL|member|ucd
DECL|member|ucd
DECL|member|untracked
DECL|member|valid
DECL|member|valid
DECL|struct|cached_dir
DECL|struct|ondisk_untracked_cache
DECL|struct|path_simplify
DECL|struct|read_data
DECL|struct|write_data
