DECL|enumerator|ignore_directory
DECL|enumerator|index_directory
DECL|enumerator|index_gitdir
DECL|enumerator|index_nonexistent
DECL|enumerator|recurse_into_directory
DECL|enumerator|show_directory
DECL|enum|directory_treatment
DECL|enum|exist_status
DECL|function|add_exclude
DECL|function|add_excludes_from_file
DECL|function|add_excludes_from_file_1
DECL|function|cmp_name
DECL|function|common_prefix
DECL|function|create_simplify
DECL|function|dir_add_ignored
DECL|function|dir_add_name
DECL|function|dir_entry_new
DECL|function|directory_exists_in_index
DECL|function|excluded
DECL|function|excluded_1
DECL|function|file_exists
DECL|function|free_simplify
DECL|function|get_dtype
DECL|function|get_relative_cwd
DECL|function|in_pathspec
DECL|function|is_empty_dir
DECL|function|is_inside_dir
DECL|function|match_one
DECL|function|match_pathspec
DECL|function|no_wildcard
DECL|function|prep_exclude
DECL|function|read_directory
DECL|function|read_directory_recursive
DECL|function|remove_dir_recursively
DECL|function|remove_path
DECL|function|setup_standard_excludes
DECL|function|simple_length
DECL|function|simplify_away
DECL|function|treat_directory
DECL|member|len
DECL|member|path
DECL|struct|path_simplify
