DECL|macro|DIR_H
DECL|macro|EXC_CMDL
DECL|macro|EXC_DIRS
DECL|macro|EXC_FILE
DECL|macro|EXC_FLAG_ENDSWITH
DECL|macro|EXC_FLAG_MUSTBEDIR
DECL|macro|EXC_FLAG_NODIR
DECL|macro|EXC_FLAG_NOWILDCARD
DECL|macro|MATCHED_EXACTLY
DECL|macro|MATCHED_FNMATCH
DECL|macro|MATCHED_RECURSIVELY
DECL|member|alloc
DECL|member|alloc
DECL|member|base
DECL|member|basebuf
DECL|member|baselen
DECL|member|baselen
DECL|member|collect_ignored
DECL|member|entries
DECL|member|exclude_ix
DECL|member|exclude_list
DECL|member|exclude_per_dir
DECL|member|exclude_stack
DECL|member|excludes
DECL|member|filebuf
DECL|member|flags
DECL|member|hide_empty_directories
DECL|member|ignored
DECL|member|ignored_alloc
DECL|member|ignored_nr
DECL|member|len
DECL|member|name
DECL|member|no_gitlinks
DECL|member|nr
DECL|member|nr
DECL|member|pattern
DECL|member|patternlen
DECL|member|prev
DECL|member|show_ignored
DECL|member|show_other_directories
DECL|member|to_exclude
DECL|struct|dir_entry
DECL|struct|dir_struct
DECL|struct|exclude
DECL|struct|exclude_list
DECL|struct|exclude_stack
