DECL|function|check_path
DECL|function|checkout_entry
DECL|function|create_directories
DECL|function|create_file
DECL|function|fstat_output
DECL|function|open_output_fd
DECL|function|read_blob_entry
DECL|function|remove_subtree
DECL|function|write_entry
