DECL|function|add
DECL|function|clear_fraction
DECL|function|compare
DECL|function|copy
DECL|function|divide
DECL|function|emit_stack
DECL|function|find_base
DECL|function|find_base_for_list
DECL|function|find_next_epoch_boundary
DECL|function|free_mass_counter
DECL|function|get_BN_CTX
DECL|function|get_one
DECL|function|get_zero
DECL|function|init_fraction
DECL|function|is_parent_of
DECL|function|mark_ancestors_uninteresting
DECL|function|new_mass_counter
DECL|function|new_zero
DECL|function|push_onto_merge_order_stack
DECL|function|sort_first_epoch
DECL|function|sort_in_merge_order
DECL|function|sort_list_in_merge_order
DECL|macro|HAS_EXACTLY_ONE_PARENT
DECL|member|denominator
DECL|member|numerator
DECL|member|pending
DECL|member|seen
DECL|struct|fraction
DECL|struct|mass_counter
DECL|variable|context
DECL|variable|one
DECL|variable|zero
