DECL|function|add_path
DECL|function|execl_git_cmd
DECL|function|execv_git_cmd
DECL|function|git_exec_path
DECL|function|git_set_argv0_path
DECL|function|git_set_argv_exec_path
DECL|function|prepare_git_cmd
DECL|function|setup_path
DECL|function|system_path
DECL|macro|MAX_ARGS
DECL|variable|argv0_path
DECL|variable|argv_exec_path
