DECL|function|encode_header
DECL|function|fixup_header_footer
DECL|function|init_pack_header
DECL|function|insert_object
DECL|function|main
DECL|function|new_object
DECL|function|oecmp
DECL|function|write_blob
DECL|function|write_index
DECL|function|yread
DECL|function|ywrite
DECL|member|next
DECL|member|next
DECL|member|oe
DECL|member|offset
DECL|member|sha1
DECL|struct|object_entry
DECL|struct|overflow_object_entry
DECL|variable|current_depth
DECL|variable|duplicate_count
DECL|variable|lastdat
DECL|variable|lastdatlen
DECL|variable|lastsha1
DECL|variable|max_depth
DECL|variable|object_count
DECL|variable|overflow
DECL|variable|overflow_count
DECL|variable|packfd
DECL|variable|packoff
DECL|variable|packsha1
DECL|variable|pool_end
DECL|variable|pool_next
DECL|variable|pool_start
DECL|variable|table
