DECL|enumerator|WHENSPEC_NOW
DECL|enumerator|WHENSPEC_RAW
DECL|enumerator|WHENSPEC_RFC2822
DECL|function|alloc_objects
DECL|function|cat_blob
DECL|function|cat_blob_write
DECL|function|change_note_fanout
DECL|function|checkpoint
DECL|function|checkpoint_signal
DECL|function|construct_path_with_fanout
DECL|function|convert_num_notes_to_fanout
DECL|function|create_index
DECL|function|cycle_packfile
DECL|function|die_nicely
DECL|function|do_change_note_fanout
DECL|function|dump_branches
DECL|function|dump_marks
DECL|function|dump_marks_helper
DECL|function|dump_tags
DECL|function|dup_tree_content
DECL|function|end_packfile
DECL|function|file_change_cr
DECL|function|file_change_d
DECL|function|file_change_deleteall
DECL|function|file_change_m
DECL|function|find_mark
DECL|function|find_object
DECL|function|get_mode
DECL|function|gfi_unpack_entry
DECL|function|git_pack_config
DECL|function|grow_tree_content
DECL|function|hc_entries
DECL|function|hc_str
DECL|function|insert_mark
DECL|function|insert_object
DECL|function|keep_pack
DECL|function|load_branch
DECL|function|load_tree
DECL|function|lookup_branch
DECL|function|main
DECL|function|make_fast_import_path
DECL|function|mktree
DECL|function|new_branch
DECL|function|new_object
DECL|function|new_tree_content
DECL|function|new_tree_entry
DECL|function|note_change_n
DECL|function|option_active_branches
DECL|function|option_cat_blob_fd
DECL|function|option_date_format
DECL|function|option_depth
DECL|function|option_export_marks
DECL|function|option_export_pack_edges
DECL|function|option_import_marks
DECL|function|parse_and_store_blob
DECL|function|parse_argv
DECL|function|parse_cat_blob
DECL|function|parse_checkpoint
DECL|function|parse_data
DECL|function|parse_feature
DECL|function|parse_from
DECL|function|parse_from_commit
DECL|function|parse_from_existing
DECL|function|parse_ident
DECL|function|parse_mark
DECL|function|parse_merge
DECL|function|parse_new_blob
DECL|function|parse_new_commit
DECL|function|parse_new_tag
DECL|function|parse_one_feature
DECL|function|parse_one_option
DECL|function|parse_option
DECL|function|parse_progress
DECL|function|parse_reset_branch
DECL|function|pool_alloc
DECL|function|pool_calloc
DECL|function|pool_strdup
DECL|function|read_marks
DECL|function|read_next_command
DECL|function|release_tree_content
DECL|function|release_tree_content_recursive
DECL|function|release_tree_entry
DECL|function|set_checkpoint_signal
DECL|function|set_checkpoint_signal
DECL|function|skip_optional_lf
DECL|function|start_packfile
DECL|function|store_object
DECL|function|store_tree
DECL|function|stream_blob
DECL|function|tecmp0
DECL|function|tecmp1
DECL|function|to_atom
DECL|function|tree_content_get
DECL|function|tree_content_remove
DECL|function|tree_content_replace
DECL|function|tree_content_set
DECL|function|truncate_pack
DECL|function|ulong_arg
DECL|function|unkeep_all_packs
DECL|function|unload_one_branch
DECL|function|update_branch
DECL|function|validate_raw_date
DECL|function|write_branch_report
DECL|function|write_crash_report
DECL|macro|DEPTH_BITS
DECL|macro|MAX_DEPTH
DECL|macro|MAX_PACK_ID
DECL|macro|PACK_ID_BITS
DECL|member|active
DECL|member|active_next_branch
DECL|member|branch_tree
DECL|member|buf
DECL|member|data
DECL|member|data
DECL|member|delta_depth
DECL|member|depth
DECL|member|depth
DECL|member|end
DECL|member|end
DECL|member|entries
DECL|member|entries
DECL|member|entry_capacity
DECL|member|entry_capacity
DECL|member|entry_count
DECL|member|idx
DECL|member|last_commit
DECL|member|marked
DECL|member|mode
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next_atom
DECL|member|next_avail
DECL|member|next_free
DECL|member|next_free
DECL|member|next_pool
DECL|member|next_pool
DECL|member|next_tag
DECL|member|no_swap
DECL|member|num_notes
DECL|member|offset
DECL|member|pack_id
DECL|member|pack_id
DECL|member|pack_id
DECL|member|prev
DECL|member|sets
DECL|member|sha1
DECL|member|sha1
DECL|member|sha1
DECL|member|sha1
DECL|member|shift
DECL|member|space
DECL|member|str_dat
DECL|member|str_len
DECL|member|table_next_branch
DECL|member|tree
DECL|member|type
DECL|member|versions
DECL|struct|atom_str
DECL|struct|avail_tree_content
DECL|struct|branch
DECL|struct|hash_list
DECL|struct|last_object
DECL|struct|mark_set
DECL|struct|mem_pool
DECL|struct|object_entry
DECL|struct|object_entry_pool
DECL|struct|recent_command
DECL|struct|tag
DECL|struct|tree_content
DECL|struct|tree_entry
DECL|struct|tree_entry_ms
DECL|typedef|whenspec_type
DECL|variable|active_branches
DECL|variable|all_packs
DECL|variable|alloc_count
DECL|variable|atom_cnt
DECL|variable|atom_table
DECL|variable|atom_table_sz
DECL|variable|avail_tree_entry
DECL|variable|avail_tree_table
DECL|variable|avail_tree_table_sz
DECL|variable|big_file_threshold
DECL|variable|blocks
DECL|variable|branch_count
DECL|variable|branch_load_count
DECL|variable|branch_table
DECL|variable|branch_table_sz
DECL|variable|cat_blob_fd
DECL|variable|checkpoint_requested
DECL|variable|cmd_hist
DECL|variable|cmd_save
DECL|variable|cmd_tail
DECL|variable|command_buf
DECL|variable|cur_active_branches
DECL|variable|delta_count_by_type
DECL|variable|duplicate_count_by_type
DECL|variable|export_marks_file
DECL|variable|failure
DECL|variable|fast_import_usage
DECL|variable|first_tag
DECL|variable|force_update
DECL|variable|global_argc
DECL|variable|global_argv
DECL|variable|import_marks_file
DECL|variable|import_marks_file_from_stream
DECL|variable|import_marks_file_ignore_missing
DECL|variable|last_blob
DECL|variable|last_tag
DECL|variable|marks
DECL|variable|marks_set_count
DECL|variable|max_active_branches
DECL|variable|max_depth
DECL|variable|max_packsize
DECL|variable|mem_pool
DECL|variable|mem_pool_alloc
DECL|variable|new_data
DECL|variable|new_tree
DECL|variable|next_mark
DECL|variable|object_count
DECL|variable|object_count_by_type
DECL|variable|object_entry_alloc
DECL|variable|object_table
DECL|variable|old_tree
DECL|variable|pack_compression_level
DECL|variable|pack_compression_seen
DECL|variable|pack_data
DECL|variable|pack_edges
DECL|variable|pack_file
DECL|variable|pack_id
DECL|variable|pack_idx_opts
DECL|variable|pack_size
DECL|variable|rc_free
DECL|variable|relative_marks_paths
DECL|variable|seen_data_command
DECL|variable|show_stats
DECL|variable|total_allocd
DECL|variable|tree_entry_alloc
DECL|variable|unread_command_buf
DECL|variable|whenspec
