DECL|macro|FETCH_PACK_H
DECL|member|depth
DECL|member|fetch_all
DECL|member|include_tag
DECL|member|keep_pack
DECL|member|lock_pack
DECL|member|no_progress
DECL|member|quiet
DECL|member|stateless_rpc
DECL|member|unpacklimit
DECL|member|uploadpack
DECL|member|use_thin_pack
DECL|member|verbose
DECL|struct|fetch_pack_args
