DECL|function|everything_local
DECL|function|fetch_pack
DECL|function|filter_refs
DECL|function|find_common
DECL|function|get_rev
DECL|function|main
DECL|function|mark_common
DECL|function|mark_complete
DECL|function|mark_recent_complete_commits
DECL|function|rev_list_insert_ref
DECL|function|rev_list_push
DECL|macro|COMMON
DECL|macro|COMMON_REF
DECL|macro|COMPLETE
DECL|macro|POPPED
DECL|macro|SEEN
DECL|variable|complete
DECL|variable|exec
DECL|variable|fetch_pack_usage
DECL|variable|keep_pack
DECL|variable|multi_ack
DECL|variable|non_common_revs
DECL|variable|quiet
DECL|variable|rev_list
DECL|variable|use_thin_pack
DECL|variable|verbose
