DECL|function|everything_local
DECL|function|fetch_pack
DECL|function|fetch_pack_config
DECL|function|filter_refs
DECL|function|find_common
DECL|function|get_pack
DECL|function|get_rev
DECL|function|main
DECL|function|mark_common
DECL|function|mark_complete
DECL|function|mark_recent_complete_commits
DECL|function|remove_duplicates
DECL|function|rev_list_insert_ref
DECL|function|rev_list_push
DECL|function|setup_sideband
DECL|macro|COMMON
DECL|macro|COMMON_REF
DECL|macro|COMPLETE
DECL|macro|MAX_IN_VAIN
DECL|macro|POPPED
DECL|macro|SEEN
DECL|variable|complete
DECL|variable|depth
DECL|variable|fetch_all
DECL|variable|fetch_pack_usage
DECL|variable|fetch_unpack_limit
DECL|variable|keep_pack
DECL|variable|lock
DECL|variable|multi_ack
DECL|variable|non_common_revs
DECL|variable|quiet
DECL|variable|rev_list
DECL|variable|transfer_unpack_limit
DECL|variable|unpack_limit
DECL|variable|uploadpack
DECL|variable|use_sideband
DECL|variable|use_thin_pack
DECL|variable|verbose
