DECL|function|interpret_target
DECL|function|loop
DECL|function|mark_complete
DECL|function|process
DECL|function|process_commit
DECL|function|process_object
DECL|function|process_tag
DECL|function|process_tree
DECL|function|pull
DECL|function|pull_say
DECL|function|pull_targets_free
DECL|function|pull_targets_stdin
DECL|function|report_missing
DECL|macro|COMPLETE
DECL|macro|SEEN
DECL|macro|TO_SCAN
DECL|variable|complete
DECL|variable|current_commit_sha1
DECL|variable|get_all
DECL|variable|get_history
DECL|variable|get_recover
DECL|variable|get_tree
DECL|variable|get_verbosely
DECL|variable|process_queue
DECL|variable|process_queue_end
