DECL|function|interpret_target
DECL|function|loop
DECL|function|make_sure_we_have_it
DECL|function|mark_complete
DECL|function|process
DECL|function|process_commit
DECL|function|process_object
DECL|function|process_tag
DECL|function|process_tree
DECL|function|pull
DECL|function|pull_say
DECL|function|report_missing
DECL|variable|complete
DECL|variable|current_commit_sha1
DECL|variable|current_ref
DECL|variable|get_all
DECL|variable|get_history
DECL|variable|get_tree
DECL|variable|get_verbosely
DECL|variable|process_queue
DECL|variable|process_queue_end
DECL|variable|write_ref
