DECL|enumerator|FOREACH_MSG_ID
DECL|enum|fsck_msg_id
DECL|function|append_msg_id
DECL|function|fsck_commit
DECL|function|fsck_commit_buffer
DECL|function|fsck_error_function
DECL|function|fsck_ident
DECL|function|fsck_msg_type
DECL|function|fsck_object
DECL|function|fsck_set_msg_type
DECL|function|fsck_set_msg_types
DECL|function|fsck_tag
DECL|function|fsck_tag_buffer
DECL|function|fsck_tree
DECL|function|fsck_walk
DECL|function|fsck_walk_commit
DECL|function|fsck_walk_tag
DECL|function|fsck_walk_tree
DECL|function|is_valid_msg_type
DECL|function|parse_msg_id
DECL|function|parse_msg_type
DECL|function|report
DECL|function|require_end_of_header
DECL|function|verify_ordered
DECL|macro|FOREACH_MSG_ID
DECL|macro|MSG_ID
DECL|macro|MSG_ID
DECL|macro|MSG_ID
DECL|macro|MSG_ID
DECL|macro|STR
DECL|macro|TREE_HAS_DUPS
DECL|macro|TREE_UNORDERED
DECL|member|downcased
DECL|member|id_string
DECL|member|msg_type
DECL|variable|msg_id_info
