DECL|function|add_sha1_list
DECL|function|check_connectivity
DECL|function|fsck_cache_tree
DECL|function|fsck_commit
DECL|function|fsck_dir
DECL|function|fsck_handle_ref
DECL|function|fsck_handle_reflog_ent
DECL|function|fsck_head_link
DECL|function|fsck_object_dir
DECL|function|fsck_sha1
DECL|function|fsck_sha1_list
DECL|function|fsck_tag
DECL|function|fsck_tree
DECL|function|get_default_heads
DECL|function|ino_compare
DECL|function|main
DECL|function|objerror
DECL|function|objreport
DECL|function|objwarning
DECL|function|verify_ordered
DECL|macro|DIRENT_SORT_HINT
DECL|macro|DIRENT_SORT_HINT
DECL|macro|MAX_SHA1_ENTRIES
DECL|macro|REACHABLE
DECL|macro|SEEN
DECL|macro|SORT_DIRENT
DECL|macro|SORT_DIRENT
DECL|macro|TREE_HAS_DUPS
DECL|macro|TREE_UNORDERED
DECL|member|entry
DECL|member|ino
DECL|member|nr
DECL|member|sha1
DECL|struct|sha1_entry
DECL|variable|check_full
DECL|variable|check_strict
DECL|variable|default_refs
DECL|variable|head_sha1
DECL|variable|keep_cache_objects
DECL|variable|sha1_list
DECL|variable|show_root
DECL|variable|show_tags
DECL|variable|show_unreachable
