DECL|macro|FSCK_ERROR
DECL|macro|FSCK_OPTIONS_DEFAULT
DECL|macro|FSCK_OPTIONS_STRICT
DECL|macro|FSCK_WARN
DECL|macro|GIT_FSCK_H
DECL|member|error_func
DECL|member|msg_type
DECL|member|strict
DECL|member|walk
DECL|struct|fsck_options
DECL|typedef|fsck_error
DECL|typedef|fsck_walk_func
