DECL|function|check_connectivity
DECL|function|compare_seen
DECL|function|fsck_commit
DECL|function|fsck_dir
DECL|function|fsck_entry
DECL|function|fsck_name
DECL|function|fsck_tree
DECL|function|lookup_seen
DECL|function|main
DECL|function|mark_needs_sha1
DECL|function|mark_sha1_seen
DECL|member|needed
DECL|member|needs
DECL|member|parent
DECL|member|sha1
DECL|member|tag
DECL|member|tag
DECL|struct|needs
DECL|struct|seen
DECL|variable|alloc_needs
DECL|variable|alloc_seen
DECL|variable|needs
DECL|variable|nr_needs
DECL|variable|nr_seen
DECL|variable|seen
