DECL|function|add_relationship
DECL|function|check_connectivity
DECL|function|find_rev
DECL|function|fsck_commit
DECL|function|fsck_dir
DECL|function|fsck_entry
DECL|function|fsck_name
DECL|function|fsck_tree
DECL|function|lookup_rev
DECL|function|main
DECL|function|mark_needs_sha1
DECL|function|mark_reachable
DECL|function|mark_sha1_seen
DECL|macro|MAX_COMMITS
DECL|macro|REACHABLE
DECL|macro|SEEN
DECL|macro|USED
DECL|macro|marked
DECL|member|date
DECL|member|flags
DECL|member|next
DECL|member|parent
DECL|member|parent
DECL|member|sha1
DECL|struct|parent
DECL|struct|revision
DECL|variable|head_sha1
DECL|variable|head_supplied
DECL|variable|nr_revs
DECL|variable|rev_allocs
DECL|variable|revs
DECL|variable|show_unreachable
