DECL|function|add_sha1_list
DECL|function|check_connectivity
DECL|function|fsck_commit
DECL|function|fsck_dir
DECL|function|fsck_sha1
DECL|function|fsck_sha1_list
DECL|function|fsck_tag
DECL|function|fsck_tree
DECL|function|ino_compare
DECL|function|main
DECL|function|verify_ordered
DECL|macro|MAX_SHA1_ENTRIES
DECL|macro|REACHABLE
DECL|macro|TREE_HAS_DUPS
DECL|macro|TREE_UNORDERED
DECL|member|entry
DECL|member|ino
DECL|member|nr
DECL|member|sha1
DECL|struct|sha1_entry
DECL|variable|head_sha1
DECL|variable|keep_cache_objects
DECL|variable|sha1_list
DECL|variable|show_root
DECL|variable|show_tags
DECL|variable|show_unreachable
