DECL|function|Q_
DECL|function|_
DECL|function|git_setup_gettext
DECL|macro|FORMAT_PRESERVING
DECL|macro|GETTEXT_H
DECL|macro|N_
DECL|macro|gettext
DECL|macro|gettext
DECL|macro|ngettext
DECL|macro|ngettext
DECL|macro|use_gettext_poison
