DECL|function|gitmempcpy
DECL|function|gitstrchrnul
DECL|function|has_extension
DECL|function|sane_case
DECL|function|skip_prefix
DECL|function|strtol_i
DECL|function|strtoul_ui
DECL|function|xsize_t
DECL|macro|ARRAY_SIZE
DECL|macro|DEFAULT_PACKED_GIT_LIMIT
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|DIV_ROUND_UP
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FORCE_DIR_SET_GID
DECL|macro|FORCE_DIR_SET_GID
DECL|macro|GIT_ALPHA
DECL|macro|GIT_COMPAT_UTIL_H
DECL|macro|GIT_DIGIT
DECL|macro|GIT_GLOB_SPECIAL
DECL|macro|GIT_REGEX_SPECIAL
DECL|macro|GIT_SPACE
DECL|macro|HAS_MULTI_BITS
DECL|macro|HAVE_MEMPCPY
DECL|macro|HAVE_STRCHRNUL
DECL|macro|MAP_FAILED
DECL|macro|MAP_PRIVATE
DECL|macro|MSB
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|NORETURN_PTR
DECL|macro|NORETURN_PTR
DECL|macro|NORETURN_PTR
DECL|macro|NORETURN_PTR
DECL|macro|PATH_MAX
DECL|macro|PATH_SEP
DECL|macro|PRIo32
DECL|macro|PRIu32
DECL|macro|PRIuMAX
DECL|macro|PRIx32
DECL|macro|PROT_READ
DECL|macro|PROT_WRITE
DECL|macro|STRIP_EXTENSION
DECL|macro|ST_CTIME_NSEC
DECL|macro|ST_CTIME_NSEC
DECL|macro|ST_CTIME_NSEC
DECL|macro|ST_MTIME_NSEC
DECL|macro|ST_MTIME_NSEC
DECL|macro|ST_MTIME_NSEC
DECL|macro|TYPEOF
DECL|macro|TYPEOF
DECL|macro|USE_NSEC
DECL|macro|WIN32_LEAN_AND_MEAN
DECL|macro|_ALL_SOURCE
DECL|macro|_ALL_SOURCE
DECL|macro|_ALL_SOURCE
DECL|macro|_BSD_SOURCE
DECL|macro|_FILE_OFFSET_BITS
DECL|macro|_GNU_SOURCE
DECL|macro|_NETBSD_SOURCE
DECL|macro|_PATH_DEFPATH
DECL|macro|_SGI_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE_EXTENDED
DECL|macro|__attribute__
DECL|macro|basename
DECL|macro|bitsizeof
DECL|macro|decimal_length
DECL|macro|find_last_dir_sep
DECL|macro|fopen
DECL|macro|fopen
DECL|macro|fstat_is_reliable
DECL|macro|fstat_is_reliable
DECL|macro|has_dos_drive_prefix
DECL|macro|hstrerror
DECL|macro|is_dir_sep
DECL|macro|is_glob_special
DECL|macro|is_regex_special
DECL|macro|isalnum
DECL|macro|isalnum
DECL|macro|isalpha
DECL|macro|isalpha
DECL|macro|isascii
DECL|macro|isascii
DECL|macro|isdigit
DECL|macro|isdigit
DECL|macro|isspace
DECL|macro|isspace
DECL|macro|maximum_signed_value_of_type
DECL|macro|maximum_unsigned_value_of_type
DECL|macro|memmem
DECL|macro|mempcpy
DECL|macro|mkdtemp
DECL|macro|mkstemps
DECL|macro|mmap
DECL|macro|munmap
DECL|macro|on_disk_bytes
DECL|macro|on_disk_bytes
DECL|macro|pread
DECL|macro|qsort
DECL|macro|sane_istest
DECL|macro|setenv
DECL|macro|signed_add_overflows
DECL|macro|snprintf
DECL|macro|strcasestr
DECL|macro|strchrnul
DECL|macro|strlcpy
DECL|macro|strtok_r
DECL|macro|strtoumax
DECL|macro|tolower
DECL|macro|tolower
DECL|macro|toupper
DECL|macro|toupper
DECL|macro|unsetenv
DECL|macro|unsigned_add_overflows
DECL|macro|vsnprintf
DECL|typedef|try_to_free_t
