DECL|function|has_extension
DECL|function|sane_case
DECL|function|xcalloc
DECL|function|xmalloc
DECL|function|xmmap
DECL|function|xread
DECL|function|xrealloc
DECL|function|xstrdup
DECL|function|xwrite
DECL|macro|ARRAY_SIZE
DECL|macro|DEFAULT_PACKED_GIT_LIMIT
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|GIT_ALPHA
DECL|macro|GIT_COMPAT_UTIL_H
DECL|macro|GIT_DIGIT
DECL|macro|GIT_SPACE
DECL|macro|MAP_FAILED
DECL|macro|MAP_PRIVATE
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|PATH_MAX
DECL|macro|PROT_READ
DECL|macro|PROT_WRITE
DECL|macro|_BSD_SOURCE
DECL|macro|_GNU_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE_EXTENDED
DECL|macro|__attribute__
DECL|macro|isalnum
DECL|macro|isalnum
DECL|macro|isalpha
DECL|macro|isalpha
DECL|macro|isdigit
DECL|macro|isdigit
DECL|macro|isspace
DECL|macro|isspace
DECL|macro|mmap
DECL|macro|munmap
DECL|macro|sane_istest
DECL|macro|setenv
DECL|macro|strcasestr
DECL|macro|strlcpy
DECL|macro|tolower
DECL|macro|tolower
DECL|macro|toupper
DECL|macro|toupper
DECL|macro|unsetenv
