DECL|function|gitstrchrnul
DECL|function|has_extension
DECL|function|sane_case
DECL|function|skip_prefix
DECL|function|strtol_i
DECL|function|strtoul_ui
DECL|function|xsize_t
DECL|macro|ARRAY_SIZE
DECL|macro|DEFAULT_PACKED_GIT_LIMIT
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|DEFAULT_PACKED_GIT_WINDOW_SIZE
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FLEX_ARRAY
DECL|macro|FORCE_DIR_SET_GID
DECL|macro|FORCE_DIR_SET_GID
DECL|macro|GIT_ALPHA
DECL|macro|GIT_COMPAT_UTIL_H
DECL|macro|GIT_DIGIT
DECL|macro|GIT_SPACE
DECL|macro|HAS_MULTI_BITS
DECL|macro|HAVE_STRCHRNUL
DECL|macro|MAP_FAILED
DECL|macro|MAP_PRIVATE
DECL|macro|MSB
DECL|macro|NORETURN
DECL|macro|NORETURN
DECL|macro|PATH_MAX
DECL|macro|PATH_SEP
DECL|macro|PRIu32
DECL|macro|PRIuMAX
DECL|macro|PRIx32
DECL|macro|PROT_READ
DECL|macro|PROT_WRITE
DECL|macro|STRIP_EXTENSION
DECL|macro|TYPEOF
DECL|macro|TYPEOF
DECL|macro|_ALL_SOURCE
DECL|macro|_ALL_SOURCE
DECL|macro|_ALL_SOURCE
DECL|macro|_BSD_SOURCE
DECL|macro|_FILE_OFFSET_BITS
DECL|macro|_GNU_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|macro|_XOPEN_SOURCE_EXTENDED
DECL|macro|__attribute__
DECL|macro|decimal_length
DECL|macro|fopen
DECL|macro|fopen
DECL|macro|has_dos_drive_prefix
DECL|macro|hstrerror
DECL|macro|is_dir_sep
DECL|macro|isalnum
DECL|macro|isalnum
DECL|macro|isalpha
DECL|macro|isalpha
DECL|macro|isdigit
DECL|macro|isdigit
DECL|macro|isspace
DECL|macro|isspace
DECL|macro|memmem
DECL|macro|mkdtemp
DECL|macro|mmap
DECL|macro|munmap
DECL|macro|pread
DECL|macro|qsort
DECL|macro|sane_istest
DECL|macro|setenv
DECL|macro|snprintf
DECL|macro|strcasestr
DECL|macro|strchrnul
DECL|macro|strlcpy
DECL|macro|strtoumax
DECL|macro|tolower
DECL|macro|tolower
DECL|macro|toupper
DECL|macro|toupper
DECL|macro|unsetenv
DECL|macro|vsnprintf
