DECL|function|list_commands
DECL|function|main
DECL|function|mput_char
DECL|function|prepend_to_path
DECL|function|pretty_print_string_list
DECL|function|term_columns
DECL|function|usage
DECL|macro|PATH_MAX
DECL|member|len
DECL|member|next
DECL|member|str
DECL|struct|string_list
DECL|variable|git_usage
