DECL|function|git_alias_config
DECL|function|handle_alias
DECL|function|handle_internal_command
DECL|function|handle_options
DECL|function|main
DECL|function|prepend_to_path
DECL|function|split_cmdline
DECL|macro|NEEDS_PREFIX
DECL|macro|USE_PAGER
DECL|variable|alias_command
DECL|variable|alias_string
DECL|variable|git_usage_string
DECL|variable|git_version_string
