DECL|function|get_signing_key
DECL|function|git_gpg_config
DECL|function|parse_gpg_output
DECL|function|set_signing_key
DECL|function|sign_buffer
DECL|function|signature_check_clear
DECL|function|verify_signed_buffer
DECL|member|check
DECL|member|result
DECL|variable|configured_signing_key
DECL|variable|gpg_program
DECL|variable|sigcheck_gpg_status
