DECL|function|append_grep_pat
DECL|function|append_grep_pattern
DECL|function|append_header_grep_pattern
DECL|function|chk_hit_marker
DECL|function|clr_hit_marker
DECL|function|compile_grep_patterns
DECL|function|compile_pattern_and
DECL|function|compile_pattern_atom
DECL|function|compile_pattern_expr
DECL|function|compile_pattern_not
DECL|function|compile_pattern_or
DECL|function|compile_pcre_regexp
DECL|function|compile_pcre_regexp
DECL|function|compile_regexp
DECL|function|compile_regexp_failed
DECL|function|end_of_line
DECL|function|fixmatch
DECL|function|free_grep_patterns
DECL|function|free_pattern_expr
DECL|function|free_pcre_regexp
DECL|function|free_pcre_regexp
DECL|function|grep_attr_lock
DECL|function|grep_attr_unlock
DECL|function|grep_buffer
DECL|function|grep_opt_dup
DECL|function|grep_or_expr
DECL|function|grep_source
DECL|function|grep_source_1
DECL|function|grep_source_clear
DECL|function|grep_source_clear_data
DECL|function|grep_source_init
DECL|function|grep_source_is_binary
DECL|function|grep_source_load
DECL|function|grep_source_load_driver
DECL|function|grep_source_load_file
DECL|function|grep_source_load_sha1
DECL|function|grep_true_expr
DECL|function|is_fixed
DECL|function|look_ahead
DECL|function|match_expr
DECL|function|match_expr_eval
DECL|function|match_funcname
DECL|function|match_line
DECL|function|match_next_pattern
DECL|function|match_one_pattern
DECL|function|next_match
DECL|function|output_color
DECL|function|output_sep
DECL|function|patmatch
DECL|function|pcrematch
DECL|function|pcrematch
DECL|function|prep_header_patterns
DECL|function|regmatch
DECL|function|should_lookahead
DECL|function|show_funcname_line
DECL|function|show_line
DECL|function|show_name
DECL|function|show_pre_context
DECL|function|std_output
DECL|function|strip_timestamp
DECL|function|word_char
DECL|macro|grep_attr_lock
DECL|macro|grep_attr_unlock
DECL|member|field
DECL|member|len
DECL|variable|grep_attr_mutex
DECL|variable|grep_read_mutex
DECL|variable|grep_use_locks
DECL|variable|header_field
