DECL|function|append_grep_pattern
DECL|function|buffer_is_binary
DECL|function|compile_grep_patterns
DECL|function|compile_pattern_and
DECL|function|compile_pattern_atom
DECL|function|compile_pattern_expr
DECL|function|compile_pattern_not
DECL|function|compile_pattern_or
DECL|function|compile_regexp
DECL|function|end_of_line
DECL|function|fixmatch
DECL|function|grep_buffer
DECL|function|match_expr
DECL|function|match_expr_eval
DECL|function|match_line
DECL|function|match_one_pattern
DECL|function|show_line
DECL|function|word_char
DECL|macro|FIRST_FEW_BYTES
