DECL|enumerator|GREP_AND
DECL|enumerator|GREP_CLOSE_PAREN
DECL|enumerator|GREP_CONTEXT_BODY
DECL|enumerator|GREP_CONTEXT_HEAD
DECL|enumerator|GREP_HEADER_AUTHOR
DECL|enumerator|GREP_HEADER_COMMITTER
DECL|enumerator|GREP_NODE_AND
DECL|enumerator|GREP_NODE_ATOM
DECL|enumerator|GREP_NODE_NOT
DECL|enumerator|GREP_NODE_OR
DECL|enumerator|GREP_NOT
DECL|enumerator|GREP_OPEN_PAREN
DECL|enumerator|GREP_OR
DECL|enumerator|GREP_PATTERN
DECL|enumerator|GREP_PATTERN_BODY
DECL|enumerator|GREP_PATTERN_HEAD
DECL|enum|grep_context
DECL|enum|grep_expr_node
DECL|enum|grep_header_field
DECL|enum|grep_pat_token
DECL|macro|GREP_BINARY_DEFAULT
DECL|macro|GREP_BINARY_NOMATCH
DECL|macro|GREP_BINARY_TEXT
DECL|macro|GREP_H
DECL|member|all_match
DECL|member|atom
DECL|member|binary
DECL|member|binary
DECL|member|color
DECL|member|color_match
DECL|member|count
DECL|member|extended
DECL|member|field
DECL|member|fixed
DECL|member|fixed
DECL|member|funcname
DECL|member|hit
DECL|member|ignore_case
DECL|member|ignore_case
DECL|member|invert
DECL|member|last_shown
DECL|member|left
DECL|member|linenum
DECL|member|max_depth
DECL|member|name_only
DECL|member|next
DECL|member|no
DECL|member|node
DECL|member|null_following_name
DECL|member|origin
DECL|member|output
DECL|member|output_priv
DECL|member|pathname
DECL|member|pattern
DECL|member|pattern_expression
DECL|member|pattern_list
DECL|member|pattern_tail
DECL|member|post_context
DECL|member|pre_context
DECL|member|prefix
DECL|member|prefix_length
DECL|member|priv
DECL|member|regexp
DECL|member|regexp
DECL|member|regflags
DECL|member|relative
DECL|member|right
DECL|member|show_hunk_mark
DECL|member|status_only
DECL|member|token
DECL|member|u
DECL|member|unary
DECL|member|unmatch_name_only
DECL|member|word_regexp
DECL|member|word_regexp
DECL|struct|grep_expr
DECL|struct|grep_opt
DECL|struct|grep_pat
