DECL|function|append_grep_pattern
DECL|function|append_header_grep_pattern
DECL|function|chk_hit_marker
DECL|function|clr_hit_marker
DECL|function|compile_grep_patterns
DECL|function|compile_pattern_and
DECL|function|compile_pattern_atom
DECL|function|compile_pattern_expr
DECL|function|compile_pattern_not
DECL|function|compile_pattern_or
DECL|function|compile_regexp
DECL|function|end_of_line
DECL|function|fixmatch
DECL|function|free_grep_patterns
DECL|function|free_pattern_expr
DECL|function|grep_buffer
DECL|function|grep_buffer_1
DECL|function|grep_opt_dup
DECL|function|grep_threads_ok
DECL|function|look_ahead
DECL|function|match_expr
DECL|function|match_expr_eval
DECL|function|match_funcname
DECL|function|match_line
DECL|function|match_next_pattern
DECL|function|match_one_pattern
DECL|function|next_match
DECL|function|should_lookahead
DECL|function|show_funcname_line
DECL|function|show_line
DECL|function|show_name
DECL|function|show_pre_context
DECL|function|std_output
DECL|function|strip_timestamp
DECL|function|word_char
DECL|member|field
DECL|member|len
DECL|variable|header_field
