DECL|function|alloc_table
DECL|function|always_equal
DECL|function|bucket
DECL|function|entry_equals
DECL|function|find_entry_ptr
DECL|function|hashmap_add
DECL|function|hashmap_free
DECL|function|hashmap_get
DECL|function|hashmap_get_next
DECL|function|hashmap_init
DECL|function|hashmap_iter_init
DECL|function|hashmap_iter_next
DECL|function|hashmap_put
DECL|function|hashmap_remove
DECL|function|memhash
DECL|function|memihash
DECL|function|memintern
DECL|function|pool_entry_cmp
DECL|function|rehash
DECL|function|strhash
DECL|function|strihash
DECL|macro|FNV32_BASE
DECL|macro|FNV32_PRIME
DECL|macro|HASHMAP_INITIAL_SIZE
DECL|macro|HASHMAP_LOAD_FACTOR
DECL|macro|HASHMAP_RESIZE_BITS
DECL|member|data
DECL|member|ent
DECL|member|len
DECL|struct|pool_entry
