DECL|function|hashmap_entry_init
DECL|function|hashmap_iter_first
DECL|macro|HASHMAP_H
DECL|member|cmpfn
DECL|member|grow_at
DECL|member|hash
DECL|member|map
DECL|member|next
DECL|member|next
DECL|member|shrink_at
DECL|member|size
DECL|member|table
DECL|member|tablepos
DECL|member|tablesize
DECL|struct|hashmap
DECL|struct|hashmap_entry
DECL|struct|hashmap_iter
DECL|typedef|hashmap_cmp_fn
