DECL|enumerator|HELP_FORMAT_INFO
DECL|enumerator|HELP_FORMAT_MAN
DECL|enumerator|HELP_FORMAT_WEB
DECL|enum|help_format
DECL|function|add_cmdname
DECL|function|check_emacsclient_version
DECL|function|cmd_help
DECL|function|cmd_to_page
DECL|function|cmd_version
DECL|function|cmdname_compare
DECL|function|exclude_cmds
DECL|function|exec_man_konqueror
DECL|function|exec_woman_emacs
DECL|function|get_html_page_path
DECL|function|git_help_config
DECL|function|help_unknown_cmd
DECL|function|is_git_command
DECL|function|is_in_cmdlist
DECL|function|list_commands
DECL|function|list_commands_in_dir
DECL|function|list_common_cmds_help
DECL|function|load_command_list
DECL|function|mput_char
DECL|function|parse_help_format
DECL|function|pretty_print_string_list
DECL|function|setup_man_path
DECL|function|show_html_page
DECL|function|show_info_page
DECL|function|show_man_page
DECL|function|term_columns
DECL|function|uniq
DECL|member|alloc
DECL|member|cnt
DECL|member|len
DECL|member|name
DECL|member|names
DECL|struct|cmdname
DECL|struct|cmdnames
DECL|variable|builtin_help_options
DECL|variable|builtin_help_usage
DECL|variable|help_format
DECL|variable|main_cmds
DECL|variable|man_viewer
DECL|variable|other_cmds
DECL|variable|show_all
