DECL|function|add_cmdname
DECL|function|cmd_help
DECL|function|cmd_to_page
DECL|function|cmd_version
DECL|function|cmdname_compare
DECL|function|exclude_cmds
DECL|function|help_unknown_cmd
DECL|function|list_commands
DECL|function|list_commands_in_dir
DECL|function|list_common_cmds_help
DECL|function|mput_char
DECL|function|pretty_print_string_list
DECL|function|show_html_page
DECL|function|show_info_page
DECL|function|show_man_page
DECL|function|term_columns
DECL|function|uniq
DECL|member|alloc
DECL|member|cnt
DECL|member|len
DECL|member|name
DECL|member|names
DECL|struct|cmdname
DECL|struct|cmdnames
DECL|variable|main_cmds
DECL|variable|other_cmds
