DECL|function|add_cmd_list
DECL|function|add_cmdname
DECL|function|clean_cmdnames
DECL|function|cmd_version
DECL|function|cmdname_compare
DECL|function|exclude_cmds
DECL|function|git_unknown_cmd_config
DECL|function|help_unknown_cmd
DECL|function|is_executable
DECL|function|is_in_cmdlist
DECL|function|levenshtein_compare
DECL|function|list_commands
DECL|function|list_commands_in_dir
DECL|function|load_command_list
DECL|function|pretty_print_string_list
DECL|function|term_columns
DECL|function|uniq
DECL|variable|aliases
DECL|variable|autocorrect
