DECL|function|fetch
DECL|function|fetch_ref
DECL|function|fwrite_sha1_file
DECL|function|main
DECL|variable|base
DECL|variable|c
DECL|variable|curl
DECL|variable|local
DECL|variable|stream
DECL|variable|zret
