DECL|enumerator|ABORTED
DECL|enumerator|ACTIVE
DECL|enumerator|COMPLETE
DECL|enumerator|WAITING
DECL|enum|transfer_state
DECL|function|fetch
DECL|function|fetch_alternates
DECL|function|fetch_index
DECL|function|fetch_indices
DECL|function|fetch_object
DECL|function|fetch_pack
DECL|function|fetch_ref
DECL|function|finish_request
DECL|function|fwrite_buffer
DECL|function|fwrite_sha1_file
DECL|function|get_active_slot
DECL|function|hex
DECL|function|main
DECL|function|needs_quote
DECL|function|prefetch
DECL|function|process_curl_messages
DECL|function|process_request_queue
DECL|function|quote_ref_url
DECL|function|release_request
DECL|function|run_active_slot
DECL|function|setup_index
DECL|function|start_active_slot
DECL|function|start_request
DECL|macro|DEFAULT_MAX_REQUESTS
DECL|macro|PREV_BUF_SIZE
DECL|macro|RANGE_HEADER_SIZE
DECL|macro|USE_CURL_MULTI
DECL|macro|curl_global_cleanup
DECL|macro|curl_global_init
DECL|member|base
DECL|member|buffer
DECL|member|c
DECL|member|curl
DECL|member|curl_result
DECL|member|curl_result
DECL|member|done
DECL|member|errorstr
DECL|member|filename
DECL|member|got_indices
DECL|member|http_code
DECL|member|in_use
DECL|member|local
DECL|member|local
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|packs
DECL|member|posn
DECL|member|real_sha1
DECL|member|rename
DECL|member|repo
DECL|member|sha1
DECL|member|size
DECL|member|slot
DECL|member|state
DECL|member|stream
DECL|member|tmpfile
DECL|member|url
DECL|member|zret
DECL|struct|active_request_slot
DECL|struct|alt_base
DECL|struct|buffer
DECL|struct|transfer_request
DECL|variable|active_queue_head
DECL|variable|active_requests
DECL|variable|alt
DECL|variable|curl_default
DECL|variable|curl_errorstr
DECL|variable|curl_ssl_verify
DECL|variable|curlm
DECL|variable|data_received
DECL|variable|max_requests
DECL|variable|no_pragma_header
DECL|variable|no_range_header
DECL|variable|pragma_header
DECL|variable|request_queue_head
DECL|variable|ssl_cainfo
DECL|variable|ssl_capath
DECL|variable|ssl_cert
DECL|variable|ssl_key
