DECL|function|add_fill_function
DECL|function|closedown_active_slot
DECL|function|fill_active_slots
DECL|function|finish_active_slot
DECL|function|finish_all_active_slots
DECL|function|fread_buffer
DECL|function|fwrite_buffer
DECL|function|fwrite_null
DECL|function|get_active_slot
DECL|function|get_curl_handle
DECL|function|hex
DECL|function|http_auth_init
DECL|function|http_cleanup
DECL|function|http_fetch_ref
DECL|function|http_init
DECL|function|http_options
DECL|function|init_curl_http_auth
DECL|function|ioctl_buffer
DECL|function|needs_quote
DECL|function|process_curl_messages
DECL|function|quote_ref_url
DECL|function|release_active_slot
DECL|function|run_active_slot
DECL|function|set_from_env
DECL|function|start_active_slot
DECL|function|step_active_slots
DECL|member|data
DECL|member|fill
DECL|member|next
DECL|struct|fill_chain
DECL|variable|active_queue_head
DECL|variable|active_requests
DECL|variable|curl_default
DECL|variable|curl_errorstr
DECL|variable|curl_ftp_no_epsv
DECL|variable|curl_http_proxy
DECL|variable|curl_low_speed_limit
DECL|variable|curl_low_speed_time
DECL|variable|curl_ssl_verify
DECL|variable|curlm
DECL|variable|data_received
DECL|variable|fill_cfg
DECL|variable|max_requests
DECL|variable|pragma_header
DECL|variable|ssl_cainfo
DECL|variable|ssl_capath
DECL|variable|ssl_cert
DECL|variable|ssl_key
DECL|variable|user_name
DECL|variable|user_pass
