DECL|enumerator|ABORTED
DECL|enumerator|ACTIVE
DECL|enumerator|COMPLETE
DECL|enumerator|WAITING
DECL|enum|transfer_state
DECL|function|fetch
DECL|function|fetch_alternates
DECL|function|fetch_index
DECL|function|fetch_indices
DECL|function|fetch_object
DECL|function|fetch_pack
DECL|function|fetch_ref
DECL|function|fill_active_slots
DECL|function|finish_request
DECL|function|fwrite_sha1_file
DECL|function|hex
DECL|function|main
DECL|function|needs_quote
DECL|function|prefetch
DECL|function|process_alternates
DECL|function|process_object_response
DECL|function|quote_ref_url
DECL|function|release_request
DECL|function|setup_index
DECL|function|start_request
DECL|macro|PREV_BUF_SIZE
DECL|macro|RANGE_HEADER_SIZE
DECL|member|base
DECL|member|base
DECL|member|buffer
DECL|member|c
DECL|member|curl_result
DECL|member|errorstr
DECL|member|filename
DECL|member|got_indices
DECL|member|http_code
DECL|member|http_specific
DECL|member|local
DECL|member|next
DECL|member|next
DECL|member|packs
DECL|member|real_sha1
DECL|member|rename
DECL|member|repo
DECL|member|sha1
DECL|member|slot
DECL|member|slot
DECL|member|state
DECL|member|stream
DECL|member|tmpfile
DECL|member|url
DECL|member|url
DECL|member|zret
DECL|struct|alt_base
DECL|struct|alt_request
DECL|struct|transfer_request
DECL|variable|alt
DECL|variable|got_alternates
DECL|variable|no_pragma_header
DECL|variable|request_queue_head
