DECL|enumerator|ABORTED
DECL|enumerator|ACTIVE
DECL|enumerator|COMPLETE
DECL|enumerator|WAITING
DECL|enum|object_request_state
DECL|function|abort_object_request
DECL|function|cleanup
DECL|function|fetch
DECL|function|fetch_alternates
DECL|function|fetch_index
DECL|function|fetch_indices
DECL|function|fetch_object
DECL|function|fetch_pack
DECL|function|fetch_ref
DECL|function|fill_active_slot
DECL|function|finish_object_request
DECL|function|fwrite_sha1_file
DECL|function|get_http_walker
DECL|function|prefetch
DECL|function|process_alternates_response
DECL|function|process_object_response
DECL|function|release_object_request
DECL|function|setup_index
DECL|function|start_object_request
DECL|macro|PREV_BUF_SIZE
DECL|macro|RANGE_HEADER_SIZE
DECL|member|alt
DECL|member|base
DECL|member|base
DECL|member|buffer
DECL|member|c
DECL|member|curl_result
DECL|member|errorstr
DECL|member|filename
DECL|member|got_alternates
DECL|member|got_indices
DECL|member|http_code
DECL|member|http_specific
DECL|member|local
DECL|member|next
DECL|member|next
DECL|member|no_pragma_header
DECL|member|packs
DECL|member|real_sha1
DECL|member|rename
DECL|member|repo
DECL|member|sha1
DECL|member|slot
DECL|member|slot
DECL|member|state
DECL|member|stream
DECL|member|tmpfile
DECL|member|url
DECL|member|url
DECL|member|url
DECL|member|walker
DECL|member|walker
DECL|member|zret
DECL|struct|alt_base
DECL|struct|alternates_request
DECL|struct|object_request
DECL|struct|walker_data
DECL|variable|object_queue_head
