DECL|enumerator|ABORTED
DECL|enumerator|COMPLETE
DECL|enumerator|NEED_CHECK
DECL|enumerator|NEED_PUSH
DECL|enumerator|RUN_HEAD
DECL|enumerator|RUN_MKCOL
DECL|enumerator|RUN_MOVE
DECL|enumerator|RUN_PUT
DECL|enumerator|XML_STATUS_ERROR
DECL|enumerator|XML_STATUS_OK
DECL|enum|XML_Status
DECL|enum|transfer_state
DECL|function|activelock_cdata
DECL|function|add_request
DECL|function|check_locking
DECL|function|end_activelock_element
DECL|function|end_lockprop_element
DECL|function|fetch_index
DECL|function|fetch_indices
DECL|function|fetch_ref
DECL|function|fill_active_slots
DECL|function|finish_request
DECL|function|get_delta
DECL|function|hex
DECL|function|is_ancestor
DECL|function|lock_remote
DECL|function|main
DECL|function|main
DECL|function|needs_quote
DECL|function|process_response
DECL|function|quote_ref_url
DECL|function|refresh_lock
DECL|function|release_request
DECL|function|setup_index
DECL|function|start_activelock_element
DECL|function|start_check
DECL|function|start_lockprop_element
DECL|function|start_mkcol
DECL|function|start_move
DECL|function|start_put
DECL|function|unlock_remote
DECL|function|update_remote
DECL|macro|DAV_LOCK
DECL|macro|DAV_MKCOL
DECL|macro|DAV_MOVE
DECL|macro|DAV_PROPFIND
DECL|macro|DAV_PUT
DECL|macro|DAV_UNLOCK
DECL|macro|LOCK_REFRESH
DECL|macro|LOCK_REQUEST
DECL|macro|LOCK_TIME
DECL|macro|PROPFIND_REQUEST
DECL|macro|RANGE_HEADER_SIZE
DECL|macro|XML_STATUS_ERROR
DECL|macro|XML_STATUS_OK
DECL|member|buffer
DECL|member|c
DECL|member|ctx_activelock
DECL|member|ctx_locktoken
DECL|member|ctx_locktoken_href
DECL|member|ctx_owner
DECL|member|ctx_owner_href
DECL|member|ctx_timeout
DECL|member|curl_result
DECL|member|dest
DECL|member|errorstr
DECL|member|filename
DECL|member|headers
DECL|member|http_code
DECL|member|lock
DECL|member|lock_entry
DECL|member|lock_exclusive
DECL|member|lock_exclusive_write
DECL|member|lock_scope
DECL|member|lock_type
DECL|member|next
DECL|member|owner
DECL|member|packs
DECL|member|real_sha1
DECL|member|refreshing
DECL|member|rename
DECL|member|sha1
DECL|member|slot
DECL|member|start_time
DECL|member|state
DECL|member|stream
DECL|member|supported_lock
DECL|member|timeout
DECL|member|tmpfile
DECL|member|token
DECL|member|url
DECL|member|url
DECL|member|url
DECL|member|zret
DECL|struct|active_lock
DECL|struct|lockprop
DECL|struct|repo
DECL|struct|transfer_request
DECL|variable|aborted
DECL|variable|default_headers
DECL|variable|force_all
DECL|variable|http_push_usage
DECL|variable|no_pragma_header
DECL|variable|push_all
DECL|variable|push_verbosely
DECL|variable|pushing
DECL|variable|remote
DECL|variable|remote_dir_exists
DECL|variable|request_queue_head
