DECL|enumerator|ABORTED
DECL|enumerator|ACTIVE
DECL|enumerator|COMPLETE
DECL|enumerator|WAITING
DECL|enum|object_request_state
DECL|function|abort_object_request
DECL|function|cleanup
DECL|function|fetch
DECL|function|fetch_alternates
DECL|function|fetch_indices
DECL|function|fetch_object
DECL|function|fetch_pack
DECL|function|fetch_ref
DECL|function|fill_active_slot
DECL|function|finish_object_request
DECL|function|get_http_walker
DECL|function|prefetch
DECL|function|process_alternates_response
DECL|function|process_object_response
DECL|function|release_object_request
DECL|function|start_object_request
DECL|member|alt
DECL|member|base
DECL|member|base
DECL|member|buffer
DECL|member|got_alternates
DECL|member|got_indices
DECL|member|http_specific
DECL|member|next
DECL|member|next
DECL|member|packs
DECL|member|repo
DECL|member|req
DECL|member|sha1
DECL|member|slot
DECL|member|state
DECL|member|url
DECL|member|url
DECL|member|walker
DECL|member|walker
DECL|struct|alt_base
DECL|struct|alternates_request
DECL|struct|object_request
DECL|struct|walker_data
DECL|variable|object_queue_head
