DECL|macro|DEFAULT_MAX_REQUESTS
DECL|macro|HTTP_H
DECL|macro|NO_CURL_EASY_DUPHANDLE
DECL|macro|USE_CURL_MULTI
DECL|macro|curl_global_cleanup
DECL|macro|curl_global_init
DECL|member|buffer
DECL|member|callback_data
DECL|member|callback_func
DECL|member|curl
DECL|member|curl_result
DECL|member|curl_result
DECL|member|http_code
DECL|member|http_code
DECL|member|in_use
DECL|member|local
DECL|member|next
DECL|member|posn
DECL|member|results
DECL|member|size
DECL|struct|active_request_slot
DECL|struct|buffer
DECL|struct|slot_results
