DECL|enumerator|ABORTED
DECL|enumerator|COMPLETE
DECL|enumerator|NEED_PUSH
DECL|enumerator|RUN_MKCOL
DECL|enumerator|RUN_MOVE
DECL|enumerator|RUN_PUT
DECL|enumerator|XML_STATUS_ERROR
DECL|enumerator|XML_STATUS_OK
DECL|enum|XML_Status
DECL|enum|transfer_state
DECL|function|add_request
DECL|function|check_locks
DECL|function|fetch_index
DECL|function|fetch_indices
DECL|function|fetch_ref
DECL|function|fill_active_slots
DECL|function|finish_request
DECL|function|get_dav_remote_heads
DECL|function|get_delta
DECL|function|get_local_heads
DECL|function|get_remote_object_list
DECL|function|handle_lockprop_ctx
DECL|function|handle_new_lock_ctx
DECL|function|handle_remote_ls_ctx
DECL|function|hex
DECL|function|is_zero_sha1
DECL|function|lock_remote
DECL|function|locking_available
DECL|function|main
DECL|function|mark_edge_parents_uninteresting
DECL|function|mark_edges_uninteresting
DECL|function|needs_quote
DECL|function|one_local_ref
DECL|function|one_remote_object
DECL|function|one_remote_ref
DECL|function|process_blob
DECL|function|process_ls_object
DECL|function|process_ls_ref
DECL|function|process_response
DECL|function|process_tree
DECL|function|quote_ref_url
DECL|function|ref_newer
DECL|function|refresh_lock
DECL|function|release_request
DECL|function|remote_ls
DECL|function|setup_index
DECL|function|start_mkcol
DECL|function|start_move
DECL|function|start_put
DECL|function|unlock_remote
DECL|function|unmark_and_free
DECL|function|update_remote
DECL|function|xml_cdata
DECL|function|xml_end_tag
DECL|function|xml_start_tag
DECL|macro|DAV_ACTIVELOCK_OWNER
DECL|macro|DAV_ACTIVELOCK_TIMEOUT
DECL|macro|DAV_ACTIVELOCK_TOKEN
DECL|macro|DAV_CTX_LOCKENTRY
DECL|macro|DAV_CTX_LOCKTYPE_EXCLUSIVE
DECL|macro|DAV_CTX_LOCKTYPE_WRITE
DECL|macro|DAV_LOCK
DECL|macro|DAV_LOCK_OK
DECL|macro|DAV_MKCOL
DECL|macro|DAV_MOVE
DECL|macro|DAV_PROPFIND
DECL|macro|DAV_PROPFIND_COLLECTION
DECL|macro|DAV_PROPFIND_NAME
DECL|macro|DAV_PROPFIND_RESP
DECL|macro|DAV_PROP_LOCKEX
DECL|macro|DAV_PROP_LOCKWR
DECL|macro|DAV_PUT
DECL|macro|DAV_UNLOCK
DECL|macro|IS_DIR
DECL|macro|LOCAL
DECL|macro|LOCK_REFRESH
DECL|macro|LOCK_REQUEST
DECL|macro|LOCK_TIME
DECL|macro|PROCESS_DIRS
DECL|macro|PROCESS_FILES
DECL|macro|PROPFIND_ALL_REQUEST
DECL|macro|PROPFIND_SUPPORTEDLOCK_REQUEST
DECL|macro|PUSHING
DECL|macro|RANGE_HEADER_SIZE
DECL|macro|RECURSIVE
DECL|macro|REMOTE
DECL|macro|XML_STATUS_ERROR
DECL|macro|XML_STATUS_OK
DECL|member|buffer
DECL|member|c
DECL|member|cdata
DECL|member|curl_result
DECL|member|dentry_flags
DECL|member|dentry_name
DECL|member|dest
DECL|member|errorstr
DECL|member|filename
DECL|member|flags
DECL|member|headers
DECL|member|http_code
DECL|member|len
DECL|member|lock
DECL|member|locks
DECL|member|name
DECL|member|next
DECL|member|next
DECL|member|obj
DECL|member|owner
DECL|member|packs
DECL|member|parent
DECL|member|path
DECL|member|path_len
DECL|member|real_sha1
DECL|member|refreshing
DECL|member|rename
DECL|member|slot
DECL|member|start_time
DECL|member|state
DECL|member|stream
DECL|member|timeout
DECL|member|tmpfile
DECL|member|token
DECL|member|url
DECL|member|url
DECL|member|url
DECL|member|userData
DECL|member|userData
DECL|member|userFunc
DECL|member|userFunc
DECL|member|zret
DECL|struct|remote_lock
DECL|struct|remote_ls_ctx
DECL|struct|repo
DECL|struct|transfer_request
DECL|struct|xml_ctx
DECL|variable|aborted
DECL|variable|default_headers
DECL|variable|force_all
DECL|variable|http_push_usage
DECL|variable|local_refs
DECL|variable|local_tail
DECL|variable|no_pragma_header
DECL|variable|objects
DECL|variable|push_all
DECL|variable|push_verbosely
DECL|variable|pushing
DECL|variable|remote
DECL|variable|remote_dir_exists
DECL|variable|remote_refs
DECL|variable|remote_tail
DECL|variable|request_queue_head
