DECL|function|fetch
DECL|function|fetch_ref
DECL|function|fwrite_buffer
DECL|function|fwrite_sha1_file
DECL|function|main
DECL|macro|curl_global_cleanup
DECL|macro|curl_global_init
DECL|member|buffer
DECL|member|posn
DECL|member|size
DECL|struct|buffer
DECL|variable|base
DECL|variable|c
DECL|variable|curl
DECL|variable|curl_ssl_verify
DECL|variable|local
DECL|variable|stream
DECL|variable|zret
