DECL|function|missing__target
DECL|macro|CURLE_HTTP_RETURNED_ERROR
DECL|macro|DEFAULT_MAX_REQUESTS
DECL|macro|HTTP_H
DECL|macro|NO_CURL_EASY_DUPHANDLE
DECL|macro|USE_CURL_MULTI
DECL|macro|USE_CURL_MULTI
DECL|macro|curl_global_cleanup
DECL|macro|curl_global_init
DECL|macro|missing_target
DECL|member|buf
DECL|member|callback_data
DECL|member|callback_func
DECL|member|curl
DECL|member|curl_result
DECL|member|curl_result
DECL|member|finished
DECL|member|http_code
DECL|member|http_code
DECL|member|in_use
DECL|member|local
DECL|member|next
DECL|member|posn
DECL|member|results
DECL|struct|active_request_slot
DECL|struct|buffer
DECL|struct|slot_results
