DECL|function|check_content_type
DECL|function|decode_char
DECL|function|decode_parameter
DECL|function|die_webcgi
DECL|function|end_headers
DECL|function|forbidden
DECL|function|format_write
DECL|function|get_idx_file
DECL|function|get_info_packs
DECL|function|get_info_refs
DECL|function|get_loose_object
DECL|function|get_pack_file
DECL|function|get_parameter
DECL|function|get_parameters
DECL|function|get_text_file
DECL|function|getdir
DECL|function|hdr_cache_forever
DECL|function|hdr_date
DECL|function|hdr_int
DECL|function|hdr_nocache
DECL|function|hdr_str
DECL|function|http_config
DECL|function|http_status
DECL|function|inflate_request
DECL|function|main
DECL|function|not_found
DECL|function|run_service
DECL|function|select_getanyfile
DECL|function|select_service
DECL|function|send_local_file
DECL|function|send_strbuf
DECL|function|service_rpc
DECL|function|show_text_ref
DECL|member|config_name
DECL|member|enabled
DECL|member|imp
DECL|member|method
DECL|member|name
DECL|member|pattern
DECL|struct|rpc_service
DECL|struct|service_cmd
DECL|variable|content_length
DECL|variable|content_type
DECL|variable|getanyfile
DECL|variable|last_modified
DECL|variable|query_params
DECL|variable|rpc_service
DECL|variable|services
