DECL|function|missing__target
DECL|macro|CURLE_HTTP_RETURNED_ERROR
DECL|macro|CURLOPT_USE_SSL
DECL|macro|CURLUSESSL_TRY
DECL|macro|DEFAULT_MAX_REQUESTS
DECL|macro|HTTP_ERROR
DECL|macro|HTTP_H
DECL|macro|HTTP_MISSING_TARGET
DECL|macro|HTTP_NOAUTH
DECL|macro|HTTP_OK
DECL|macro|HTTP_REAUTH
DECL|macro|HTTP_START_FAILED
DECL|macro|NO_CURL_EASY_DUPHANDLE
DECL|macro|NO_CURL_IOCTL
DECL|macro|USE_CURL_MULTI
DECL|macro|USE_CURL_MULTI
DECL|macro|curl_global_cleanup
DECL|macro|curl_global_init
DECL|macro|missing_target
DECL|member|auth_avail
DECL|member|base_url
DECL|member|buf
DECL|member|c
DECL|member|callback_data
DECL|member|callback_func
DECL|member|charset
DECL|member|content_type
DECL|member|curl
DECL|member|curl_result
DECL|member|curl_result
DECL|member|curl_result
DECL|member|effective_url
DECL|member|errorstr
DECL|member|finished
DECL|member|http_code
DECL|member|http_code
DECL|member|http_code
DECL|member|in_use
DECL|member|keep_error
DECL|member|localfile
DECL|member|lst
DECL|member|next
DECL|member|no_cache
DECL|member|packfile
DECL|member|posn
DECL|member|range_header
DECL|member|real_sha1
DECL|member|rename
DECL|member|results
DECL|member|sha1
DECL|member|slot
DECL|member|slot
DECL|member|stream
DECL|member|target
DECL|member|tmpfile
DECL|member|tmpfile
DECL|member|url
DECL|member|url
DECL|member|zret
DECL|struct|active_request_slot
DECL|struct|buffer
DECL|struct|http_get_options
DECL|struct|http_object_request
DECL|struct|http_pack_request
DECL|struct|slot_results
