DECL|function|die_webcgi
DECL|function|end_headers
DECL|function|format_write
DECL|function|get_idx_file
DECL|function|get_info_packs
DECL|function|get_info_refs
DECL|function|get_loose_object
DECL|function|get_pack_file
DECL|function|get_text_file
DECL|function|hdr_cache_forever
DECL|function|hdr_date
DECL|function|hdr_int
DECL|function|hdr_nocache
DECL|function|hdr_str
DECL|function|http_status
DECL|function|main
DECL|function|not_found
DECL|function|send_file
DECL|function|send_strbuf
DECL|function|show_text_ref
DECL|member|imp
DECL|member|method
DECL|member|pattern
DECL|struct|service_cmd
DECL|variable|content_length
DECL|variable|content_type
DECL|variable|last_modified
DECL|variable|services
