DECL|function|add_domainname
DECL|function|add_mailname_host
DECL|function|add_raw
DECL|function|copy
DECL|function|copy_email
DECL|function|copy_gecos
DECL|function|crud
DECL|function|fmt_ident
DECL|function|fmt_name
DECL|function|git_author_info
DECL|function|git_committer_info
DECL|function|setup_ident
DECL|function|split_ident_line
DECL|function|user_ident_sufficiently_given
DECL|macro|get_gecos
DECL|macro|get_gecos
DECL|variable|env_hint
DECL|variable|git_default_date
