DECL|function|add_raw
DECL|function|copy
DECL|function|copy_email
DECL|function|copy_gecos
DECL|function|crud
DECL|function|fmt_ident
DECL|function|fmt_name
DECL|function|git_author_info
DECL|function|git_committer_info
DECL|function|setup_ident
DECL|variable|au_env
DECL|variable|co_env
DECL|variable|env_hint
DECL|variable|git_default_date
