DECL|enumerator|AUTH_CRAM_MD5
DECL|enumerator|LITERALPLUS
DECL|enumerator|NAMESPACE
DECL|enumerator|NOLOGIN
DECL|enumerator|STARTTLS
DECL|enumerator|UIDPLUS
DECL|enum|CAPABILITY
DECL|function|auth_cram_md5
DECL|function|buffer_gets
DECL|function|count_messages
DECL|function|cram
DECL|function|cram
DECL|function|get_cmd_result
DECL|function|git_imap_config
DECL|function|hexchar
DECL|function|host_matches
DECL|function|imap_close_server
DECL|function|imap_close_store
DECL|function|imap_exec
DECL|function|imap_exec_m
DECL|function|imap_info
DECL|function|imap_open_store
DECL|function|imap_store_msg
DECL|function|imap_warn
DECL|function|issue_imap_cmd
DECL|function|lf_to_crlf
DECL|function|main
DECL|function|next_arg
DECL|function|nfsnprintf
DECL|function|nfvasprintf
DECL|function|parse_capability
DECL|function|parse_response_code
DECL|function|read_message
DECL|function|skip_imap_list_l
DECL|function|skip_list
DECL|function|socket_perror
DECL|function|socket_read
DECL|function|socket_shutdown
DECL|function|socket_write
DECL|function|split_msg
DECL|function|ssl_socket_connect
DECL|function|ssl_socket_connect
DECL|function|ssl_socket_perror
DECL|function|v_issue_imap_cmd
DECL|function|verify_hostname
DECL|function|wrap_in_html
DECL|macro|CAP
DECL|macro|CHUNKSIZE
DECL|macro|DRV_BOX_BAD
DECL|macro|DRV_MSG_BAD
DECL|macro|DRV_OK
DECL|macro|DRV_OK
DECL|macro|DRV_STORE_BAD
DECL|macro|ENCODED_SIZE
DECL|macro|RESP_BAD
DECL|macro|RESP_NO
DECL|macro|RESP_OK
DECL|member|auth_method
DECL|member|buf
DECL|member|buf
DECL|member|bytes
DECL|member|caps
DECL|member|cb
DECL|member|cmd
DECL|member|cont
DECL|member|create
DECL|member|ctx
DECL|member|data
DECL|member|dlen
DECL|member|done
DECL|member|fd
DECL|member|folder
DECL|member|host
DECL|member|imap
DECL|member|in_progress
DECL|member|in_progress_append
DECL|member|literal_pending
DECL|member|name
DECL|member|name
DECL|member|next
DECL|member|nexttag
DECL|member|num_in_progress
DECL|member|offset
DECL|member|pass
DECL|member|port
DECL|member|prefix
DECL|member|rcaps
DECL|member|sock
DECL|member|ssl
DECL|member|ssl_verify
DECL|member|tag
DECL|member|trycreate
DECL|member|tunnel
DECL|member|uid
DECL|member|uidnext
DECL|member|uidvalidity
DECL|member|use_html
DECL|member|use_ssl
DECL|member|user
DECL|struct|imap
DECL|struct|imap_buffer
DECL|struct|imap_cmd
DECL|struct|imap_cmd_cb
DECL|struct|imap_server_conf
DECL|struct|imap_socket
DECL|struct|imap_store
DECL|typedef|SSL
DECL|variable|Quiet
DECL|variable|Verbose
DECL|variable|cap_list
DECL|variable|imap_send_usage
DECL|variable|server
