DECL|enumerator|LITERALPLUS
DECL|enumerator|NAMESPACE
DECL|enumerator|NOLOGIN
DECL|enumerator|UIDPLUS
DECL|enum|CAPABILITY
DECL|function|arc4_getbyte
DECL|function|arc4_init
DECL|function|buffer_gets
DECL|function|count_messages
DECL|function|free_generic_messages
DECL|function|free_list
DECL|function|get_cmd_result
DECL|function|git_imap_config
DECL|function|imap_close_server
DECL|function|imap_close_store
DECL|function|imap_exec
DECL|function|imap_exec_m
DECL|function|imap_make_flags
DECL|function|imap_open_store
DECL|function|imap_store_msg
DECL|function|info
DECL|function|is_atom
DECL|function|is_list
DECL|function|issue_imap_cmd
DECL|function|main
DECL|function|next_arg
DECL|function|nfsnprintf
DECL|function|nfvasprintf
DECL|function|parse_capability
DECL|function|parse_imap_list
DECL|function|parse_imap_list_l
DECL|function|parse_list
DECL|function|parse_response_code
DECL|function|read_message
DECL|function|socket_perror
DECL|function|socket_read
DECL|function|socket_write
DECL|function|split_msg
DECL|function|v_issue_imap_cmd
DECL|function|vasprintf
DECL|function|warn
DECL|macro|CAP
DECL|macro|CHUNKSIZE
DECL|macro|DRV_BOX_BAD
DECL|macro|DRV_MSG_BAD
DECL|macro|DRV_OK
DECL|macro|DRV_STORE_BAD
DECL|macro|LIST
DECL|macro|M_DEAD
DECL|macro|M_FLAGS
DECL|macro|M_RECENT
DECL|macro|NIL
DECL|macro|RESP_BAD
DECL|macro|RESP_NO
DECL|macro|RESP_OK
DECL|macro|TUIDL
DECL|member|buf
DECL|member|buf
DECL|member|bytes
DECL|member|caps
DECL|member|cb
DECL|member|channels
DECL|member|child
DECL|member|cmd
DECL|member|conf
DECL|member|cont
DECL|member|count
DECL|member|create
DECL|member|crlf
DECL|member|ctx
DECL|member|data
DECL|member|data
DECL|member|dlen
DECL|member|done
DECL|member|fd
DECL|member|flags
DECL|member|flags
DECL|member|gen
DECL|member|gen
DECL|member|host
DECL|member|i
DECL|member|imap
DECL|member|in_progress
DECL|member|in_progress_append
DECL|member|j
DECL|member|len
DECL|member|len
DECL|member|literal_pending
DECL|member|map_inbox
DECL|member|master
DECL|member|master_name
DECL|member|max_messages
DECL|member|max_size
DECL|member|mops
DECL|member|msgs
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|nexttag
DECL|member|ns_other
DECL|member|ns_personal
DECL|member|ns_shared
DECL|member|num_in_progress
DECL|member|offset
DECL|member|opts
DECL|member|pass
DECL|member|path
DECL|member|path
DECL|member|patterns
DECL|member|port
DECL|member|prefix
DECL|member|rcaps
DECL|member|recent
DECL|member|s
DECL|member|server
DECL|member|size
DECL|member|slave
DECL|member|slave_name
DECL|member|sock
DECL|member|sops
DECL|member|status
DECL|member|string
DECL|member|sync_state
DECL|member|tag
DECL|member|trash
DECL|member|trash_only_new
DECL|member|trash_remote_new
DECL|member|trashnc
DECL|member|trycreate
DECL|member|tunnel
DECL|member|uid
DECL|member|uid
DECL|member|uidnext
DECL|member|uidvalidity
DECL|member|uidvalidity
DECL|member|user
DECL|member|val
DECL|struct|_list
DECL|struct|channel_conf
DECL|struct|group_conf
DECL|struct|imap
DECL|struct|imap_cmd
DECL|struct|imap_cmd_cb
DECL|struct|imap_server_conf
DECL|struct|imap_store
DECL|struct|imap_store_conf
DECL|struct|message
DECL|struct|store
DECL|struct|store_conf
DECL|struct|string_list
DECL|typedef|Socket_t
DECL|typedef|buffer_t
DECL|typedef|channel_conf_t
DECL|typedef|group_conf_t
DECL|typedef|imap_server_conf_t
DECL|typedef|imap_store_conf_t
DECL|typedef|imap_store_t
DECL|typedef|imap_t
DECL|typedef|list_t
DECL|typedef|message_t
DECL|typedef|msg_data_t
DECL|typedef|store_conf_t
DECL|typedef|store_t
DECL|typedef|string_list_t
DECL|variable|Flags
DECL|variable|Quiet
DECL|variable|Verbose
DECL|variable|cap_list
DECL|variable|imap_folder
DECL|variable|rs
DECL|variable|server
