DECL|function|append_obj_to_pack
DECL|function|bad_object
DECL|function|compare_delta_entry
DECL|function|delta_pos_compare
DECL|function|fill
DECL|function|final
DECL|function|find_delta
DECL|function|find_delta_children
DECL|function|fix_unresolved_deltas
DECL|function|flush
DECL|function|get_data_from_pack
DECL|function|main
DECL|function|open_pack_file
DECL|function|parse_pack_header
DECL|function|parse_pack_objects
DECL|function|resolve_delta
DECL|function|sha1_compare
DECL|function|sha1_object
DECL|function|unpack_entry_data
DECL|function|unpack_raw_entry
DECL|function|use
DECL|function|write_compressed
DECL|function|write_index_file
DECL|macro|UNION_BASE_SZ
DECL|member|base
DECL|member|crc32
DECL|member|hdr_size
DECL|member|obj_no
DECL|member|offset
DECL|member|offset
DECL|member|real_type
DECL|member|sha1
DECL|member|sha1
DECL|member|size
DECL|member|type
DECL|struct|delta_entry
DECL|struct|object_entry
DECL|union|delta_base
DECL|variable|consumed_bytes
DECL|variable|deltas
DECL|variable|from_stdin
DECL|variable|index_default_version
DECL|variable|index_off32_limit
DECL|variable|index_pack_usage
DECL|variable|input_buffer
DECL|variable|input_crc32
DECL|variable|input_ctx
DECL|variable|input_fd
DECL|variable|input_len
DECL|variable|input_offset
DECL|variable|nr_deltas
DECL|variable|nr_objects
DECL|variable|nr_resolved_deltas
DECL|variable|objects
DECL|variable|output_fd
DECL|variable|pack_fd
DECL|variable|progress
DECL|variable|verbose
