DECL|function|__ac_X31_hash_string
DECL|function|__kh_oid_hash
DECL|macro|AC_VERSION_KHASH_H
DECL|macro|KHASH_DECLARE
DECL|macro|KHASH_INIT
DECL|macro|KHASH_INIT2
DECL|macro|__AC_KHASH_H
DECL|macro|__KHASH_IMPL
DECL|macro|__KHASH_PROTOTYPES
DECL|macro|__KHASH_TYPE
DECL|macro|__ac_fsize
DECL|macro|__ac_isdel
DECL|macro|__ac_iseither
DECL|macro|__ac_isempty
DECL|macro|__ac_set_isboth_false
DECL|macro|__ac_set_isdel_false
DECL|macro|__ac_set_isdel_true
DECL|macro|__ac_set_isempty_false
DECL|macro|__kh_oid_cmp
DECL|macro|kh_begin
DECL|macro|kh_end
DECL|macro|kh_exist
DECL|macro|kh_foreach
DECL|macro|kh_foreach_value
DECL|macro|kh_key
DECL|macro|kh_n_buckets
DECL|macro|kh_size
DECL|macro|kh_str_hash_equal
DECL|macro|kh_str_hash_func
DECL|macro|kh_val
DECL|macro|kh_value
DECL|macro|kroundup32
DECL|typedef|khash_sha1
DECL|typedef|khash_sha1_pos
DECL|typedef|khint32_t
DECL|typedef|khint64_t
DECL|typedef|khint_t
DECL|typedef|khiter_t
DECL|variable|__ac_HASH_UPPER
