DECL|function|bmexec
DECL|function|cwexec
DECL|function|enqueue
DECL|function|hasevery
DECL|function|kwsalloc
DECL|function|kwsexec
DECL|function|kwsfree
DECL|function|kwsincr
DECL|function|kwsprep
DECL|function|treedelta
DECL|function|treefails
DECL|function|treenext
DECL|macro|DEPTH_SIZE
DECL|macro|NCHAR
DECL|macro|U
DECL|macro|malloc
DECL|macro|malloc
DECL|macro|obstack_chunk_alloc
DECL|macro|obstack_chunk_free
DECL|member|accepting
DECL|member|balance
DECL|member|delta
DECL|member|depth
DECL|member|fail
DECL|member|label
DECL|member|links
DECL|member|llink
DECL|member|maxd
DECL|member|maxshift
DECL|member|mind
DECL|member|mind2
DECL|member|next
DECL|member|next
DECL|member|obstack
DECL|member|parent
DECL|member|rlink
DECL|member|shift
DECL|member|target
DECL|member|trans
DECL|member|trie
DECL|member|trie
DECL|member|words
DECL|struct|kwset
DECL|struct|tree
DECL|struct|trie
