DECL|macro|LINE_LOG_H
DECL|member|alloc
DECL|member|arg_alloc
DECL|member|arg_nr
DECL|member|args
DECL|member|diff
DECL|member|end
DECL|member|next
DECL|member|nr
DECL|member|pair
DECL|member|parent
DECL|member|ranges
DECL|member|ranges
DECL|member|spec
DECL|member|start
DECL|member|status
DECL|member|target
DECL|struct|diff_ranges
DECL|struct|line_log_data
DECL|struct|range
DECL|struct|range_set
