DECL|function|create_temp
DECL|function|find_ll_merge_driver
DECL|function|git_path_check_merge
DECL|function|initialize_ll_merge
DECL|function|ll_binary_merge
DECL|function|ll_ext_merge
DECL|function|ll_merge
DECL|function|ll_merge_marker_size
DECL|function|ll_union_merge
DECL|function|ll_xdl_merge
DECL|function|normalize_file
DECL|function|read_merge_config
DECL|macro|LL_BINARY_MERGE
DECL|macro|LL_TEXT_MERGE
DECL|macro|LL_UNION_MERGE
DECL|member|cmdline
DECL|member|description
DECL|member|fn
DECL|member|name
DECL|member|next
DECL|member|recursive
DECL|struct|ll_merge_driver
DECL|typedef|ll_merge_fn
DECL|variable|default_ll_merge
DECL|variable|ll_merge_drv
DECL|variable|ll_user_merge
DECL|variable|ll_user_merge_tail
