DECL|function|copy_file
DECL|function|fetch
DECL|function|fetch_file
DECL|function|fetch_pack
DECL|function|fetch_ref
DECL|function|main
DECL|function|prefetch
DECL|function|setup_index
DECL|function|setup_indices
DECL|variable|commits_on_stdin
DECL|variable|local_pull_usage
DECL|variable|packs
DECL|variable|path
DECL|variable|use_filecopy
DECL|variable|use_link
DECL|variable|use_symlink
