DECL|function|close_lock_file
DECL|function|commit_lock_file_to
DECL|function|fdopen_lock_file
DECL|function|get_lock_file_fd
DECL|function|get_lock_file_fp
DECL|function|get_lock_file_path
DECL|function|hold_lock_file_for_update
DECL|function|reopen_lock_file
DECL|function|rollback_lock_file
DECL|macro|LOCKFILE_H
DECL|macro|LOCK_DIE_ON_ERROR
DECL|macro|LOCK_NO_DEREF
DECL|macro|LOCK_SUFFIX
DECL|macro|LOCK_SUFFIX_LEN
DECL|member|tempfile
DECL|struct|lock_file
