DECL|function|diff_root_tree
DECL|function|do_diff_combined
DECL|function|generate_header
DECL|function|init_log_tree_opt
DECL|function|log_tree_commit
DECL|function|log_tree_diff_flush
DECL|function|log_tree_opt_parse
