DECL|macro|LOG_TREE_H
DECL|member|abbrev
DECL|member|abbrev_commit
DECL|member|always_show_header
DECL|member|combine_merges
DECL|member|commit_format
DECL|member|commit_format
DECL|member|dense_combined_merges
DECL|member|diffopt
DECL|member|do_diff
DECL|member|full_diff
DECL|member|header
DECL|member|header_prefix
DECL|member|ignore_merges
DECL|member|logopt
DECL|member|no_commit_id
DECL|member|revopt
DECL|member|show_root_diff
DECL|member|verbose_header
DECL|struct|log_tree_opt
DECL|struct|whatchanged_opt
