DECL|function|add_exclude
DECL|function|add_excludes_from_file
DECL|function|add_excludes_from_file_1
DECL|function|add_name
DECL|function|cmp_name
DECL|function|excluded
DECL|function|main
DECL|function|pop_exclude_per_directory
DECL|function|push_exclude_per_directory
DECL|function|read_directory
DECL|function|show_files
DECL|function|show_killed_files
DECL|member|base
DECL|member|baselen
DECL|member|len
DECL|member|name
DECL|member|pattern
DECL|struct|exclude
DECL|struct|nond_on_fs
DECL|variable|dir
DECL|variable|dir_alloc
DECL|variable|exclude_per_dir
DECL|variable|excludes
DECL|variable|excludes_alloc
DECL|variable|line_terminator
DECL|variable|ls_files_usage
DECL|variable|nr_dir
DECL|variable|nr_excludes
DECL|variable|show_cached
DECL|variable|show_deleted
DECL|variable|show_ignored
DECL|variable|show_killed
DECL|variable|show_others
DECL|variable|show_stage
DECL|variable|show_unmerged
DECL|variable|tag_cached
DECL|variable|tag_killed
DECL|variable|tag_other
DECL|variable|tag_removed
DECL|variable|tag_unmerged
