DECL|function|add_exclude
DECL|function|add_excludes_from_file
DECL|function|add_name
DECL|function|cmp_name
DECL|function|excluded
DECL|function|main
DECL|function|read_directory
DECL|function|show_files
DECL|variable|dir
DECL|variable|dir_alloc
DECL|variable|excludes
DECL|variable|excludes_alloc
DECL|variable|line_terminator
DECL|variable|ls_files_usage
DECL|variable|nr_dir
DECL|variable|nr_excludes
DECL|variable|show_cached
DECL|variable|show_deleted
DECL|variable|show_ignored
DECL|variable|show_others
DECL|variable|show_stage
DECL|variable|show_unmerged
