DECL|function|add_exclude
DECL|function|add_excludes_from_file
DECL|function|add_excludes_from_file_1
DECL|function|add_name
DECL|function|cmp_name
DECL|function|dir_exists
DECL|function|excluded
DECL|function|excluded_1
DECL|function|main
DECL|function|match
DECL|function|pop_exclude_per_directory
DECL|function|prune_cache
DECL|function|push_exclude_per_directory
DECL|function|read_directory
DECL|function|show_ce_entry
DECL|function|show_dir_entry
DECL|function|show_files
DECL|function|show_killed_files
DECL|function|show_other_files
DECL|function|verify_pathspec
DECL|macro|EXC_CMDL
DECL|macro|EXC_DIRS
DECL|macro|EXC_FILE
DECL|member|alloc
DECL|member|base
DECL|member|baselen
DECL|member|excludes
DECL|member|len
DECL|member|name
DECL|member|nr
DECL|member|pattern
DECL|struct|exclude
DECL|struct|exclude_list
DECL|struct|nond_on_fs
DECL|variable|dir
DECL|variable|dir_alloc
DECL|variable|error_unmatch
DECL|variable|exclude_list
DECL|variable|exclude_per_dir
DECL|variable|hide_empty_directories
DECL|variable|line_terminator
DECL|variable|ls_files_usage
DECL|variable|nr_dir
DECL|variable|pathspec
DECL|variable|prefix
DECL|variable|prefix_len
DECL|variable|prefix_offset
DECL|variable|ps_matched
DECL|variable|show_cached
DECL|variable|show_deleted
DECL|variable|show_ignored
DECL|variable|show_killed
DECL|variable|show_modified
DECL|variable|show_other_directories
DECL|variable|show_others
DECL|variable|show_stage
DECL|variable|show_unmerged
DECL|variable|show_valid_bit
DECL|variable|tag_cached
DECL|variable|tag_killed
DECL|variable|tag_modified
DECL|variable|tag_other
DECL|variable|tag_removed
DECL|variable|tag_unmerged
