DECL|function|entry_hex
DECL|function|entry_type
DECL|function|find_entry
DECL|function|list
DECL|function|list_one
DECL|function|main
DECL|function|prepare_children
DECL|function|prepare_root
DECL|function|show_children
DECL|function|show_entry
DECL|macro|LS_RECURSIVE
DECL|macro|LS_TREE_ONLY
DECL|variable|line_termination
DECL|variable|ls_options
DECL|variable|ls_tree_usage
DECL|variable|root_entry
