DECL|function|add_mapping
DECL|function|clear_mailmap
DECL|function|debug_mm
DECL|function|debug_str
DECL|function|free_mailmap_entry
DECL|function|free_mailmap_info
DECL|function|lookup_prefix
DECL|function|map_user
DECL|function|parse_name_and_email
DECL|function|read_mailmap
DECL|function|read_mailmap_blob
DECL|function|read_mailmap_buf
DECL|function|read_mailmap_file
DECL|function|read_mailmap_line
DECL|macro|DEBUG_MAILMAP
DECL|macro|debug_mm
DECL|macro|debug_str
DECL|member|email
DECL|member|email
DECL|member|name
DECL|member|name
DECL|member|namemap
DECL|struct|mailmap_entry
DECL|struct|mailmap_info
DECL|variable|git_mailmap_blob
DECL|variable|git_mailmap_file
