DECL|enumerator|TE_BASE64
DECL|enumerator|TE_DONTCARE
DECL|enumerator|TE_QP
DECL|macro|MAILINFO_H
DECL|macro|MAX_BOUNDARIES
DECL|member|add_message_id
DECL|member|charset
DECL|member|content
DECL|member|content_top
DECL|member|email
DECL|member|filter_stage
DECL|member|header_stage
DECL|member|input
DECL|member|input_error
DECL|member|keep_non_patch_brackets_in_subject
DECL|member|keep_subject
DECL|member|log_message
DECL|member|message_id
DECL|member|metainfo_charset
DECL|member|name
DECL|member|output
DECL|member|p_hdr_data
DECL|member|patch_lines
DECL|member|patchfile
DECL|member|s_hdr_data
DECL|member|transfer_encoding
DECL|member|use_inbody_headers
DECL|member|use_scissors
DECL|struct|mailinfo
