DECL|function|add_subject_line
DECL|function|check_line
DECL|function|cleanup_space
DECL|function|cleanup_subject
DECL|function|eatspace
DECL|function|handle_body
DECL|function|handle_date
DECL|function|handle_from
DECL|function|handle_rest
DECL|function|handle_subject
DECL|function|main
DECL|function|sanity_check
DECL|function|show_filename
DECL|function|usage
DECL|variable|cmitmsg
DECL|variable|date
DECL|variable|email
DECL|variable|filelist
DECL|variable|line
DECL|variable|name
DECL|variable|patchfile
DECL|variable|subject
