DECL|function|add_mapping
DECL|function|clear_mailmap
DECL|function|debug_mm
DECL|function|free_mailmap_entry
DECL|function|free_mailmap_info
DECL|function|map_email
DECL|function|map_user
DECL|function|parse_name_and_email
DECL|function|read_mailmap
DECL|function|read_single_mailmap
DECL|macro|DEBUG_MAILMAP
DECL|macro|debug_mm
DECL|member|email
DECL|member|email
DECL|member|name
DECL|member|name
DECL|member|namemap
DECL|struct|mailmap_entry
DECL|struct|mailmap_info
DECL|variable|git_mailmap_file
