DECL|function|main
DECL|function|merge_all
DECL|function|merge_entry
DECL|function|merge_file
DECL|function|run_program
DECL|variable|arguments
DECL|variable|err
DECL|variable|one_shot
DECL|variable|pgm
DECL|variable|quiet
