DECL|function|add_cacheinfo
DECL|function|better_branch_name
DECL|function|commit_list_count
DECL|function|conflict_rename_dir
DECL|function|conflict_rename_rename
DECL|function|conflict_rename_rename_2
DECL|function|fill_mm
DECL|function|flush_buffer
DECL|function|get_files_dirs
DECL|function|get_ref
DECL|function|get_renames
DECL|function|get_unmerged
DECL|function|git_merge_trees
DECL|function|git_write_tree
DECL|function|has_sha
DECL|function|insert_stage_data
DECL|function|main
DECL|function|make_cache_entry
DECL|function|make_virtual_commit
DECL|function|merge
DECL|function|merge_file
DECL|function|merge_trees
DECL|function|mkdir_p
DECL|function|output
DECL|function|output_commit_title
DECL|function|process_entry
DECL|function|process_renames
DECL|function|remove_file
DECL|function|remove_path
DECL|function|reverse_commit_list
DECL|function|save_files_dirs
DECL|function|sha_eq
DECL|function|unique_path
DECL|function|unmerged_index
DECL|function|update_file
DECL|function|update_file_flags
DECL|function|update_stages
DECL|member|clean
DECL|member|dst_entry
DECL|member|merge
DECL|member|mode
DECL|member|mode
DECL|member|pair
DECL|member|processed
DECL|member|processed
DECL|member|sha
DECL|member|sha
DECL|member|src_entry
DECL|member|stages
DECL|struct|merge_file_info
DECL|struct|rename
DECL|struct|stage_data
DECL|variable|current_directory_set
DECL|variable|current_file_set
DECL|variable|index_only
DECL|variable|output_indent
