DECL|function|get_merge_bases
DECL|function|interesting
DECL|function|main
DECL|function|mark_reachable_commits
DECL|function|merge_base
DECL|macro|PARENT1
DECL|macro|PARENT2
DECL|macro|UNINTERESTING
DECL|variable|merge_base_usage
DECL|variable|show_all
