DECL|enumerator|MERGE_RECURSIVE_NORMAL
DECL|enumerator|MERGE_RECURSIVE_OURS
DECL|enumerator|MERGE_RECURSIVE_THEIRS
DECL|macro|MERGE_RECURSIVE_H
DECL|member|branch1
DECL|member|branch2
DECL|member|buffer_output
DECL|member|call_depth
DECL|member|current_directory_set
DECL|member|current_file_set
DECL|member|diff_rename_limit
DECL|member|merge_rename_limit
DECL|member|obuf
DECL|member|recursive_variant
DECL|member|subtree_shift
DECL|member|verbosity
DECL|struct|merge_options
