DECL|function|add_cacheinfo
DECL|function|conflict_rename_dir
DECL|function|conflict_rename_rename
DECL|function|conflict_rename_rename_2
DECL|function|fill_mm
DECL|function|flush_buffer
DECL|function|flush_output
DECL|function|get_files_dirs
DECL|function|get_ref
DECL|function|get_renames
DECL|function|get_unmerged
DECL|function|git_merge_trees
DECL|function|init_merge_options
DECL|function|init_tree_desc_from_tree
DECL|function|insert_stage_data
DECL|function|make_room_for_path
DECL|function|make_virtual_commit
DECL|function|merge_3way
DECL|function|merge_file
DECL|function|merge_recursive
DECL|function|merge_recursive_config
DECL|function|merge_recursive_generic
DECL|function|merge_trees
DECL|function|output
DECL|function|output_commit_title
DECL|function|process_entry
DECL|function|process_renames
DECL|function|remove_file
DECL|function|reverse_commit_list
DECL|function|save_files_dirs
DECL|function|sha_eq
DECL|function|shift_tree_object
DECL|function|show
DECL|function|stage_sha
DECL|function|unique_path
DECL|function|update_file
DECL|function|update_file_flags
DECL|function|update_stages
DECL|function|would_lose_untracked
DECL|function|write_tree_from_memory
DECL|member|clean
DECL|member|dst_entry
DECL|member|merge
DECL|member|mode
DECL|member|mode
DECL|member|pair
DECL|member|processed
DECL|member|processed
DECL|member|sha
DECL|member|sha
DECL|member|src_entry
DECL|member|stages
DECL|struct|merge_file_info
DECL|struct|rename
DECL|struct|stage_data
