DECL|function|create_delta_object
DECL|function|create_object
DECL|function|expand_delta
DECL|function|get_buffer
DECL|function|get_object_size
DECL|function|main
DECL|function|replace_object
DECL|function|restore_original_object
DECL|variable|mkdelta_usage
