DECL|function|append_to_tree
DECL|function|ent_compare
DECL|function|main
DECL|function|write_tree
DECL|member|len
DECL|member|mode
DECL|member|name
DECL|member|sha1
DECL|struct|treeent
DECL|variable|alloc
DECL|variable|entries
DECL|variable|mktree_usage
DECL|variable|used
