DECL|function|add_dir_entry
DECL|function|add_name_hash
DECL|function|find_dir_entry
DECL|function|free_dir_entry
DECL|function|free_name_hash
DECL|function|hash_dir_entry
DECL|function|hash_index_entry
DECL|function|hash_name
DECL|function|icase_hash
DECL|function|index_dir_exists
DECL|function|index_file_exists
DECL|function|index_name_exists
DECL|function|lazy_init_name_hash
DECL|function|remove_dir_entry
DECL|function|remove_name_hash
DECL|function|same_name
DECL|function|slow_same_name
DECL|macro|NO_THE_INDEX_COMPATIBILITY_MACROS
DECL|member|ce
DECL|member|namelen
DECL|member|next
DECL|member|nr
DECL|member|parent
DECL|struct|dir_entry
