DECL|function|concatenate_notes
DECL|function|free_notes
DECL|function|get_commit_notes
DECL|function|get_sha1_hex_segment
DECL|function|initialize_notes
DECL|function|load_subtree
DECL|function|lookup_notes
DECL|function|note_tree_find
DECL|function|note_tree_free
DECL|function|note_tree_insert
DECL|function|note_tree_search
DECL|macro|CLR_PTR_TYPE
DECL|macro|GET_NIBBLE
DECL|macro|GET_PTR_TYPE
DECL|macro|PTR_TYPE_INTERNAL
DECL|macro|PTR_TYPE_NOTE
DECL|macro|PTR_TYPE_NULL
DECL|macro|PTR_TYPE_SUBTREE
DECL|macro|SET_PTR_TYPE
DECL|macro|SUBTREE_SHA1_PREFIXCMP
DECL|member|a
DECL|member|key_sha1
DECL|member|val_sha1
DECL|struct|int_node
DECL|struct|leaf_node
DECL|variable|initialized
DECL|variable|root_node
