DECL|function|add_entry
DECL|function|get_commit_notes
DECL|function|hash_index
DECL|function|initialize_hash_map
DECL|function|lookup_notes
DECL|member|commit_sha1
DECL|member|count
DECL|member|entries
DECL|member|notes_sha1
DECL|member|size
DECL|struct|entry
DECL|struct|hash_map
DECL|variable|hash_map
DECL|variable|initialized
