DECL|function|add_non_note
DECL|function|add_note
DECL|function|combine_notes_cat_sort_uniq
DECL|function|combine_notes_concatenate
DECL|function|combine_notes_ignore
DECL|function|combine_notes_overwrite
DECL|function|construct_path_with_fanout
DECL|function|copy_note
DECL|function|default_notes_ref
DECL|function|determine_fanout
DECL|function|expand_notes_ref
DECL|function|for_each_note
DECL|function|for_each_note_helper
DECL|function|format_display_notes
DECL|function|format_note
DECL|function|free_notes
DECL|function|get_note
DECL|function|get_sha1_hex_segment
DECL|function|init_display_notes
DECL|function|init_notes
DECL|function|load_notes_trees
DECL|function|load_subtree
DECL|function|matches_tree_write_stack
DECL|function|non_note_cmp
DECL|function|note_tree_consolidate
DECL|function|note_tree_find
DECL|function|note_tree_free
DECL|function|note_tree_insert
DECL|function|note_tree_remove
DECL|function|note_tree_search
DECL|function|notes_display_config
DECL|function|prune_notes
DECL|function|prune_notes_helper
DECL|function|remove_note
DECL|function|string_list_add_note_lines
DECL|function|string_list_add_one_ref
DECL|function|string_list_add_refs_by_glob
DECL|function|string_list_add_refs_from_colon_sep
DECL|function|string_list_join_lines_helper
DECL|function|tree_write_stack_finish_subtree
DECL|function|tree_write_stack_init_subtree
DECL|function|write_each_non_note_until
DECL|function|write_each_note
DECL|function|write_each_note_helper
DECL|function|write_notes_tree
DECL|function|write_tree_entry
DECL|macro|CLR_PTR_TYPE
DECL|macro|GET_NIBBLE
DECL|macro|GET_PTR_TYPE
DECL|macro|PTR_TYPE_INTERNAL
DECL|macro|PTR_TYPE_NOTE
DECL|macro|PTR_TYPE_NULL
DECL|macro|PTR_TYPE_SUBTREE
DECL|macro|SET_PTR_TYPE
DECL|macro|SUBTREE_SHA1_PREFIXCMP
DECL|member|a
DECL|member|buf
DECL|member|key_sha1
DECL|member|mode
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next_non_note
DECL|member|path
DECL|member|path
DECL|member|root
DECL|member|sha1
DECL|member|sha1
DECL|member|val_sha1
DECL|struct|int_node
DECL|struct|leaf_node
DECL|struct|non_note
DECL|struct|note_delete_list
DECL|struct|tree_write_stack
DECL|struct|write_each_note_data
DECL|variable|default_notes_tree
DECL|variable|display_notes_refs
DECL|variable|display_notes_trees
