DECL|enumerator|NOTES_MERGE_RESOLVE_CAT_SORT_UNIQ
DECL|enumerator|NOTES_MERGE_RESOLVE_MANUAL
DECL|enumerator|NOTES_MERGE_RESOLVE_OURS
DECL|enumerator|NOTES_MERGE_RESOLVE_THEIRS
DECL|enumerator|NOTES_MERGE_RESOLVE_UNION
DECL|enum|notes_merge_strategy
DECL|macro|NOTES_UTILS_H
DECL|member|cmd
DECL|member|combine
DECL|member|enabled
DECL|member|mode_from_env
DECL|member|refs
DECL|member|refs_from_env
DECL|member|trees
DECL|struct|notes_rewrite_cfg
