DECL|macro|FOR_EACH_NOTE_DONT_UNPACK_SUBTREES
DECL|macro|FOR_EACH_NOTE_YIELD_SUBTREES
DECL|macro|NOTES_H
DECL|macro|NOTES_INDENT
DECL|macro|NOTES_INIT_EMPTY
DECL|macro|NOTES_SHOW_HEADER
DECL|member|initialized
DECL|member|ref
DECL|member|root
DECL|struct|notes_tree
DECL|typedef|each_note_fn
