DECL|macro|FLAG_BITS
DECL|macro|OBJECT_ARRAY_INIT
DECL|macro|OBJECT_H
DECL|macro|TYPE_BITS
DECL|macro|type_from_string
DECL|member|alloc
DECL|member|flags
DECL|member|item
DECL|member|item
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|nr
DECL|member|objects
DECL|member|parsed
DECL|member|path
DECL|member|sha1
DECL|member|type
DECL|member|used
DECL|struct|object
DECL|struct|object_array
DECL|struct|object_array_entry
DECL|struct|object_list
DECL|typedef|object_array_each_func_t
