DECL|function|add_object_array
DECL|function|created_object
DECL|function|find_object
DECL|function|get_indexed_object
DECL|function|get_max_object_index
DECL|function|hashtable_index
DECL|function|lookup_object
DECL|function|lookup_object_type
DECL|function|lookup_unknown_object
DECL|function|object_list_append
DECL|function|object_list_contains
DECL|function|object_list_insert
DECL|function|object_list_length
DECL|function|parse_object
DECL|member|blob
DECL|member|commit
DECL|member|object
DECL|member|tag
DECL|member|tree
DECL|union|any_object
DECL|variable|nr_objs
DECL|variable|obj_allocs
DECL|variable|objs
DECL|variable|type_names
