DECL|function|typename
DECL|macro|FLAG_BITS
DECL|macro|OBJECT_H
DECL|macro|TYPE_BITS
DECL|member|alloc
DECL|member|base
DECL|member|count
DECL|member|flags
DECL|member|item
DECL|member|item
DECL|member|name
DECL|member|next
DECL|member|nr
DECL|member|objects
DECL|member|parsed
DECL|member|ref
DECL|member|sha1
DECL|member|type
DECL|member|used
DECL|struct|object
DECL|struct|object_array
DECL|struct|object_array_entry
DECL|struct|object_list
DECL|struct|object_refs
