DECL|enumerator|OBJ_BLOB
DECL|enumerator|OBJ_COMMIT
DECL|enumerator|OBJ_DELTA
DECL|enumerator|OBJ_NONE
DECL|enumerator|OBJ_TREE
DECL|enum|object_type
DECL|function|add_object_entry
DECL|function|check_object
DECL|function|create_file
DECL|function|create_sorted_list
DECL|function|delta_against
DECL|function|find_deltas
DECL|function|fwrite_compressed
DECL|function|get_object_details
DECL|function|main
DECL|function|sha1_sort
DECL|function|sort_comparator
DECL|function|try_delta
DECL|function|type_size_sort
DECL|function|write_index_file
DECL|function|write_object
DECL|function|write_pack_file
DECL|member|buffer
DECL|member|chars
DECL|member|data
DECL|member|delta
DECL|member|delta_size
DECL|member|depth
DECL|member|entry
DECL|member|fd
DECL|member|hash
DECL|member|offset
DECL|member|sha1
DECL|member|size
DECL|member|type
DECL|struct|myfile
DECL|struct|object_entry
DECL|struct|unpacked
DECL|typedef|entry_sort_t
DECL|variable|base_name
DECL|variable|current_sort
DECL|variable|nr_alloc
DECL|variable|nr_objects
DECL|variable|objects
DECL|variable|pack_usage
DECL|variable|sorted_by_sha
DECL|variable|sorted_by_type
