DECL|function|check_pack_crc
DECL|function|compare_entries
DECL|function|verify_pack
DECL|function|verify_pack_index
DECL|function|verify_packfile
DECL|member|nr
DECL|member|offset
DECL|member|sha1
DECL|struct|idx_entry
