DECL|macro|PACK_OBJECTS_H
DECL|member|delta
DECL|member|delta_child
DECL|member|delta_data
DECL|member|delta_sibling
DECL|member|delta_size
DECL|member|filled
DECL|member|hash
DECL|member|idx
DECL|member|in_pack
DECL|member|in_pack_header_size
DECL|member|in_pack_offset
DECL|member|in_pack_type
DECL|member|index
DECL|member|index_size
DECL|member|no_try_delta
DECL|member|nr_alloc
DECL|member|nr_objects
DECL|member|objects
DECL|member|preferred_base
DECL|member|size
DECL|member|tagged
DECL|member|type
DECL|member|z_delta_size
DECL|struct|object_entry
DECL|struct|packing_data
