DECL|enumerator|BITMAP_FLAG_REUSE
DECL|enumerator|BITMAP_OPT_FULL_DAG
DECL|enum|pack_bitmap_flags
DECL|enum|pack_bitmap_opts
DECL|macro|NEEDS_BITMAP
DECL|macro|PACK_BITMAP_H
DECL|member|checksum
DECL|member|entry_count
DECL|member|flags
DECL|member|magic
DECL|member|object_pos
DECL|member|options
DECL|member|version
DECL|member|xor_offset
DECL|struct|bitmap_disk_entry
DECL|struct|bitmap_disk_header
DECL|typedef|show_reachable_fn
DECL|variable|BITMAP_IDX_SIGNATURE
