DECL|function|create_pack_revindex
DECL|function|find_pack_revindex
DECL|function|find_revindex_position
DECL|function|init_pack_revindex
DECL|function|pack_revindex_ix
DECL|function|revindex_for_pack
DECL|function|sort_revindex
DECL|macro|BUCKETS
DECL|macro|BUCKETS
DECL|macro|BUCKET_FOR
DECL|macro|BUCKET_FOR
DECL|macro|DIGIT_SIZE
DECL|macro|DIGIT_SIZE
DECL|variable|pack_revindex
DECL|variable|pack_revindex_hashsz
