DECL|function|add_to_include_set
DECL|function|bitmap_position
DECL|function|bitmap_position_extended
DECL|function|bitmap_position_packfile
DECL|function|count_bitmap_commit_list
DECL|function|count_object_type
DECL|function|ext_index_add_object
DECL|function|find_objects
DECL|function|in_bitmapped_pack
DECL|function|load_bitmap_entries_v1
DECL|function|load_bitmap_header
DECL|function|load_pack_bitmap
DECL|function|lookup_stored_bitmap
DECL|function|open_pack_bitmap
DECL|function|open_pack_bitmap_1
DECL|function|pack_bitmap_filename
DECL|function|prepare_bitmap_git
DECL|function|prepare_bitmap_walk
DECL|function|read_be32
DECL|function|read_bitmap_1
DECL|function|read_u8
DECL|function|rebuild_bitmap
DECL|function|rebuild_existing_bitmaps
DECL|function|reuse_partial_packfile_from_bitmap
DECL|function|should_include
DECL|function|show_commit
DECL|function|show_extended_objects
DECL|function|show_object
DECL|function|show_objects_for_type
DECL|function|store_bitmap
DECL|function|test_bitmap_walk
DECL|function|test_show_commit
DECL|function|test_show_object
DECL|function|traverse_bitmap_commit_list
DECL|member|alloc
DECL|member|base
DECL|member|base
DECL|member|bitmaps
DECL|member|blobs
DECL|member|commits
DECL|member|count
DECL|member|entry_count
DECL|member|ext_index
DECL|member|flags
DECL|member|hashes
DECL|member|hashes
DECL|member|loaded
DECL|member|map
DECL|member|map_pos
DECL|member|map_size
DECL|member|objects
DECL|member|pack
DECL|member|positions
DECL|member|prg
DECL|member|result
DECL|member|reuse_objects
DECL|member|reverse_index
DECL|member|root
DECL|member|seen
DECL|member|seen
DECL|member|sha1
DECL|member|tags
DECL|member|trees
DECL|member|version
DECL|member|xor
DECL|struct|bitmap_index
DECL|struct|bitmap_test_data
DECL|struct|eindex
DECL|struct|include_data
DECL|struct|stored_bitmap
DECL|variable|bitmap_git
