DECL|function|encode_in_pack_object_header
DECL|function|fixup_pack_header_footer
DECL|function|index_pack_lockfile
DECL|function|sha1_compare
DECL|function|write_idx_file
DECL|variable|pack_idx_default_version
DECL|variable|pack_idx_off32_limit
