DECL|function|add_object_entry
DECL|function|add_pbase_tree
DECL|function|add_preferred_base
DECL|function|check_delta_limit
DECL|function|check_object
DECL|function|cmp_offset
DECL|function|create_final_object_list
DECL|function|create_sorted_list
DECL|function|delta_against
DECL|function|encode_header
DECL|function|find_deltas
DECL|function|find_packed_object_size
DECL|function|get_object_details
DECL|function|locate_object_entry
DECL|function|locate_object_entry_hash
DECL|function|main
DECL|function|name_hash
DECL|function|pack_revindex_ix
DECL|function|prepare_pack
DECL|function|prepare_pack_ix
DECL|function|prepare_pack_revindex
DECL|function|rehash_objects
DECL|function|reuse_cached_pack
DECL|function|sha1_sort
DECL|function|sort_comparator
DECL|function|try_delta
DECL|function|type_size_sort
DECL|function|write_index_file
DECL|function|write_object
DECL|function|write_one
DECL|function|write_pack_file
DECL|member|based_on_preferred
DECL|member|data
DECL|member|delta
DECL|member|delta_child
DECL|member|delta_limit
DECL|member|delta_sibling
DECL|member|delta_size
DECL|member|depth
DECL|member|elem
DECL|member|entry
DECL|member|hash
DECL|member|in_pack
DECL|member|in_pack_offset
DECL|member|in_pack_type
DECL|member|len
DECL|member|offset
DECL|member|p
DECL|member|preferred_base
DECL|member|revindex
DECL|member|sha1
DECL|member|size
DECL|member|type
DECL|member|up
DECL|struct|name_path
DECL|struct|object_entry
DECL|struct|pack_revindex
DECL|struct|unpacked
DECL|typedef|entry_sort_t
DECL|variable|base_name
DECL|variable|current_sort
DECL|variable|incremental
DECL|variable|local
DECL|variable|no_reuse_delta
DECL|variable|non_empty
DECL|variable|nr_alloc
DECL|variable|nr_objects
DECL|variable|nr_result
DECL|variable|object_ix
DECL|variable|object_ix_hashsz
DECL|variable|object_list_sha1
DECL|variable|objects
DECL|variable|pack_file_sha1
DECL|variable|pack_revindex
DECL|variable|pack_revindex_hashsz
DECL|variable|pack_usage
DECL|variable|progress
DECL|variable|reused
DECL|variable|reused_delta
DECL|variable|sorted_by_sha
DECL|variable|sorted_by_type
DECL|variable|written
DECL|variable|written_delta
