DECL|function|add_to_include_set
DECL|function|bitmap_writer_build
DECL|function|bitmap_writer_build_type_index
DECL|function|bitmap_writer_finish
DECL|function|bitmap_writer_reuse_bitmaps
DECL|function|bitmap_writer_select_commits
DECL|function|bitmap_writer_set_checksum
DECL|function|bitmap_writer_show_progress
DECL|function|compute_xor_offsets
DECL|function|date_compare
DECL|function|dump_bitmap
DECL|function|find_object_pos
DECL|function|find_reused_bitmap
DECL|function|mark_as_seen
DECL|function|next_commit_index
DECL|function|push_bitmapped_commit
DECL|function|reset_all_seen
DECL|function|sha1_access
DECL|function|sha1write_ewah_helper
DECL|function|should_include
DECL|function|show_commit
DECL|function|show_object
DECL|function|write_selected_commits_v1
DECL|member|bitmap
DECL|member|bitmaps
DECL|member|blobs
DECL|member|commit
DECL|member|commit_pos
DECL|member|commits
DECL|member|flags
DECL|member|pack_checksum
DECL|member|progress
DECL|member|reused
DECL|member|selected
DECL|member|selected_alloc
DECL|member|selected_nr
DECL|member|show_progress
DECL|member|tags
DECL|member|to_pack
DECL|member|trees
DECL|member|write_as
DECL|member|xor_offset
DECL|struct|bitmap_writer
DECL|struct|bitmapped_commit
DECL|variable|seen_objects
DECL|variable|seen_objects_alloc
DECL|variable|seen_objects_nr
DECL|variable|writer
