DECL|macro|PACK_H
DECL|macro|PACK_IDX_SIGNATURE
DECL|macro|PACK_SIGNATURE
DECL|macro|PACK_VERSION
DECL|macro|PH_ERROR_EOF
DECL|macro|PH_ERROR_PACK_SIGNATURE
DECL|macro|PH_ERROR_PROTOCOL
DECL|macro|WRITE_IDX_VERIFY
DECL|macro|pack_version_ok
DECL|member|anomaly
DECL|member|anomaly_alloc
DECL|member|anomaly_nr
DECL|member|crc32
DECL|member|flags
DECL|member|hdr_entries
DECL|member|hdr_signature
DECL|member|hdr_version
DECL|member|idx_signature
DECL|member|idx_version
DECL|member|off32_limit
DECL|member|offset
DECL|member|sha1
DECL|member|version
DECL|struct|pack_header
DECL|struct|pack_idx_entry
DECL|struct|pack_idx_header
DECL|struct|pack_idx_option
