DECL|function|cmp_offset
DECL|function|create_pack_revindex
DECL|function|find_pack_revindex
DECL|function|init_pack_revindex
DECL|function|pack_revindex_ix
DECL|member|p
DECL|member|revindex
DECL|struct|pack_revindex
DECL|variable|pack_revindex
DECL|variable|pack_revindex_hashsz
