DECL|enumerator|OBJ_BLOB
DECL|enumerator|OBJ_COMMIT
DECL|enumerator|OBJ_DELTA
DECL|enumerator|OBJ_NONE
DECL|enumerator|OBJ_TAG
DECL|enumerator|OBJ_TREE
DECL|enum|object_type
DECL|macro|PACK_H
DECL|macro|PACK_SIGNATURE
DECL|member|hdr_entries
DECL|member|hdr_signature
DECL|member|hdr_version
DECL|struct|pack_header
