DECL|function|git_pager
DECL|function|pager_in_use
DECL|function|pager_preexec
DECL|function|setup_pager
DECL|function|term_columns
DECL|function|wait_for_pager
DECL|function|wait_for_pager_signal
DECL|macro|DEFAULT_PAGER
DECL|variable|pager_argv
DECL|variable|pager_process
