DECL|enumerator|OPTION_ARGUMENT
DECL|enumerator|OPTION_BIT
DECL|enumerator|OPTION_CALLBACK
DECL|enumerator|OPTION_COUNTUP
DECL|enumerator|OPTION_END
DECL|enumerator|OPTION_FILENAME
DECL|enumerator|OPTION_GROUP
DECL|enumerator|OPTION_INTEGER
DECL|enumerator|OPTION_LOWLEVEL_CALLBACK
DECL|enumerator|OPTION_NEGBIT
DECL|enumerator|OPTION_NUMBER
DECL|enumerator|OPTION_SET_INT
DECL|enumerator|OPTION_SET_PTR
DECL|enumerator|OPTION_STRING
DECL|enumerator|PARSE_OPT_DONE
DECL|enumerator|PARSE_OPT_HELP
DECL|enumerator|PARSE_OPT_HIDDEN
DECL|enumerator|PARSE_OPT_KEEP_ARGV0
DECL|enumerator|PARSE_OPT_KEEP_DASHDASH
DECL|enumerator|PARSE_OPT_KEEP_UNKNOWN
DECL|enumerator|PARSE_OPT_LASTARG_DEFAULT
DECL|enumerator|PARSE_OPT_LITERAL_ARGHELP
DECL|enumerator|PARSE_OPT_NEGHELP
DECL|enumerator|PARSE_OPT_NOARG
DECL|enumerator|PARSE_OPT_NODASH
DECL|enumerator|PARSE_OPT_NONEG
DECL|enumerator|PARSE_OPT_NON_OPTION
DECL|enumerator|PARSE_OPT_NO_INTERNAL_HELP
DECL|enumerator|PARSE_OPT_OPTARG
DECL|enumerator|PARSE_OPT_SHELL_EVAL
DECL|enumerator|PARSE_OPT_STOP_AT_NON_OPTION
DECL|enumerator|PARSE_OPT_UNKNOWN
DECL|enum|parse_opt_flags
DECL|enum|parse_opt_option_flags
DECL|enum|parse_opt_type
DECL|macro|OPTION_BOOLEAN
DECL|macro|OPT_ARGUMENT
DECL|macro|OPT_BIT
DECL|macro|OPT_BOOL
DECL|macro|OPT_BOOLEAN
DECL|macro|OPT_CALLBACK
DECL|macro|OPT_COLOR_FLAG
DECL|macro|OPT_COLUMN
DECL|macro|OPT_COUNTUP
DECL|macro|OPT_DATE
DECL|macro|OPT_END
DECL|macro|OPT_FILENAME
DECL|macro|OPT_GROUP
DECL|macro|OPT_INTEGER
DECL|macro|OPT_NEGBIT
DECL|macro|OPT_NOOP_NOARG
DECL|macro|OPT_NUMBER_CALLBACK
DECL|macro|OPT_SET_INT
DECL|macro|OPT_SET_PTR
DECL|macro|OPT_STRING
DECL|macro|OPT_STRING_LIST
DECL|macro|OPT_UYN
DECL|macro|OPT__ABBREV
DECL|macro|OPT__COLOR
DECL|macro|OPT__DRY_RUN
DECL|macro|OPT__FORCE
DECL|macro|OPT__QUIET
DECL|macro|OPT__VERBOSE
DECL|macro|OPT__VERBOSITY
DECL|macro|PARSE_OPTIONS_H
DECL|member|argc
DECL|member|argh
DECL|member|argv
DECL|member|callback
DECL|member|cpidx
DECL|member|defval
DECL|member|flags
DECL|member|flags
DECL|member|help
DECL|member|long_name
DECL|member|opt
DECL|member|out
DECL|member|prefix
DECL|member|short_name
DECL|member|type
DECL|member|value
DECL|struct|option
DECL|struct|parse_opt_ctx_t
DECL|typedef|parse_opt_cb
DECL|typedef|parse_opt_ll_cb
