DECL|enumerator|OPTION_BOOLEAN
DECL|enumerator|OPTION_END
DECL|enumerator|OPTION_GROUP
DECL|enumerator|OPTION_INTEGER
DECL|enumerator|OPTION_STRING
DECL|enumerator|PARSE_OPT_KEEP_DASHDASH
DECL|enum|parse_opt_flags
DECL|enum|parse_opt_type
DECL|macro|OPT_BOOLEAN
DECL|macro|OPT_END
DECL|macro|OPT_GROUP
DECL|macro|OPT_INTEGER
DECL|macro|OPT_STRING
DECL|macro|PARSE_OPTIONS_H
DECL|member|argh
DECL|member|help
DECL|member|long_name
DECL|member|short_name
DECL|member|type
DECL|member|value
DECL|struct|option
