DECL|enumerator|OPTION_BIT
DECL|enumerator|OPTION_BOOLEAN
DECL|enumerator|OPTION_CALLBACK
DECL|enumerator|OPTION_END
DECL|enumerator|OPTION_GROUP
DECL|enumerator|OPTION_INTEGER
DECL|enumerator|OPTION_SET_INT
DECL|enumerator|OPTION_SET_PTR
DECL|enumerator|OPTION_STRING
DECL|enumerator|PARSE_OPT_HIDDEN
DECL|enumerator|PARSE_OPT_KEEP_DASHDASH
DECL|enumerator|PARSE_OPT_NOARG
DECL|enumerator|PARSE_OPT_NONEG
DECL|enumerator|PARSE_OPT_OPTARG
DECL|enumerator|PARSE_OPT_STOP_AT_NON_OPTION
DECL|enum|parse_opt_flags
DECL|enum|parse_opt_option_flags
DECL|enum|parse_opt_type
DECL|macro|OPT_BIT
DECL|macro|OPT_BOOLEAN
DECL|macro|OPT_CALLBACK
DECL|macro|OPT_END
DECL|macro|OPT_GROUP
DECL|macro|OPT_INTEGER
DECL|macro|OPT_SET_INT
DECL|macro|OPT_SET_PTR
DECL|macro|OPT_STRING
DECL|macro|OPT__ABBREV
DECL|macro|OPT__DRY_RUN
DECL|macro|OPT__QUIET
DECL|macro|OPT__VERBOSE
DECL|macro|PARSE_OPTIONS_H
DECL|member|argh
DECL|member|callback
DECL|member|defval
DECL|member|flags
DECL|member|help
DECL|member|long_name
DECL|member|short_name
DECL|member|type
DECL|member|value
DECL|struct|option
DECL|typedef|parse_opt_cb
