DECL|function|check_typos
DECL|function|fix_filename
DECL|function|get_arg
DECL|function|get_value
DECL|function|optbug
DECL|function|opterror
DECL|function|parse_long_opt
DECL|function|parse_nodash_opt
DECL|function|parse_options
DECL|function|parse_options_check
DECL|function|parse_options_end
DECL|function|parse_options_start
DECL|function|parse_options_step
DECL|function|parse_options_usage
DECL|function|parse_short_opt
DECL|function|usage_argh
DECL|function|usage_msg_opt
DECL|function|usage_with_options
DECL|function|usage_with_options_internal
DECL|macro|OPT_SHORT
DECL|macro|OPT_UNSET
DECL|macro|USAGE_GAP
DECL|macro|USAGE_OPTS_WIDTH
