DECL|function|chomp_trailing_dir_sep
DECL|function|cleanup_path
DECL|function|daemon_avoid_alias
DECL|function|enter_repo
DECL|function|expand_user_path
DECL|function|get_pathname
DECL|function|getpw_str
DECL|function|git_path
DECL|function|git_path_submodule
DECL|function|git_pathdup
DECL|function|git_snpath
DECL|function|git_vsnpath
DECL|function|longest_ancestor_length
DECL|function|mkpath
DECL|function|mksnpath
DECL|function|normalize_path_copy
DECL|function|offset_1st_component
DECL|function|relative_path
DECL|function|set_shared_perm
DECL|function|strip_path_suffix
DECL|function|validate_headref
DECL|variable|bad_path
