DECL|function|format_packet
DECL|function|packet_buf_flush
DECL|function|packet_buf_write
DECL|function|packet_flush
DECL|function|packet_get_line
DECL|function|packet_length
DECL|function|packet_read_line
DECL|function|packet_write
DECL|function|safe_read
DECL|function|safe_write
DECL|macro|hex
DECL|variable|buffer
