DECL|function|format_packet
DECL|function|get_packet_data
DECL|function|packet_buf_flush
DECL|function|packet_buf_write
DECL|function|packet_flush
DECL|function|packet_length
DECL|function|packet_read
DECL|function|packet_read_line
DECL|function|packet_read_line_buf
DECL|function|packet_read_line_generic
DECL|function|packet_trace
DECL|function|packet_trace_identity
DECL|function|packet_write
DECL|macro|hex
DECL|variable|buffer
DECL|variable|packet_buffer
DECL|variable|packet_trace_prefix
DECL|variable|trace_packet
