DECL|function|add_again
DECL|function|add_merge_info
DECL|function|add_rfc2047
DECL|function|format_commit_item
DECL|function|format_commit_message
DECL|function|format_person_part
DECL|function|get_commit_format
DECL|function|get_header
DECL|function|get_one_line
DECL|function|is_empty_line
DECL|function|is_rfc2047_special
DECL|function|logmsg_reencode
DECL|function|mailmap_name
DECL|function|non_ascii
DECL|function|parse_commit_header
DECL|function|pp_header
DECL|function|pp_remainder
DECL|function|pp_title_line
DECL|function|pp_user_info
DECL|function|pretty_print_commit
DECL|function|replace_encoding_header
DECL|member|abbrev_commit_hash
DECL|member|abbrev_parent_hashes
DECL|member|abbrev_tree_hash
DECL|member|author
DECL|member|body_off
DECL|member|commit
DECL|member|commit_header_parsed
DECL|member|committer
DECL|member|encoding
DECL|member|len
DECL|member|off
DECL|member|subject
DECL|struct|chunk
DECL|struct|format_commit_context
DECL|variable|user_format
