DECL|function|add_again
DECL|function|add_merge_info
DECL|function|add_rfc2047
DECL|function|add_rfc822_quoted
DECL|function|find_commit_format
DECL|function|find_commit_format_recursive
DECL|function|format_commit_item
DECL|function|format_commit_message
DECL|function|format_commit_one
DECL|function|format_decoration
DECL|function|format_person_part
DECL|function|format_sanitized_subject
DECL|function|format_subject
DECL|function|get_commit_format
DECL|function|get_header
DECL|function|get_one_line
DECL|function|git_pretty_formats_config
DECL|function|has_non_ascii
DECL|function|has_rfc822_specials
DECL|function|is_empty_line
DECL|function|is_rfc2047_special
DECL|function|is_rfc822_special
DECL|function|istitlechar
DECL|function|logmsg_reencode
DECL|function|mailmap_name
DECL|function|non_ascii
DECL|function|parse_commit_header
DECL|function|parse_commit_message
DECL|function|parse_commit_signature
DECL|function|parse_signature_lines
DECL|function|pp_commit_easy
DECL|function|pp_header
DECL|function|pp_remainder
DECL|function|pp_title_line
DECL|function|pp_user_info
DECL|function|pretty_print_commit
DECL|function|reencode_commit_message
DECL|function|replace_encoding_header
DECL|function|rewrap_message_tail
DECL|function|save_user_format
DECL|function|setup_commit_formats
DECL|function|skip_empty_lines
DECL|function|strbuf_wrap
DECL|function|userformat_find_requirements
DECL|function|userformat_want_item
DECL|member|abbrev_commit_hash
DECL|member|abbrev_parent_hashes
DECL|member|abbrev_tree_hash
DECL|member|author
DECL|member|body_off
DECL|member|check
DECL|member|commit
DECL|member|commit_header_parsed
DECL|member|commit_message_parsed
DECL|member|commit_signature_parsed
DECL|member|committer
DECL|member|encoding
DECL|member|format
DECL|member|good_bad
DECL|member|gpg_output
DECL|member|indent1
DECL|member|indent2
DECL|member|is_alias
DECL|member|is_tformat
DECL|member|len
DECL|member|message
DECL|member|message_off
DECL|member|name
DECL|member|off
DECL|member|pretty_ctx
DECL|member|result
DECL|member|signature
DECL|member|signer
DECL|member|subject_off
DECL|member|user_format
DECL|member|width
DECL|member|wrap_start
DECL|struct|chunk
DECL|struct|cmt_fmt_map
DECL|struct|format_commit_context
DECL|variable|builtin_formats_len
DECL|variable|commit_formats
DECL|variable|commit_formats_alloc
DECL|variable|commit_formats_len
DECL|variable|signature_check
DECL|variable|user_format
