DECL|function|add_merge_info
DECL|function|add_rfc2047
DECL|function|add_user_info
DECL|function|fill_person
DECL|function|format_commit_message
DECL|function|get_commit_format
DECL|function|get_header
DECL|function|get_one_line
DECL|function|is_empty_line
DECL|function|is_rfc2047_special
DECL|function|logmsg_reencode
DECL|function|non_ascii
DECL|function|pp_header
DECL|function|pp_remainder
DECL|function|pp_title_line
DECL|function|pretty_print_commit
DECL|function|replace_encoding_header
DECL|member|cmp_len
DECL|member|n
DECL|member|v
DECL|struct|cmt_fmt_map
DECL|variable|cmt_fmts
DECL|variable|user_format
