DECL|function|clear_progress_signal
DECL|function|display
DECL|function|display_progress
DECL|function|display_throughput
DECL|function|progress_interval
DECL|function|set_progress_signal
DECL|function|start_progress
DECL|function|start_progress_delay
DECL|function|stop_progress
DECL|function|stop_progress_msg
DECL|function|throughput_string
DECL|macro|TP_IDX_MAX
DECL|member|avg_bytes
DECL|member|avg_misecs
DECL|member|curr_total
DECL|member|delay
DECL|member|delayed_percent_treshold
DECL|member|display
DECL|member|idx
DECL|member|last_bytes
DECL|member|last_misecs
DECL|member|last_percent
DECL|member|last_value
DECL|member|prev_total
DECL|member|prev_tv
DECL|member|throughput
DECL|member|title
DECL|member|total
DECL|struct|progress
DECL|struct|throughput
DECL|variable|progress_update
