DECL|function|make_sure_we_have_it
DECL|function|process_commit
DECL|function|process_tree
DECL|function|pull
DECL|function|report_missing
DECL|variable|blobS
DECL|variable|commitS
DECL|variable|current_commit_sha1
DECL|variable|get_all
DECL|variable|get_history
DECL|variable|get_tree
DECL|variable|treeS
