DECL|function|need_bs_quote
DECL|function|next_quote_pos
DECL|function|path_relative
DECL|function|perl_quote_print
DECL|function|python_quote_print
DECL|function|quote_c_style
DECL|function|quote_c_style_counted
DECL|function|quote_path_relative
DECL|function|quote_two_c_style
DECL|function|sq_dequote
DECL|function|sq_dequote_step
DECL|function|sq_dequote_to_argv
DECL|function|sq_dequote_to_argv_array
DECL|function|sq_dequote_to_argv_internal
DECL|function|sq_must_quote
DECL|function|sq_quote_argv
DECL|function|sq_quote_buf
DECL|function|sq_quote_print
DECL|function|tcl_quote_print
DECL|function|unquote_c_style
DECL|function|write_name_quoted
DECL|function|write_name_quoted_relative
DECL|function|write_name_quotedpfx
DECL|macro|EMIT
DECL|macro|EMIT
DECL|macro|EMITBUF
DECL|macro|X16
DECL|macro|X8
DECL|variable|quote_path_fully
DECL|variable|sq_lookup
