DECL|function|append8
DECL|function|fls16
DECL|function|fls32
DECL|function|fls64
DECL|function|fls8
DECL|function|polymmult
DECL|function|polymod
DECL|function|polymult
DECL|function|rabin_init
DECL|function|rabin_reset
DECL|function|rabin_slide8
DECL|macro|MSB64
DECL|variable|T
DECL|variable|U
DECL|variable|buf
DECL|variable|bufpos
DECL|variable|fingerprint
DECL|variable|poly
DECL|variable|shift
DECL|variable|size
