DECL|function|add_one_ref
DECL|function|add_recent_loose
DECL|function|add_recent_object
DECL|function|add_recent_packed
DECL|function|add_unseen_recent_objects_to_traversal
DECL|function|mark_commit
DECL|function|mark_object
DECL|function|mark_reachable_objects
DECL|function|update_progress
DECL|member|count
DECL|member|progress
DECL|member|revs
DECL|member|timestamp
DECL|struct|connectivity_progress
DECL|struct|recent_data
