DECL|function|add_cache_refs
DECL|function|add_cache_tree
DECL|function|add_one_ref
DECL|function|add_one_reflog
DECL|function|add_one_reflog_ent
DECL|function|add_one_tree
DECL|function|mark_reachable_objects
DECL|function|process_blob
DECL|function|process_gitlink
DECL|function|process_tag
DECL|function|process_tree
DECL|function|walk_commit_list
