DECL|function|add_cache_refs
DECL|function|add_cache_tree
DECL|function|add_one_ref
DECL|function|add_one_tree
DECL|function|mark_commit
DECL|function|mark_object
DECL|function|mark_reachable_objects
DECL|function|update_progress
DECL|member|count
DECL|member|progress
DECL|struct|connectivity_progress
