DECL|function|causes_df_conflict
DECL|function|check_updates
DECL|function|deleted_entry
DECL|function|main
DECL|function|merge_cache
DECL|function|merge_entries
DECL|function|merged_entry
DECL|function|merged_entry_allow_dirty
DECL|function|merged_entry_internal
DECL|function|oneway_merge
DECL|function|path_matches
DECL|function|read_cache_unmerged
DECL|function|reject_merge
DECL|function|same
DECL|function|setup_emu23
DECL|function|threeway_merge
DECL|function|twoway_merge
DECL|function|unpack_tree
DECL|function|verify_uptodate
DECL|typedef|merge_fn_t
DECL|variable|cache_file
DECL|variable|read_tree_usage
DECL|variable|stage
DECL|variable|update
