DECL|function|add_file_to_index
DECL|function|add_index_entry
DECL|function|add_index_entry_with_check
DECL|function|add_to_index
DECL|function|base_name_compare
DECL|function|cache_entry_from_ondisk
DECL|function|cache_name_compare
DECL|function|ce_compare_data
DECL|function|ce_compare_gitlink
DECL|function|ce_compare_link
DECL|function|ce_flush
DECL|function|ce_match_stat_basic
DECL|function|ce_modified_check_fs
DECL|function|ce_path_match
DECL|function|ce_same_name
DECL|function|ce_smudge_racily_clean_entry
DECL|function|ce_write
DECL|function|ce_write_entry
DECL|function|ce_write_flush
DECL|function|check_file_directory_conflict
DECL|function|compare_name
DECL|function|copy_cache_entry_to_ondisk
DECL|function|create_alias_ce
DECL|function|create_from_disk
DECL|function|df_name_compare
DECL|function|different_name
DECL|function|discard_index
DECL|function|expand_name_field
DECL|function|fill_stat_cache_info
DECL|function|has_dir_name
DECL|function|has_file_name
DECL|function|has_racy_timestamp
DECL|function|ie_match_stat
DECL|function|ie_modified
DECL|function|index_name_is_other
DECL|function|index_name_pos
DECL|function|index_name_pos_also_unmerged
DECL|function|is_empty_blob_sha1
DECL|function|is_index_unborn
DECL|function|is_racy_timestamp
DECL|function|make_cache_entry
DECL|function|ntoh_l_force_align
DECL|function|ntoh_s_force_align
DECL|function|read_index
DECL|function|read_index_extension
DECL|function|read_index_from
DECL|function|read_index_unmerged
DECL|function|record_intent_to_add
DECL|function|refresh_cache_ent
DECL|function|refresh_cache_entry
DECL|function|refresh_index
DECL|function|remove_file_from_index
DECL|function|remove_index_entry_at
DECL|function|remove_marked_cache_entries
DECL|function|rename_index_entry_at
DECL|function|replace_index_entry
DECL|function|set_index_entry
DECL|function|show_file
DECL|function|unmerged_index
DECL|function|update_index_if_able
DECL|function|verify_dotfile
DECL|function|verify_hdr
DECL|function|verify_path
DECL|function|write_index
DECL|function|write_index_ext_header
DECL|macro|CACHE_EXT
DECL|macro|CACHE_EXT_RESOLVE_UNDO
DECL|macro|CACHE_EXT_TREE
DECL|macro|INDEX_FORMAT_DEFAULT
DECL|macro|NO_THE_INDEX_COMPATIBILITY_MACROS
DECL|macro|WRITE_BUFFER_SIZE
DECL|macro|align_flex_name
DECL|macro|ntoh_l
DECL|macro|ntoh_l
DECL|macro|ntoh_s
DECL|macro|ntoh_s
DECL|macro|ondisk_cache_entry_extended_size
DECL|macro|ondisk_cache_entry_size
DECL|macro|ondisk_ce_size
DECL|member|ctime
DECL|member|ctime
DECL|member|dev
DECL|member|dev
DECL|member|flags
DECL|member|flags
DECL|member|flags2
DECL|member|gid
DECL|member|gid
DECL|member|ino
DECL|member|ino
DECL|member|mode
DECL|member|mode
DECL|member|mtime
DECL|member|mtime
DECL|member|name
DECL|member|name
DECL|member|sha1
DECL|member|sha1
DECL|member|size
DECL|member|size
DECL|member|uid
DECL|member|uid
DECL|struct|ondisk_cache_entry
DECL|struct|ondisk_cache_entry_extended
DECL|variable|the_index
DECL|variable|write_buffer
DECL|variable|write_buffer_len
