DECL|function|main
DECL|function|merge_entries
DECL|function|merge_stat_info
DECL|function|old_match
DECL|function|path_matches
DECL|function|remove_lock_file
DECL|function|same
DECL|function|trivially_merge_cache
DECL|function|unpack_tree
DECL|function|verify_cleared
DECL|function|verify_uptodate
DECL|variable|lockfile_name
DECL|variable|read_tree_usage
DECL|variable|stage
