DECL|function|execute_commands
DECL|function|main
DECL|function|read_head_info
DECL|function|report
DECL|function|run_update_hook
DECL|function|run_update_post_hook
DECL|function|show_ref
DECL|function|unpack
DECL|function|update
DECL|function|write_head_info
DECL|member|error_string
DECL|member|new_sha1
DECL|member|next
DECL|member|old_sha1
DECL|member|ref_name
DECL|struct|command
DECL|variable|capabilities
DECL|variable|capabilities_sent
DECL|variable|commands
DECL|variable|receive_pack_usage
DECL|variable|report_status
DECL|variable|unpacker
DECL|variable|update_hook
DECL|variable|update_post_hook
