DECL|function|execute_commands
DECL|function|is_all_zeroes
DECL|function|main
DECL|function|read_head_info
DECL|function|read_ref
DECL|function|show_ref
DECL|function|unpack
DECL|function|update
DECL|function|verify_old_ref
DECL|function|write_head_info
DECL|member|new_sha1
DECL|member|next
DECL|member|old_sha1
DECL|member|ref_name
DECL|struct|command
DECL|variable|commands
DECL|variable|receive_pack_usage
DECL|variable|unpacker
