DECL|function|execute_commands
DECL|function|main
DECL|function|path_match
DECL|function|read_head_info
DECL|function|read_ref
DECL|function|show_ref
DECL|function|unpack
DECL|function|write_head_info
DECL|member|data
DECL|member|next
DECL|struct|line
DECL|variable|commands
DECL|variable|receive_pack_usage
DECL|variable|unpacker
