DECL|macro|QUOTE_NONE
DECL|macro|QUOTE_PERL
DECL|macro|QUOTE_PYTHON
DECL|macro|QUOTE_SHELL
DECL|macro|QUOTE_TCL
DECL|macro|REF_FILTER_H
DECL|member|alloc
DECL|member|array
DECL|member|atom
DECL|member|filter
DECL|member|flag
DECL|member|items
DECL|member|name_patterns
DECL|member|next
DECL|member|nr
DECL|member|objectname
DECL|member|refname
DECL|member|reverse
DECL|member|s
DECL|member|symref
DECL|member|ul
DECL|member|value
DECL|struct|atom_value
DECL|struct|ref_array
DECL|struct|ref_array_item
DECL|struct|ref_filter
DECL|struct|ref_filter_cbdata
DECL|struct|ref_sorting
