DECL|enumerator|REF_FILTER_MERGED_INCLUDE
DECL|enumerator|REF_FILTER_MERGED_NONE
DECL|enumerator|REF_FILTER_MERGED_OMIT
DECL|macro|FILTER_REFS_ALL
DECL|macro|FILTER_REFS_BRANCHES
DECL|macro|FILTER_REFS_DETACHED_HEAD
DECL|macro|FILTER_REFS_INCLUDE_BROKEN
DECL|macro|FILTER_REFS_KIND_MASK
DECL|macro|FILTER_REFS_OTHERS
DECL|macro|FILTER_REFS_REMOTES
DECL|macro|FILTER_REFS_TAGS
DECL|macro|OPT_MERGED
DECL|macro|OPT_NO_MERGED
DECL|macro|QUOTE_NONE
DECL|macro|QUOTE_PERL
DECL|macro|QUOTE_PYTHON
DECL|macro|QUOTE_SHELL
DECL|macro|QUOTE_TCL
DECL|macro|REF_FILTER_H
DECL|macro|_OPT_MERGED_NO_MERGED
DECL|member|abbrev
DECL|member|alloc
DECL|member|array
DECL|member|atom
DECL|member|commit
DECL|member|detached
DECL|member|filter
DECL|member|flag
DECL|member|items
DECL|member|kind
DECL|member|kind
DECL|member|lines
DECL|member|match_as_path
DECL|member|merge
DECL|member|merge_commit
DECL|member|name_patterns
DECL|member|next
DECL|member|nr
DECL|member|objectname
DECL|member|points_at
DECL|member|refname
DECL|member|reverse
DECL|member|revs
DECL|member|symref
DECL|member|value
DECL|member|verbose
DECL|member|version
DECL|member|with_commit
DECL|member|with_commit_tag_algo
DECL|struct|ref_array
DECL|struct|ref_array_item
DECL|struct|ref_filter
DECL|struct|ref_filter_cbdata
DECL|struct|ref_sorting
