DECL|enumerator|FIELD_STR
DECL|enumerator|FIELD_TIME
DECL|enumerator|FIELD_ULONG
DECL|function|cmp_ref_sorting
DECL|function|compare_refs
DECL|function|copy_advance
DECL|function|copy_email
DECL|function|copy_line
DECL|function|copy_name
DECL|function|copy_subject
DECL|function|emit
DECL|function|fill_missing_values
DECL|function|find_next
DECL|function|find_subpos
DECL|function|find_wholine
DECL|function|free_array_item
DECL|function|get_obj
DECL|function|get_ref_atom_value
DECL|function|grab_commit_values
DECL|function|grab_common_values
DECL|function|grab_date
DECL|function|grab_objectname
DECL|function|grab_person
DECL|function|grab_sub_body_contents
DECL|function|grab_tag_values
DECL|function|grab_values
DECL|function|hex1
DECL|function|hex2
DECL|function|match_name_as_path
DECL|function|new_ref_array_item
DECL|function|parse_opt_ref_sorting
DECL|function|parse_ref_filter_atom
DECL|function|populate_value
DECL|function|print_value
DECL|function|ref_array_clear
DECL|function|ref_array_sort
DECL|function|ref_default_sorting
DECL|function|ref_filter_handler
DECL|function|show_ref_array_item
DECL|function|verify_ref_format
DECL|member|cmp_type
DECL|member|name
DECL|typedef|cmp_type
DECL|variable|need_color_reset_at_eol
DECL|variable|need_symref
DECL|variable|need_tagged
DECL|variable|ref_sorting
DECL|variable|used_atom
DECL|variable|used_atom_cnt
DECL|variable|used_atom_type
DECL|variable|valid_atom
