DECL|enumerator|CONTAINS_NO
DECL|enumerator|CONTAINS_UNKNOWN
DECL|enumerator|CONTAINS_YES
DECL|enumerator|FIELD_STR
DECL|enumerator|FIELD_TIME
DECL|enumerator|FIELD_ULONG
DECL|enum|contains_result
DECL|function|cmp_ref_sorting
DECL|function|commit_contains
DECL|function|compare_refs
DECL|function|contains_tag_algo
DECL|function|contains_test
DECL|function|copy_advance
DECL|function|copy_email
DECL|function|copy_line
DECL|function|copy_name
DECL|function|copy_subject
DECL|function|do_merge_filter
DECL|function|emit
DECL|function|fill_missing_values
DECL|function|filter_refs
DECL|function|find_next
DECL|function|find_subpos
DECL|function|find_wholine
DECL|function|free_array_item
DECL|function|get_obj
DECL|function|get_ref_atom_value
DECL|function|grab_commit_values
DECL|function|grab_common_values
DECL|function|grab_date
DECL|function|grab_objectname
DECL|function|grab_person
DECL|function|grab_sub_body_contents
DECL|function|grab_tag_values
DECL|function|grab_values
DECL|function|hex1
DECL|function|hex2
DECL|function|in_commit_list
DECL|function|match_name_as_path
DECL|function|match_points_at
DECL|function|new_ref_array_item
DECL|function|parse_opt_merge_filter
DECL|function|parse_opt_ref_sorting
DECL|function|parse_ref_filter_atom
DECL|function|populate_value
DECL|function|print_value
DECL|function|push_to_contains_stack
DECL|function|ref_array_clear
DECL|function|ref_array_sort
DECL|function|ref_default_sorting
DECL|function|ref_filter_handler
DECL|function|show_ref_array_item
DECL|function|verify_ref_format
DECL|member|alloc
DECL|member|cmp_type
DECL|member|commit
DECL|member|contains_stack
DECL|member|name
DECL|member|nr
DECL|member|parents
DECL|member|s
DECL|member|ul
DECL|struct|atom_value
DECL|struct|contains_stack
DECL|struct|contains_stack_entry
DECL|typedef|cmp_type
DECL|variable|need_color_reset_at_eol
DECL|variable|need_symref
DECL|variable|need_tagged
DECL|variable|ref_sorting
DECL|variable|used_atom
DECL|variable|used_atom_cnt
DECL|variable|used_atom_type
DECL|variable|valid_atom
