DECL|function|add_commit_info
DECL|function|add_reflog_for_walk
DECL|function|fake_reflog_parent
DECL|function|get_commit_info
DECL|function|get_reflog_ident
DECL|function|get_reflog_message
DECL|function|get_reflog_recno_by_time
DECL|function|get_reflog_selector
DECL|function|init_reflog_walk
DECL|function|read_complete_reflog
DECL|function|read_one_reflog
DECL|function|show_reflog_message
DECL|member|alloc
DECL|member|alloc
DECL|member|commit
DECL|member|complete_reflogs
DECL|member|email
DECL|member|flag
DECL|member|items
DECL|member|items
DECL|member|last_commit_reflog
DECL|member|message
DECL|member|nr
DECL|member|nr
DECL|member|nsha1
DECL|member|osha1
DECL|member|recno
DECL|member|ref
DECL|member|reflogs
DECL|member|reflogs
DECL|member|short_ref
DECL|member|timestamp
DECL|member|tz
DECL|member|util
DECL|struct|commit_info
DECL|struct|commit_info_lifo
DECL|struct|commit_reflog
DECL|struct|complete_reflogs
DECL|struct|reflog_info
DECL|struct|reflog_walk_info
