DECL|function|add_extra_ref
DECL|function|add_ref
DECL|function|bad_ref_char
DECL|function|check_ref_format
DECL|function|clear_cached_refs
DECL|function|clear_extra_refs
DECL|function|close_ref
DECL|function|commit_ref
DECL|function|copy_msg
DECL|function|create_symref
DECL|function|delete_ref
DECL|function|do_for_each_ref
DECL|function|do_for_each_reflog
DECL|function|do_head_ref
DECL|function|do_one_ref
DECL|function|filter_refs
DECL|function|find_ref_by_name
DECL|function|for_each_branch_ref
DECL|function|for_each_branch_ref_submodule
DECL|function|for_each_glob_ref
DECL|function|for_each_glob_ref_in
DECL|function|for_each_rawref
DECL|function|for_each_recent_reflog_ent
DECL|function|for_each_ref
DECL|function|for_each_ref_in
DECL|function|for_each_ref_in_submodule
DECL|function|for_each_ref_submodule
DECL|function|for_each_reflog
DECL|function|for_each_reflog_ent
DECL|function|for_each_remote_ref
DECL|function|for_each_remote_ref_submodule
DECL|function|for_each_replace_ref
DECL|function|for_each_tag_ref
DECL|function|for_each_tag_ref_submodule
DECL|function|free_ref_list
DECL|function|gen_scanf_fmt
DECL|function|get_cached_refs
DECL|function|get_loose_refs
DECL|function|get_packed_refs
DECL|function|get_ref_dir
DECL|function|head_ref
DECL|function|head_ref_submodule
DECL|function|invalidate_cached_refs
DECL|function|is_branch
DECL|function|is_refname_available
DECL|function|lock_any_ref_for_update
DECL|function|lock_ref_sha1
DECL|function|lock_ref_sha1_basic
DECL|function|log_ref_setup
DECL|function|log_ref_write
DECL|function|parse_ref_line
DECL|function|peel_ref
DECL|function|prettify_refname
DECL|function|read_packed_refs
DECL|function|read_ref
DECL|function|read_ref_at
DECL|function|ref_exists
DECL|function|ref_msg
DECL|function|refname_match
DECL|function|remove_empty_directories
DECL|function|rename_ref
DECL|function|repack_without_ref
DECL|function|resolve_gitlink_packed_ref
DECL|function|resolve_gitlink_ref
DECL|function|resolve_gitlink_ref_recursive
DECL|function|resolve_ref
DECL|function|shorten_unambiguous_ref
DECL|function|sort_ref_list
DECL|function|unlock_ref
DECL|function|update_ref
DECL|function|verify_lock
DECL|function|warn_dangling_symref
DECL|function|warn_if_dangling_symref
DECL|function|write_ref_sha1
DECL|macro|DO_FOR_EACH_INCLUDE_BROKEN
DECL|macro|MAXDEPTH
DECL|macro|MAXREFLEN
DECL|macro|REF_BROKEN
DECL|macro|REF_KNOWS_PEELED
DECL|macro|TMP_RENAMED_LOG
DECL|member|cb_data
DECL|member|did_loose
DECL|member|did_packed
DECL|member|flag
DECL|member|fn
DECL|member|fp
DECL|member|loose
DECL|member|msg_fmt
DECL|member|name
DECL|member|next
DECL|member|packed
DECL|member|pattern
DECL|member|peeled
DECL|member|refname
DECL|member|sha1
DECL|struct|cached_refs
DECL|struct|ref_filter
DECL|struct|ref_list
DECL|struct|warn_if_dangling_data
DECL|variable|cached_refs
DECL|variable|current_ref
DECL|variable|extra_refs
DECL|variable|packlock
DECL|variable|ref_fetch_rules
DECL|variable|ref_rev_parse_rules
DECL|variable|submodule_refs
