DECL|function|bad_ref_char
DECL|function|check_ref_format
DECL|function|create_symref
DECL|function|do_for_each_ref
DECL|function|for_each_branch_ref
DECL|function|for_each_ref
DECL|function|for_each_remote_ref
DECL|function|for_each_tag_ref
DECL|function|get_ref_sha1
DECL|function|head_ref
DECL|function|lock_ref_file
DECL|function|lock_ref_sha1
DECL|function|read_ref
DECL|function|ref_file_name
DECL|function|ref_lock_file_name
DECL|function|resolve_ref
DECL|function|write_ref_file
DECL|function|write_ref_sha1
DECL|function|write_ref_sha1_unlocked
DECL|macro|MAXDEPTH
