DECL|macro|REFS_H
DECL|macro|REF_ISPACKED
DECL|macro|REF_ISSYMREF
DECL|member|force_write
DECL|member|lk
DECL|member|lock_fd
DECL|member|old_sha1
DECL|member|orig_ref_name
DECL|member|ref_name
DECL|struct|ref_lock
DECL|typedef|each_ref_fn
DECL|typedef|each_reflog_ent_fn
