DECL|enumerator|UPDATE_REFS_DIE_ON_ERR
DECL|enumerator|UPDATE_REFS_MSG_ON_ERR
DECL|enumerator|UPDATE_REFS_QUIET_ON_ERR
DECL|enum|action_on_err
DECL|function|has_glob_specials
DECL|macro|PACK_REFS_ALL
DECL|macro|PACK_REFS_PRUNE
DECL|macro|REFNAME_ALLOW_ONELEVEL
DECL|macro|REFNAME_DOT_COMPONENT
DECL|macro|REFNAME_REFSPEC_PATTERN
DECL|macro|REFS_H
DECL|macro|REF_ISBROKEN
DECL|macro|REF_ISPACKED
DECL|macro|REF_ISSYMREF
DECL|macro|REF_NODEREF
DECL|member|flags
DECL|member|force_write
DECL|member|have_old
DECL|member|lk
DECL|member|lock_fd
DECL|member|new_sha1
DECL|member|old_sha1
DECL|member|old_sha1
DECL|member|orig_ref_name
DECL|member|ref_name
DECL|member|ref_name
DECL|struct|ref_lock
DECL|struct|ref_update
DECL|typedef|each_ref_fn
DECL|typedef|each_reflog_ent_fn
