DECL|function|discover_refs
DECL|function|fetch_dumb
DECL|function|free_discovery
DECL|function|get_refs
DECL|function|init_walker
DECL|function|main
DECL|function|output_refs
DECL|function|parse_fetch
DECL|function|parse_git_refs
DECL|function|parse_info_refs
DECL|function|parse_push
DECL|function|push_dav
DECL|function|set_option
DECL|function|write_discovery
DECL|member|buf
DECL|member|buf_alloc
DECL|member|depth
DECL|member|dry_run
DECL|member|followtags
DECL|member|len
DECL|member|progress
DECL|member|proto_git
DECL|member|service
DECL|member|verbosity
DECL|struct|discovery
DECL|struct|options
DECL|variable|last_discovery
DECL|variable|options
DECL|variable|remote
DECL|variable|url
DECL|variable|walker
