DECL|macro|REMOTE_H
DECL|member|dst
DECL|member|fetch
DECL|member|fetch_refspec
DECL|member|fetch_refspec_nr
DECL|member|fetch_tags
DECL|member|force
DECL|member|merge
DECL|member|merge_name
DECL|member|merge_nr
DECL|member|name
DECL|member|name
DECL|member|pattern
DECL|member|push
DECL|member|push_refspec
DECL|member|push_refspec_nr
DECL|member|receivepack
DECL|member|refname
DECL|member|remote
DECL|member|remote_name
DECL|member|src
DECL|member|uploadpack
DECL|member|uri
DECL|member|uri_nr
DECL|struct|branch
DECL|struct|refspec
DECL|struct|remote
DECL|typedef|each_remote_fn
