DECL|enumerator|MATCH_REFS_ALL
DECL|enumerator|MATCH_REFS_MIRROR
DECL|enumerator|MATCH_REFS_NONE
DECL|enum|match_refs_flags
DECL|macro|REMOTE_H
DECL|member|dst
DECL|member|fetch
DECL|member|fetch_refspec
DECL|member|fetch_refspec_alloc
DECL|member|fetch_refspec_nr
DECL|member|fetch_tags
DECL|member|force
DECL|member|http_proxy
DECL|member|matching
DECL|member|merge
DECL|member|merge_alloc
DECL|member|merge_name
DECL|member|merge_nr
DECL|member|mirror
DECL|member|name
DECL|member|name
DECL|member|pattern
DECL|member|push
DECL|member|push_refspec
DECL|member|push_refspec_alloc
DECL|member|push_refspec_nr
DECL|member|receivepack
DECL|member|refname
DECL|member|remote
DECL|member|remote_name
DECL|member|skip_default_update
DECL|member|src
DECL|member|uploadpack
DECL|member|url
DECL|member|url_alloc
DECL|member|url_nr
DECL|struct|branch
DECL|struct|refspec
DECL|struct|remote
DECL|typedef|each_remote_fn
