DECL|function|add_fetch_refspec
DECL|function|add_instead_of
DECL|function|add_merge
DECL|function|add_push_refspec
DECL|function|add_pushurl
DECL|function|add_pushurl_alias
DECL|function|add_url
DECL|function|add_url_alias
DECL|function|alias_all_urls
DECL|function|alias_url
DECL|function|alloc_ref
DECL|function|alloc_ref_with_prefix
DECL|function|apply_refspecs
DECL|function|branch_get
DECL|function|branch_has_merge_config
DECL|function|branch_merge_matches
DECL|function|check_pattern_match
DECL|function|copy_ref
DECL|function|copy_ref_list
DECL|function|count_refspec_match
DECL|function|find_ref_by_name_abbrev
DECL|function|for_each_remote
DECL|function|format_tracking_info
DECL|function|free_ref
DECL|function|free_refs
DECL|function|free_refspec
DECL|function|free_refspecs
DECL|function|get_expanded_map
DECL|function|get_fetch_map
DECL|function|get_local_heads
DECL|function|get_local_ref
DECL|function|get_remote_ref
DECL|function|get_stale_heads
DECL|function|get_stale_heads_cb
DECL|function|guess_ref
DECL|function|guess_remote_head
DECL|function|handle_config
DECL|function|make_branch
DECL|function|make_linked_ref
DECL|function|make_remote
DECL|function|make_rewrite
DECL|function|match_explicit
DECL|function|match_explicit_refs
DECL|function|match_name_with_pattern
DECL|function|match_refs
DECL|function|one_local_ref
DECL|function|parse_fetch_refspec
DECL|function|parse_push_refspec
DECL|function|parse_refspec_internal
DECL|function|query_refspecs
DECL|function|read_branches_file
DECL|function|read_config
DECL|function|read_remotes_file
DECL|function|ref_newer
DECL|function|ref_remove_duplicates
DECL|function|remote_find_tracking
DECL|function|remote_get
DECL|function|remote_has_url
DECL|function|remote_is_configured
DECL|function|resolve_remote_symref
DECL|function|set_ref_status_for_push
DECL|function|stat_tracking_info
DECL|function|tail_link_ref
DECL|function|tail_ref
DECL|function|try_explicit_object_name
DECL|function|unmark_and_free
DECL|function|valid_fetch_refspec
DECL|function|valid_remote
DECL|function|valid_remote_nick
DECL|function|verify_refname
DECL|macro|BUF_SIZE
DECL|member|base
DECL|member|baselen
DECL|member|instead_of
DECL|member|instead_of_alloc
DECL|member|instead_of_nr
DECL|member|len
DECL|member|ref_count
DECL|member|ref_names
DECL|member|refs
DECL|member|rewrite
DECL|member|rewrite_alloc
DECL|member|rewrite_nr
DECL|member|s
DECL|member|stale_refs_tail
DECL|struct|counted_string
DECL|struct|rewrite
DECL|struct|rewrites
DECL|struct|stale_heads_info
DECL|variable|branches
DECL|variable|branches_alloc
DECL|variable|branches_nr
DECL|variable|buffer
DECL|variable|current_branch
DECL|variable|default_remote_name
DECL|variable|explicit_default_remote_name
DECL|variable|remotes
DECL|variable|remotes_alloc
DECL|variable|remotes_nr
DECL|variable|rewrites
DECL|variable|rewrites_push
DECL|variable|s_tag_refspec
DECL|variable|tag_refspec
