DECL|function|add_fetch_refspec
DECL|function|add_merge
DECL|function|add_push_refspec
DECL|function|add_uri
DECL|function|alloc_ref
DECL|function|branch_get
DECL|function|branch_has_merge_config
DECL|function|branch_merges
DECL|function|check_pattern_match
DECL|function|count_refspec_match
DECL|function|find_ref_by_name
DECL|function|for_each_remote
DECL|function|free_refs
DECL|function|handle_config
DECL|function|make_branch
DECL|function|make_linked_ref
DECL|function|make_remote
DECL|function|match_explicit
DECL|function|match_explicit_refs
DECL|function|match_refs
DECL|function|parse_ref_spec
DECL|function|read_branches_file
DECL|function|read_config
DECL|function|read_remotes_file
DECL|function|ref_matches_abbrev
DECL|function|remote_find_tracking
DECL|function|remote_get
DECL|function|remote_has_uri
DECL|function|tail_link_ref
DECL|function|try_explicit_object_name
DECL|macro|BUF_SIZE
DECL|variable|allocated_branches
DECL|variable|allocated_remotes
DECL|variable|branches
DECL|variable|buffer
DECL|variable|current_branch
DECL|variable|default_remote_name
DECL|variable|remotes
