DECL|function|check_or_regenerate_marks
DECL|function|cmd_capabilities
DECL|function|cmd_import
DECL|function|cmd_list
DECL|function|do_command
DECL|function|main
DECL|function|note2mark_cb
DECL|function|parse_rev_note
DECL|function|read_ref_note
DECL|function|regenerate_marks
DECL|function|terminate_batch
DECL|member|batchable
DECL|member|fn
DECL|member|name
DECL|member|rev_nr
DECL|struct|input_command_entry
DECL|struct|rev_note
DECL|typedef|input_command_handler
DECL|variable|dump_from_file
DECL|variable|input_command_list
DECL|variable|marksfilename
DECL|variable|notes_ref
DECL|variable|private_ref
DECL|variable|remote_ref
DECL|variable|url
