DECL|function|get_value
DECL|function|main
DECL|function|show_config
DECL|variable|do_all
DECL|variable|do_not_match
DECL|variable|git_config_set_usage
DECL|variable|key
DECL|variable|regexp
DECL|variable|seen
DECL|variable|value
