DECL|function|do_plain_rerere
DECL|function|find_conflict
DECL|function|git_rerere_config
DECL|function|handle_file
DECL|function|has_resolution
DECL|function|is_rerere_enabled
DECL|function|merge
DECL|function|read_rr
DECL|function|rerere
DECL|function|rr_path
DECL|function|setup_rerere
DECL|function|update_paths
DECL|function|write_rr
DECL|variable|index_lock
DECL|variable|merge_rr_path
DECL|variable|rerere_autoupdate
DECL|variable|rerere_enabled
DECL|variable|write_lock
