DECL|function|check_one_conflict
DECL|function|do_plain_rerere
DECL|function|ferr_puts
DECL|function|ferr_write
DECL|function|find_conflict
DECL|function|git_rerere_config
DECL|function|handle_cache
DECL|function|handle_file
DECL|function|handle_path
DECL|function|has_rerere_resolution
DECL|function|is_cmarker
DECL|function|is_rerere_enabled
DECL|function|merge
DECL|function|read_rr
DECL|function|rerere
DECL|function|rerere_file_getline
DECL|function|rerere_forget
DECL|function|rerere_forget_one_path
DECL|function|rerere_io_putconflict
DECL|function|rerere_io_putmem
DECL|function|rerere_io_putstr
DECL|function|rerere_mem_getline
DECL|function|rerere_path
DECL|function|rerere_remaining
DECL|function|setup_rerere
DECL|function|update_paths
DECL|function|write_rr
DECL|macro|PUNTED
DECL|macro|RESOLVED
DECL|macro|THREE_STAGED
DECL|member|getline
DECL|member|input
DECL|member|input
DECL|member|io
DECL|member|io
DECL|member|output
DECL|member|wrerror
DECL|struct|rerere_io
DECL|struct|rerere_io_file
DECL|struct|rerere_io_mem
DECL|variable|RERERE_RESOLVED
DECL|variable|index_lock
DECL|variable|merge_rr_path
DECL|variable|rerere_autoupdate
DECL|variable|rerere_enabled
DECL|variable|write_lock
