DECL|function|interesting
DECL|function|main
DECL|function|process_commit
DECL|function|read_cache_file
DECL|macro|MAX_COMMITS
DECL|macro|_BSD_SOURCE
DECL|macro|_XOPEN_SOURCE
DECL|variable|basemask
DECL|variable|show_edges
