DECL|function|add_parent
DECL|function|alloc_list_elem
DECL|function|create_rev_cache
DECL|function|find_rev_cache
DECL|function|read_rev_cache
DECL|function|record_rev_cache
DECL|function|write_one_rev_cache
DECL|function|write_rev_cache
DECL|macro|BATCH_SIZE
DECL|variable|alloc_revs
DECL|variable|last_sha1
DECL|variable|nr_revs
DECL|variable|rev_cache
DECL|variable|rle_free
