DECL|macro|REV_CACHE_H
DECL|member|children
DECL|member|head_list
DECL|member|next
DECL|member|num_children
DECL|member|num_parents
DECL|member|parents
DECL|member|parents_tail
DECL|member|parsed
DECL|member|ri
DECL|member|sha1
DECL|member|work
DECL|member|work_ptr
DECL|member|written
DECL|struct|rev_cache
DECL|struct|rev_list_elem
