DECL|function|is_rev_argument
DECL|function|main
DECL|function|show
DECL|function|show_arg
DECL|function|show_default
DECL|function|show_norev
DECL|function|show_reference
DECL|function|show_rev
DECL|function|show_rev_arg
DECL|macro|NORMAL
DECL|macro|REVERSED
DECL|variable|def
DECL|variable|do_rev_argument
DECL|variable|flags_only
DECL|variable|no_flags
DECL|variable|no_revs
DECL|variable|output_revs
DECL|variable|output_sq
DECL|variable|revs_only
DECL|variable|show_type
DECL|variable|single_rev
DECL|variable|symbolic
