DECL|function|add_parents_to_list
DECL|function|clear_distance
DECL|function|compare_tree
DECL|function|count_distance
DECL|function|everybody_uninteresting
DECL|function|file_add_remove
DECL|function|file_change
DECL|function|filter_commit
DECL|function|find_bisection
DECL|function|limit_list
DECL|function|main
DECL|function|mark_edge_parents_uninteresting
DECL|function|mark_edges_uninteresting
DECL|function|process_blob
DECL|function|process_commit
DECL|function|process_tree
DECL|function|rewrite_one
DECL|function|rewrite_parents
DECL|function|same_tree_as_empty
DECL|function|show_commit
DECL|function|show_commit_list
DECL|function|try_to_simplify_commit
DECL|macro|COUNTED
DECL|macro|SHOWN
DECL|macro|TMP_MARK
DECL|macro|TREECHANGE
DECL|macro|TREE_DIFFERENT
DECL|macro|TREE_NEW
DECL|macro|TREE_SAME
DECL|variable|abbrev
DECL|variable|bisect_list
DECL|variable|commit_format
DECL|variable|commit_prefix
DECL|variable|diff_opt
DECL|variable|hdr_termination
DECL|variable|merge_order
DECL|variable|no_merges
DECL|variable|rev_list_usage
DECL|variable|revs
DECL|variable|show_breaks
DECL|variable|show_parents
DECL|variable|stop_traversal
DECL|variable|tree_difference
DECL|variable|verbose_header
