DECL|function|get_extended_sha1
DECL|function|get_parent
DECL|function|is_rev_argument
DECL|function|main
DECL|function|show_arg
DECL|function|show_default
DECL|function|show_norev
DECL|function|show_rev
DECL|function|show_rev_arg
DECL|macro|NORMAL
DECL|macro|REVERSED
DECL|variable|def
DECL|variable|do_rev_argument
DECL|variable|no_revs
DECL|variable|output_revs
DECL|variable|revs_only
DECL|variable|show_type
DECL|variable|single_rev
