DECL|function|add_relationship
DECL|function|find_rev
DECL|function|lookup_rev
DECL|function|mark_reachable
DECL|macro|REACHABLE
DECL|macro|REVISION_H
DECL|macro|SEEN
DECL|macro|USED
DECL|macro|marked
DECL|member|date
DECL|member|flags
DECL|member|next
DECL|member|parent
DECL|member|parent
DECL|member|sha1
DECL|struct|parent
DECL|struct|revision
DECL|variable|nr_revs
DECL|variable|rev_allocs
DECL|variable|revs
