DECL|function|add_object
DECL|function|add_one_commit
DECL|function|add_parents_to_list
DECL|function|add_pending_object
DECL|function|compare_tree
DECL|function|everybody_uninteresting
DECL|function|file_add_remove
DECL|function|file_change
DECL|function|get_commit_reference
DECL|function|get_revision
DECL|function|handle_all
DECL|function|handle_one_ref
DECL|function|limit_list
DECL|function|mark_blob_uninteresting
DECL|function|mark_parents_uninteresting
DECL|function|mark_tree_uninteresting
DECL|function|path_name
DECL|function|prepare_revision_walk
DECL|function|same_tree_as_empty
DECL|function|setup_revisions
DECL|function|try_to_simplify_commit
DECL|macro|TREE_DIFFERENT
DECL|macro|TREE_NEW
DECL|macro|TREE_SAME
DECL|variable|all_flags
DECL|variable|all_revs
DECL|variable|diff_opt
DECL|variable|tree_difference
