DECL|function|close_pair
DECL|function|die_async
DECL|function|die_child
DECL|function|dup_devnull
DECL|function|error_child
DECL|function|execv_shell_cmd
DECL|function|finish_async
DECL|function|finish_command
DECL|function|notify_parent
DECL|function|prepare_run_command_v_opt
DECL|function|prepare_shell_cmd
DECL|function|run_command
DECL|function|run_command_v_opt
DECL|function|run_command_v_opt_cd_env
DECL|function|run_hook
DECL|function|run_thread
DECL|function|set_cloexec
DECL|function|start_async
DECL|function|start_command
DECL|function|wait_or_whine
DECL|variable|async_key
DECL|variable|child_err
DECL|variable|child_notifier
DECL|variable|main_thread
DECL|variable|main_thread_set
