DECL|macro|RUN_COMMAND_H
DECL|macro|RUN_COMMAND_NO_STDIN
DECL|macro|RUN_COMMAND_STDOUT_TO_STDERR
DECL|macro|RUN_GIT_CMD
DECL|macro|RUN_SILENT_EXEC_FAILURE
DECL|macro|RUN_USING_SHELL
DECL|member|argv
DECL|member|data
DECL|member|dir
DECL|member|env
DECL|member|err
DECL|member|git_cmd
DECL|member|in
DECL|member|in
DECL|member|no_stderr
DECL|member|no_stdin
DECL|member|no_stdout
DECL|member|out
DECL|member|out
DECL|member|pid
DECL|member|pid
DECL|member|preexec_cb
DECL|member|proc
DECL|member|proc_in
DECL|member|proc_out
DECL|member|silent_exec_failure
DECL|member|stdout_to_stderr
DECL|member|tid
DECL|member|use_shell
DECL|struct|async
DECL|struct|child_process
