DECL|function|close_pair
DECL|function|dup_devnull
DECL|function|finish_async
DECL|function|finish_command
DECL|function|prepare_run_command_v_opt
DECL|function|run_command
DECL|function|run_command_v_opt
DECL|function|run_command_v_opt_cd_env
DECL|function|run_hook
DECL|function|run_thread
DECL|function|start_async
DECL|function|start_command
DECL|function|wait_or_whine
