DECL|enumerator|ERR_RUN_COMMAND_EXEC
DECL|enumerator|ERR_RUN_COMMAND_FORK
DECL|enumerator|ERR_RUN_COMMAND_PIPE
DECL|enumerator|ERR_RUN_COMMAND_WAITPID
DECL|enumerator|ERR_RUN_COMMAND_WAITPID_NOEXIT
DECL|enumerator|ERR_RUN_COMMAND_WAITPID_SIGNAL
DECL|enumerator|ERR_RUN_COMMAND_WAITPID_WRONG_PID
DECL|macro|RUN_COMMAND_H
DECL|macro|RUN_COMMAND_NO_STDIN
DECL|macro|RUN_COMMAND_STDOUT_TO_STDERR
DECL|macro|RUN_GIT_CMD
DECL|member|argv
DECL|member|data
DECL|member|dir
DECL|member|env
DECL|member|err
DECL|member|fd_for_proc
DECL|member|git_cmd
DECL|member|in
DECL|member|no_stderr
DECL|member|no_stdin
DECL|member|no_stdout
DECL|member|out
DECL|member|out
DECL|member|pid
DECL|member|pid
DECL|member|proc
DECL|member|stdout_to_stderr
DECL|member|tid
DECL|struct|async
DECL|struct|child_process
