DECL|function|exec_pack_objects
DECL|function|exec_rev_list
DECL|function|is_zero_sha1
DECL|function|main
DECL|function|pack_objects
DECL|function|read_ref
DECL|function|ref_newer
DECL|function|rev_list
DECL|function|send_pack
DECL|function|try_to_match
DECL|variable|exec
DECL|variable|force_update
DECL|variable|local_last_ref
DECL|variable|local_ref_list
DECL|variable|local_ref_match
DECL|variable|local_ref_nr_match
DECL|variable|send_all
DECL|variable|send_pack_usage
