DECL|function|exec_pack_objects
DECL|function|exec_rev_list
DECL|function|main
DECL|function|pack_objects
DECL|function|read_ref
DECL|function|rev_list
DECL|function|send_pack
DECL|member|name
DECL|member|new_sha1
DECL|member|next
DECL|member|old_sha1
DECL|struct|ref
DECL|variable|exec
DECL|variable|send_pack_usage
