DECL|enumerator|REPLAY_CONTINUE
DECL|enumerator|REPLAY_NONE
DECL|enumerator|REPLAY_PICK
DECL|enumerator|REPLAY_REMOVE_STATE
DECL|enumerator|REPLAY_REVERT
DECL|enumerator|REPLAY_ROLLBACK
DECL|enum|replay_action
DECL|enum|replay_subcommand
DECL|macro|SEQUENCER_H
DECL|macro|SEQ_DIR
DECL|macro|SEQ_HEAD_FILE
DECL|macro|SEQ_OPTS_FILE
DECL|macro|SEQ_TODO_FILE
DECL|member|action
DECL|member|allow_empty
DECL|member|allow_ff
DECL|member|allow_rerere_auto
DECL|member|edit
DECL|member|mainline
DECL|member|no_commit
DECL|member|record_origin
DECL|member|revs
DECL|member|signoff
DECL|member|strategy
DECL|member|subcommand
DECL|member|xopts
DECL|member|xopts_alloc
DECL|member|xopts_nr
DECL|struct|replay_opts
