DECL|function|action_name
DECL|function|allow_empty
DECL|function|commit_list_append
DECL|function|continue_single_pick
DECL|function|create_seq_dir
DECL|function|do_pick_commit
DECL|function|do_recursive_merge
DECL|function|empty_tree
DECL|function|error_dirty_index
DECL|function|fast_forward_to
DECL|function|format_todo
DECL|function|free_message
DECL|function|get_encoding
DECL|function|get_message
DECL|function|is_index_unchanged
DECL|function|is_original_commit_empty
DECL|function|parse_insn_buffer
DECL|function|parse_insn_line
DECL|function|pick_commits
DECL|function|populate_opts_cb
DECL|function|prepare_revs
DECL|function|print_advice
DECL|function|read_and_refresh_cache
DECL|function|read_populate_opts
DECL|function|read_populate_todo
DECL|function|remove_sequencer_state
DECL|function|reset_for_rollback
DECL|function|rollback_single_pick
DECL|function|run_git_commit
DECL|function|save_head
DECL|function|save_opts
DECL|function|save_todo
DECL|function|sequencer_continue
DECL|function|sequencer_pick_revisions
DECL|function|sequencer_rollback
DECL|function|single_pick
DECL|function|walk_revs_populate_todo
DECL|function|write_cherry_pick_head
DECL|function|write_message
DECL|macro|GIT_REFLOG_ACTION
DECL|member|label
DECL|member|message
DECL|member|parent_label
DECL|member|reencoded_message
DECL|member|subject
DECL|struct|commit_message
