DECL|function|add_head_def
DECL|function|add_info_ref
DECL|function|compare_info
DECL|function|find_pack_by_name
DECL|function|find_pack_by_old_num
DECL|function|find_pack_info
DECL|function|find_pack_info_one
DECL|function|get_latest_commit_date
DECL|function|init_pack_info
DECL|function|parse_depend_def
DECL|function|parse_head_def
DECL|function|parse_object_cheap
DECL|function|parse_pack_def
DECL|function|read_pack_info_file
DECL|function|record_rev_cache_ref
DECL|function|show
DECL|function|stat_ref
DECL|function|update_info_packs
DECL|function|update_info_refs
DECL|function|update_info_revs
DECL|function|update_server_info
DECL|function|write_pack_info_file
DECL|macro|EMITTED
DECL|macro|INTERNAL
DECL|macro|REFERENCED
DECL|member|dep
DECL|member|head
DECL|member|latest
DECL|member|new_num
DECL|member|nr_alloc
DECL|member|nr_heads
DECL|member|old_num
DECL|member|p
DECL|struct|pack_info
DECL|variable|info
DECL|variable|info_ref_fp
DECL|variable|info_ref_is_stale
DECL|variable|info_ref_time
DECL|variable|num_pack
DECL|variable|objdir
DECL|variable|objdirlen
