DECL|function|add_info_ref
DECL|function|compare_info
DECL|function|find_pack_by_name
DECL|function|init_pack_info
DECL|function|parse_pack_def
DECL|function|read_pack_info_file
DECL|function|update_info_packs
DECL|function|update_info_refs
DECL|function|update_server_info
DECL|function|write_pack_info_file
DECL|member|head
DECL|member|new_num
DECL|member|nr_alloc
DECL|member|nr_heads
DECL|member|old_num
DECL|member|p
DECL|struct|pack_info
DECL|variable|info
DECL|variable|info_ref_fp
DECL|variable|num_pack
DECL|variable|objdir
DECL|variable|objdirlen
