DECL|function|check_repository_format
DECL|function|check_repository_format_version
DECL|function|get_pathspec
DECL|function|is_toplevel_directory
DECL|function|prefix_path
DECL|function|setup_git_directory
DECL|function|setup_git_directory_1
