DECL|function|check_sha1_signature
DECL|function|get_sha1
DECL|function|get_sha1_file
DECL|function|get_sha1_hex
DECL|function|has_sha1_file
DECL|function|hexval
DECL|function|index_fd
DECL|function|map_sha1_file
DECL|function|read_object_with_reference
DECL|function|read_sha1_file
DECL|function|sha1_file_name
DECL|function|sha1_to_hex
DECL|function|unpack_sha1_file
DECL|function|write_sha1_file
DECL|function|write_sha1_from_fd
DECL|macro|O_NOATIME
DECL|macro|O_NOATIME
DECL|variable|sha1_file_directory
DECL|variable|sha1_file_open_flag
