DECL|function|find_short_object_filename
DECL|function|find_short_packed_object
DECL|function|get_nth_ancestor
DECL|function|get_parent
DECL|function|get_sha1
DECL|function|get_sha1_1
DECL|function|get_sha1_basic
DECL|function|get_sha1_file
DECL|function|get_short_sha1
DECL|function|match_sha
