DECL|function|ambiguous_path
DECL|function|dwim_log
DECL|function|dwim_ref
DECL|function|find_short_object_filename
DECL|function|find_short_packed_object
DECL|function|find_unique_abbrev
DECL|function|find_unique_short_object
DECL|function|get_describe_name
DECL|function|get_nth_ancestor
DECL|function|get_parent
DECL|function|get_sha1
DECL|function|get_sha1_1
DECL|function|get_sha1_basic
DECL|function|get_sha1_oneline
DECL|function|get_sha1_with_mode
DECL|function|get_short_sha1
DECL|function|handle_one_ref
DECL|function|match_sha
DECL|function|peel_onion
DECL|function|peel_to_type
DECL|macro|ONELINE_SEEN
DECL|macro|SHORT_NAME_AMBIGUOUS
DECL|macro|SHORT_NAME_NOT_FOUND
