DECL|function|check_sha1_signature
DECL|function|fill_sha1_path
DECL|function|find_sha1_file
DECL|function|get_index_file
DECL|function|get_object_directory
DECL|function|get_refs_directory
DECL|function|get_sha1
DECL|function|get_sha1_file
DECL|function|get_sha1_hex
DECL|function|has_sha1_file
DECL|function|hexval
DECL|function|index_fd
DECL|function|map_sha1_file
DECL|function|parse_sha1_header
DECL|function|prepare_alt_odb
DECL|function|read_object_with_reference
DECL|function|read_sha1_file
DECL|function|setup_git_env
DECL|function|sha1_delta_base
DECL|function|sha1_file_name
DECL|function|sha1_file_size
DECL|function|sha1_to_hex
DECL|function|unpack_sha1_file
DECL|function|unpack_sha1_header
DECL|function|unpack_sha1_rest
DECL|function|write_sha1_file
DECL|function|write_sha1_from_fd
DECL|macro|O_NOATIME
DECL|macro|O_NOATIME
DECL|member|base
DECL|member|name
DECL|struct|alternate_object_database
DECL|variable|alt_odb
DECL|variable|git_dir
DECL|variable|git_index_file
DECL|variable|git_object_dir
DECL|variable|git_refs_dir
DECL|variable|sha1_file_open_flag
