DECL|function|add_ref
DECL|function|advertise_shallow_grafts
DECL|function|advertise_shallow_grafts_cb
DECL|function|assign_shallow_commits_to_refs
DECL|function|check_shallow_file_for_update
DECL|function|clear_shallow_info
DECL|function|get_shallow_commits
DECL|function|is_repository_shallow
DECL|function|mark_uninteresting
DECL|function|paint_alloc
DECL|function|paint_down
DECL|function|post_assign_shallow
DECL|function|prepare_shallow_info
DECL|function|register_shallow
DECL|function|remove_nonexistent_ours_in_pack
DECL|function|remove_nonexistent_theirs_shallow
DECL|function|set_alternate_shallow_file
DECL|function|setup_alternate_shallow
DECL|function|setup_temporary_shallow
DECL|function|update_refstatus
DECL|function|write_one_shallow
DECL|function|write_shallow_commits
DECL|macro|TRACE_KEY
DECL|member|alloc
DECL|member|commits
DECL|member|count
DECL|member|end
DECL|member|free
DECL|member|nr
DECL|member|nr_bits
DECL|member|out
DECL|member|ref_bitmap
DECL|member|slab
DECL|member|slab_count
DECL|member|use_pack_protocol
DECL|struct|commit_array
DECL|struct|paint_info
DECL|struct|write_shallow_data
DECL|variable|alternate_shallow_file
DECL|variable|is_shallow
DECL|variable|shallow_stat
