DECL|function|do_cvs_cmd
DECL|function|do_generic_cmd
DECL|function|main
DECL|function|release_pack_memory
DECL|function|trace_argv_printf
DECL|function|trace_printf
DECL|member|exec
DECL|member|name
DECL|struct|commands
DECL|variable|cmd_list
