DECL|function|append_head_ref
DECL|function|append_ref
DECL|function|append_tag_ref
DECL|function|compare_ref_name
DECL|function|interesting
DECL|function|join_revs
DECL|function|main
DECL|function|mark_seen
DECL|function|name_commit
DECL|function|name_parent
DECL|function|pop_one_commit
DECL|function|rev_is_head
DECL|function|show_merge_base
DECL|function|show_one_commit
DECL|function|snarf_refs
DECL|function|sort_ref_range
DECL|macro|MAX_REVS
DECL|macro|REV_SHIFT
DECL|macro|UNINTERESTING
DECL|member|generation
DECL|member|head_rev
DECL|struct|commit_name
DECL|variable|ref_name
DECL|variable|ref_name_cnt
DECL|variable|show_branch_usage
