DECL|function|main
DECL|function|matches_pathspec
DECL|function|show_file
DECL|function|show_modified
DECL|function|show_unmerge
DECL|variable|generate_patch
DECL|variable|line_termination
DECL|variable|show_diff_usage
DECL|variable|silent
DECL|variable|silent_on_nonexisting_files
