DECL|function|main
DECL|function|matches_pathspec
DECL|function|prepare_diff_cmd
DECL|function|show_diff_empty
DECL|function|show_differences
DECL|function|sq_expand
DECL|variable|diff_arg_forward
DECL|variable|diff_arg_reverse
DECL|variable|diff_cmd
DECL|variable|diff_opts
DECL|variable|show_diff_usage
