DECL|macro|SPLIT_INDEX_H
DECL|member|base
DECL|member|base_sha1
DECL|member|delete_bitmap
DECL|member|nr_deletions
DECL|member|nr_replacements
DECL|member|refcount
DECL|member|replace_bitmap
DECL|member|saved_cache
DECL|member|saved_cache_nr
DECL|struct|split_index
