DECL|function|main
DECL|function|serve_object
DECL|function|serve_ref
DECL|function|serve_version
DECL|function|service
DECL|macro|COUNTERPART_ENV_NAME
DECL|macro|COUNTERPART_PROGRAM_NAME
DECL|macro|MY_PROGRAM_NAME
DECL|variable|local_version
DECL|variable|remote_version
DECL|variable|ssh_push_usage
DECL|variable|verbose
