DECL|function|fetch
DECL|function|fetch_ref
DECL|function|get_version
DECL|function|main
DECL|function|prefetch
DECL|variable|fd_in
DECL|variable|fd_out
DECL|variable|local_version
DECL|variable|remote_version
