DECL|function|prefixcmp
DECL|function|strbuf_add
DECL|function|strbuf_adddup
DECL|function|strbuf_addf
DECL|function|strbuf_attach
DECL|function|strbuf_branchname
DECL|function|strbuf_check_branch_ref
DECL|function|strbuf_cmp
DECL|function|strbuf_detach
DECL|function|strbuf_expand
DECL|function|strbuf_expand_dict_cb
DECL|function|strbuf_fread
DECL|function|strbuf_getline
DECL|function|strbuf_grow
DECL|function|strbuf_init
DECL|function|strbuf_insert
DECL|function|strbuf_list_free
DECL|function|strbuf_ltrim
DECL|function|strbuf_read
DECL|function|strbuf_read_file
DECL|function|strbuf_readlink
DECL|function|strbuf_release
DECL|function|strbuf_remove
DECL|function|strbuf_rtrim
DECL|function|strbuf_splice
DECL|function|strbuf_split
DECL|function|strbuf_tolower
DECL|function|strbuf_trim
DECL|macro|STRBUF_MAXLINK
DECL|variable|strbuf_slopbuf
