DECL|function|strbuf_addbuf
DECL|function|strbuf_addch
DECL|function|strbuf_addstr
DECL|function|strbuf_avail
DECL|function|strbuf_setlen
DECL|function|strbuf_swap
DECL|macro|STRBUF_H
DECL|macro|STRBUF_INIT
DECL|macro|strbuf_reset
DECL|member|alloc
DECL|member|buf
DECL|member|len
DECL|member|placeholder
DECL|member|value
DECL|struct|strbuf
DECL|struct|strbuf_expand_dict_entry
DECL|typedef|expand_fn_t
