DECL|function|strbuf_add
DECL|function|strbuf_addf
DECL|function|strbuf_attach
DECL|function|strbuf_cmp
DECL|function|strbuf_detach
DECL|function|strbuf_fread
DECL|function|strbuf_getline
DECL|function|strbuf_grow
DECL|function|strbuf_init
DECL|function|strbuf_insert
DECL|function|strbuf_read
DECL|function|strbuf_read_file
DECL|function|strbuf_release
DECL|function|strbuf_remove
DECL|function|strbuf_reset
DECL|function|strbuf_rtrim
DECL|function|strbuf_splice
