DECL|function|strbuf_addbuf
DECL|function|strbuf_addch
DECL|function|strbuf_addstr
DECL|function|strbuf_avail
DECL|function|strbuf_setlen
DECL|macro|STRBUF_H
DECL|macro|STRBUF_INIT
DECL|member|alloc
DECL|member|buf
DECL|member|len
DECL|struct|strbuf
