DECL|enumerator|incore
DECL|enumerator|loose
DECL|enumerator|pack_non_delta
DECL|enumerator|stream_error
DECL|enum|input_source
DECL|function|close_istream
DECL|function|close_method_decl
DECL|function|istream_source
DECL|function|open_istream
DECL|function|open_method_decl
DECL|function|open_method_decl
DECL|function|open_method_decl
DECL|function|read_istream
DECL|function|read_method_decl
DECL|macro|close_method_decl
DECL|macro|open_method_decl
DECL|macro|read_method_decl
DECL|member|buf
DECL|member|close
DECL|member|fd
DECL|member|fd
DECL|member|in_pack
DECL|member|incore
DECL|member|loose
DECL|member|read
DECL|member|read_ptr
DECL|member|size
DECL|member|u
DECL|member|vtbl
DECL|struct|git_istream
DECL|struct|stream_vtbl
DECL|typedef|close_istream_fn
DECL|typedef|open_istream_fn
DECL|typedef|read_istream_fn
DECL|variable|incore_vtbl
DECL|variable|open_istream_tbl
