DECL|enumerator|incore
DECL|enumerator|loose
DECL|enumerator|pack_non_delta
DECL|enumerator|stream_error
DECL|enumerator|z_done
DECL|enumerator|z_error
DECL|enumerator|z_unused
DECL|enumerator|z_used
DECL|enum|input_source
DECL|function|attach_stream_filter
DECL|function|close_deflated_stream
DECL|function|close_istream
DECL|function|close_method_decl
DECL|function|close_method_decl
DECL|function|close_method_decl
DECL|function|close_method_decl
DECL|function|istream_source
DECL|function|open_istream
DECL|function|open_method_decl
DECL|function|open_method_decl
DECL|function|open_method_decl
DECL|function|read_istream
DECL|function|read_method_decl
DECL|function|read_method_decl
DECL|function|read_method_decl
DECL|function|read_method_decl
DECL|function|stream_blob_to_fd
DECL|macro|FILTER_BUFFER
DECL|macro|close_method_decl
DECL|macro|open_method_decl
DECL|macro|read_method_decl
DECL|member|buf
DECL|member|close
DECL|member|filter
DECL|member|filtered
DECL|member|hdr
DECL|member|hdr_avail
DECL|member|hdr_used
DECL|member|i_end
DECL|member|i_ptr
DECL|member|ibuf
DECL|member|in_pack
DECL|member|incore
DECL|member|input_finished
DECL|member|loose
DECL|member|mapped
DECL|member|mapsize
DECL|member|o_end
DECL|member|o_ptr
DECL|member|obuf
DECL|member|pack
DECL|member|pos
DECL|member|read
DECL|member|read_ptr
DECL|member|size
DECL|member|u
DECL|member|upstream
DECL|member|vtbl
DECL|member|z
DECL|member|z_state
DECL|struct|filtered_istream
DECL|struct|git_istream
DECL|struct|stream_vtbl
DECL|typedef|close_istream_fn
DECL|typedef|open_istream_fn
DECL|typedef|read_istream_fn
DECL|variable|filtered_vtbl
DECL|variable|incore_vtbl
DECL|variable|loose_vtbl
DECL|variable|open_istream_tbl
DECL|variable|pack_non_delta_vtbl
