DECL|macro|PATH_LIST_H
DECL|member|alloc
DECL|member|items
DECL|member|nr
DECL|member|strdup_strings
DECL|member|string
DECL|member|util
DECL|struct|string_list
DECL|struct|string_list_item
DECL|typedef|string_list_clear_func_t
DECL|typedef|string_list_each_func_t
