DECL|enumerator|lookup_name
DECL|enumerator|lookup_path
DECL|enum|lookup_type
DECL|function|cache_add
DECL|function|cache_free
DECL|function|cache_init
DECL|function|cache_lookup_name
DECL|function|cache_lookup_path
DECL|function|cache_put_path
DECL|function|cache_remove_path
DECL|function|config_from
DECL|function|config_from_name
DECL|function|config_from_path
DECL|function|config_name_cmp
DECL|function|config_path_cmp
DECL|function|ensure_cache_init
DECL|function|free_one_config
DECL|function|gitmodule_sha1_from_commit
DECL|function|hash_sha1_string
DECL|function|lookup_or_create_by_name
DECL|function|name_and_item_from_var
DECL|function|parse_config
DECL|function|parse_fetch_recurse
DECL|function|parse_fetch_recurse_submodules_arg
DECL|function|parse_push_recurse
DECL|function|parse_push_recurse_submodules_arg
DECL|function|parse_submodule_config_option
DECL|function|submodule_free
DECL|function|submodule_from_name
DECL|function|submodule_from_path
DECL|function|warn_multiple_config
DECL|member|cache
DECL|member|commit_sha1
DECL|member|config
DECL|member|ent
DECL|member|for_name
DECL|member|for_path
DECL|member|gitmodules_sha1
DECL|member|overwrite
DECL|struct|parse_config_parameter
DECL|struct|submodule_cache
DECL|struct|submodule_entry
DECL|variable|cache
DECL|variable|is_cache_init
