DECL|function|has_symlink_leading_path
DECL|function|has_symlink_or_noent_leading_path
DECL|function|longest_match_lstat_cache
DECL|function|lstat_cache
DECL|function|reset_lstat_cache
DECL|macro|FL_DIR
DECL|macro|FL_ERR
DECL|macro|FL_LSTATERR
DECL|macro|FL_NOENT
DECL|macro|FL_SYMLINK
DECL|member|flags
DECL|member|len
DECL|member|path
DECL|member|track_flags
DECL|struct|cache_def
DECL|variable|cache
