DECL|function|clear_lstat_cache
DECL|function|do_remove_scheduled_dirs
DECL|function|has_dirs_only_path
DECL|function|has_symlink_leading_path
DECL|function|has_symlink_or_noent_leading_path
DECL|function|invalidate_lstat_cache
DECL|function|longest_path_match
DECL|function|lstat_cache
DECL|function|remove_scheduled_dirs
DECL|function|reset_lstat_cache
DECL|function|schedule_dir_for_removal
DECL|macro|FL_DIR
DECL|macro|FL_ERR
DECL|macro|FL_FULLPATH
DECL|macro|FL_LSTATERR
DECL|macro|FL_NOENT
DECL|macro|FL_SYMLINK
DECL|macro|USE_ONLY_LSTAT
DECL|member|flags
DECL|member|len
DECL|member|len
DECL|member|path
DECL|member|path
DECL|member|prefix_len_stat_func
DECL|member|track_flags
DECL|struct|cache_def
DECL|struct|removal_def
DECL|variable|cache
DECL|variable|removal
