DECL|function|deref_tag
DECL|function|lookup_tag
DECL|function|parse_signature
DECL|function|parse_tag
DECL|function|parse_tag_buffer
DECL|function|parse_tag_date
DECL|macro|PGP_MESSAGE
DECL|macro|PGP_SIGNATURE
DECL|variable|tag_type
