DECL|function|append_char
DECL|function|append_long
DECL|function|append_path
DECL|function|append_path_prefix
DECL|function|append_string
DECL|function|commit_time
DECL|function|main
DECL|function|path_len
DECL|function|path_prefix_len
DECL|function|reliable_write
DECL|function|traverse_tree
DECL|function|write_blocked
DECL|function|write_extended_header
DECL|function|write_header
DECL|function|write_if_needed
DECL|function|write_trailer
DECL|macro|BLOCKSIZE
DECL|macro|RECORDSIZE
DECL|member|name
DECL|member|prev
DECL|struct|path_prefix
DECL|variable|archive_time
DECL|variable|basedir
DECL|variable|block
DECL|variable|offset
DECL|variable|tar_tree_usage
