DECL|macro|TYPEFLAG_AUTO
DECL|macro|TYPEFLAG_DIR
DECL|macro|TYPEFLAG_EXT_HEADER
DECL|macro|TYPEFLAG_GLOBAL_HEADER
DECL|macro|TYPEFLAG_LNK
DECL|macro|TYPEFLAG_REG
DECL|member|chksum
DECL|member|devmajor
DECL|member|devminor
DECL|member|gid
DECL|member|gname
DECL|member|linkname
DECL|member|magic
DECL|member|mode
DECL|member|mtime
DECL|member|name
DECL|member|prefix
DECL|member|size
DECL|member|typeflag
DECL|member|uid
DECL|member|uname
DECL|member|version
DECL|struct|ustar_header
