DECL|function|is_tempfile_active
DECL|function|mks_tempfile
DECL|function|mks_tempfile_m
DECL|function|mks_tempfile_s
DECL|function|mks_tempfile_t
DECL|function|mks_tempfile_tm
DECL|function|mks_tempfile_ts
DECL|function|xmks_tempfile
DECL|macro|TEMPFILE_H
DECL|member|active
DECL|member|fd
DECL|member|filename
DECL|member|fp
DECL|member|next
DECL|member|on_list
DECL|member|owner
DECL|struct|tempfile
