DECL|function|alloc_test_entry
DECL|function|get_value
DECL|function|hash
DECL|function|main
DECL|function|perf_hashmap
DECL|function|test_entry_cmp
DECL|function|test_entry_cmp_icase
DECL|macro|DELIM
DECL|macro|HASH_METHOD_0
DECL|macro|HASH_METHOD_FNV
DECL|macro|HASH_METHOD_I
DECL|macro|HASH_METHOD_IDIV10
DECL|macro|HASH_METHOD_X2
DECL|macro|TEST_ADD
DECL|macro|TEST_SIZE
DECL|macro|TEST_SPARSE
DECL|member|ent
DECL|member|key
DECL|struct|test_entry
