DECL|function|main
DECL|function|md_to_str
DECL|function|process_file
DECL|function|str_to_md
DECL|function|usage
DECL|macro|MAX
DECL|macro|MIN
DECL|member|length
DECL|member|match
DECL|member|md
DECL|member|name
DECL|struct|fileinfo
DECL|typedef|File
DECL|variable|cmd
DECL|variable|file
DECL|variable|file_bytes
DECL|variable|file_count
DECL|variable|flag_debug
DECL|variable|flag_relative
DECL|variable|flag_verbose
DECL|variable|hex
DECL|variable|md_strbuf
DECL|variable|relative_md
