DECL|function|length_callback
DECL|function|main
DECL|variable|abbrev
DECL|variable|boolean
DECL|variable|dry_run
DECL|variable|integer
DECL|variable|quiet
DECL|variable|string
DECL|variable|timestamp
DECL|variable|verbose
