DECL|macro|TRACE_CONTEXT
DECL|macro|TRACE_H
DECL|macro|TRACE_KEY_INIT
DECL|macro|trace_argv_printf
DECL|macro|trace_printf
DECL|macro|trace_printf_key
DECL|macro|trace_strbuf
DECL|member|fd
DECL|member|initialized
DECL|member|key
DECL|member|need_close
DECL|struct|trace_key
