DECL|function|get_trace_fd
DECL|function|quote_crnl
DECL|function|trace_argv_printf
DECL|function|trace_printf
DECL|function|trace_printf_key
DECL|function|trace_repo_setup
DECL|function|trace_strbuf
DECL|function|trace_vprintf
DECL|function|trace_want
DECL|variable|err_msg
