DECL|enumerator|EXISTS_ADD
DECL|enumerator|EXISTS_ADD_IF_DIFFERENT
DECL|enumerator|EXISTS_ADD_IF_DIFFERENT_NEIGHBOR
DECL|enumerator|EXISTS_DO_NOTHING
DECL|enumerator|EXISTS_REPLACE
DECL|enumerator|MISSING_ADD
DECL|enumerator|MISSING_DO_NOTHING
DECL|enumerator|TRAILER_COMMAND
DECL|enumerator|TRAILER_IF_EXISTS
DECL|enumerator|TRAILER_IF_MISSING
DECL|enumerator|TRAILER_KEY
DECL|enumerator|TRAILER_WHERE
DECL|enumerator|WHERE_AFTER
DECL|enumerator|WHERE_BEFORE
DECL|enumerator|WHERE_END
DECL|enumerator|WHERE_START
DECL|enum|action_if_exists
DECL|enum|action_if_missing
DECL|enum|action_where
DECL|enum|trailer_info_type
DECL|function|add_arg_to_input_list
DECL|function|add_trailer_item
DECL|function|after_or_end
DECL|function|apply_arg_if_exists
DECL|function|apply_arg_if_missing
DECL|function|check_if_different
DECL|function|contains_only_spaces
DECL|function|create_trailer_item
DECL|function|duplicate_conf
DECL|function|find_patch_start
DECL|function|find_same_and_apply_arg
DECL|function|find_trailer_start
DECL|function|free_trailer_item
DECL|function|get_conf_item
DECL|function|git_trailer_config
DECL|function|git_trailer_default_config
DECL|function|has_blank_line_before
DECL|function|new_trailer_item
DECL|function|parse_trailer
DECL|function|print_lines
DECL|function|process_command_line_args
DECL|function|process_input_file
DECL|function|process_trailers_lists
DECL|function|read_input_file
DECL|function|remove_first
DECL|function|remove_from_list
DECL|function|same_token
DECL|function|same_trailer
DECL|function|same_value
DECL|function|set_if_exists
DECL|function|set_if_missing
DECL|function|set_where
DECL|function|token_from_item
DECL|function|token_len_without_separator
DECL|function|token_matches_item
DECL|function|update_first
DECL|function|update_last
DECL|member|command
DECL|member|conf
DECL|member|if_exists
DECL|member|if_missing
DECL|member|key
DECL|member|name
DECL|member|name
DECL|member|next
DECL|member|previous
DECL|member|token
DECL|member|type
DECL|member|value
DECL|member|where
DECL|struct|conf_info
DECL|struct|trailer_item
DECL|variable|default_conf_info
DECL|variable|first_conf_item
DECL|variable|separators
DECL|variable|trailer_config_items
