DECL|enumerator|EXISTS_ADD
DECL|enumerator|EXISTS_ADD_IF_DIFFERENT
DECL|enumerator|EXISTS_ADD_IF_DIFFERENT_NEIGHBOR
DECL|enumerator|EXISTS_DO_NOTHING
DECL|enumerator|EXISTS_REPLACE
DECL|enumerator|MISSING_ADD
DECL|enumerator|MISSING_DO_NOTHING
DECL|enumerator|WHERE_AFTER
DECL|enumerator|WHERE_BEFORE
DECL|enumerator|WHERE_END
DECL|enumerator|WHERE_START
DECL|enum|action_if_exists
DECL|enum|action_if_missing
DECL|enum|action_where
DECL|function|after_or_end
DECL|function|same_token
DECL|function|same_trailer
DECL|function|same_value
DECL|function|token_len_without_separator
DECL|member|command
DECL|member|conf
DECL|member|if_exists
DECL|member|if_missing
DECL|member|key
DECL|member|name
DECL|member|next
DECL|member|previous
DECL|member|token
DECL|member|value
DECL|member|where
DECL|struct|conf_info
DECL|struct|trailer_item
DECL|variable|default_conf_info
DECL|variable|first_conf_item
DECL|variable|separators
