DECL|function|connect_helper
DECL|function|disconnect_helper
DECL|function|do_take_over
DECL|function|fetch
DECL|function|fetch_with_fetch
DECL|function|fetch_with_import
DECL|function|get_helper
DECL|function|get_importer
DECL|function|get_refs_list
DECL|function|has_attribute
DECL|function|process_connect
DECL|function|process_connect_service
DECL|function|push_refs
DECL|function|recvline
DECL|function|recvline_fh
DECL|function|release_helper
DECL|function|remove_ext_force
DECL|function|sendline
DECL|function|set_helper_option
DECL|function|standard_options
DECL|function|transport_helper_init
DECL|function|write_constant
DECL|function|xchgline
DECL|member|connect
DECL|member|fetch
DECL|member|helper
DECL|member|import
DECL|member|name
DECL|member|no_disconnect_req
DECL|member|option
DECL|member|out
DECL|member|push
DECL|member|refspec_nr
DECL|member|refspecs
DECL|member|transport_options
DECL|struct|helper_data
DECL|variable|boolean_options
DECL|variable|debug
DECL|variable|unsupported_options
