DECL|macro|TRANSPORT_H
DECL|macro|TRANSPORT_PUSH_ALL
DECL|macro|TRANSPORT_PUSH_FORCE
DECL|macro|TRANS_OPT_DEPTH
DECL|macro|TRANS_OPT_KEEP
DECL|macro|TRANS_OPT_RECEIVEPACK
DECL|macro|TRANS_OPT_THIN
DECL|macro|TRANS_OPT_UNPACKLIMIT
DECL|macro|TRANS_OPT_UPLOADPACK
DECL|member|data
DECL|member|disconnect
DECL|member|fetch
DECL|member|get_refs_list
DECL|member|ops
DECL|member|pack_lockfile
DECL|member|push
DECL|member|remote
DECL|member|remote_refs
DECL|member|set_option
DECL|member|url
DECL|member|verbose
DECL|struct|transport
DECL|struct|transport_ops
