DECL|macro|REJECT_ALREADY_EXISTS
DECL|macro|REJECT_FETCH_FIRST
DECL|macro|REJECT_NEEDS_FORCE
DECL|macro|REJECT_NON_FF_HEAD
DECL|macro|REJECT_NON_FF_OTHER
DECL|macro|TRANSPORT_H
DECL|macro|TRANSPORT_PUSH_ALL
DECL|macro|TRANSPORT_PUSH_DRY_RUN
DECL|macro|TRANSPORT_PUSH_FOLLOW_TAGS
DECL|macro|TRANSPORT_PUSH_FORCE
DECL|macro|TRANSPORT_PUSH_MIRROR
DECL|macro|TRANSPORT_PUSH_NO_HOOK
DECL|macro|TRANSPORT_PUSH_PORCELAIN
DECL|macro|TRANSPORT_PUSH_PRUNE
DECL|macro|TRANSPORT_PUSH_SET_UPSTREAM
DECL|macro|TRANSPORT_RECURSE_SUBMODULES_CHECK
DECL|macro|TRANSPORT_RECURSE_SUBMODULES_ON_DEMAND
DECL|macro|TRANSPORT_SUMMARY
DECL|macro|TRANSPORT_SUMMARY_WIDTH
DECL|macro|TRANS_OPT_CAS
DECL|macro|TRANS_OPT_DEPTH
DECL|macro|TRANS_OPT_FOLLOWTAGS
DECL|macro|TRANS_OPT_KEEP
DECL|macro|TRANS_OPT_RECEIVEPACK
DECL|macro|TRANS_OPT_THIN
DECL|macro|TRANS_OPT_UPLOADPACK
DECL|member|cannot_reuse
DECL|member|cas
DECL|member|check_self_contained_and_connected
DECL|member|cloning
DECL|member|connect
DECL|member|data
DECL|member|depth
DECL|member|disconnect
DECL|member|fetch
DECL|member|followtags
DECL|member|get_refs_list
DECL|member|got_remote_refs
DECL|member|keep
DECL|member|pack_lockfile
DECL|member|progress
DECL|member|push
DECL|member|push_refs
DECL|member|receivepack
DECL|member|remote
DECL|member|remote_refs
DECL|member|self_contained_and_connected
DECL|member|set_option
DECL|member|smart_options
DECL|member|thin
DECL|member|uploadpack
DECL|member|url
DECL|member|verbose
DECL|struct|git_transport_options
DECL|struct|transport
DECL|typedef|alternate_ref_fn
