DECL|function|disconnect_helper
DECL|function|fetch
DECL|function|fetch_with_fetch
DECL|function|fetch_with_import
DECL|function|get_helper
DECL|function|get_importer
DECL|function|get_refs_list
DECL|function|has_attribute
DECL|function|release_helper
DECL|function|transport_helper_init
DECL|member|fetch
DECL|member|helper
DECL|member|import
DECL|member|name
DECL|member|refspec_nr
DECL|member|refspecs
DECL|struct|helper_data
