DECL|function|close_bundle
DECL|function|connect_git
DECL|function|connect_setup
DECL|function|disconnect_git
DECL|function|external_specification_len
DECL|function|fetch_objs_via_rsync
DECL|function|fetch_refs_from_bundle
DECL|function|fetch_refs_via_pack
DECL|function|get_refs_from_bundle
DECL|function|get_refs_via_connect
DECL|function|get_refs_via_rsync
DECL|function|git_transport_push
DECL|function|insert_packed_refs
DECL|function|is_file
DECL|function|is_local
DECL|function|is_url
DECL|function|print_ok_ref_status
DECL|function|print_one_push_status
DECL|function|print_push_status
DECL|function|print_ref_status
DECL|function|push_had_errors
DECL|function|read_loose_refs
DECL|function|refs_pushed
DECL|function|rsync_transport_push
DECL|function|rsync_url
DECL|function|set_git_option
DECL|function|set_upstreams
DECL|function|status_abbrev
DECL|function|str_cmp
DECL|function|transport_anonymize_url
DECL|function|transport_connect
DECL|function|transport_disconnect
DECL|function|transport_fetch_refs
DECL|function|transport_get
DECL|function|transport_get_remote_refs
DECL|function|transport_push
DECL|function|transport_set_option
DECL|function|transport_take_over
DECL|function|transport_unlock_pack
DECL|function|update_tracking_ref
DECL|function|verify_remote_names
DECL|function|write_one_ref
DECL|function|write_refs_to_temp_dir
DECL|macro|SUMMARY_WIDTH
DECL|member|conn
DECL|member|extra_have
DECL|member|fd
DECL|member|fd
DECL|member|got_remote_heads
DECL|member|header
DECL|member|options
DECL|struct|bundle_transport_data
DECL|struct|git_transport_data
