DECL|function|close_bundle
DECL|function|connect_setup
DECL|function|curl_transport_push
DECL|function|disconnect_git
DECL|function|disconnect_walker
DECL|function|fetch_objs_via_curl
DECL|function|fetch_objs_via_rsync
DECL|function|fetch_objs_via_walker
DECL|function|fetch_refs_from_bundle
DECL|function|fetch_refs_via_pack
DECL|function|get_refs_from_bundle
DECL|function|get_refs_via_connect
DECL|function|get_refs_via_curl
DECL|function|get_refs_via_rsync
DECL|function|git_transport_push
DECL|function|insert_packed_refs
DECL|function|is_file
DECL|function|is_local
DECL|function|read_loose_refs
DECL|function|rsync_transport_push
DECL|function|set_git_option
DECL|function|str_cmp
DECL|function|transport_disconnect
DECL|function|transport_fetch_refs
DECL|function|transport_get
DECL|function|transport_get_remote_refs
DECL|function|transport_push
DECL|function|transport_set_option
DECL|function|transport_unlock_pack
DECL|function|write_one_ref
DECL|function|write_refs_to_temp_dir
DECL|member|conn
DECL|member|depth
DECL|member|fd
DECL|member|fd
DECL|member|followtags
DECL|member|header
DECL|member|keep
DECL|member|receivepack
DECL|member|thin
DECL|member|uploadpack
DECL|struct|bundle_transport_data
DECL|struct|git_transport_data
