DECL|macro|TRANSPORT_H
DECL|macro|TRANSPORT_PUSH_ALL
DECL|macro|TRANSPORT_PUSH_DRY_RUN
DECL|macro|TRANSPORT_PUSH_FORCE
DECL|macro|TRANSPORT_PUSH_MIRROR
DECL|macro|TRANSPORT_PUSH_VERBOSE
DECL|macro|TRANS_OPT_DEPTH
DECL|macro|TRANS_OPT_FOLLOWTAGS
DECL|macro|TRANS_OPT_KEEP
DECL|macro|TRANS_OPT_RECEIVEPACK
DECL|macro|TRANS_OPT_THIN
DECL|macro|TRANS_OPT_UPLOADPACK
DECL|member|data
DECL|member|disconnect
DECL|member|fetch
DECL|member|get_refs_list
DECL|member|pack_lockfile
DECL|member|progress
DECL|member|push
DECL|member|push_refs
DECL|member|remote
DECL|member|remote_refs
DECL|member|set_option
DECL|member|url
DECL|member|verbose
DECL|struct|transport
