DECL|function|traverse_path_len
DECL|function|tree_entry_extract
DECL|function|tree_entry_len
DECL|macro|TREE_WALK_H
DECL|member|buffer
DECL|member|conflicts
DECL|member|data
DECL|member|entry
DECL|member|fn
DECL|member|mode
DECL|member|name
DECL|member|path
DECL|member|pathlen
DECL|member|pathspec
DECL|member|prev
DECL|member|sha1
DECL|member|show_all_errors
DECL|member|size
DECL|struct|name_entry
DECL|struct|traverse_info
DECL|struct|tree_desc
DECL|typedef|traverse_callback_t
