DECL|function|tree_entry_len
DECL|macro|TREE_WALK_H
DECL|member|buffer
DECL|member|mode
DECL|member|path
DECL|member|sha1
DECL|member|size
DECL|struct|name_entry
DECL|struct|tree_desc
DECL|typedef|traverse_callback_t
