DECL|function|compare_tree_entry
DECL|function|count_paths
DECL|function|diff_tree
DECL|function|diff_tree_release_paths
DECL|function|diff_tree_setup_paths
DECL|function|diff_tree_sha1
DECL|function|interesting
DECL|function|malloc_base
DECL|function|show_entry
DECL|function|show_tree
