DECL|macro|TREE_WALK_H
DECL|member|buf
DECL|member|mode
DECL|member|path
DECL|member|pathlen
DECL|member|sha1
DECL|member|size
DECL|struct|name_entry
DECL|struct|tree_desc
DECL|typedef|traverse_callback_t
