DECL|function|check_entry_match
DECL|function|decode_tree_entry
DECL|function|entry_clear
DECL|function|entry_extract
DECL|function|extended_entry_extract
DECL|function|fill_tree_descriptor
DECL|function|find_tree_entry
DECL|function|free_extended_entry
DECL|function|get_mode
DECL|function|get_tree_entry
DECL|function|init_tree_desc
DECL|function|make_traverse_path
DECL|function|name_compare
DECL|function|setup_traverse_info
DECL|function|traverse_trees
DECL|function|tree_entry
DECL|function|update_extended_entry
DECL|function|update_tree_entry
DECL|member|d
DECL|member|prev
DECL|member|ptr
DECL|member|skip
DECL|struct|tree_desc_skip
DECL|struct|tree_desc_x
