DECL|macro|READ_TREE_RECURSIVE
DECL|macro|TREE_H
DECL|member|any
DECL|member|blob
DECL|member|buffer
DECL|member|directory
DECL|member|entries
DECL|member|executable
DECL|member|item
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|object
DECL|member|size
DECL|member|symlink
DECL|member|tree
DECL|member|zeropad
DECL|struct|tree
DECL|struct|tree_entry_list
DECL|typedef|read_tree_fn_t
