DECL|macro|TREE_H
DECL|member|blob
DECL|member|directory
DECL|member|entries
DECL|member|executable
DECL|member|item
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|object
DECL|member|parent
DECL|member|symlink
DECL|member|tree
DECL|struct|tree
DECL|struct|tree_entry_list
