DECL|function|decode_tree_entry
DECL|function|entry_clear
DECL|function|entry_compare
DECL|function|entry_extract
DECL|function|fill_tree_descriptor
DECL|function|find_tree_entry
DECL|function|get_mode
DECL|function|get_tree_entry
DECL|function|init_tree_desc
DECL|function|make_traverse_path
DECL|function|setup_traverse_info
DECL|function|traverse_trees
DECL|function|tree_entry
DECL|function|update_tree_entry
