DECL|macro|UNPACK_TREES_H
DECL|member|aggressive
DECL|member|df_conflict_entry
DECL|member|dir
DECL|member|dst_index
DECL|member|fn
DECL|member|gently
DECL|member|head_idx
DECL|member|index_only
DECL|member|merge
DECL|member|merge_size
DECL|member|nontrivial_merge
DECL|member|pos
DECL|member|prefix
DECL|member|reset
DECL|member|result
DECL|member|skip_unmerged
DECL|member|src_index
DECL|member|trivial_merges_only
DECL|member|unpack_data
DECL|member|update
DECL|member|verbose_update
DECL|struct|unpack_trees_options
DECL|typedef|merge_fn_t
