DECL|function|bind_merge
DECL|function|check_updates
DECL|function|create_tree_entry_list
DECL|function|deleted_entry
DECL|function|entcmp
DECL|function|invalidate_ce_path
DECL|function|keep_entry
DECL|function|merged_entry
DECL|function|oneway_merge
DECL|function|progress_interval
DECL|function|reject_merge
DECL|function|same
DECL|function|setup_progress_signal
DECL|function|show_stage_entry
DECL|function|threeway_merge
DECL|function|twoway_merge
DECL|function|unlink_entry
DECL|function|unpack_trees
DECL|function|unpack_trees_rec
DECL|function|verify_absent
DECL|function|verify_uptodate
DECL|macro|DBRT_DEBUG
DECL|member|directory
DECL|member|executable
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|sha1
DECL|member|symlink
DECL|struct|tree_entry_list
DECL|variable|progress_update
DECL|variable|state
