DECL|function|add_delta_to_list
DECL|function|added_object
DECL|function|fill
DECL|function|get_data
DECL|function|main
DECL|function|resolve_delta
DECL|function|unpack_all
DECL|function|unpack_delta_entry
DECL|function|unpack_non_delta_entry
DECL|function|unpack_one
DECL|function|use
DECL|member|base_sha1
DECL|member|delta
DECL|member|next
DECL|member|size
DECL|struct|delta_info
DECL|variable|buffer
DECL|variable|ctx
DECL|variable|delta_list
DECL|variable|dry_run
DECL|variable|eof
DECL|variable|len
DECL|variable|offset
DECL|variable|unpack_usage
