DECL|function|add_entry
DECL|function|bind_merge
DECL|function|call_unpack_fn
DECL|function|check_updates
DECL|function|compare_entry
DECL|function|create_ce_entry
DECL|function|deleted_entry
DECL|function|do_compare_entry
DECL|function|icase_exists
DECL|function|invalidate_ce_path
DECL|function|keep_entry
DECL|function|merged_entry
DECL|function|oneway_merge
DECL|function|reject_merge
DECL|function|same
DECL|function|show_stage_entry
DECL|function|threeway_merge
DECL|function|traverse_trees_recursive
DECL|function|twoway_merge
DECL|function|unlink_entry
DECL|function|unpack_callback
DECL|function|unpack_failed
DECL|function|unpack_index_entry
DECL|function|unpack_nondirectories
DECL|function|unpack_trees
DECL|function|verify_absent
DECL|function|verify_clean_subdirectory
DECL|function|verify_clean_submodule
DECL|function|verify_uptodate
DECL|macro|ERRORMSG
DECL|macro|NO_THE_INDEX_COMPATIBILITY_MACROS
DECL|variable|state
DECL|variable|unpack_plumbing_errors
