DECL|enumerator|ERROR_BIND_OVERLAP
DECL|enumerator|ERROR_NOT_UPTODATE_DIR
DECL|enumerator|ERROR_NOT_UPTODATE_FILE
DECL|enumerator|ERROR_SPARSE_NOT_UPTODATE_FILE
DECL|enumerator|ERROR_WOULD_LOSE_ORPHANED_OVERWRITTEN
DECL|enumerator|ERROR_WOULD_LOSE_ORPHANED_REMOVED
DECL|enumerator|ERROR_WOULD_LOSE_UNTRACKED_OVERWRITTEN
DECL|enumerator|ERROR_WOULD_LOSE_UNTRACKED_REMOVED
DECL|enumerator|ERROR_WOULD_OVERWRITE
DECL|enumerator|NB_UNPACK_TREES_ERROR_TYPES
DECL|enum|unpack_trees_error_types
DECL|macro|MAX_UNPACK_TREES
DECL|macro|UNPACK_TREES_H
DECL|member|aggressive
DECL|member|cache_bottom
DECL|member|debug_unpack
DECL|member|df_conflict_entry
DECL|member|diff_index_cached
DECL|member|dir
DECL|member|dry_run
DECL|member|dst_index
DECL|member|el
DECL|member|fn
DECL|member|gently
DECL|member|head_idx
DECL|member|index_only
DECL|member|initial_checkout
DECL|member|merge
DECL|member|merge_size
DECL|member|msgs
DECL|member|nontrivial_merge
DECL|member|pathspec
DECL|member|prefix
DECL|member|reset
DECL|member|result
DECL|member|show_all_errors
DECL|member|skip_sparse_checkout
DECL|member|skip_unmerged
DECL|member|src_index
DECL|member|trivial_merges_only
DECL|member|unpack_data
DECL|member|unpack_rejects
DECL|member|update
DECL|member|verbose_update
DECL|struct|unpack_trees_options
DECL|typedef|merge_fn_t
