DECL|function|check_updates
DECL|function|create_tree_entry_list
DECL|function|entcmp
DECL|function|progress_interval
DECL|function|setup_progress_signal
DECL|function|unlink_entry
DECL|function|unpack_trees
DECL|function|unpack_trees_rec
DECL|member|directory
DECL|member|executable
DECL|member|mode
DECL|member|name
DECL|member|next
DECL|member|sha1
DECL|member|symlink
DECL|struct|tree_entry_list
DECL|variable|progress_update
DECL|variable|state
