DECL|macro|UNPACK_TREES_H
DECL|member|aggressive
DECL|member|df_conflict_entry
DECL|member|fn
DECL|member|head_idx
DECL|member|index_only
DECL|member|merge
DECL|member|merge_size
DECL|member|nontrivial_merge
DECL|member|prefix
DECL|member|reset
DECL|member|trivial_merges_only
DECL|member|update
DECL|member|verbose_update
DECL|struct|unpack_trees_options
DECL|typedef|merge_fn_t
