DECL|function|add_cacheinfo
DECL|function|add_file_to_cache
DECL|function|compare_data
DECL|function|fill_stat_cache_info
DECL|function|index_fd
DECL|function|main
DECL|function|match_data
DECL|function|refresh_cache
DECL|function|refresh_entry
DECL|function|remove_lock_file
DECL|function|verify_path
DECL|variable|allow_add
DECL|variable|allow_remove
DECL|variable|lockfile_name
