DECL|function|ERR_PTR
DECL|function|IS_ERR
DECL|function|PTR_ERR
DECL|function|add_cacheinfo
DECL|function|add_file_to_cache
DECL|function|compare_data
DECL|function|compare_link
DECL|function|main
DECL|function|match_data
DECL|function|refresh_cache
DECL|function|refresh_entry
DECL|function|verify_dotfile
DECL|function|verify_path
DECL|variable|allow_add
DECL|variable|allow_remove
DECL|variable|allow_replace
DECL|variable|cache_file
DECL|variable|force_remove
DECL|variable|not_new
