DECL|function|create_pack_file
DECL|function|get_common_commits
DECL|function|got_sha1
DECL|function|main
DECL|function|ok_to_give_up
DECL|function|reachable
DECL|function|receive_needs
DECL|function|reset_timeout
DECL|function|send_client_data
DECL|function|send_ref
DECL|function|strip
DECL|function|upload_pack
DECL|macro|COMMON_KNOWN
DECL|macro|OUR_REF
DECL|macro|REACHABLE
DECL|macro|THEY_HAVE
DECL|macro|WANTED
DECL|variable|have_obj
DECL|variable|multi_ack
DECL|variable|nr_our_refs
DECL|variable|oldest_have
DECL|variable|timeout
DECL|variable|upload_pack_usage
DECL|variable|use_ofs_delta
DECL|variable|use_sideband
DECL|variable|use_thin_pack
DECL|variable|want_obj
