DECL|function|create_pack_file
DECL|function|get_common_commits
DECL|function|got_sha1
DECL|function|main
DECL|function|receive_needs
DECL|function|reset_timeout
DECL|function|send_client_data
DECL|function|send_ref
DECL|function|strip
DECL|function|upload_pack
DECL|macro|MAX_HAS
DECL|macro|MAX_NEEDS
DECL|macro|OUR_REF
DECL|macro|PACKET_MAX
DECL|macro|THEY_HAVE
DECL|macro|WANTED
DECL|variable|has_tip
DECL|variable|multi_ack
DECL|variable|needs_tip
DECL|variable|nr_has
DECL|variable|nr_needs
DECL|variable|nr_our_refs
DECL|variable|timeout
DECL|variable|upload_pack_usage
DECL|variable|use_sideband
DECL|variable|use_thin_pack
