DECL|function|append_normalized_escapes
DECL|function|match_urls
DECL|function|url_match_prefix
DECL|function|url_normalize
DECL|function|urlmatch_config_entry
DECL|macro|URL_ALPHA
DECL|macro|URL_ALPHADIGIT
DECL|macro|URL_DIGIT
DECL|macro|URL_GEN_RESERVED
DECL|macro|URL_HOST_CHARS
DECL|macro|URL_RESERVED
DECL|macro|URL_SCHEME_CHARS
DECL|macro|URL_SUB_RESERVED
DECL|macro|URL_UNSAFE_CHARS
