DECL|member|cascade_fn
DECL|member|cb
DECL|member|collect_fn
DECL|member|err
DECL|member|host_len
DECL|member|host_off
DECL|member|key
DECL|member|matched_len
DECL|member|passwd_len
DECL|member|passwd_off
DECL|member|path_len
DECL|member|path_off
DECL|member|port_len
DECL|member|scheme_len
DECL|member|section
DECL|member|url
DECL|member|url
DECL|member|url_len
DECL|member|user_len
DECL|member|user_matched
DECL|member|user_off
DECL|member|vars
DECL|struct|url_info
DECL|struct|urlmatch_config
DECL|struct|urlmatch_item
