DECL|function|die
DECL|function|die_builtin
DECL|function|die_errno
DECL|function|die_is_recursing_builtin
DECL|function|error
DECL|function|error_builtin
DECL|function|set_die_is_recursing_routine
DECL|function|set_die_routine
DECL|function|set_error_routine
DECL|function|usage
DECL|function|usage_builtin
DECL|function|usagef
DECL|function|vreportf
DECL|function|vwritef
DECL|function|warn_builtin
DECL|function|warning
DECL|macro|error
DECL|variable|die_is_recursing
DECL|variable|die_routine
DECL|variable|error_routine
DECL|variable|usage_routine
DECL|variable|warn_routine
