DECL|function|die
DECL|function|die_builtin
DECL|function|error
DECL|function|error_builtin
DECL|function|report
DECL|function|set_die_routine
DECL|function|set_error_routine
DECL|function|set_usage_routine
DECL|function|usage
DECL|function|usage_builtin
DECL|variable|error_routine
