DECL|macro|USERDIFF_H
DECL|member|binary
DECL|member|cflags
DECL|member|external
DECL|member|funcname
DECL|member|name
DECL|member|pattern
DECL|member|textconv
DECL|struct|userdiff_driver
DECL|struct|userdiff_funcname
