DECL|function|parse_driver
DECL|function|parse_funcname
DECL|function|parse_string
DECL|function|userdiff_config_basic
DECL|function|userdiff_config_porcelain
DECL|function|userdiff_find_by_name
DECL|function|userdiff_find_by_namelen
DECL|function|userdiff_find_by_path
DECL|macro|FUNCNAME
DECL|macro|FUNCNAME
DECL|variable|USERDIFF_ATTR_FALSE
DECL|variable|USERDIFF_ATTR_TRUE
DECL|variable|builtin_drivers
DECL|variable|driver_false
DECL|variable|driver_true
DECL|variable|drivers
DECL|variable|drivers_alloc
DECL|variable|ndrivers
