DECL|function|parse_bool
DECL|function|parse_driver
DECL|function|parse_funcname
DECL|function|parse_tristate
DECL|function|userdiff_config
DECL|function|userdiff_find_by_name
DECL|function|userdiff_find_by_namelen
DECL|function|userdiff_find_by_path
DECL|function|userdiff_get_textconv
DECL|macro|IPATTERN
DECL|macro|IPATTERN
DECL|macro|PATTERNS
DECL|macro|PATTERNS
DECL|variable|builtin_drivers
DECL|variable|driver_false
DECL|variable|driver_true
DECL|variable|drivers
DECL|variable|drivers_alloc
DECL|variable|ndrivers
