DECL|function|bisearch
DECL|function|is_encoding_utf8
DECL|function|is_utf8
DECL|function|print_spaces
DECL|function|print_wrapped_text
DECL|function|reencode_string
DECL|function|utf8_width
DECL|function|wcwidth
DECL|member|first
DECL|member|last
DECL|struct|interval
