DECL|function|interpret_target
DECL|function|loop
DECL|function|mark_complete
DECL|function|process
DECL|function|process_commit
DECL|function|process_object
DECL|function|process_tag
DECL|function|process_tree
DECL|function|report_missing
DECL|function|walker_fetch
DECL|function|walker_free
DECL|function|walker_say
DECL|function|walker_targets_free
DECL|function|walker_targets_stdin
DECL|macro|COMPLETE
DECL|macro|SEEN
DECL|macro|TO_SCAN
DECL|variable|complete
DECL|variable|current_commit_sha1
DECL|variable|process_queue
DECL|variable|process_queue_end
