DECL|function|doliteral
DECL|function|dowild
DECL|function|iwildmatch
DECL|function|litmatch_array
DECL|function|trailing_N_elements
DECL|function|wildmatch
DECL|function|wildmatch_array
DECL|macro|ABORT_ALL
DECL|macro|ABORT_TO_STARSTAR
DECL|macro|CC_EQ
DECL|macro|FALSE
DECL|macro|ISALNUM
DECL|macro|ISALPHA
DECL|macro|ISASCII
DECL|macro|ISASCII
DECL|macro|ISBLANK
DECL|macro|ISBLANK
DECL|macro|ISCNTRL
DECL|macro|ISDIGIT
DECL|macro|ISGRAPH
DECL|macro|ISGRAPH
DECL|macro|ISLOWER
DECL|macro|ISPRINT
DECL|macro|ISPUNCT
DECL|macro|ISSPACE
DECL|macro|ISUPPER
DECL|macro|ISXDIGIT
DECL|macro|NEGATE_CLASS
DECL|macro|NEGATE_CLASS2
DECL|macro|TRUE
DECL|variable|force_lower_case
DECL|variable|wildmatch_iteration_count
