DECL|function|do_nothing
DECL|function|git_mkstemp
DECL|function|git_mkstemp_mode
DECL|function|git_mkstemps
DECL|function|git_mkstemps_mode
DECL|function|gitmkstemps
DECL|function|memory_limit_check
DECL|function|read_in_full
DECL|function|remove_or_warn
DECL|function|rmdir_or_warn
DECL|function|set_try_to_free_routine
DECL|function|unlink_or_warn
DECL|function|warn_if_unremovable
DECL|function|write_in_full
DECL|function|xcalloc
DECL|function|xdup
DECL|function|xfdopen
DECL|function|xgetpwuid_self
DECL|function|xmalloc
DECL|function|xmallocz
DECL|function|xmemdupz
DECL|function|xmkstemp
DECL|function|xmkstemp_mode
DECL|function|xread
DECL|function|xrealloc
DECL|function|xstrdup
DECL|function|xstrndup
DECL|function|xwrite
DECL|macro|TMP_MAX
DECL|macro|TMP_MAX
DECL|variable|try_to_free_routine
