DECL|function|parse_whitespace_rule
DECL|function|setup_whitespace_attr_check
DECL|function|whitespace_error_string
DECL|function|whitespace_rule
DECL|function|ws_blank_line
DECL|function|ws_check
DECL|function|ws_check_emit
DECL|function|ws_check_emit_1
DECL|function|ws_fix_copy
DECL|member|loosens_error
DECL|member|rule_bits
DECL|member|rule_name
DECL|struct|whitespace_rule
DECL|variable|whitespace_rule_names
