DECL|enumerator|WT_STATUS_CHANGED
DECL|enumerator|WT_STATUS_HEADER
DECL|enumerator|WT_STATUS_UNTRACKED
DECL|enumerator|WT_STATUS_UPDATED
DECL|enum|color_wt_status
DECL|macro|STATUS_H
DECL|member|amend
DECL|member|branch
DECL|member|commitable
DECL|member|is_initial
DECL|member|reference
DECL|member|untracked
DECL|member|verbose
DECL|member|workdir_dirty
DECL|member|workdir_untracked
DECL|struct|wt_status
