DECL|enumerator|SHOW_ALL_UNTRACKED_FILES
DECL|enumerator|SHOW_NORMAL_UNTRACKED_FILES
DECL|enumerator|SHOW_NO_UNTRACKED_FILES
DECL|enumerator|WT_STATUS_CHANGED
DECL|enumerator|WT_STATUS_HEADER
DECL|enumerator|WT_STATUS_NOBRANCH
DECL|enumerator|WT_STATUS_UNTRACKED
DECL|enumerator|WT_STATUS_UPDATED
DECL|enum|color_wt_status
DECL|enum|untracked_status_type
DECL|macro|STATUS_H
DECL|member|amend
DECL|member|branch
DECL|member|commitable
DECL|member|fp
DECL|member|index_file
DECL|member|is_initial
DECL|member|nowarn
DECL|member|prefix
DECL|member|reference
DECL|member|untracked
DECL|member|verbose
DECL|member|workdir_dirty
DECL|member|workdir_untracked
DECL|struct|wt_status
