DECL|enumerator|FROM_CHERRY_PICK
DECL|enumerator|FROM_COMMIT
DECL|enumerator|FROM_MERGE
DECL|enumerator|SHOW_ALL_UNTRACKED_FILES
DECL|enumerator|SHOW_NORMAL_UNTRACKED_FILES
DECL|enumerator|SHOW_NO_UNTRACKED_FILES
DECL|enumerator|WT_STATUS_CHANGED
DECL|enumerator|WT_STATUS_HEADER
DECL|enumerator|WT_STATUS_LOCAL_BRANCH
DECL|enumerator|WT_STATUS_MAXSLOT
DECL|enumerator|WT_STATUS_NOBRANCH
DECL|enumerator|WT_STATUS_ONBRANCH
DECL|enumerator|WT_STATUS_REMOTE_BRANCH
DECL|enumerator|WT_STATUS_UNMERGED
DECL|enumerator|WT_STATUS_UNTRACKED
DECL|enumerator|WT_STATUS_UPDATED
DECL|enum|color_wt_status
DECL|enum|commit_whence
DECL|enum|untracked_status_type
DECL|macro|STATUS_H
DECL|member|amend
DECL|member|branch
DECL|member|change
DECL|member|color_palette
DECL|member|commitable
DECL|member|dirty_submodule
DECL|member|fp
DECL|member|head_path
DECL|member|ignore_submodule_arg
DECL|member|ignored
DECL|member|index_file
DECL|member|index_status
DECL|member|is_initial
DECL|member|new_submodule_commits
DECL|member|nowarn
DECL|member|null_termination
DECL|member|pathspec
DECL|member|prefix
DECL|member|reference
DECL|member|relative_paths
DECL|member|show_branch
DECL|member|show_ignored_files
DECL|member|show_untracked_files
DECL|member|stagemask
DECL|member|submodule_summary
DECL|member|untracked
DECL|member|use_color
DECL|member|verbose
DECL|member|whence
DECL|member|workdir_dirty
DECL|member|worktree_status
DECL|struct|wt_status
DECL|struct|wt_status_change_data
