DECL|function|buffer_is_binary
DECL|function|consume_one
DECL|function|ff_regexp
DECL|function|git_xmerge_config
DECL|function|parse_hunk_header
DECL|function|parse_num
DECL|function|process_diff
DECL|function|read_mmfile
DECL|function|trim_common_tail
DECL|function|xdi_diff
DECL|function|xdi_diff_hunks
DECL|function|xdi_diff_outf
DECL|function|xdiff_clear_find_func
DECL|function|xdiff_outf
DECL|function|xdiff_set_find_func
DECL|macro|FIRST_FEW_BYTES
DECL|member|array
DECL|member|consume
DECL|member|consume
DECL|member|consume_callback_data
DECL|member|consume_callback_data
DECL|member|negate
DECL|member|nr
DECL|member|re
DECL|member|remainder
DECL|struct|ff_reg
DECL|struct|ff_regs
DECL|struct|xdiff_emit_hunk_state
DECL|struct|xdiff_emit_state
DECL|variable|git_xmerge_style
