DECL|function|buffer_is_binary
DECL|function|consume_one
DECL|function|ff_regexp
DECL|function|parse_hunk_header
DECL|function|parse_num
DECL|function|read_mmfile
DECL|function|xdiff_outf
DECL|function|xdiff_set_find_func
DECL|macro|FIRST_FEW_BYTES
DECL|member|array
DECL|member|negate
DECL|member|nr
DECL|member|re
DECL|struct|ff_reg
DECL|struct|ff_regs
