DECL|function|buffer_copy_bytes
DECL|function|buffer_deinit
DECL|function|buffer_init
DECL|function|buffer_read_line
DECL|function|buffer_read_string
DECL|function|buffer_reset
DECL|function|buffer_skip_bytes
DECL|macro|COPY_BUFFER_LEN
DECL|macro|LINE_BUFFER_LEN
DECL|variable|infile
DECL|variable|line_buffer
