DECL|function|mark_init
DECL|function|next_blob_mark
DECL|function|repo_add
DECL|function|repo_clone_dir
DECL|function|repo_commit
DECL|function|repo_commit_root_dir
DECL|function|repo_copy
DECL|function|repo_delete
DECL|function|repo_diff
DECL|function|repo_diff_r
DECL|function|repo_dir_from_dirent
DECL|function|repo_dirent_is_dir
DECL|function|repo_dirent_name_cmp
DECL|function|repo_first_dirent
DECL|function|repo_git_add
DECL|function|repo_git_add_r
DECL|function|repo_init
DECL|function|repo_modify_path
DECL|function|repo_read_dirent
DECL|function|repo_read_path
DECL|function|repo_reset
DECL|function|repo_write_dirent
DECL|member|children
DECL|member|content_offset
DECL|member|entries
DECL|member|mode
DECL|member|name_offset
DECL|member|root_dir_offset
DECL|struct|repo_commit
DECL|struct|repo_dir
DECL|struct|repo_dirent
DECL|variable|active_commit
DECL|variable|mark
DECL|variable|path_stack
