DECL|function|node_cmp
DECL|function|node_value
DECL|function|pool_fetch
DECL|function|pool_intern
DECL|function|pool_print_seq
DECL|function|pool_print_seq_q
DECL|function|pool_reset
DECL|function|pool_tok_r
DECL|function|pool_tok_seq
DECL|member|children
DECL|member|offset
DECL|struct|node
DECL|variable|tree
