DECL|function|apply_one_window
DECL|function|apply_window_in_core
DECL|function|copyfrom_data
DECL|function|copyfrom_target
DECL|function|error_short_read
DECL|function|execute_one_instruction
DECL|function|parse_first_operand
DECL|function|parse_int
DECL|function|read_chunk
DECL|function|read_int
DECL|function|read_length
DECL|function|read_magic
DECL|function|read_offset
DECL|function|svndiff0_apply
DECL|function|window_release
DECL|function|write_strbuf
DECL|macro|INSN_COPYFROM_DATA
DECL|macro|INSN_COPYFROM_TARGET
DECL|macro|INSN_MASK
DECL|macro|OPERAND_MASK
DECL|macro|VLI_BITS_PER_DIGIT
DECL|macro|VLI_CONTINUE
DECL|macro|VLI_DIGIT_MASK
DECL|macro|WINDOW_INIT
DECL|member|data
DECL|member|instructions
DECL|member|out
DECL|struct|window
