DECL|function|apply_one_window
DECL|function|error_short_read
DECL|function|read_int
DECL|function|read_length
DECL|function|read_magic
DECL|function|read_offset
DECL|function|svndiff0_apply
DECL|macro|VLI_BITS_PER_DIGIT
DECL|macro|VLI_CONTINUE
DECL|macro|VLI_DIGIT_MASK
