DECL|macro|git_SHA1_Final
DECL|macro|git_SHA1_Init
DECL|macro|git_SHA1_Update
DECL|macro|git_SHA_CTX
DECL|member|H
DECL|member|W
DECL|member|lenW
DECL|member|sizeHi
DECL|member|sizeLo
DECL|typedef|moz_SHA_CTX
