DECL|function|die
DECL|function|erase_credential
DECL|function|get_credential
DECL|function|load_cred_funcs
DECL|function|main
DECL|function|match_attr
DECL|function|match_cred
DECL|function|read_credential
DECL|function|store_credential
DECL|function|utf8_to_utf16_dup
DECL|function|write_attr
DECL|function|write_item
DECL|function|xmalloc
DECL|function|xstrdup
DECL|macro|CRED_MAX_ATTRIBUTES
DECL|macro|CRED_PERSIST_LOCAL_MACHINE
DECL|macro|CRED_TYPE_GENERIC
DECL|member|AttributeCount
DECL|member|Attributes
DECL|member|Comment
DECL|member|CredentialBlob
DECL|member|CredentialBlobSize
DECL|member|Flags
DECL|member|Flags
DECL|member|Keyword
DECL|member|LastWritten
DECL|member|Persist
DECL|member|TargetAlias
DECL|member|TargetName
DECL|member|Type
DECL|member|UserName
DECL|member|Value
DECL|member|ValueSize
DECL|struct|_CREDENTIALW
DECL|struct|_CREDENTIAL_ATTRIBUTEW
DECL|typedef|CREDENTIALW
DECL|typedef|CREDENTIAL_ATTRIBUTEW
DECL|typedef|CredDeleteWT
DECL|typedef|CredEnumerateWT
DECL|typedef|CredFreeT
DECL|typedef|CredPackAuthenticationBufferWT
DECL|typedef|CredUnPackAuthenticationBufferWT
DECL|typedef|CredWriteWT
DECL|typedef|PCREDENTIALW
DECL|typedef|PCREDENTIAL_ATTRIBUTEW
DECL|variable|CredDeleteW
DECL|variable|CredEnumerateW
DECL|variable|CredFree
DECL|variable|CredPackAuthenticationBufferW
DECL|variable|CredUnPackAuthenticationBufferW
DECL|variable|CredWriteW
DECL|variable|advapi
DECL|variable|credui
DECL|variable|host
DECL|variable|password
DECL|variable|path
DECL|variable|protocol
DECL|variable|target
DECL|variable|target_buf
DECL|variable|username
DECL|variable|wusername
