DECL|function|convert_ascii_sha1
DECL|function|convert_binary_sha1
DECL|function|convert_commit
DECL|function|convert_date
DECL|function|convert_date_line
DECL|function|convert_entry
DECL|function|convert_mode
DECL|function|convert_tree
DECL|function|insert_new
DECL|function|lookup_entry
DECL|function|main
DECL|function|parse_oldstyle_date
DECL|function|write_subdirectory
DECL|macro|MAXOBJECTS
DECL|member|converted
DECL|member|new_sha1
DECL|member|old_sha1
DECL|struct|entry
DECL|variable|convert
DECL|variable|nr_convert
