DECL|macro|PATH_MAX
DECL|macro|_DIRENT_H_
DECL|macro|__MINGW_NOTHROW
DECL|member|d_ino
DECL|member|d_ino
DECL|member|d_name
DECL|member|d_name
DECL|member|d_namlen
DECL|member|d_namlen
DECL|member|d_reclen
DECL|member|d_reclen
DECL|member|dd_dir
DECL|member|dd_dir
DECL|member|dd_dta
DECL|member|dd_handle
DECL|member|dd_handle
DECL|member|dd_name
DECL|member|dd_name
DECL|member|dd_stat
DECL|member|dd_stat
DECL|struct|_wdirent
DECL|struct|dirent
DECL|typedef|DIR
DECL|typedef|_WDIR
