DECL|macro|F_OK
DECL|macro|R_OK
DECL|macro|STDERR_FILENO
DECL|macro|STDOUT_FILENO
DECL|macro|S_IEXEC
DECL|macro|S_IFBLK
DECL|macro|S_IFCHR
DECL|macro|S_IFDIR
DECL|macro|S_IFIFO
DECL|macro|S_IFMT
DECL|macro|S_IFREG
DECL|macro|S_IREAD
DECL|macro|S_IRUSR
DECL|macro|S_IRWXU
DECL|macro|S_ISDIR
DECL|macro|S_ISFIFO
DECL|macro|S_ISREG
DECL|macro|S_IWRITE
DECL|macro|S_IWUSR
DECL|macro|S_IXUSR
DECL|macro|W_OK
DECL|macro|X_OK
DECL|macro|_MODE_T_
DECL|macro|_OFF_T_
DECL|macro|_SSIZE_T_
DECL|macro|_S_IFBLK
DECL|macro|_S_IFCHR
DECL|macro|_S_IFDIR
DECL|macro|_S_IFIFO
DECL|macro|_S_IFMT
DECL|macro|_S_IFREG
DECL|macro|_S_IRUSR
DECL|macro|_S_ISDIR
DECL|macro|_S_IWUSR
DECL|macro|_S_IXUSR
DECL|macro|_UNISTD_
DECL|typedef|_mode_t
DECL|typedef|_off_t
DECL|typedef|_ssize_t
DECL|typedef|int16_t
DECL|typedef|int32_t
DECL|typedef|int64_t
DECL|typedef|int8_t
DECL|typedef|intmax_t
DECL|typedef|mode_t
DECL|typedef|off64_t
DECL|typedef|off_t
DECL|typedef|ssize_t
DECL|typedef|uint16_t
DECL|typedef|uint32_t
DECL|typedef|uint64_t
DECL|typedef|uint8_t
DECL|typedef|uintmax_t
