DECL|macro|git_SHA1_Final
DECL|macro|git_SHA1_Init
DECL|macro|git_SHA1_Update
DECL|macro|git_SHA_CTX
DECL|member|b
DECL|member|buf
DECL|member|cnt
DECL|member|hash
DECL|member|l
DECL|member|len
DECL|typedef|ppc_SHA_CTX
