DECL|function|git_CC_EVP_DecodeBlock
DECL|function|git_CC_EVP_EncodeBlock
DECL|macro|APPLE_LION_OR_NEWER
DECL|macro|EVP_DecodeBlock
DECL|macro|EVP_EncodeBlock
DECL|macro|EVP_md5
DECL|macro|HEADER_HMAC_H
DECL|macro|HEADER_SHA_H
DECL|macro|HMAC_CTX
DECL|macro|HMAC_CTX_cleanup
DECL|macro|HMAC_Final
DECL|macro|HMAC_Init
DECL|macro|HMAC_Update
DECL|macro|OPENSSL_NO_MD5
DECL|macro|TYPE_BOOL
DECL|macro|git_CC_error_check
