DECL|function|default_bswap64
DECL|function|default_swab32
DECL|function|git_bswap32
DECL|function|git_bswap64
DECL|function|git_bswap64
DECL|macro|__BIG_ENDIAN
DECL|macro|__BYTE_ORDER
DECL|macro|__LITTLE_ENDIAN
DECL|macro|bswap32
DECL|macro|bswap32
DECL|macro|bswap32
DECL|macro|bswap64
DECL|macro|bswap64
DECL|macro|bswap64
DECL|macro|htonl
DECL|macro|htonl
DECL|macro|htonll
DECL|macro|htonll
DECL|macro|htonll
DECL|macro|htonll
DECL|macro|htonll
DECL|macro|ntohl
DECL|macro|ntohl
DECL|macro|ntohll
DECL|macro|ntohll
DECL|macro|ntohll
DECL|macro|ntohll
DECL|macro|ntohll
