DECL|function|alarm
DECL|function|fchmod
DECL|function|fcntl
DECL|function|fork
DECL|function|fsync
DECL|function|getppid
DECL|function|getpwnam
DECL|function|getuid
DECL|function|git_ntohl
DECL|function|mingw_SSL_set_fd
DECL|function|mingw_SSL_set_rfd
DECL|function|mingw_SSL_set_wfd
DECL|function|mingw_mkdir
DECL|function|mingw_unlink
DECL|function|readlink
DECL|function|symlink
DECL|function|sync
DECL|function|waitpid
DECL|macro|DT_DIR
DECL|macro|DT_DIR
DECL|macro|DT_LNK
DECL|macro|DT_LNK
DECL|macro|DT_REG
DECL|macro|DT_REG
DECL|macro|DT_UNKNOWN
DECL|macro|DT_UNKNOWN
DECL|macro|FD_CLOEXEC
DECL|macro|F_GETFD
DECL|macro|F_SETFD
DECL|macro|ITIMER_REAL
DECL|macro|PATH_SEP
DECL|macro|POLLHUP
DECL|macro|POLLIN
DECL|macro|PRIuMAX
DECL|macro|SA_RESTART
DECL|macro|SIGALRM
DECL|macro|SIGCHLD
DECL|macro|SIGHUP
DECL|macro|SIGKILL
DECL|macro|SIGPIPE
DECL|macro|SIGQUIT
DECL|macro|SSL_set_fd
DECL|macro|SSL_set_rfd
DECL|macro|SSL_set_wfd
DECL|macro|S_IFLNK
DECL|macro|S_IRGRP
DECL|macro|S_IROTH
DECL|macro|S_ISGID
DECL|macro|S_ISLNK
DECL|macro|S_ISSOCK
DECL|macro|S_IWGRP
DECL|macro|S_IXGRP
DECL|macro|S_IXOTH
DECL|macro|WEXITSTATUS
DECL|macro|WIFEXITED
DECL|macro|WIFSIGNALED
DECL|macro|WTERMSIG
DECL|macro|_stati64
DECL|macro|connect
DECL|macro|dirent
DECL|macro|execvp
DECL|macro|exit
DECL|macro|fprintf
DECL|macro|fputs
DECL|macro|freeaddrinfo
DECL|macro|fstat
DECL|macro|getaddrinfo
DECL|macro|getcwd
DECL|macro|getenv
DECL|macro|gethostbyname
DECL|macro|getnameinfo
DECL|macro|getpagesize
DECL|macro|has_dos_drive_prefix
DECL|macro|hstrerror
DECL|macro|is_dir_sep
DECL|macro|lseek
DECL|macro|lstat
DECL|macro|main
DECL|macro|mkdir
DECL|macro|ntohl
DECL|macro|off_t
DECL|macro|open
DECL|macro|open_html
DECL|macro|printf
DECL|macro|readdir
DECL|macro|rename
DECL|macro|sigemptyset
DECL|macro|signal
DECL|macro|socket
DECL|macro|stat
DECL|macro|unlink
DECL|macro|utime
DECL|member|d_ino
DECL|member|d_name
DECL|member|d_namlen
DECL|member|d_reclen
DECL|member|d_type
DECL|member|events
DECL|member|fd
DECL|member|it_interval
DECL|member|it_value
DECL|member|pw_dir
DECL|member|pw_gecos
DECL|member|pw_name
DECL|member|revents
DECL|member|sa_flags
DECL|member|sa_handler
DECL|struct|itimerval
DECL|struct|mingw_dirent
DECL|struct|passwd
DECL|struct|pollfd
DECL|struct|sigaction
DECL|typedef|pid_t
DECL|typedef|sig_handler_t
