DECL|function|alarm
DECL|function|fchmod
DECL|function|fcntl
DECL|function|fork
DECL|function|fsync
DECL|function|getppid
DECL|function|getpwnam
DECL|function|getrlimit
DECL|function|getuid
DECL|function|git_ntohl
DECL|function|mingw_SSL_set_fd
DECL|function|mingw_SSL_set_rfd
DECL|function|mingw_SSL_set_wfd
DECL|function|mingw_find_last_dir_sep
DECL|function|mingw_mkdir
DECL|function|readlink
DECL|function|symlink
DECL|function|sync
DECL|macro|EAFNOSUPPORT
DECL|macro|ECONNABORTED
DECL|macro|EWOULDBLOCK
DECL|macro|FD_CLOEXEC
DECL|macro|F_GETFD
DECL|macro|F_SETFD
DECL|macro|HELP_COMMAND
DECL|macro|ITIMER_REAL
DECL|macro|PATH_SEP
DECL|macro|PRIuMAX
DECL|macro|RLIMIT_NOFILE
DECL|macro|SA_RESTART
DECL|macro|SHUT_WR
DECL|macro|SIGALRM
DECL|macro|SIGCHLD
DECL|macro|SIGHUP
DECL|macro|SIGKILL
DECL|macro|SIGPIPE
DECL|macro|SIGQUIT
DECL|macro|SSL_set_fd
DECL|macro|SSL_set_rfd
DECL|macro|SSL_set_wfd
DECL|macro|S_IFLNK
DECL|macro|S_IRGRP
DECL|macro|S_IROTH
DECL|macro|S_IRWXG
DECL|macro|S_IRWXO
DECL|macro|S_ISGID
DECL|macro|S_ISLNK
DECL|macro|S_ISSOCK
DECL|macro|S_ISUID
DECL|macro|S_ISVTX
DECL|macro|S_IWGRP
DECL|macro|S_IWOTH
DECL|macro|S_IXGRP
DECL|macro|S_IXOTH
DECL|macro|WEXITSTATUS
DECL|macro|WIFEXITED
DECL|macro|WIFSIGNALED
DECL|macro|WNOHANG
DECL|macro|WTERMSIG
DECL|macro|_stati64
DECL|macro|accept
DECL|macro|bind
DECL|macro|connect
DECL|macro|execv
DECL|macro|execvp
DECL|macro|exit
DECL|macro|find_last_dir_sep
DECL|macro|fopen
DECL|macro|fprintf
DECL|macro|fputs
DECL|macro|freeaddrinfo
DECL|macro|freopen
DECL|macro|fstat
DECL|macro|getaddrinfo
DECL|macro|getcwd
DECL|macro|getenv
DECL|macro|gethostbyname
DECL|macro|getnameinfo
DECL|macro|getpagesize
DECL|macro|has_dos_drive_prefix
DECL|macro|hstrerror
DECL|macro|is_dir_sep
DECL|macro|kill
DECL|macro|listen
DECL|macro|lseek
DECL|macro|lstat
DECL|macro|main
DECL|macro|mkdir
DECL|macro|ntohl
DECL|macro|off_t
DECL|macro|open
DECL|macro|open_html
DECL|macro|printf
DECL|macro|rename
DECL|macro|rmdir
DECL|macro|setsockopt
DECL|macro|shutdown
DECL|macro|sigemptyset
DECL|macro|signal
DECL|macro|socket
DECL|macro|stat
DECL|macro|unlink
DECL|macro|utime
DECL|macro|write
DECL|member|it_interval
DECL|member|it_value
DECL|member|pw_dir
DECL|member|pw_gecos
DECL|member|pw_name
DECL|member|rlim_cur
DECL|member|sa_flags
DECL|member|sa_handler
DECL|struct|itimerval
DECL|struct|passwd
DECL|struct|rlimit
DECL|struct|sigaction
DECL|typedef|pid_t
DECL|typedef|sig_handler_t
DECL|typedef|socklen_t
DECL|typedef|uid_t
