DECL|function|alarm
DECL|function|fchmod
DECL|function|fcntl
DECL|function|fork
DECL|function|fsync
DECL|function|getppid
DECL|function|getpwnam
DECL|function|getuid
DECL|function|link
DECL|function|mingw_mkdir
DECL|function|mingw_unlink
DECL|function|pipe
DECL|function|readlink
DECL|function|symlink
DECL|function|sync
DECL|function|waitpid
DECL|macro|FD_CLOEXEC
DECL|macro|F_GETFD
DECL|macro|F_SETFD
DECL|macro|ITIMER_REAL
DECL|macro|PATH_SEP
DECL|macro|POLLHUP
DECL|macro|POLLIN
DECL|macro|SA_RESTART
DECL|macro|SIGALRM
DECL|macro|SIGCHLD
DECL|macro|SIGHUP
DECL|macro|SIGKILL
DECL|macro|SIGPIPE
DECL|macro|SIGQUIT
DECL|macro|S_IFLNK
DECL|macro|S_IRGRP
DECL|macro|S_IROTH
DECL|macro|S_ISGID
DECL|macro|S_ISLNK
DECL|macro|S_ISSOCK
DECL|macro|S_IWGRP
DECL|macro|S_IXGRP
DECL|macro|S_IXOTH
DECL|macro|WEXITSTATUS
DECL|macro|WIFEXITED
DECL|macro|WIFSIGNALED
DECL|macro|getcwd
DECL|macro|has_dos_drive_prefix
DECL|macro|hstrerror
DECL|macro|is_dir_sep
DECL|macro|lstat
DECL|macro|mkdir
DECL|macro|open
DECL|macro|rename
DECL|macro|sigemptyset
DECL|macro|st_blocks
DECL|macro|unlink
DECL|member|events
DECL|member|fd
DECL|member|it_interval
DECL|member|it_value
DECL|member|pw_dir
DECL|member|pw_gecos
DECL|member|pw_name
DECL|member|revents
DECL|member|sa_flags
DECL|member|sa_handler
DECL|struct|itimerval
DECL|struct|passwd
DECL|struct|pollfd
DECL|struct|sigaction
DECL|typedef|pid_t
DECL|typedef|sig_handler_t
