DECL|function|getpwuid
DECL|function|gettimeofday
DECL|function|gmtime_r
DECL|function|is_timeval_eq
DECL|function|localtime_r
DECL|function|mingw_getcwd
DECL|function|mingw_open
DECL|function|mingw_rename
DECL|function|mingw_signal
DECL|function|mkstemp
DECL|function|poll
DECL|function|setitimer
DECL|function|sigaction
DECL|function|sleep
DECL|function|start_timer_thread
DECL|function|stop_timer_thread
DECL|function|ticktack
DECL|macro|getcwd
DECL|macro|open
DECL|macro|rename
DECL|macro|signal
DECL|variable|_CRT_fmode
DECL|variable|one_shot
DECL|variable|timer_event
DECL|variable|timer_fn
DECL|variable|timer_interval
DECL|variable|timer_thread
