DECL|function|ask_yes_no_if_possible
DECL|function|copy_environ
DECL|function|do_lstat
DECL|function|do_stat_internal
DECL|function|ensure_socket_initialization
DECL|function|env_compare
DECL|function|env_setenv
DECL|function|err_win_to_posix
DECL|function|filetime_to_hnsec
DECL|function|filetime_to_time_t
DECL|function|free_environ
DECL|function|free_path_split
DECL|function|freeaddrinfo_stub
DECL|function|get_path_split
DECL|function|getaddrinfo_stub
DECL|function|getenv_cs
DECL|function|getnameinfo_stub
DECL|function|getpass
DECL|function|getpwuid
DECL|function|gettimeofday
DECL|function|gmtime_r
DECL|function|is_dir_empty
DECL|function|is_file_in_use_error
DECL|function|is_timeval_eq
DECL|function|link
DECL|function|localtime_r
DECL|function|lookup_env
DECL|function|lookup_prog
DECL|function|make_augmented_environ
DECL|function|make_backslash_path
DECL|function|mingw_accept
DECL|function|mingw_bind
DECL|function|mingw_connect
DECL|function|mingw_execv
DECL|function|mingw_execve
DECL|function|mingw_execvp
DECL|function|mingw_fopen
DECL|function|mingw_freeaddrinfo
DECL|function|mingw_freopen
DECL|function|mingw_fstat
DECL|function|mingw_getaddrinfo
DECL|function|mingw_getcwd
DECL|function|mingw_getenv
DECL|function|mingw_gethostbyname
DECL|function|mingw_getnameinfo
DECL|function|mingw_getpagesize
DECL|function|mingw_kill
DECL|function|mingw_listen
DECL|function|mingw_lstat
DECL|function|mingw_open
DECL|function|mingw_open_html
DECL|function|mingw_rename
DECL|function|mingw_rmdir
DECL|function|mingw_setsockopt
DECL|function|mingw_shutdown
DECL|function|mingw_signal
DECL|function|mingw_socket
DECL|function|mingw_spawnve
DECL|function|mingw_spawnve_fd
DECL|function|mingw_spawnvpe
DECL|function|mingw_stat
DECL|function|mingw_unlink
DECL|function|mingw_utime
DECL|function|mingw_write
DECL|function|mkstemp
DECL|function|parse_interpreter
DECL|function|path_lookup
DECL|function|pipe
DECL|function|quote_arg
DECL|function|read_yes_no_answer
DECL|function|setitimer
DECL|function|sigaction
DECL|function|sleep
DECL|function|socket_cleanup
DECL|function|start_timer_thread
DECL|function|stop_timer_thread
DECL|function|ticktack
DECL|function|time_t_to_filetime
DECL|function|try_shell_exec
DECL|function|waitpid
DECL|macro|accept
DECL|macro|bind
DECL|macro|connect
DECL|macro|fopen
DECL|macro|freopen
DECL|macro|fstat
DECL|macro|getcwd
DECL|macro|getenv
DECL|macro|gethostbyname
DECL|macro|listen
DECL|macro|open
DECL|macro|rename
DECL|macro|rmdir
DECL|macro|setsockopt
DECL|macro|shutdown
DECL|macro|signal
DECL|macro|unlink
DECL|macro|write
DECL|member|next
DECL|member|pid
DECL|member|proc
DECL|struct|pinfo_t
DECL|variable|delay
DECL|variable|ipv6_dll
DECL|variable|ipv6_freeaddrinfo
DECL|variable|ipv6_getaddrinfo
DECL|variable|ipv6_getnameinfo
DECL|variable|one_shot
DECL|variable|pinfo
DECL|variable|pinfo_cs
DECL|variable|pinfo_t
DECL|variable|timer_event
DECL|variable|timer_fn
DECL|variable|timer_interval
DECL|variable|timer_thread
