DECL|function|strcasecmp
DECL|macro|ERROR
DECL|macro|NTDDI_VERSION
DECL|macro|WINVER
DECL|macro|_WIN32_IE
DECL|macro|_WIN32_WINDOWS
DECL|macro|_WIN32_WINNT
DECL|macro|__MSVC__HEAD
DECL|macro|__attribute__
DECL|macro|__inline__
DECL|macro|_stat64
DECL|macro|_stati64
DECL|macro|inline
DECL|macro|stat
DECL|macro|stat
DECL|macro|stat
DECL|macro|va_copy
DECL|member|st_atime
DECL|member|st_ctime
DECL|member|st_dev
DECL|member|st_gid
DECL|member|st_ino
DECL|member|st_mode
DECL|member|st_mtime
DECL|member|st_nlink
DECL|member|st_rdev
DECL|member|st_size
DECL|member|st_uid
DECL|struct|_stati64
