DECL|function|strcasecmp
DECL|macro|ERROR
DECL|macro|__MSVC__HEAD
DECL|macro|__attribute__
DECL|macro|__inline__
DECL|macro|ftruncate
DECL|macro|inline
DECL|macro|strncasecmp
DECL|macro|strtoll
DECL|macro|strtoull
