DECL|macro|PTR_INT_TYPE
DECL|macro|PTR_INT_TYPE
DECL|macro|_OBSTACK_H
DECL|macro|__BPTR_ALIGN
DECL|macro|__PTR_ALIGN
DECL|macro|__extension__
DECL|macro|obstack_1grow
DECL|macro|obstack_1grow
DECL|macro|obstack_1grow_fast
DECL|macro|obstack_alignment_mask
DECL|macro|obstack_alloc
DECL|macro|obstack_alloc
DECL|macro|obstack_base
DECL|macro|obstack_begin
DECL|macro|obstack_blank
DECL|macro|obstack_blank
DECL|macro|obstack_blank_fast
DECL|macro|obstack_chunk_size
DECL|macro|obstack_chunkfun
DECL|macro|obstack_copy
DECL|macro|obstack_copy
DECL|macro|obstack_copy0
DECL|macro|obstack_copy0
DECL|macro|obstack_empty_p
DECL|macro|obstack_empty_p
DECL|macro|obstack_finish
DECL|macro|obstack_finish
DECL|macro|obstack_free
DECL|macro|obstack_free
DECL|macro|obstack_freefun
DECL|macro|obstack_grow
DECL|macro|obstack_grow
DECL|macro|obstack_grow0
DECL|macro|obstack_grow0
DECL|macro|obstack_init
DECL|macro|obstack_int_grow
DECL|macro|obstack_int_grow
DECL|macro|obstack_int_grow_fast
DECL|macro|obstack_int_grow_fast
DECL|macro|obstack_make_room
DECL|macro|obstack_make_room
DECL|macro|obstack_memory_used
DECL|macro|obstack_next_free
DECL|macro|obstack_object_size
DECL|macro|obstack_object_size
DECL|macro|obstack_ptr_grow
DECL|macro|obstack_ptr_grow
DECL|macro|obstack_ptr_grow_fast
DECL|macro|obstack_ptr_grow_fast
DECL|macro|obstack_room
DECL|macro|obstack_room
DECL|macro|obstack_specify_allocation
DECL|macro|obstack_specify_allocation_with_arg
DECL|member|alignment_mask
DECL|member|alloc_failed
DECL|member|chunk
DECL|member|chunk_limit
DECL|member|chunk_size
DECL|member|chunkfun
DECL|member|contents
DECL|member|extra_arg
DECL|member|freefun
DECL|member|limit
DECL|member|maybe_empty_object
DECL|member|next_free
DECL|member|object_base
DECL|member|prev
DECL|member|temp
DECL|member|tempint
DECL|member|tempptr
DECL|member|use_extra_arg
DECL|struct|_obstack_chunk
DECL|struct|obstack
