DECL|enumerator|DEFAULT_ALIGNMENT
DECL|enumerator|DEFAULT_ROUNDING
DECL|function|_obstack_begin
DECL|function|_obstack_begin_1
DECL|function|_obstack_newchunk
DECL|function|obstack_free
DECL|function|print_and_abort
DECL|function|strong_alias
DECL|macro|CALL_CHUNKFUN
DECL|macro|CALL_FREEFUN
DECL|macro|COPYING_UNIT
DECL|macro|ELIDE_CODE
DECL|macro|OBSTACK_INTERFACE_VERSION
DECL|macro|_
DECL|macro|__attribute__
DECL|macro|obstack_exit_failure
DECL|macro|obstack_free
DECL|member|c
DECL|member|d
DECL|member|i
DECL|member|p
DECL|member|u
DECL|struct|fooalign
DECL|union|fooround
DECL|variable|_obstack_compat
DECL|variable|obstack_alloc_failed_handler
DECL|variable|obstack_exit_failure
