DECL|enumerator|after_dot
DECL|enumerator|anychar
DECL|enumerator|at_dot
DECL|enumerator|before_dot
DECL|enumerator|begbuf
DECL|enumerator|begline
DECL|enumerator|charset
DECL|enumerator|charset_not
DECL|enumerator|dummy_failure_jump
DECL|enumerator|duplicate
DECL|enumerator|endbuf
DECL|enumerator|endline
DECL|enumerator|exactn
DECL|enumerator|jump
DECL|enumerator|jump_n
DECL|enumerator|jump_past_alt
DECL|enumerator|maybe_pop_jump
DECL|enumerator|no_op
DECL|enumerator|notsyntaxspec
DECL|enumerator|notwordbound
DECL|enumerator|notwordchar
DECL|enumerator|on_failure_jump
DECL|enumerator|on_failure_keep_string_jump
DECL|enumerator|pop_failure_jump
DECL|enumerator|push_dummy_failure
DECL|enumerator|set_number_at
DECL|enumerator|start_memory
DECL|enumerator|stop_memory
DECL|enumerator|succeed_n
DECL|enumerator|syntaxspec
DECL|enumerator|wordbeg
DECL|enumerator|wordbound
DECL|enumerator|wordchar
DECL|enumerator|wordend
DECL|function|alt_match_null_string_p
DECL|function|at_begline_loc_p
DECL|function|at_endline_loc_p
DECL|function|bcmp_translate
DECL|function|common_op_match_null_string_p
DECL|function|compile_range
DECL|function|extract_number
DECL|function|extract_number_and_incr
DECL|function|group_in_compile_stack
DECL|function|group_match_null_string_p
DECL|function|init_syntax_once
DECL|function|insert_op1
DECL|function|insert_op2
DECL|function|print_compiled_pattern
DECL|function|print_double_string
DECL|function|print_fastmap
DECL|function|print_partial_compiled_pattern
DECL|function|re_comp
DECL|function|re_compile_fastmap
DECL|function|re_compile_pattern
DECL|function|re_exec
DECL|function|re_match
DECL|function|re_match_2
DECL|function|re_search
DECL|function|re_search_2
DECL|function|re_set_registers
DECL|function|re_set_syntax
DECL|function|regcomp
DECL|function|regerror
DECL|function|regex_compile
DECL|function|regexec
DECL|function|regfree
DECL|function|store_op1
DECL|function|store_op2
DECL|macro|AT_STRINGS_BEG
DECL|macro|AT_STRINGS_END
DECL|macro|AT_WORD_BOUNDARY
DECL|macro|BUF_PUSH
DECL|macro|BUF_PUSH_2
DECL|macro|BUF_PUSH_3
DECL|macro|BYTEWIDTH
DECL|macro|CHAR_CLASS_MAX_LENGTH
DECL|macro|CHAR_SET_SIZE
DECL|macro|COMPILE_STACK_EMPTY
DECL|macro|COMPILE_STACK_FULL
DECL|macro|COMPILE_STACK_TOP
DECL|macro|DEBUG_POP
DECL|macro|DEBUG_POP
DECL|macro|DEBUG_PRINT1
DECL|macro|DEBUG_PRINT1
DECL|macro|DEBUG_PRINT2
DECL|macro|DEBUG_PRINT2
DECL|macro|DEBUG_PRINT3
DECL|macro|DEBUG_PRINT3
DECL|macro|DEBUG_PRINT4
DECL|macro|DEBUG_PRINT4
DECL|macro|DEBUG_PRINT_COMPILED_PATTERN
DECL|macro|DEBUG_PRINT_COMPILED_PATTERN
DECL|macro|DEBUG_PRINT_DOUBLE_STRING
DECL|macro|DEBUG_PRINT_DOUBLE_STRING
DECL|macro|DEBUG_PUSH
DECL|macro|DEBUG_PUSH
DECL|macro|DEBUG_STATEMENT
DECL|macro|DEBUG_STATEMENT
DECL|macro|DOUBLE_FAIL_STACK
DECL|macro|EVER_MATCHED_SOMETHING
DECL|macro|EXTEND_BUFFER
DECL|macro|EXTRACT_NUMBER
DECL|macro|EXTRACT_NUMBER
DECL|macro|EXTRACT_NUMBER
DECL|macro|EXTRACT_NUMBER_AND_INCR
DECL|macro|EXTRACT_NUMBER_AND_INCR
DECL|macro|EXTRACT_NUMBER_AND_INCR
DECL|macro|FAIL_STACK_EMPTY
DECL|macro|FAIL_STACK_FULL
DECL|macro|FAIL_STACK_PTR_EMPTY
DECL|macro|FAIL_STACK_TOP
DECL|macro|FIRST_STRING_P
DECL|macro|FREE_VAR
DECL|macro|FREE_VARIABLES
DECL|macro|FREE_VARIABLES
DECL|macro|GET_BUFFER_SPACE
DECL|macro|GET_UNSIGNED_NUMBER
DECL|macro|INIT_BUF_SIZE
DECL|macro|INIT_COMPILE_STACK_SIZE
DECL|macro|INIT_FAILURE_ALLOC
DECL|macro|INIT_FAIL_STACK
DECL|macro|INSERT_JUMP
DECL|macro|INSERT_JUMP2
DECL|macro|ISALNUM
DECL|macro|ISALPHA
DECL|macro|ISBLANK
DECL|macro|ISBLANK
DECL|macro|ISCNTRL
DECL|macro|ISDIGIT
DECL|macro|ISGRAPH
DECL|macro|ISGRAPH
DECL|macro|ISLOWER
DECL|macro|ISPRINT
DECL|macro|ISPUNCT
DECL|macro|ISSPACE
DECL|macro|ISUPPER
DECL|macro|ISXDIGIT
DECL|macro|IS_ACTIVE
DECL|macro|IS_CHAR_CLASS
DECL|macro|MATCHED_SOMETHING
DECL|macro|MATCHING_IN_FIRST_STRING
DECL|macro|MATCH_NULL_UNSET_VALUE
DECL|macro|MAX
DECL|macro|MAX_BUF_SIZE
DECL|macro|MAX_FAILURE_ITEMS
DECL|macro|MAX_REGNUM
DECL|macro|MIN
DECL|macro|NO_HIGHEST_ACTIVE_REG
DECL|macro|NO_LOWEST_ACTIVE_REG
DECL|macro|NULL
DECL|macro|NUM_FAILURE_ITEMS
DECL|macro|NUM_NONREG_ITEMS
DECL|macro|NUM_NONREG_ITEMS
DECL|macro|NUM_REG_ITEMS
DECL|macro|PATFETCH
DECL|macro|PATFETCH_RAW
DECL|macro|PATUNFETCH
DECL|macro|POINTER_TO_OFFSET
DECL|macro|POP_FAILURE_ITEM
DECL|macro|POP_FAILURE_POINT
DECL|macro|PREFETCH
DECL|macro|PUSH_FAILURE_ITEM
DECL|macro|PUSH_FAILURE_POINT
DECL|macro|PUSH_PATTERN_OP
DECL|macro|REGEX_ALLOCATE
DECL|macro|REGEX_ALLOCATE
DECL|macro|REGEX_REALLOCATE
DECL|macro|REGEX_REALLOCATE
DECL|macro|REGEX_TALLOC
DECL|macro|REG_MATCH_NULL_STRING_P
DECL|macro|REG_UNSET
DECL|macro|REG_UNSET_VALUE
DECL|macro|REMAINING_AVAIL_SLOTS
DECL|macro|RETALLOC
DECL|macro|SET_LIST_BIT
DECL|macro|SET_REGS_MATCHED
DECL|macro|SIGN_EXTEND_CHAR
DECL|macro|SIGN_EXTEND_CHAR
DECL|macro|SIGN_EXTEND_CHAR
DECL|macro|STORE_JUMP
DECL|macro|STORE_JUMP2
DECL|macro|STORE_NUMBER
DECL|macro|STORE_NUMBER_AND_INCR
DECL|macro|STREQ
DECL|macro|SYNTAX
DECL|macro|Sword
DECL|macro|TALLOC
DECL|macro|TRANSLATE
DECL|macro|WORDCHAR_P
DECL|macro|_GNU_SOURCE
DECL|macro|alloca
DECL|macro|assert
DECL|macro|assert
DECL|macro|bcmp
DECL|macro|bcopy
DECL|macro|bzero
DECL|macro|false
DECL|macro|isascii
DECL|macro|true
DECL|member|avail
DECL|member|avail
DECL|member|begalt_offset
DECL|member|bits
DECL|member|ever_matched_something
DECL|member|fixup_alt_jump
DECL|member|inner_group_offset
DECL|member|is_active
DECL|member|laststart_offset
DECL|member|match_null_string_p
DECL|member|matched_something
DECL|member|regnum
DECL|member|size
DECL|member|size
DECL|member|stack
DECL|member|stack
DECL|member|word
DECL|typedef|boolean
DECL|typedef|compile_stack_elt_t
DECL|typedef|compile_stack_type
DECL|typedef|fail_stack_elt_t
DECL|typedef|fail_stack_type
DECL|typedef|pattern_offset_t
DECL|typedef|re_opcode_t
DECL|typedef|register_info_type
DECL|typedef|regnum_t
DECL|variable|debug
DECL|variable|re_comp_buf
DECL|variable|re_error_msg
DECL|variable|re_max_failures
DECL|variable|re_syntax_options
DECL|variable|re_syntax_table
