DECL|enumerator|REG_BADBR
DECL|enumerator|REG_BADPAT
DECL|enumerator|REG_BADRPT
DECL|enumerator|REG_EBRACE
DECL|enumerator|REG_EBRACK
DECL|enumerator|REG_ECOLLATE
DECL|enumerator|REG_ECTYPE
DECL|enumerator|REG_EEND
DECL|enumerator|REG_EESCAPE
DECL|enumerator|REG_EPAREN
DECL|enumerator|REG_ERANGE
DECL|enumerator|REG_ERPAREN
DECL|enumerator|REG_ESIZE
DECL|enumerator|REG_ESPACE
DECL|enumerator|REG_ESUBREG
DECL|enumerator|REG_NOERROR
DECL|enumerator|REG_NOMATCH
DECL|macro|REGS_FIXED
DECL|macro|REGS_REALLOCATE
DECL|macro|REGS_UNALLOCATED
DECL|macro|REG_EXTENDED
DECL|macro|REG_ICASE
DECL|macro|REG_NEWLINE
DECL|macro|REG_NOSUB
DECL|macro|REG_NOTBOL
DECL|macro|REG_NOTEOL
DECL|macro|RE_BACKSLASH_ESCAPE_IN_LISTS
DECL|macro|RE_BK_PLUS_QM
DECL|macro|RE_CHAR_CLASSES
DECL|macro|RE_CONTEXT_INDEP_ANCHORS
DECL|macro|RE_CONTEXT_INDEP_OPS
DECL|macro|RE_CONTEXT_INVALID_OPS
DECL|macro|RE_DOT_NEWLINE
DECL|macro|RE_DOT_NOT_NULL
DECL|macro|RE_DUP_MAX
DECL|macro|RE_DUP_MAX
DECL|macro|RE_EXACTN_VALUE
DECL|macro|RE_HAT_LISTS_NOT_NEWLINE
DECL|macro|RE_INTERVALS
DECL|macro|RE_LIMITED_OPS
DECL|macro|RE_NEWLINE_ALT
DECL|macro|RE_NO_BK_BRACES
DECL|macro|RE_NO_BK_PARENS
DECL|macro|RE_NO_BK_REFS
DECL|macro|RE_NO_BK_VBAR
DECL|macro|RE_NO_EMPTY_RANGES
DECL|macro|RE_NREGS
DECL|macro|RE_SYNTAX_AWK
DECL|macro|RE_SYNTAX_ED
DECL|macro|RE_SYNTAX_EGREP
DECL|macro|RE_SYNTAX_EMACS
DECL|macro|RE_SYNTAX_GREP
DECL|macro|RE_SYNTAX_POSIX_AWK
DECL|macro|RE_SYNTAX_POSIX_BASIC
DECL|macro|RE_SYNTAX_POSIX_EGREP
DECL|macro|RE_SYNTAX_POSIX_EXTENDED
DECL|macro|RE_SYNTAX_POSIX_MINIMAL_BASIC
DECL|macro|RE_SYNTAX_POSIX_MINIMAL_EXTENDED
DECL|macro|RE_SYNTAX_SED
DECL|macro|RE_UNMATCHED_RIGHT_PAREN_ORD
DECL|macro|_RE_ARGS
DECL|macro|_RE_ARGS
DECL|macro|_RE_SYNTAX_POSIX_COMMON
DECL|macro|__REGEXP_LIBRARY_H__
DECL|member|allocated
DECL|member|buffer
DECL|member|can_be_null
DECL|member|end
DECL|member|fastmap
DECL|member|fastmap_accurate
DECL|member|newline_anchor
DECL|member|no_sub
DECL|member|not_bol
DECL|member|not_eol
DECL|member|num_regs
DECL|member|re_nsub
DECL|member|regs_allocated
DECL|member|rm_eo
DECL|member|rm_so
DECL|member|start
DECL|member|syntax
DECL|member|translate
DECL|member|used
DECL|struct|re_pattern_buffer
DECL|struct|re_registers
DECL|typedef|reg_errcode_t
DECL|typedef|reg_syntax_t
DECL|typedef|regex_t
DECL|typedef|regmatch_t
DECL|typedef|regoff_t
