DECL|enumerator|BRACKET
DECL|enumerator|ESCAPE
DECL|enumerator|TEXT
DECL|function|_pioinfo
DECL|function|console_thread
DECL|function|die_lasterr
DECL|function|duplicate_handle
DECL|function|erase_in_line
DECL|function|init_sizeof_ioinfo
DECL|function|is_console
DECL|function|set_attr
DECL|function|set_console_attr
DECL|function|swap_osfhnd
DECL|function|warn_if_raster_font
DECL|function|winansi_exit
DECL|function|winansi_get_osfhandle
DECL|function|winansi_init
DECL|function|write_console
DECL|macro|BACKGROUND_ALL
DECL|macro|BUFFER_SIZE
DECL|macro|FDEV
DECL|macro|FOREGROUND_ALL
DECL|macro|IOINFO_ARRAY_ELTS
DECL|macro|IOINFO_L2E
DECL|macro|MAX_PARAMS
DECL|macro|NOGDI
DECL|member|FaceName
DECL|member|FontFamily
DECL|member|FontWeight
DECL|member|cbSize
DECL|member|dwFontSize
DECL|member|nFont
DECL|member|osfhnd
DECL|member|osflags
DECL|struct|_CONSOLE_FONT_INFOEX
DECL|typedef|CONSOLE_FONT_INFOEX
DECL|typedef|PCONSOLE_FONT_INFOEX
DECL|typedef|PGETCURRENTCONSOLEFONTEX
DECL|typedef|ioinfo
DECL|variable|attr
DECL|variable|console
DECL|variable|hconsole1
DECL|variable|hconsole2
DECL|variable|hread
DECL|variable|hthread
DECL|variable|hwrite
DECL|variable|negative
DECL|variable|non_ascii_used
DECL|variable|plain_attr
DECL|variable|sizeof_ioinfo
