DECL|function|ansi_emulate
DECL|function|check_truetype_font
DECL|function|erase_in_line
DECL|function|is_console
DECL|function|print_font_warning
DECL|function|set_attr
DECL|function|set_console_attr
DECL|function|winansi_fprintf
DECL|function|winansi_fputs
DECL|function|winansi_printf
DECL|function|winansi_vfprintf
DECL|function|write_console
DECL|macro|BACKGROUND_ALL
DECL|macro|FOREGROUND_ALL
DECL|macro|NOGDI
DECL|macro|fprintf
DECL|macro|fputs
DECL|macro|printf
DECL|macro|vfprintf
DECL|member|FaceName
DECL|member|FontFamily
DECL|member|FontWeight
DECL|member|cbSize
DECL|member|dwFontSize
DECL|member|nFont
DECL|struct|_CONSOLE_FONT_INFOEX
DECL|typedef|CONSOLE_FONT_INFOEX
DECL|typedef|PCONSOLE_FONT_INFOEX
DECL|typedef|PGETCURRENTCONSOLEFONTEX
DECL|variable|attr
DECL|variable|console
DECL|variable|last_stream
DECL|variable|negative
DECL|variable|plain_attr
