DECL|function|credential_clear
DECL|function|credential_init
DECL|function|credential_read
DECL|function|credential_write
DECL|function|credential_write_item
DECL|function|die_errno
DECL|function|error
DECL|function|keyring_erase
DECL|function|keyring_get
DECL|function|keyring_object
DECL|function|keyring_store
DECL|function|main
DECL|function|usage
DECL|function|warning
DECL|function|xstrdup
DECL|macro|CREDENTIAL_INIT
DECL|macro|CREDENTIAL_OP_END
DECL|member|host
DECL|member|name
DECL|member|op
DECL|member|password
DECL|member|path
DECL|member|port
DECL|member|protocol
DECL|member|username
DECL|struct|credential
DECL|struct|credential_operation
DECL|typedef|credential_op_cb
DECL|variable|credential_helper_ops
