DECL|function|credential_clear
DECL|function|credential_init
DECL|function|credential_read
DECL|function|credential_write
DECL|function|credential_write_item
DECL|function|gnome_keyring_result_to_message
DECL|function|keyring_erase
DECL|function|keyring_get
DECL|function|keyring_object
DECL|function|keyring_store
DECL|function|main
DECL|function|usage
DECL|macro|CREDENTIAL_INIT
DECL|macro|CREDENTIAL_OP_END
DECL|macro|GNOME_KEYRING_DEFAULT
DECL|macro|GNOME_KEYRING_RESULT_NO_MATCH
DECL|macro|gnome_keyring_memory_alloc
DECL|macro|gnome_keyring_memory_free
DECL|macro|gnome_keyring_memory_strdup
DECL|member|host
DECL|member|name
DECL|member|op
DECL|member|password
DECL|member|path
DECL|member|port
DECL|member|protocol
DECL|member|username
DECL|struct|credential
DECL|struct|credential_operation
DECL|typedef|credential_op_cb
DECL|variable|credential_helper_ops
