DECL|enumerator|PEEL_BROKEN
DECL|enumerator|PEEL_INVALID
DECL|enumerator|PEEL_IS_SYMREF
DECL|enumerator|PEEL_NON_TAG
DECL|enumerator|PEEL_PEELED
DECL|enumerator|REF_TRANSACTION_CLOSED
DECL|enumerator|REF_TRANSACTION_OPEN
DECL|enum|peel_status
DECL|enum|ref_transaction_state
DECL|macro|REFS_REFS_INTERNAL_H
DECL|macro|REF_DELETING
DECL|macro|REF_HAVE_NEW
DECL|macro|REF_HAVE_OLD
DECL|macro|REF_ISPRUNING
DECL|macro|REF_NEEDS_COMMIT
DECL|member|alloc
DECL|member|flags
DECL|member|lock
DECL|member|msg
DECL|member|new_sha1
DECL|member|nr
DECL|member|old_sha1
DECL|member|refname
DECL|member|state
DECL|member|type
DECL|member|updates
DECL|struct|ref_transaction
DECL|struct|ref_update
