DECL|function|add_config
DECL|function|add_files
DECL|function|add_files_to_cache
DECL|function|cmd_add
DECL|function|edit_patch
DECL|function|fix_unmerged_status
DECL|function|ignore_removal_cb
DECL|function|interactive_add
DECL|function|prune_directory
DECL|function|refresh
DECL|function|run_add_interactive
DECL|function|treat_gitlinks
DECL|function|update_callback
DECL|function|update_files_in_cache
DECL|function|validate_pathspec
DECL|function|warn_pathless_add
DECL|macro|ADDREMOVE_DEFAULT
DECL|macro|WARN_IMPLICIT_DOT
DECL|member|add_errors
DECL|member|flags
DECL|member|implicit_dot
DECL|member|implicit_dot_len
DECL|struct|update_callback_data
DECL|variable|add_interactive
DECL|variable|addremove
DECL|variable|addremove_explicit
DECL|variable|builtin_add_options
DECL|variable|builtin_add_usage
DECL|variable|edit_interactive
DECL|variable|ignore_add_errors
DECL|variable|ignore_error
DECL|variable|ignore_missing
DECL|variable|ignored_too
DECL|variable|intent_to_add
DECL|variable|lock_file
DECL|variable|option_with_implicit_dot
DECL|variable|patch_interactive
DECL|variable|refresh_only
DECL|variable|short_option_with_implicit_dot
DECL|variable|show_only
DECL|variable|take_worktree_changes
DECL|variable|verbose
