DECL|enumerator|PATCH_FORMAT_MBOX
DECL|enumerator|PATCH_FORMAT_UNKNOWN
DECL|enum|patch_format
DECL|function|am_destroy
DECL|function|am_in_progress
DECL|function|am_load
DECL|function|am_next
DECL|function|am_path
DECL|function|am_run
DECL|function|am_setup
DECL|function|am_state_init
DECL|function|am_state_release
DECL|function|cmd_am
DECL|function|detect_patch_format
DECL|function|is_mail
DECL|function|parse_opt_patchformat
DECL|function|read_state_file
DECL|function|split_mail
DECL|function|split_mail_mbox
DECL|function|strbuf_getline_crlf
DECL|member|cur
DECL|member|dir
DECL|member|last
DECL|member|prec
DECL|struct|am_state
