DECL|enumerator|KEEP_FALSE
DECL|enumerator|KEEP_NON_PATCH
DECL|enumerator|KEEP_TRUE
DECL|enumerator|PATCH_FORMAT_HG
DECL|enumerator|PATCH_FORMAT_MBOX
DECL|enumerator|PATCH_FORMAT_STGIT
DECL|enumerator|PATCH_FORMAT_STGIT_SERIES
DECL|enumerator|PATCH_FORMAT_UNKNOWN
DECL|enumerator|RESUME_ABORT
DECL|enumerator|RESUME_APPLY
DECL|enumerator|RESUME_FALSE
DECL|enumerator|RESUME_RESOLVED
DECL|enumerator|RESUME_SKIP
DECL|enumerator|SCISSORS_FALSE
DECL|enumerator|SCISSORS_TRUE
DECL|enumerator|SCISSORS_UNSET
DECL|enum|keep_type
DECL|enum|patch_format
DECL|enum|resume_mode
DECL|enum|scissors_type
DECL|function|am_abort
DECL|function|am_destroy
DECL|function|am_in_progress
DECL|function|am_load
DECL|function|am_next
DECL|function|am_path
DECL|function|am_rerere_clear
DECL|function|am_resolve
DECL|function|am_run
DECL|function|am_setup
DECL|function|am_skip
DECL|function|am_state_init
DECL|function|am_state_release
DECL|function|build_fake_ancestor
DECL|function|clean_index
DECL|function|cmd_am
DECL|function|copy_notes_for_rebase
DECL|function|detect_patch_format
DECL|function|die_user_resolve
DECL|function|do_commit
DECL|function|do_interactive
DECL|function|fall_back_threeway
DECL|function|fast_forward_to
DECL|function|get_commit_info
DECL|function|get_mail_commit_sha1
DECL|function|git_am_config
DECL|function|hg_patch_to_mail
DECL|function|index_has_changes
DECL|function|is_empty_file
DECL|function|is_mail
DECL|function|linelen
DECL|function|msgnum
DECL|function|parse_mail
DECL|function|parse_mail_rebase
DECL|function|parse_opt_patchformat
DECL|function|read_author_script
DECL|function|read_commit_msg
DECL|function|read_shell_var
DECL|function|read_state_file
DECL|function|refresh_and_write_cache
DECL|function|run_apply
DECL|function|run_applypatch_msg_hook
DECL|function|run_post_rewrite_hook
DECL|function|safe_to_abort
DECL|function|say
DECL|function|split_mail
DECL|function|split_mail_conv
DECL|function|split_mail_mbox
DECL|function|split_mail_stgit_series
DECL|function|stgit_patch_to_mail
DECL|function|str_isspace
DECL|function|strbuf_getline_crlf
DECL|function|validate_resume_state
DECL|function|write_author_script
DECL|function|write_commit_msg
DECL|function|write_commit_patch
DECL|function|write_index_patch
DECL|member|allow_rerere_autoupdate
DECL|member|author_date
DECL|member|author_email
DECL|member|author_name
DECL|member|committer_date_is_author_date
DECL|member|cur
DECL|member|dir
DECL|member|git_apply_opts
DECL|member|ignore_date
DECL|member|interactive
DECL|member|keep
DECL|member|last
DECL|member|message_id
DECL|member|msg
DECL|member|msg_len
DECL|member|orig_commit
DECL|member|prec
DECL|member|quiet
DECL|member|rebasing
DECL|member|resolvemsg
DECL|member|scissors
DECL|member|sign_commit
DECL|member|signoff
DECL|member|threeway
DECL|member|utf8
DECL|struct|am_state
DECL|typedef|mail_conv_fn
