DECL|enumerator|PATCH_FORMAT_MBOX
DECL|enumerator|PATCH_FORMAT_UNKNOWN
DECL|enumerator|RESUME_APPLY
DECL|enumerator|RESUME_FALSE
DECL|enumerator|RESUME_RESOLVED
DECL|enumerator|RESUME_SKIP
DECL|enum|patch_format
DECL|enum|resume_mode
DECL|function|am_destroy
DECL|function|am_in_progress
DECL|function|am_load
DECL|function|am_next
DECL|function|am_path
DECL|function|am_resolve
DECL|function|am_run
DECL|function|am_setup
DECL|function|am_skip
DECL|function|am_state_init
DECL|function|am_state_release
DECL|function|clean_index
DECL|function|cmd_am
DECL|function|detect_patch_format
DECL|function|do_commit
DECL|function|fast_forward_to
DECL|function|index_has_changes
DECL|function|is_empty_file
DECL|function|is_mail
DECL|function|linelen
DECL|function|msgnum
DECL|function|parse_mail
DECL|function|parse_opt_patchformat
DECL|function|read_author_script
DECL|function|read_commit_msg
DECL|function|read_shell_var
DECL|function|read_state_file
DECL|function|refresh_and_write_cache
DECL|function|run_apply
DECL|function|split_mail
DECL|function|split_mail_mbox
DECL|function|strbuf_getline_crlf
DECL|function|validate_resume_state
DECL|function|write_author_script
DECL|function|write_commit_msg
DECL|member|author_date
DECL|member|author_email
DECL|member|author_name
DECL|member|cur
DECL|member|dir
DECL|member|last
DECL|member|msg
DECL|member|msg_len
DECL|member|prec
DECL|struct|am_state
