DECL|function|add_blame_entry
DECL|function|add_prefix
DECL|function|append_merge_parents
DECL|function|append_parent
DECL|function|assign_blame
DECL|function|blame_chunk
DECL|function|blame_chunk_cb
DECL|function|blame_copy_callback
DECL|function|blame_merge
DECL|function|blame_move_callback
DECL|function|blame_sort
DECL|function|cmd_blame
DECL|function|coalesce
DECL|function|commit_info_destroy
DECL|function|commit_info_init
DECL|function|compare_blame_final
DECL|function|compare_blame_suspect
DECL|function|compare_commits_by_reverse_commit_date
DECL|function|copy_split_if_better
DECL|function|decref_split
DECL|function|diff_hunks
DECL|function|distribute_blame
DECL|function|drop_origin_blob
DECL|function|dup_entry
DECL|function|emit_one_suspect_detail
DECL|function|emit_other
DECL|function|emit_porcelain
DECL|function|emit_porcelain_details
DECL|function|ent_score
DECL|function|fake_working_tree_commit
DECL|function|fill_blob_sha1_and_mode
DECL|function|fill_origin_blob
DECL|function|filter_small
DECL|function|find_alignment
DECL|function|find_copy_in_blob
DECL|function|find_copy_in_parent
DECL|function|find_move_in_parent
DECL|function|find_origin
DECL|function|find_rename
DECL|function|first_scapegoat
DECL|function|format_time
DECL|function|found_guilty_entry
DECL|function|get_ac_line
DECL|function|get_commit_info
DECL|function|get_next_blame
DECL|function|get_next_line
DECL|function|get_origin
DECL|function|git_blame_config
DECL|function|handle_split
DECL|function|handle_split_cb
DECL|function|make_origin
DECL|function|nth_line
DECL|function|nth_line_cb
DECL|function|num_scapegoats
DECL|function|origin_decref
DECL|function|origin_incref
DECL|function|output
DECL|function|parse_score
DECL|function|pass_blame
DECL|function|pass_blame_to_parent
DECL|function|pass_whole_blame
DECL|function|prepare_final
DECL|function|prepare_initial
DECL|function|prepare_lines
DECL|function|queue_blames
DECL|function|read_ancestry
DECL|function|reverse_blame
DECL|function|sanity_check_refcnt
DECL|function|set_commit_buffer_from_strbuf
DECL|function|set_next_blame
DECL|function|setup_blame_list
DECL|function|split_blame
DECL|function|split_overlap
DECL|function|textconv_object
DECL|function|update_auto_abbrev
DECL|function|verify_working_tree_path
DECL|function|write_filename_info
DECL|macro|BLAME_DEFAULT_COPY_SCORE
DECL|macro|BLAME_DEFAULT_MOVE_SCORE
DECL|macro|DEBUG
DECL|macro|MAXSG
DECL|macro|METAINFO_SHOWN
DECL|macro|MORE_THAN_ONE_PATH
DECL|macro|OUTPUT_ANNOTATE_COMPAT
DECL|macro|OUTPUT_LINE_PORCELAIN
DECL|macro|OUTPUT_LONG_OBJECT_NAME
DECL|macro|OUTPUT_NO_AUTHOR
DECL|macro|OUTPUT_PORCELAIN
DECL|macro|OUTPUT_RAW_TIMESTAMP
DECL|macro|OUTPUT_SHOW_EMAIL
DECL|macro|OUTPUT_SHOW_NAME
DECL|macro|OUTPUT_SHOW_NUMBER
DECL|macro|OUTPUT_SHOW_SCORE
DECL|macro|PICKAXE_BLAME_COPY
DECL|macro|PICKAXE_BLAME_COPY_HARDER
DECL|macro|PICKAXE_BLAME_COPY_HARDEST
DECL|macro|PICKAXE_BLAME_MOVE
DECL|member|author
DECL|member|author_mail
DECL|member|author_time
DECL|member|author_tz
DECL|member|blob_sha1
DECL|member|commit
DECL|member|commits
DECL|member|committer
DECL|member|committer_mail
DECL|member|committer_time
DECL|member|committer_tz
DECL|member|dstq
DECL|member|ent
DECL|member|ent
DECL|member|ent
DECL|member|file
DECL|member|final
DECL|member|final_buf
DECL|member|final_buf_size
DECL|member|guilty
DECL|member|lineno
DECL|member|lno
DECL|member|mode
DECL|member|next
DECL|member|next
DECL|member|num_lines
DECL|member|num_lines
DECL|member|offset
DECL|member|parent
DECL|member|parent
DECL|member|path
DECL|member|path
DECL|member|plno
DECL|member|previous
DECL|member|refcnt
DECL|member|revs
DECL|member|s_lno
DECL|member|sb
DECL|member|score
DECL|member|split
DECL|member|split
DECL|member|srcq
DECL|member|summary
DECL|member|suspect
DECL|member|suspects
DECL|member|tlno
DECL|struct|blame_chunk_cb_data
DECL|struct|blame_entry
DECL|struct|blame_list
DECL|struct|commit_info
DECL|struct|handle_split_cb_data
DECL|struct|origin
DECL|struct|scoreboard
DECL|variable|abbrev
DECL|variable|blame_copy_score
DECL|variable|blame_date_mode
DECL|variable|blame_date_width
DECL|variable|blame_move_score
DECL|variable|blame_opt_usage
DECL|variable|blame_usage
DECL|variable|blank_boundary
DECL|variable|incremental
DECL|variable|longest_author
DECL|variable|longest_file
DECL|variable|mailmap
DECL|variable|max_digits
DECL|variable|max_orig_digits
DECL|variable|max_score_digits
DECL|variable|no_whole_file_rename
DECL|variable|num_commits
DECL|variable|num_get_patch
DECL|variable|num_read_blob
DECL|variable|reverse
DECL|variable|show_root
DECL|variable|xdl_opts
