DECL|function|batch_objects
DECL|function|batch_one_object
DECL|function|batch_option_callback
DECL|function|cat_one_file
DECL|function|cmd_cat_file
DECL|function|expand_atom
DECL|function|expand_format
DECL|function|git_cat_file_config
DECL|function|is_atom
DECL|function|print_object_or_die
DECL|member|delta_base_sha1
DECL|member|disk_size
DECL|member|enabled
DECL|member|format
DECL|member|info
DECL|member|mark_query
DECL|member|print_contents
DECL|member|rest
DECL|member|sha1
DECL|member|size
DECL|member|split_on_whitespace
DECL|member|type
DECL|struct|batch_options
DECL|struct|expand_data
DECL|variable|cat_file_usage
