DECL|function|batch_objects
DECL|function|batch_one_object
DECL|function|batch_option_callback
DECL|function|cat_one_file
DECL|function|cmd_cat_file
DECL|function|git_cat_file_config
DECL|function|print_object_or_die
DECL|member|enabled
DECL|member|print_contents
DECL|struct|batch_options
DECL|variable|cat_file_usage
