DECL|function|check_ref_format_branch
DECL|function|cmd_check_ref_format
DECL|function|collapse_slashes
DECL|function|refname_format_print
DECL|macro|REFNAME_ALLOW_ONELEVEL
DECL|macro|REFNAME_REFSPEC_PATTERN
DECL|variable|builtin_check_ref_format_usage
