DECL|function|add_pending_uninteresting_ref
DECL|function|check_all_stages
DECL|function|check_stage
DECL|function|check_tracking_name
DECL|function|checkout_merged
DECL|function|checkout_paths
DECL|function|checkout_stage
DECL|function|clear_commit_marks_from_one_ref
DECL|function|cmd_checkout
DECL|function|describe_detached_head
DECL|function|describe_one_orphan
DECL|function|detach_advice
DECL|function|git_checkout_config
DECL|function|interactive_checkout
DECL|function|merge_working_tree
DECL|function|orphaned_commit_warning
DECL|function|parse_branchname_arg
DECL|function|post_checkout_hook
DECL|function|read_tree_some
DECL|function|report_tracking
DECL|function|reset_tree
DECL|function|setup_branch_path
DECL|function|show_local_changes
DECL|function|skip_same_name
DECL|function|suggest_reattach
DECL|function|switch_branches
DECL|function|unique_tracking_name
DECL|function|update_refs_for_switch
DECL|function|update_some
DECL|macro|ORPHAN_CUTOFF
DECL|member|branch_exists
DECL|member|commit
DECL|member|diff_options
DECL|member|force
DECL|member|force_detach
DECL|member|merge
DECL|member|name
DECL|member|name
DECL|member|new_branch
DECL|member|new_branch_force
DECL|member|new_branch_log
DECL|member|new_orphan_branch
DECL|member|path
DECL|member|quiet
DECL|member|remote
DECL|member|track
DECL|member|unique
DECL|member|writeout_error
DECL|member|writeout_stage
DECL|struct|branch_info
DECL|struct|checkout_opts
DECL|struct|tracking_name_data
DECL|variable|checkout_usage
