DECL|function|check_ignore
DECL|function|check_ignore_stdin_paths
DECL|function|cmd_check_ignore
DECL|function|output_exclude
DECL|variable|check_ignore_options
DECL|variable|check_ignore_usage
DECL|variable|nul_term_line
DECL|variable|quiet
DECL|variable|stdin_paths
DECL|variable|verbose
