DECL|function|add_pending_uninteresting_ref
DECL|function|check_linked_checkout
DECL|function|check_linked_checkouts
DECL|function|check_stage
DECL|function|check_stages
DECL|function|check_tracking_name
DECL|function|checkout_branch
DECL|function|checkout_merged
DECL|function|checkout_paths
DECL|function|checkout_stage
DECL|function|cmd_checkout
DECL|function|describe_detached_head
DECL|function|describe_one_orphan
DECL|function|git_checkout_config
DECL|function|merge_working_tree
DECL|function|orphaned_commit_warning
DECL|function|parse_branchname_arg
DECL|function|post_checkout_hook
DECL|function|prepare_linked_checkout
DECL|function|read_tree_some
DECL|function|remove_junk
DECL|function|remove_junk_on_signal
DECL|function|report_tracking
DECL|function|reset_tree
DECL|function|setup_branch_path
DECL|function|show_local_changes
DECL|function|skip_same_name
DECL|function|suggest_reattach
DECL|function|switch_branches
DECL|function|switch_unborn_to_new_branch
DECL|function|unique_tracking_name
DECL|function|update_refs_for_switch
DECL|function|update_some
DECL|macro|ORPHAN_CUTOFF
DECL|member|branch_exists
DECL|member|checkout
DECL|member|commit
DECL|member|diff_options
DECL|member|dst_ref
DECL|member|dst_sha1
DECL|member|force
DECL|member|force_detach
DECL|member|ignore_other_worktrees
DECL|member|ignore_skipworktree
DECL|member|merge
DECL|member|name
DECL|member|new_branch
DECL|member|new_branch_force
DECL|member|new_branch_log
DECL|member|new_orphan_branch
DECL|member|new_worktree
DECL|member|new_worktree_mode
DECL|member|overwrite_ignore
DECL|member|patch_mode
DECL|member|path
DECL|member|pathspec
DECL|member|prefix
DECL|member|quiet
DECL|member|saved_argv
DECL|member|source_tree
DECL|member|src_ref
DECL|member|track
DECL|member|unique
DECL|member|writeout_stage
DECL|struct|branch_info
DECL|struct|checkout_opts
DECL|struct|tracking_name_data
DECL|variable|checkout_usage
DECL|variable|is_junk
DECL|variable|junk_git_dir
DECL|variable|junk_pid
DECL|variable|junk_work_tree
