DECL|function|cmd_clean
DECL|function|exclude_cb
DECL|function|git_clean_config
DECL|function|interactive_main_loop
DECL|function|remove_dirs
DECL|variable|builtin_clean_usage
DECL|variable|del_list
DECL|variable|force
DECL|variable|interactive
DECL|variable|msg_remove
DECL|variable|msg_skip_git_dir
DECL|variable|msg_warn_remove_failed
DECL|variable|msg_would_remove
DECL|variable|msg_would_skip_git_dir
