DECL|enumerator|CLEAN_COLOR_ERROR
DECL|enumerator|CLEAN_COLOR_HEADER
DECL|enumerator|CLEAN_COLOR_HELP
DECL|enumerator|CLEAN_COLOR_PLAIN
DECL|enumerator|CLEAN_COLOR_PROMPT
DECL|enumerator|CLEAN_COLOR_RESET
DECL|enumerator|MENU_STUFF_TYPE_MENU_ITEM
DECL|enumerator|MENU_STUFF_TYPE_STRING_LIST
DECL|enum|color_clean
DECL|enum|menu_stuff_type
DECL|function|clean_cmd
DECL|function|clean_get_color
DECL|function|clean_print_color
DECL|function|cmd_clean
DECL|function|exclude_cb
DECL|function|filter_by_patterns_cmd
DECL|function|git_clean_config
DECL|function|help_cmd
DECL|function|interactive_main_loop
DECL|function|list_and_choose
DECL|function|parse_choice
DECL|function|parse_clean_color_slot
DECL|function|pretty_print_dels
DECL|function|pretty_print_menus
DECL|function|print_highlight_menu_stuff
DECL|function|prompt_help_cmd
DECL|function|quit_cmd
DECL|function|remove_dirs
DECL|macro|MENU_OPTS_IMMEDIATE
DECL|macro|MENU_OPTS_LIST_ONLY
DECL|macro|MENU_OPTS_SINGLETON
DECL|macro|MENU_RETURN_NO_LOOP
DECL|member|flags
DECL|member|fn
DECL|member|header
DECL|member|hotkey
DECL|member|nr
DECL|member|prompt
DECL|member|selected
DECL|member|stuff
DECL|member|title
DECL|member|type
DECL|struct|menu_item
DECL|struct|menu_opts
DECL|struct|menu_stuff
DECL|variable|builtin_clean_usage
DECL|variable|clean_colors
DECL|variable|clean_use_color
DECL|variable|colopts
DECL|variable|del_list
DECL|variable|force
DECL|variable|interactive
DECL|variable|msg_remove
DECL|variable|msg_skip_git_dir
DECL|variable|msg_warn_remove_failed
DECL|variable|msg_would_remove
DECL|variable|msg_would_skip_git_dir
