DECL|enumerator|CLEANUP_ALL
DECL|enumerator|CLEANUP_NONE
DECL|enumerator|CLEANUP_SPACE
DECL|enumerator|COMMIT_AS_IS
DECL|enumerator|COMMIT_NORMAL
DECL|enumerator|COMMIT_PARTIAL
DECL|enumerator|STATUS_FORMAT_LONG
DECL|enumerator|STATUS_FORMAT_PORCELAIN
DECL|enumerator|STATUS_FORMAT_SHORT
DECL|function|add_remove_files
DECL|function|cmd_commit
DECL|function|cmd_status
DECL|function|commit_index_files
DECL|function|create_base_index
DECL|function|cut_ident_timestamp_part
DECL|function|determine_author_info
DECL|function|determine_whence
DECL|function|dry_run_commit
DECL|function|ends_rfc2822_footer
DECL|function|find_author_by_nickname
DECL|function|git_commit_config
DECL|function|git_status_config
DECL|function|handle_untracked_files_arg
DECL|function|is_a_merge
DECL|function|list_paths
DECL|function|message_is_empty
DECL|function|opt_parse_m
DECL|function|parse_and_validate_options
DECL|function|parse_status_slot
DECL|function|prepare_index
DECL|function|prepare_to_commit
DECL|function|print_summary
DECL|function|read_commit_message
DECL|function|refresh_cache_or_die
DECL|function|rollback_index_files
DECL|function|run_rewrite_hook
DECL|function|run_status
DECL|function|whence_s
DECL|variable|all
DECL|variable|allow_empty
DECL|variable|allow_empty_message
DECL|variable|also
DECL|variable|amend
DECL|variable|author_message
DECL|variable|author_message_buffer
DECL|variable|builtin_commit_options
DECL|variable|builtin_commit_usage
DECL|variable|builtin_status_usage
DECL|variable|cleanup_arg
DECL|variable|cleanup_mode
DECL|variable|commit_editmsg
DECL|variable|commit_style
DECL|variable|dry_run
DECL|variable|edit_flag
DECL|variable|edit_message
DECL|variable|empty_amend_advice
DECL|variable|empty_cherry_pick_advice
DECL|variable|false_lock
DECL|variable|fixup_message
DECL|variable|force_author
DECL|variable|force_date
DECL|variable|head_sha1
DECL|variable|ignore_submodule_arg
DECL|variable|implicit_ident_advice
DECL|variable|include_status
DECL|variable|index_lock
DECL|variable|initial_commit
DECL|variable|interactive
DECL|variable|logfile
DECL|variable|message
DECL|variable|no_post_rewrite
DECL|variable|no_verify
DECL|variable|null_termination
DECL|variable|only
DECL|variable|only_include_assumed
DECL|variable|patch_interactive
DECL|variable|post_rewrite_hook
DECL|variable|quiet
DECL|variable|renew_authorship
DECL|variable|show_ignored_in_status
DECL|variable|sign_off_header
DECL|variable|signoff
DECL|variable|squash_message
DECL|variable|status_format
DECL|variable|status_show_branch
DECL|variable|template_file
DECL|variable|untracked_files_arg
DECL|variable|use_editor
DECL|variable|use_message
DECL|variable|use_message_buffer
DECL|variable|verbose
DECL|variable|whence
