DECL|function|cmd_diff_tree
DECL|function|diff_tree_commit_sha1
DECL|function|diff_tree_stdin
DECL|function|diff_tree_tweak_rev
DECL|function|stdin_diff_commit
DECL|function|stdin_diff_trees
DECL|variable|diff_tree_usage
DECL|variable|log_tree_opt
