DECL|enumerator|ABORT
DECL|enumerator|DROP
DECL|enumerator|ERROR
DECL|enumerator|REWRITE
DECL|enumerator|STRIP
DECL|enumerator|VERBATIM
DECL|enumerator|WARN
DECL|function|cmd_fast_export
DECL|function|export_marks
DECL|function|find_encoding
DECL|function|get_object_mark
DECL|function|get_tags_and_duplicates
DECL|function|handle_commit
DECL|function|handle_object
DECL|function|handle_tag
DECL|function|handle_tags_and_duplicates
DECL|function|handle_tail
DECL|function|has_unshown_parent
DECL|function|import_marks
DECL|function|mark_next_object
DECL|function|mark_object
DECL|function|mark_to_ptr
DECL|function|parse_opt_signed_tag_mode
DECL|function|parse_opt_tag_of_filtered_mode
DECL|function|ptr_to_mark
DECL|function|show_filemodify
DECL|function|show_progress
DECL|variable|fake_missing_tagger
DECL|variable|fast_export_usage
DECL|variable|idnums
DECL|variable|last_idnum
DECL|variable|no_data
DECL|variable|progress
DECL|variable|signed_tag_mode
DECL|variable|tag_of_filtered_mode
