DECL|enumerator|ABORT
DECL|enumerator|DROP
DECL|enumerator|ERROR
DECL|enumerator|REWRITE
DECL|enumerator|STRIP
DECL|enumerator|VERBATIM
DECL|enumerator|WARN
DECL|enumerator|WARN_STRIP
DECL|function|anonymize_blob
DECL|function|anonymize_commit_message
DECL|function|anonymize_ident
DECL|function|anonymize_ident_line
DECL|function|anonymize_mem
DECL|function|anonymize_path
DECL|function|anonymize_path_component
DECL|function|anonymize_ref_component
DECL|function|anonymize_refname
DECL|function|anonymize_sha1
DECL|function|anonymize_tag
DECL|function|anonymized_entry_cmp
DECL|function|cmd_fast_export
DECL|function|depth_first
DECL|function|export_blob
DECL|function|export_marks
DECL|function|find_encoding
DECL|function|generate_fake_sha1
DECL|function|get_commit
DECL|function|get_object_mark
DECL|function|get_tags_and_duplicates
DECL|function|handle_commit
DECL|function|handle_deletes
DECL|function|handle_tag
DECL|function|handle_tags_and_duplicates
DECL|function|handle_tail
DECL|function|has_unshown_parent
DECL|function|import_marks
DECL|function|mark_next_object
DECL|function|mark_object
DECL|function|mark_to_ptr
DECL|function|parse_opt_signed_tag_mode
DECL|function|parse_opt_tag_of_filtered_mode
DECL|function|print_path
DECL|function|print_path_1
DECL|function|ptr_to_mark
DECL|function|show_filemodify
DECL|function|show_progress
DECL|member|anon
DECL|member|anon_len
DECL|member|hash
DECL|member|orig
DECL|member|orig_len
DECL|struct|anonymized_entry
DECL|variable|anonymize
DECL|variable|extra_refs
DECL|variable|fake_missing_tagger
DECL|variable|fast_export_usage
DECL|variable|full_tree
DECL|variable|idents
DECL|variable|idnums
DECL|variable|last_idnum
DECL|variable|no_data
DECL|variable|progress
DECL|variable|refspecs
DECL|variable|refspecs_nr
DECL|variable|signed_tag_mode
DECL|variable|tag_of_filtered_mode
DECL|variable|use_done_feature
