DECL|enumerator|ACK
DECL|enumerator|ACK_common
DECL|enumerator|ACK_continue
DECL|enumerator|ACK_ready
DECL|enumerator|NAK
DECL|enum|ack_type
DECL|function|clear_marks
DECL|function|cmd_fetch_pack
DECL|function|consume_shallow_list
DECL|function|do_fetch_pack
DECL|function|everything_local
DECL|function|fetch_pack
DECL|function|fetch_pack_config
DECL|function|fetch_pack_setup
DECL|function|filter_refs
DECL|function|find_common
DECL|function|get_ack
DECL|function|get_pack
DECL|function|get_rev
DECL|function|insert_alternate_refs
DECL|function|insert_one_alternate_ref
DECL|function|mark_common
DECL|function|mark_complete
DECL|function|mark_recent_complete_commits
DECL|function|next_flush
DECL|function|remove_duplicates
DECL|function|rev_list_insert_ref
DECL|function|rev_list_push
DECL|function|send_request
DECL|function|sideband_demux
DECL|function|write_one_shallow
DECL|function|write_shallow_commits
DECL|macro|COMMON
DECL|macro|COMMON_REF
DECL|macro|COMPLETE
DECL|macro|INITIAL_FLUSH
DECL|macro|LARGE_FLUSH
DECL|macro|MAX_IN_VAIN
DECL|macro|PIPESAFE_FLUSH
DECL|macro|POPPED
DECL|macro|SEEN
DECL|member|count
DECL|member|out
DECL|member|use_pack_protocol
DECL|struct|write_shallow_data
DECL|variable|args
DECL|variable|complete
DECL|variable|fetch_fsck_objects
DECL|variable|fetch_pack_usage
DECL|variable|fetch_unpack_limit
DECL|variable|lock
DECL|variable|marked
DECL|variable|multi_ack
DECL|variable|no_done
DECL|variable|non_common_revs
DECL|variable|prefer_ofs_delta
DECL|variable|rev_list
DECL|variable|transfer_fsck_objects
DECL|variable|transfer_unpack_limit
DECL|variable|unpack_limit
DECL|variable|use_sideband
