DECL|function|add_branch_desc
DECL|function|add_merge_parent
DECL|function|cmd_fmt_merge_msg
DECL|function|find_merge_parent
DECL|function|find_merge_parents
DECL|function|fmt_merge_msg
DECL|function|fmt_merge_msg_config
DECL|function|fmt_merge_msg_sigs
DECL|function|fmt_merge_msg_title
DECL|function|fmt_tag_signature
DECL|function|handle_line
DECL|function|init_src_data
DECL|function|print_joined
DECL|function|shortlog
DECL|member|alloc
DECL|member|branch
DECL|member|commit
DECL|member|generic
DECL|member|given
DECL|member|head_status
DECL|member|is_local_branch
DECL|member|item
DECL|member|nr
DECL|member|r_branch
DECL|member|sha1
DECL|member|tag
DECL|member|used
DECL|struct|merge_parent
DECL|struct|merge_parents
DECL|struct|origin_data
DECL|struct|src_data
DECL|variable|fmt_merge_msg_usage
DECL|variable|origins
DECL|variable|srcs
DECL|variable|use_branch_desc
