DECL|function|append_to_list
DECL|function|cmd_fmt_merge_msg
DECL|function|find_in_list
DECL|function|fmt_merge_msg
DECL|function|fmt_merge_msg_config
DECL|function|free_list
DECL|function|handle_line
DECL|function|print_joined
DECL|function|shortlog
DECL|member|alloc
DECL|member|branch
DECL|member|generic
DECL|member|head_status
DECL|member|list
DECL|member|nr
DECL|member|payload
DECL|member|r_branch
DECL|member|tag
DECL|struct|list
DECL|struct|src_data
DECL|variable|fmt_merge_msg_usage
DECL|variable|merge_summary
DECL|variable|origins
DECL|variable|srcs
