DECL|function|check_connectivity
DECL|function|check_object
DECL|function|check_reachable_object
DECL|function|check_unreachable_object
DECL|function|cmd_fsck
DECL|function|fsck_cache_tree
DECL|function|fsck_config
DECL|function|fsck_dir
DECL|function|fsck_error_func
DECL|function|fsck_handle_ref
DECL|function|fsck_handle_reflog
DECL|function|fsck_handle_reflog_ent
DECL|function|fsck_handle_reflog_sha1
DECL|function|fsck_head_link
DECL|function|fsck_obj
DECL|function|fsck_obj_buffer
DECL|function|fsck_object_dir
DECL|function|fsck_sha1
DECL|function|get_default_heads
DECL|function|is_loose_object_file
DECL|function|mark_object
DECL|function|mark_object_reachable
DECL|function|mark_used
DECL|function|objerror
DECL|function|objreport
DECL|function|traverse_one_object
DECL|function|traverse_reachable
DECL|macro|ERROR_OBJECT
DECL|macro|ERROR_PACK
DECL|macro|ERROR_REACHABLE
DECL|macro|HAS_OBJ
DECL|macro|REACHABLE
DECL|macro|SEEN
DECL|variable|check_full
DECL|variable|check_strict
DECL|variable|connectivity_only
DECL|variable|default_refs
DECL|variable|errors_found
DECL|variable|fsck_obj_options
DECL|variable|fsck_opts
DECL|variable|fsck_usage
DECL|variable|fsck_walk_options
DECL|variable|head_oid
DECL|variable|head_points_at
DECL|variable|include_reflogs
DECL|variable|keep_cache_objects
DECL|variable|pending
DECL|variable|show_dangling
DECL|variable|show_progress
DECL|variable|show_root
DECL|variable|show_tags
DECL|variable|show_unreachable
DECL|variable|verbose
DECL|variable|write_lost_and_found
