DECL|function|add_repack_all_option
DECL|function|cmd_gc
DECL|function|gc_before_repack
DECL|function|gc_config
DECL|function|lock_repo_for_gc
DECL|function|need_to_gc
DECL|function|remove_pidfile
DECL|function|remove_pidfile_on_signal
DECL|function|too_many_loose_objects
DECL|function|too_many_packs
DECL|macro|FAILED_RUN
DECL|variable|aggressive_window
DECL|variable|builtin_gc_usage
DECL|variable|detach_auto
DECL|variable|gc_auto_pack_limit
DECL|variable|gc_auto_threshold
DECL|variable|pack_refs
DECL|variable|pack_refs_cmd
DECL|variable|pidfile
DECL|variable|prune
DECL|variable|prune_expire
DECL|variable|prune_reflogs
DECL|variable|reflog
DECL|variable|repack
DECL|variable|rerere
