DECL|enumerator|HELP_FORMAT_INFO
DECL|enumerator|HELP_FORMAT_MAN
DECL|enumerator|HELP_FORMAT_NONE
DECL|enumerator|HELP_FORMAT_WEB
DECL|enum|help_format
DECL|function|add_man_viewer
DECL|function|add_man_viewer_cmd
DECL|function|add_man_viewer_info
DECL|function|add_man_viewer_path
DECL|function|check_emacsclient_version
DECL|function|cmd_help
DECL|function|cmd_to_page
DECL|function|do_add_man_viewer_info
DECL|function|exec_man_cmd
DECL|function|exec_man_konqueror
DECL|function|exec_man_man
DECL|function|exec_viewer
DECL|function|exec_woman_emacs
DECL|function|get_html_page_path
DECL|function|get_man_viewer_info
DECL|function|git_help_config
DECL|function|is_git_command
DECL|function|list_common_cmds_help
DECL|function|open_html
DECL|function|parse_help_format
DECL|function|prepend
DECL|function|setup_man_path
DECL|function|show_html_page
DECL|function|show_info_page
DECL|function|show_man_page
DECL|function|supported_man_viewer
DECL|member|info
DECL|member|name
DECL|member|name
DECL|member|next
DECL|member|next
DECL|struct|man_viewer_info_list
DECL|struct|man_viewer_list
DECL|variable|builtin_help_options
DECL|variable|builtin_help_usage
DECL|variable|colopts
DECL|variable|help_format
DECL|variable|main_cmds
DECL|variable|man_viewer_info_list
DECL|variable|man_viewer_list
DECL|variable|other_cmds
DECL|variable|show_all
