DECL|function|append_obj_to_pack
DECL|function|bad_object
DECL|function|check_object
DECL|function|check_objects
DECL|function|cmd_index_pack
DECL|function|cmp_uint32
DECL|function|compare_delta_bases
DECL|function|compare_delta_entry
DECL|function|delta_pos_compare
DECL|function|fill
DECL|function|final
DECL|function|find_delta
DECL|function|find_delta_children
DECL|function|find_unresolved_deltas
DECL|function|fix_unresolved_deltas
DECL|function|flush
DECL|function|free_base_data
DECL|function|get_base_data
DECL|function|get_data_from_pack
DECL|function|git_index_pack_config
DECL|function|is_delta_type
DECL|function|link_base_data
DECL|function|mark_link
DECL|function|open_pack_file
DECL|function|parse_pack_header
DECL|function|parse_pack_objects
DECL|function|prune_base_data
DECL|function|read_idx_option
DECL|function|read_v2_anomalous_offsets
DECL|function|resolve_delta
DECL|function|sha1_object
DECL|function|show_pack_info
DECL|function|unlink_base_data
DECL|function|unpack_entry_data
DECL|function|unpack_raw_entry
DECL|function|use
DECL|function|write_compressed
DECL|macro|FLAG_CHECKED
DECL|macro|FLAG_LINK
DECL|macro|UNION_BASE_SZ
DECL|member|base
DECL|member|base
DECL|member|base_object_no
DECL|member|child
DECL|member|data
DECL|member|delta_depth
DECL|member|hdr_size
DECL|member|idx
DECL|member|obj
DECL|member|obj_no
DECL|member|offset
DECL|member|real_type
DECL|member|sha1
DECL|member|size
DECL|member|size
DECL|member|type
DECL|struct|base_data
DECL|struct|delta_entry
DECL|struct|object_entry
DECL|union|delta_base
DECL|variable|base_cache
DECL|variable|base_cache_used
DECL|variable|consumed_bytes
DECL|variable|deepest_delta
DECL|variable|deltas
DECL|variable|from_stdin
DECL|variable|index_pack_usage
DECL|variable|input_buffer
DECL|variable|input_crc32
DECL|variable|input_ctx
DECL|variable|input_fd
DECL|variable|input_len
DECL|variable|input_offset
DECL|variable|nr_deltas
DECL|variable|nr_objects
DECL|variable|nr_resolved_deltas
DECL|variable|objects
DECL|variable|output_fd
DECL|variable|pack_fd
DECL|variable|progress
DECL|variable|strict
DECL|variable|verbose
