DECL|enumerator|TE_BASE64
DECL|enumerator|TE_DONTCARE
DECL|enumerator|TE_QP
DECL|enumerator|TYPE_OTHER
DECL|enumerator|TYPE_TEXT
DECL|function|check_header
DECL|function|cleanup_space
DECL|function|cleanup_subject
DECL|function|cmd_mailinfo
DECL|function|cmp_header
DECL|function|convert_to_utf8
DECL|function|decode_b_segment
DECL|function|decode_header
DECL|function|decode_header_bq
DECL|function|decode_q_segment
DECL|function|decode_transfer_encoding
DECL|function|find_boundary
DECL|function|get_sane_name
DECL|function|git_mailinfo_config
DECL|function|guess_charset
DECL|function|handle_body
DECL|function|handle_boundary
DECL|function|handle_commit_msg
DECL|function|handle_content_transfer_encoding
DECL|function|handle_content_type
DECL|function|handle_filter
DECL|function|handle_from
DECL|function|handle_header
DECL|function|handle_info
DECL|function|handle_patch
DECL|function|is_multipart_boundary
DECL|function|is_rfc2822_header
DECL|function|is_scissors_line
DECL|function|mailinfo
DECL|function|output_header_lines
DECL|function|parse_bogus_from
DECL|function|patchbreak
DECL|function|read_one_header_line
DECL|function|slurp_attr
DECL|macro|MAX_BOUNDARIES
DECL|macro|MAX_HDR_PARSED
DECL|variable|charset
DECL|variable|cmitmsg
DECL|variable|content
DECL|variable|content_top
DECL|variable|email
DECL|variable|fin
DECL|variable|fout
DECL|variable|header
DECL|variable|keep_non_patch_brackets_in_subject
DECL|variable|keep_subject
DECL|variable|line
DECL|variable|mailinfo_usage
DECL|variable|message_type
DECL|variable|metainfo_charset
DECL|variable|name
DECL|variable|p_hdr_data
DECL|variable|patch_lines
DECL|variable|patchfile
DECL|variable|s_hdr_data
DECL|variable|transfer_encoding
DECL|variable|use_inbody_headers
DECL|variable|use_scissors
