DECL|enumerator|TE_BASE64
DECL|enumerator|TE_DONTCARE
DECL|enumerator|TE_QP
DECL|function|check_header
DECL|function|cleanup_space
DECL|function|cleanup_subject
DECL|function|clear_mailinfo
DECL|function|cmd_mailinfo
DECL|function|cmp_header
DECL|function|convert_to_utf8
DECL|function|decode_b_segment
DECL|function|decode_header
DECL|function|decode_q_segment
DECL|function|decode_transfer_encoding
DECL|function|find_boundary
DECL|function|get_sane_name
DECL|function|git_mailinfo_config
DECL|function|handle_body
DECL|function|handle_boundary
DECL|function|handle_commit_msg
DECL|function|handle_content_transfer_encoding
DECL|function|handle_content_type
DECL|function|handle_filter
DECL|function|handle_from
DECL|function|handle_header
DECL|function|handle_info
DECL|function|handle_message_id
DECL|function|handle_patch
DECL|function|is_format_patch_separator
DECL|function|is_multipart_boundary
DECL|function|is_rfc2822_header
DECL|function|is_scissors_line
DECL|function|mailinfo
DECL|function|output_header_lines
DECL|function|parse_bogus_from
DECL|function|patchbreak
DECL|function|read_one_header_line
DECL|function|setup_mailinfo
DECL|function|slurp_attr
DECL|macro|MAX_BOUNDARIES
DECL|macro|MAX_HDR_PARSED
DECL|member|add_message_id
DECL|member|email
DECL|member|filter_stage
DECL|member|header_stage
DECL|member|input
DECL|member|keep_non_patch_brackets_in_subject
DECL|member|keep_subject
DECL|member|message_id
DECL|member|name
DECL|member|output
DECL|member|patch_lines
DECL|member|use_inbody_headers
DECL|member|use_scissors
DECL|struct|mailinfo
DECL|variable|charset
DECL|variable|cmitmsg
DECL|variable|content
DECL|variable|content_top
DECL|variable|header
DECL|variable|mailinfo_usage
DECL|variable|metainfo_charset
DECL|variable|p_hdr_data
DECL|variable|patchfile
DECL|variable|s_hdr_data
DECL|variable|transfer_encoding
