DECL|function|add_one_commit
DECL|function|cmd_merge_base
DECL|function|collect_one_reflog_ent
DECL|function|get_commit_reference
DECL|function|handle_fork_point
DECL|function|handle_independent
DECL|function|handle_is_ancestor
DECL|function|handle_octopus
DECL|function|show_merge_base
DECL|member|alloc
DECL|member|commit
DECL|member|initial
DECL|member|nr
DECL|struct|rev_collect
DECL|variable|merge_base_usage
