DECL|function|add_merge_entry
DECL|function|both_empty
DECL|function|cmd_merge_tree
DECL|function|create_entry
DECL|function|explanation
DECL|function|get_tree_descriptor
DECL|function|link_entry
DECL|function|merge_trees
DECL|function|origin
DECL|function|resolve
DECL|function|result
DECL|function|same_entry
DECL|function|show_diff
DECL|function|show_outf
DECL|function|show_result
DECL|function|show_result_list
DECL|function|threeway_callback
DECL|function|traverse_path
DECL|function|unresolved
DECL|function|unresolved_directory
DECL|macro|ENTRY_SHA1
DECL|macro|ENTRY_SHA1
DECL|member|blob
DECL|member|link
DECL|member|mode
DECL|member|next
DECL|member|path
DECL|member|stage
DECL|struct|merge_list
DECL|variable|merge_result
DECL|variable|merge_result_end
DECL|variable|merge_tree_usage
