DECL|function|add_strategies
DECL|function|append_strategy
DECL|function|checkout_fast_forward
DECL|function|cmd_merge
DECL|function|count_diff_files
DECL|function|count_unmerged_entries
DECL|function|drop_save
DECL|function|evaluate_result
DECL|function|finish
DECL|function|finish_automerge
DECL|function|finish_up_to_date
DECL|function|get_strategy
DECL|function|git_merge_config
DECL|function|is_old_style_invocation
DECL|function|merge_argument
DECL|function|merge_name
DECL|function|merge_trivial
DECL|function|option_parse_message
DECL|function|option_parse_n
DECL|function|option_parse_strategy
DECL|function|option_parse_x
DECL|function|parse_branch_merge_options
DECL|function|read_empty
DECL|function|read_merge_msg
DECL|function|read_tree_trivial
DECL|function|reset_hard
DECL|function|restore_state
DECL|function|run_prepare_commit_msg
DECL|function|save_state
DECL|function|setup_with_upstream
DECL|function|split_merge_strategies
DECL|function|squash_message
DECL|function|suggest_conflicts
DECL|function|try_merge_command
DECL|function|try_merge_strategy
DECL|function|write_merge_msg
DECL|function|write_tree_trivial
DECL|macro|DEFAULT_OCTOPUS
DECL|macro|DEFAULT_TWOHEAD
DECL|macro|NO_FAST_FORWARD
DECL|macro|NO_TRIVIAL
DECL|member|attr
DECL|member|name
DECL|struct|strategy
DECL|variable|abort_current_merge
DECL|variable|all_strategy
DECL|variable|allow_fast_forward
DECL|variable|allow_rerere_auto
DECL|variable|allow_trivial
DECL|variable|branch
DECL|variable|branch_mergeoptions
DECL|variable|builtin_merge_options
DECL|variable|builtin_merge_usage
DECL|variable|default_to_upstream
DECL|variable|fast_forward_only
DECL|variable|have_message
DECL|variable|merge_msg
DECL|variable|option_commit
DECL|variable|option_renormalize
DECL|variable|pull_octopus
DECL|variable|pull_twohead
DECL|variable|remoteheads
DECL|variable|shortlog_len
DECL|variable|show_diffstat
DECL|variable|show_progress
DECL|variable|squash
DECL|variable|use_strategies
DECL|variable|use_strategies_alloc
DECL|variable|use_strategies_nr
DECL|variable|verbosity
DECL|variable|xopts
DECL|variable|xopts_alloc
DECL|variable|xopts_nr
