DECL|function|cmd_merge_base
DECL|function|get_commit_reference
DECL|function|handle_independent
DECL|function|handle_is_ancestor
DECL|function|handle_octopus
DECL|function|show_merge_base
DECL|variable|merge_base_usage
