DECL|function|cmd_name_rev
DECL|function|get_rev_name
DECL|function|name_ref
DECL|function|name_rev
DECL|function|name_rev_line
DECL|function|show_name
DECL|macro|CUTOFF_DATE_SLOP
DECL|macro|MERGE_TRAVERSAL_WEIGHT
DECL|macro|ishex
DECL|member|distance
DECL|member|generation
DECL|member|name_only
DECL|member|ref_filter
DECL|member|tags_only
DECL|member|tip_name
DECL|struct|name_ref_data
DECL|struct|rev_name
DECL|typedef|rev_name
DECL|variable|cutoff
DECL|variable|name_rev_usage
