DECL|function|add_to_tip_table
DECL|function|cmd_name_rev
DECL|function|get_exact_ref_match
DECL|function|get_rev_name
DECL|function|name_ref
DECL|function|name_ref_abbrev
DECL|function|name_rev
DECL|function|name_rev_line
DECL|function|nth_tip_table_ent
DECL|function|show_name
DECL|function|subpath_matches
DECL|function|tipcmp
DECL|macro|CUTOFF_DATE_SLOP
DECL|macro|MERGE_TRAVERSAL_WEIGHT
DECL|macro|ishex
DECL|member|alloc
DECL|member|distance
DECL|member|generation
DECL|member|name_only
DECL|member|nr
DECL|member|ref_filter
DECL|member|refname
DECL|member|sha1
DECL|member|sorted
DECL|member|table
DECL|member|tags_only
DECL|member|tip_name
DECL|struct|name_ref_data
DECL|struct|rev_name
DECL|struct|tip_table
DECL|struct|tip_table_entry
DECL|typedef|rev_name
DECL|variable|cutoff
DECL|variable|name_rev_usage
DECL|variable|tip_table
