DECL|function|add
DECL|function|append_edit
DECL|function|cmd_notes
DECL|function|commit_notes
DECL|function|copy
DECL|function|copy_note_for_rewrite
DECL|function|create_note
DECL|function|finish_copy_notes_for_rewrite
DECL|function|get_ref
DECL|function|init_copy_notes_for_rewrite
DECL|function|init_notes_check
DECL|function|list
DECL|function|list_each_note
DECL|function|merge
DECL|function|merge_abort
DECL|function|merge_commit
DECL|function|notes_copy_from_stdin
DECL|function|notes_rewrite_config
DECL|function|parse_combine_notes_fn
DECL|function|parse_file_arg
DECL|function|parse_msg_arg
DECL|function|parse_reedit_arg
DECL|function|parse_reuse_arg
DECL|function|prune
DECL|function|remove_cmd
DECL|function|remove_one_note
DECL|function|show
DECL|function|write_commented_object
DECL|function|write_note_data
DECL|macro|MISSING_OK
DECL|member|buf
DECL|member|given
DECL|member|use_editor
DECL|struct|msg_arg
DECL|variable|git_notes_add_usage
DECL|variable|git_notes_append_usage
DECL|variable|git_notes_copy_usage
DECL|variable|git_notes_edit_usage
DECL|variable|git_notes_get_ref_usage
DECL|variable|git_notes_list_usage
DECL|variable|git_notes_merge_usage
DECL|variable|git_notes_prune_usage
DECL|variable|git_notes_remove_usage
DECL|variable|git_notes_show_usage
DECL|variable|git_notes_usage
DECL|variable|note_template
