DECL|function|add
DECL|function|append_edit
DECL|function|cmd_notes
DECL|function|copy
DECL|function|copy_obj_to_fd
DECL|function|free_note_data
DECL|function|get_ref
DECL|function|init_notes_check
DECL|function|list
DECL|function|list_each_note
DECL|function|merge
DECL|function|merge_abort
DECL|function|merge_commit
DECL|function|notes_copy_from_stdin
DECL|function|parse_file_arg
DECL|function|parse_msg_arg
DECL|function|parse_reedit_arg
DECL|function|parse_reuse_arg
DECL|function|prepare_note_data
DECL|function|prune
DECL|function|remove_cmd
DECL|function|remove_one_note
DECL|function|show
DECL|function|write_commented_object
DECL|function|write_note_data
DECL|macro|IGNORE_MISSING
DECL|member|buf
DECL|member|edit_path
DECL|member|given
DECL|member|use_editor
DECL|struct|note_data
DECL|variable|git_notes_add_usage
DECL|variable|git_notes_append_usage
DECL|variable|git_notes_copy_usage
DECL|variable|git_notes_edit_usage
DECL|variable|git_notes_get_ref_usage
DECL|variable|git_notes_list_usage
DECL|variable|git_notes_merge_usage
DECL|variable|git_notes_prune_usage
DECL|variable|git_notes_remove_usage
DECL|variable|git_notes_show_usage
DECL|variable|git_notes_usage
DECL|variable|note_template
