DECL|enumerator|WRITE_ONE_BREAK
DECL|enumerator|WRITE_ONE_RECURSIVE
DECL|enumerator|WRITE_ONE_SKIP
DECL|enumerator|WRITE_ONE_WRITTEN
DECL|enum|write_one_status
DECL|function|add_descendants_to_write_order
DECL|function|add_family_to_write_order
DECL|function|add_object_entry
DECL|function|add_object_entry_from_bitmap
DECL|function|add_objects_in_unpacked_packs
DECL|function|add_pbase_object
DECL|function|add_preferred_base
DECL|function|add_preferred_base_object
DECL|function|add_ref_tag
DECL|function|add_to_write_order
DECL|function|check_delta_limit
DECL|function|check_object
DECL|function|check_pack_inflate
DECL|function|check_pbase_path
DECL|function|cleanup_preferred_base
DECL|function|cleanup_threaded_search
DECL|function|cmd_pack_objects
DECL|function|compute_write_order
DECL|function|copy_pack_data
DECL|function|create_object_entry
DECL|function|delta_cacheable
DECL|function|do_compress
DECL|function|done_pbase_path_pos
DECL|function|find_deltas
DECL|function|free_unpacked
DECL|function|get_delta
DECL|function|get_object_details
DECL|function|get_object_list
DECL|function|get_object_list_from_bitmap
DECL|function|git_pack_config
DECL|function|has_sha1_pack_kept_or_nonlocal
DECL|function|have_duplicate_entry
DECL|function|index_commit_for_bitmap
DECL|function|init_threaded_search
DECL|function|ll_find_deltas
DECL|function|loosen_unused_packed_objects
DECL|function|loosened_object_can_be_discarded
DECL|function|mark_in_pack_object
DECL|function|mark_tagged
DECL|function|name_cmp_len
DECL|function|no_try_delta
DECL|function|ofscmp
DECL|function|option_parse_index_version
DECL|function|option_parse_ulong
DECL|function|option_parse_unpack_unreachable
DECL|function|pack_offset_sort
DECL|function|pack_options_allow_reuse
DECL|function|pbase_tree_cache_ix
DECL|function|pbase_tree_cache_ix_incr
DECL|function|pbase_tree_get
DECL|function|pbase_tree_put
DECL|function|prepare_pack
DECL|function|read_object_list_from_stdin
DECL|function|record_recent_commit
DECL|function|record_recent_object
DECL|function|setup_delta_attr_check
DECL|function|show_commit
DECL|function|show_edge
DECL|function|show_object
DECL|function|threaded_find_deltas
DECL|function|try_delta
DECL|function|try_to_free_from_threads
DECL|function|type_size_sort
DECL|function|want_object_in_pack
DECL|function|write_large_blob_data
DECL|function|write_no_reuse_object
DECL|function|write_object
DECL|function|write_one
DECL|function|write_pack_file
DECL|function|write_reuse_object
DECL|function|write_reused_pack
DECL|macro|OBJECT_ADDED
DECL|macro|OPT_ULONG
DECL|macro|cache_lock
DECL|macro|cache_lock
DECL|macro|cache_unlock
DECL|macro|cache_unlock
DECL|macro|ll_find_deltas
DECL|macro|progress_lock
DECL|macro|progress_lock
DECL|macro|progress_unlock
DECL|macro|progress_unlock
DECL|macro|read_lock
DECL|macro|read_lock
DECL|macro|read_unlock
DECL|macro|read_unlock
DECL|member|alloc
DECL|member|array
DECL|member|cond
DECL|member|data
DECL|member|data_ready
DECL|member|depth
DECL|member|depth
DECL|member|entry
DECL|member|index
DECL|member|list
DECL|member|list_size
DECL|member|mutex
DECL|member|next
DECL|member|nr
DECL|member|object
DECL|member|offset
DECL|member|pcache
DECL|member|processed
DECL|member|ref
DECL|member|remaining
DECL|member|sha1
DECL|member|temporary
DECL|member|thread
DECL|member|tree_data
DECL|member|tree_size
DECL|member|window
DECL|member|working
DECL|struct|in_pack
DECL|struct|in_pack_object
DECL|struct|pbase_tree
DECL|struct|pbase_tree_cache
DECL|struct|thread_params
DECL|struct|unpacked
DECL|variable|allow_ofs_delta
DECL|variable|base_name
DECL|variable|cache_max_small_delta_size
DECL|variable|cache_mutex
DECL|variable|delta_cache_size
DECL|variable|delta_search_threads
DECL|variable|depth
DECL|variable|done_pbase_paths
DECL|variable|done_pbase_paths_alloc
DECL|variable|done_pbase_paths_num
DECL|variable|ignore_packed_keep
DECL|variable|include_tag
DECL|variable|incremental
DECL|variable|indexed_commits
DECL|variable|indexed_commits_alloc
DECL|variable|indexed_commits_nr
DECL|variable|keep_unreachable
DECL|variable|local
DECL|variable|max_delta_cache_size
DECL|variable|no_closure_warning
DECL|variable|non_empty
DECL|variable|nr_result
DECL|variable|nr_written
DECL|variable|num_preferred_base
DECL|variable|old_try_to_free_routine
DECL|variable|pack_compression_level
DECL|variable|pack_compression_seen
DECL|variable|pack_idx_opts
DECL|variable|pack_size_limit
DECL|variable|pack_to_stdout
DECL|variable|pack_usage
DECL|variable|pbase_tree
DECL|variable|pbase_tree_cache
DECL|variable|progress
DECL|variable|progress_cond
DECL|variable|progress_mutex
DECL|variable|progress_state
DECL|variable|read_mutex
DECL|variable|recent_objects
DECL|variable|reuse_delta
DECL|variable|reuse_object
DECL|variable|reuse_packfile
DECL|variable|reuse_packfile_objects
DECL|variable|reuse_packfile_offset
DECL|variable|reused
DECL|variable|reused_delta
DECL|variable|to_pack
DECL|variable|unpack_unreachable
DECL|variable|unpack_unreachable_expiration
DECL|variable|use_bitmap_index
DECL|variable|window
DECL|variable|window_memory_limit
DECL|variable|write_bitmap_index
DECL|variable|write_bitmap_options
DECL|variable|written
DECL|variable|written_delta
DECL|variable|written_list
