DECL|function|add_pack
DECL|function|add_pack_file
DECL|function|cmd_pack_redundant
DECL|function|cmp_local_packs
DECL|function|cmp_two_packs
DECL|function|get_pack_redundancy
DECL|function|get_permutations
DECL|function|is_superset
DECL|function|llist_copy
DECL|function|llist_free
DECL|function|llist_init
DECL|function|llist_insert
DECL|function|llist_insert_back
DECL|function|llist_insert_sorted_unique
DECL|function|llist_item_get
DECL|function|llist_item_put
DECL|function|llist_sorted_difference_inplace
DECL|function|llist_sorted_remove
DECL|function|load_all
DECL|function|load_all_objects
DECL|function|minimize
DECL|function|pack_list_difference
DECL|function|pack_list_insert
DECL|function|pack_list_size
DECL|function|pack_set_bytecount
DECL|function|pll_free
DECL|function|scan_alt_odb_packs
DECL|function|sizeof_union
DECL|macro|BLKSIZE
DECL|member|all_objects
DECL|member|back
DECL|member|front
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|pack
DECL|member|pl
DECL|member|sha1
DECL|member|size
DECL|member|unique_objects
DECL|struct|llist
DECL|struct|llist_item
DECL|struct|pack_list
DECL|struct|pll
DECL|variable|all_objects
DECL|variable|alt_odb
DECL|variable|altodb_packs
DECL|variable|free_nodes
DECL|variable|load_all_packs
DECL|variable|local_packs
DECL|variable|pack_redundant_usage
DECL|variable|verbose
