DECL|function|cmd_prune
DECL|function|prune_dir
DECL|function|prune_object
DECL|function|prune_object_dir
DECL|function|prune_tmp_object
DECL|function|remove_temporary_files
DECL|variable|expire
DECL|variable|prune_usage
DECL|variable|show_only
DECL|variable|show_progress
DECL|variable|verbose
