DECL|function|argv_push_force
DECL|function|argv_push_verbosity
DECL|function|cmd_pull
DECL|function|config_get_ff
DECL|function|die_no_merge_candidates
DECL|function|get_merge_heads
DECL|function|get_only_remote
DECL|function|parse_repo_refspecs
DECL|function|run_fetch
DECL|function|run_merge
DECL|variable|opt_all
DECL|variable|opt_append
DECL|variable|opt_commit
DECL|variable|opt_depth
DECL|variable|opt_diffstat
DECL|variable|opt_dry_run
DECL|variable|opt_edit
DECL|variable|opt_ff
DECL|variable|opt_force
DECL|variable|opt_gpg_sign
DECL|variable|opt_keep
DECL|variable|opt_log
DECL|variable|opt_progress
DECL|variable|opt_prune
DECL|variable|opt_recurse_submodules
DECL|variable|opt_refmap
DECL|variable|opt_squash
DECL|variable|opt_strategies
DECL|variable|opt_strategy_opts
DECL|variable|opt_tags
DECL|variable|opt_unshallow
DECL|variable|opt_update_shallow
DECL|variable|opt_upload_pack
DECL|variable|opt_verbosity
DECL|variable|opt_verify_signatures
DECL|variable|pull_options
DECL|variable|pull_usage
