DECL|function|argv_push_verbosity
DECL|function|cmd_pull
DECL|function|parse_repo_refspecs
DECL|function|run_fetch
DECL|function|run_merge
DECL|variable|opt_progress
DECL|variable|opt_verbosity
DECL|variable|pull_options
DECL|variable|pull_usage
