DECL|function|add_refspec
DECL|function|cmd_push
DECL|function|do_push
DECL|function|option_parse_recurse_submodules
DECL|function|push_url_of_remote
DECL|function|push_with_options
DECL|function|set_refspecs
DECL|function|setup_default_push_refspecs
DECL|function|setup_push_upstream
DECL|variable|deleterefs
DECL|variable|progress
DECL|variable|push_usage
DECL|variable|receivepack
DECL|variable|refspec
DECL|variable|refspec_alloc
DECL|variable|refspec_nr
DECL|variable|thin
DECL|variable|verbosity
