DECL|enumerator|DENY_IGNORE
DECL|enumerator|DENY_REFUSE
DECL|enumerator|DENY_UNCONFIGURED
DECL|enumerator|DENY_WARN
DECL|enum|deny_action
DECL|function|check_aliased_update
DECL|function|check_aliased_updates
DECL|function|check_nonce
DECL|function|cmd_receive_pack
DECL|function|collect_one_alternate_ref
DECL|function|command_singleton_iterator
DECL|function|copy_to_sideband
DECL|function|delete_only
DECL|function|execute_commands
DECL|function|execute_commands_non_atomic
DECL|function|feed_receive_hook
DECL|function|find_header
DECL|function|hmac_sha1
DECL|function|is_ref_checked_out
DECL|function|iterate_receive_command_list
DECL|function|parse_deny_action
DECL|function|parse_pack_header
DECL|function|prepare_push_cert_nonce
DECL|function|prepare_push_cert_sha1
DECL|function|prepare_shallow_update
DECL|function|queue_command
DECL|function|queue_commands_from_cert
DECL|function|read_head_info
DECL|function|receive_pack_config
DECL|function|refuse_unconfigured_deny
DECL|function|refuse_unconfigured_deny_delete_current
DECL|function|reject_updates_to_hidden
DECL|function|report
DECL|function|report_message
DECL|function|rp_error
DECL|function|rp_warning
DECL|function|run_and_feed_hook
DECL|function|run_receive_hook
DECL|function|run_update_hook
DECL|function|run_update_post_hook
DECL|function|set_connectivity_errors
DECL|function|should_process_cmd
DECL|function|show_one_alternate_sha1
DECL|function|show_ref
DECL|function|show_ref_cb
DECL|function|unpack
DECL|function|unpack_with_sideband
DECL|function|update
DECL|function|update_shallow_info
DECL|function|update_shallow_ref
DECL|function|warn_if_skipped_connectivity_check
DECL|function|write_head_info
DECL|macro|HMAC_BLOCK_SIZE
DECL|member|buf
DECL|member|cmd
DECL|member|cmds
DECL|member|did_not_exist
DECL|member|error_string
DECL|member|index
DECL|member|new_sha1
DECL|member|next
DECL|member|old_sha1
DECL|member|ref_name
DECL|member|si
DECL|member|skip_broken
DECL|member|skip_update
DECL|struct|command
DECL|struct|iterate_data
DECL|struct|receive_hook_feed_state
DECL|typedef|feed_fn
DECL|variable|NONCE_BAD
DECL|variable|NONCE_MISSING
DECL|variable|NONCE_OK
DECL|variable|NONCE_SLOP
DECL|variable|NONCE_UNSOLICITED
DECL|variable|alt_shallow_file
DECL|variable|auto_gc
DECL|variable|auto_update_server_info
DECL|variable|cert_nonce_seed
DECL|variable|deny_current_branch
DECL|variable|deny_delete_current
DECL|variable|deny_deletes
DECL|variable|deny_non_fast_forwards
DECL|variable|fix_thin
DECL|variable|head_name
DECL|variable|head_name_to_free
DECL|variable|nonce_stamp_slop
DECL|variable|nonce_stamp_slop_limit
DECL|variable|nonce_status
DECL|variable|pack_lockfile
DECL|variable|prefer_ofs_delta
DECL|variable|push_cert
DECL|variable|push_cert_nonce
DECL|variable|push_cert_sha1
DECL|variable|quiet
DECL|variable|receive_fsck_objects
DECL|variable|receive_pack_usage
DECL|variable|receive_unpack_limit
DECL|variable|refuse_unconfigured_deny_delete_current_msg
DECL|variable|refuse_unconfigured_deny_msg
DECL|variable|report_status
DECL|variable|sent_capabilities
DECL|variable|service_dir
DECL|variable|shallow_update
DECL|variable|sigcheck
DECL|variable|stateless_rpc
DECL|variable|transaction
DECL|variable|transfer_fsck_objects
DECL|variable|transfer_unpack_limit
DECL|variable|unpack_limit
DECL|variable|use_sideband
