DECL|function|cmd_remote_ext
DECL|function|command_loop
DECL|function|parse_argv
DECL|function|run_child
DECL|function|send_git_request
DECL|function|strip_escapes
DECL|macro|MAXARGUMENTS
DECL|macro|MAXCOMMAND
DECL|variable|git_req
DECL|variable|git_req_vhost
