DECL|function|cmd_replace
DECL|function|delete_replace_ref
DECL|function|for_each_replace_name
DECL|function|list_replace_refs
DECL|function|replace_object
DECL|function|show_reference
DECL|typedef|each_replace_name_fn
DECL|variable|git_replace_usage
