DECL|enumerator|REPLACE_FORMAT_LONG
DECL|enumerator|REPLACE_FORMAT_MEDIUM
DECL|enumerator|REPLACE_FORMAT_SHORT
DECL|enum|replace_format
DECL|function|check_mergetags
DECL|function|check_one_mergetag
DECL|function|check_ref_valid
DECL|function|cmd_replace
DECL|function|create_graft
DECL|function|delete_replace_ref
DECL|function|edit_and_replace
DECL|function|export_object
DECL|function|for_each_replace_name
DECL|function|import_object
DECL|function|list_replace_refs
DECL|function|replace_object
DECL|function|replace_object_sha1
DECL|function|replace_parents
DECL|function|show_reference
DECL|member|argc
DECL|member|argv
DECL|member|format
DECL|member|pattern
DECL|struct|check_mergetag_data
DECL|struct|show_data
DECL|typedef|each_replace_name_fn
DECL|variable|git_replace_usage
