DECL|enumerator|REPLACE_FORMAT_LONG
DECL|enumerator|REPLACE_FORMAT_MEDIUM
DECL|enumerator|REPLACE_FORMAT_SHORT
DECL|enum|replace_format
DECL|function|cmd_replace
DECL|function|delete_replace_ref
DECL|function|for_each_replace_name
DECL|function|list_replace_refs
DECL|function|replace_object
DECL|function|show_reference
DECL|member|format
DECL|member|pattern
DECL|struct|show_data
DECL|typedef|each_replace_name_fn
DECL|variable|git_replace_usage
