DECL|enumerator|HARD
DECL|enumerator|KEEP
DECL|enumerator|MERGE
DECL|enumerator|MIXED
DECL|enumerator|NONE
DECL|enumerator|SOFT
DECL|enum|reset_type
DECL|function|cmd_reset
DECL|function|die_if_unmerged_cache
DECL|function|interactive_reset
DECL|function|is_merge
DECL|function|print_new_head_line
DECL|function|read_from_tree
DECL|function|reset_index_file
DECL|function|set_reflog_message
DECL|function|update_index_from_diff
DECL|function|update_index_refresh
DECL|variable|git_reset_usage
DECL|variable|reset_type_names
