DECL|function|cmd_rev_list
DECL|function|finish_commit
DECL|function|finish_object
DECL|function|print_var_int
DECL|function|print_var_str
DECL|function|show_bisect_vars
DECL|function|show_commit
DECL|function|show_edge
DECL|function|show_object
DECL|function|show_object_fast
DECL|variable|rev_list_usage
