DECL|function|cmd_rev_list
DECL|function|estimate_bisect_steps
DECL|function|exp2i
DECL|function|finish_commit
DECL|function|finish_object
DECL|function|log2i
DECL|function|print_commit_list
DECL|function|print_var_int
DECL|function|print_var_str
DECL|function|show_bisect_vars
DECL|function|show_commit
DECL|function|show_edge
DECL|function|show_object
DECL|variable|rev_list_usage
