DECL|enumerator|CHERRY_PICK
DECL|enumerator|REVERT
DECL|function|add_message_to_msg
DECL|function|add_to_msg
DECL|function|cmd_cherry_pick
DECL|function|cmd_revert
DECL|function|die_dirty_index
DECL|function|empty_tree
DECL|function|get_encoding
DECL|function|get_oneline
DECL|function|help_msg
DECL|function|parse_args
DECL|function|revert_or_cherry_pick
DECL|function|set_author_ident_env
DECL|macro|GIT_REFLOG_ACTION
DECL|variable|action
DECL|variable|allow_rerere_auto
DECL|variable|cherry_pick_usage
DECL|variable|commit
DECL|variable|commit_name
DECL|variable|edit
DECL|variable|mainline
DECL|variable|me
DECL|variable|msg_fd
DECL|variable|msg_file
DECL|variable|no_commit
DECL|variable|no_replay
DECL|variable|revert_usage
DECL|variable|signoff
