DECL|enumerator|CHERRY_PICK
DECL|enumerator|REVERT
DECL|enum|replay_action
DECL|function|action_name
DECL|function|cmd_cherry_pick
DECL|function|cmd_revert
DECL|function|die_dirty_index
DECL|function|do_pick_commit
DECL|function|do_recursive_merge
DECL|function|empty_tree
DECL|function|fast_forward_to
DECL|function|free_message
DECL|function|get_encoding
DECL|function|get_message
DECL|function|option_parse_x
DECL|function|parse_args
DECL|function|pick_commits
DECL|function|prepare_revs
DECL|function|print_advice
DECL|function|read_and_refresh_cache
DECL|function|revert_or_cherry_pick_usage
DECL|function|run_git_commit
DECL|function|write_cherry_pick_head
DECL|function|write_message
DECL|macro|GIT_REFLOG_ACTION
DECL|member|action
DECL|member|allow_ff
DECL|member|allow_rerere_auto
DECL|member|commit_argc
DECL|member|commit_argv
DECL|member|edit
DECL|member|label
DECL|member|mainline
DECL|member|message
DECL|member|no_commit
DECL|member|parent_label
DECL|member|record_origin
DECL|member|reencoded_message
DECL|member|signoff
DECL|member|strategy
DECL|member|subject
DECL|member|xopts
DECL|member|xopts_alloc
DECL|member|xopts_nr
DECL|struct|commit_message
DECL|struct|replay_opts
DECL|variable|cherry_pick_usage
DECL|variable|revert_usage
