DECL|enumerator|CHERRY_PICK
DECL|enumerator|REVERT
DECL|function|add_message_to_msg
DECL|function|advise
DECL|function|cmd_cherry_pick
DECL|function|cmd_revert
DECL|function|die_dirty_index
DECL|function|do_pick_commit
DECL|function|do_recursive_merge
DECL|function|empty_tree
DECL|function|fast_forward_to
DECL|function|free_message
DECL|function|get_encoding
DECL|function|get_message
DECL|function|help_msg
DECL|function|parse_args
DECL|function|prepare_revs
DECL|function|revert_or_cherry_pick
DECL|function|revert_or_cherry_pick_usage
DECL|function|run_git_commit
DECL|function|set_author_ident_env
DECL|function|write_message
DECL|macro|GIT_REFLOG_ACTION
DECL|member|label
DECL|member|message
DECL|member|parent_label
DECL|member|reencoded_message
DECL|member|subject
DECL|struct|commit_message
DECL|variable|action
DECL|variable|allow_ff
DECL|variable|allow_rerere_auto
DECL|variable|cherry_pick_usage
DECL|variable|commit
DECL|variable|commit_argc
DECL|variable|commit_argv
DECL|variable|edit
DECL|variable|mainline
DECL|variable|me
DECL|variable|no_commit
DECL|variable|no_replay
DECL|variable|revert_usage
DECL|variable|signoff
DECL|variable|strategy
