DECL|function|check_local_mod
DECL|function|check_submodules_use_gitfiles
DECL|function|cmd_rm
DECL|function|error_removing_concrete_submodules
DECL|function|get_ours_cache_pos
DECL|function|print_error_files
DECL|member|alloc
DECL|member|entry
DECL|member|is_submodule
DECL|member|name
DECL|member|nr
DECL|variable|builtin_rm_options
DECL|variable|builtin_rm_usage
DECL|variable|force
DECL|variable|ignore_unmatch
DECL|variable|index_only
DECL|variable|list
DECL|variable|lock_file
DECL|variable|quiet
DECL|variable|recursive
DECL|variable|show_only
