DECL|function|add_existing
DECL|function|cmd_show_ref
DECL|function|exclude_existing
DECL|function|exclude_existing_callback
DECL|function|hash_callback
DECL|function|help_callback
DECL|function|show_one
DECL|function|show_ref
DECL|variable|abbrev
DECL|variable|deref_tags
DECL|variable|exclude_arg
DECL|variable|exclude_existing_arg
DECL|variable|found_match
DECL|variable|hash_only
DECL|variable|heads_only
DECL|variable|pattern
DECL|variable|quiet
DECL|variable|show_head
DECL|variable|show_ref_options
DECL|variable|show_ref_usage
DECL|variable|tags_only
DECL|variable|verify
