DECL|function|cmd_submodule__helper
DECL|function|module_list
DECL|function|module_list_compute
DECL|function|module_name
DECL|macro|MODULE_LIST_INIT
DECL|member|alloc
DECL|member|cmd
DECL|member|entries
DECL|member|fn
DECL|member|nr
DECL|struct|cmd_struct
DECL|struct|module_list
DECL|variable|commands
