DECL|enumerator|CLEANUP_ALL
DECL|enumerator|CLEANUP_NONE
DECL|enumerator|CLEANUP_SPACE
DECL|function|build_tag_object
DECL|function|cmd_tag
DECL|function|create_tag
DECL|function|delete_tag
DECL|function|do_sign
DECL|function|for_each_tag_name
DECL|function|git_tag_config
DECL|function|list_tags
DECL|function|parse_msg_arg
DECL|function|parse_sorting_string
DECL|function|strbuf_check_tag_ref
DECL|function|verify_tag
DECL|function|write_tag_body
DECL|member|buf
DECL|member|cleanup_mode
DECL|member|given
DECL|member|message_given
DECL|member|sign
DECL|struct|create_tag_options
DECL|struct|msg_arg
DECL|typedef|each_tag_name_fn
DECL|variable|colopts
DECL|variable|git_tag_usage
DECL|variable|tag_template
DECL|variable|tag_template_nocleanup
