DECL|function|cmd_update_ref
DECL|function|parse_arg
DECL|function|parse_cmd_create
DECL|function|parse_cmd_delete
DECL|function|parse_cmd_option
DECL|function|parse_cmd_update
DECL|function|parse_cmd_verify
DECL|function|parse_next_arg
DECL|function|parse_refname
DECL|function|update_alloc
DECL|function|update_refs_stdin
DECL|function|update_store_new_sha1
DECL|function|update_store_old_sha1
DECL|variable|git_update_ref_usage
DECL|variable|line_termination
DECL|variable|update_flags
DECL|variable|updates
DECL|variable|updates_alloc
DECL|variable|updates_count
