DECL|function|add_cacheinfo
DECL|function|add_one_path
DECL|function|cacheinfo_callback
DECL|function|chmod_callback
DECL|function|chmod_path
DECL|function|cmd_update_index
DECL|function|do_reupdate
DECL|function|do_unresolve
DECL|function|mark_ce_flags
DECL|function|process_directory
DECL|function|process_lstat_error
DECL|function|process_path
DECL|function|read_head_pointers
DECL|function|read_index_info
DECL|function|read_one_ent
DECL|function|really_refresh_callback
DECL|function|refresh
DECL|function|refresh_callback
DECL|function|remove_one_path
DECL|function|report
DECL|function|resolve_undo_clear_callback
DECL|function|reupdate_callback
DECL|function|stdin_cacheinfo_callback
DECL|function|stdin_callback
DECL|function|unresolve_callback
DECL|function|unresolve_one
DECL|function|update_one
DECL|macro|MARK_FLAG
DECL|macro|UNMARK_FLAG
DECL|member|flags
DECL|member|has_errors
DECL|struct|refresh_params
DECL|variable|allow_add
DECL|variable|allow_remove
DECL|variable|allow_replace
DECL|variable|force_remove
DECL|variable|head_sha1
DECL|variable|info_only
DECL|variable|mark_skip_worktree_only
DECL|variable|mark_valid_only
DECL|variable|merge_head_sha1
DECL|variable|update_index_usage
DECL|variable|verbose
