DECL|function|add
DECL|function|add_worktree
DECL|function|cmd_worktree
DECL|function|list
DECL|function|measure_widths
DECL|function|prune
DECL|function|prune_worktree
DECL|function|prune_worktrees
DECL|function|remove_junk
DECL|function|remove_junk_on_signal
DECL|function|show_worktree
DECL|function|show_worktree_porcelain
DECL|function|worktree_basename
DECL|member|detach
DECL|member|force
DECL|member|force_new_branch
DECL|member|new_branch
DECL|struct|add_opts
DECL|variable|expire
DECL|variable|is_junk
DECL|variable|junk_git_dir
DECL|variable|junk_pid
DECL|variable|junk_work_tree
DECL|variable|show_only
DECL|variable|verbose
DECL|variable|worktree_usage
