DECL|macro|EXTSPEC
DECL|macro|EXTSPEC
DECL|macro|MALLOCATTR
DECL|macro|MALLOCATTR
DECL|macro|MALLOCATTR
DECL|macro|MALLOCATTR
DECL|macro|NEDMALLOC_H
DECL|macro|NO_MALLINFO
DECL|macro|THROWSPEC
DECL|macro|nedblksize
DECL|macro|nedcalloc
DECL|macro|nedfree
DECL|macro|nedindependent_calloc
DECL|macro|nedindependent_comalloc
DECL|macro|nedmallinfo
DECL|macro|nedmalloc
DECL|macro|nedmalloc_footprint
DECL|macro|nedmalloc_stats
DECL|macro|nedmalloc_trim
DECL|macro|nedmallopt
DECL|macro|nedmemalign
DECL|macro|nedrealloc
