DECL|function|xdl_add_change
DECL|function|xdl_build_script
DECL|function|xdl_call_hunk_func
DECL|function|xdl_change_compact
DECL|function|xdl_diff
DECL|function|xdl_do_diff
DECL|function|xdl_free_script
DECL|function|xdl_recs_cmp
DECL|function|xdl_split
DECL|macro|XDL_HEUR_MIN_COST
DECL|macro|XDL_K_HEUR
DECL|macro|XDL_LINE_MAX
DECL|macro|XDL_MAX_COST_MIN
DECL|macro|XDL_SNAKE_CNT
DECL|member|i1
DECL|member|i2
DECL|member|min_hi
DECL|member|min_lo
DECL|struct|s_xdpsplit
DECL|typedef|xdpsplit_t
