DECL|macro|XDIFFI_H
DECL|member|chg1
DECL|member|chg2
DECL|member|ha
DECL|member|heur_min
DECL|member|i1
DECL|member|i2
DECL|member|mxcost
DECL|member|next
DECL|member|nrec
DECL|member|rchg
DECL|member|rindex
DECL|member|snake_cnt
DECL|struct|s_diffdata
DECL|struct|s_xdalgoenv
DECL|struct|s_xdchange
DECL|typedef|diffdata_t
DECL|typedef|xdalgoenv_t
DECL|typedef|xdchange_t
