DECL|macro|XDF_IGNORE_WHITESPACE
DECL|macro|XDF_IGNORE_WHITESPACE_AT_EOL
DECL|macro|XDF_IGNORE_WHITESPACE_CHANGE
DECL|macro|XDF_NEED_MINIMAL
DECL|macro|XDF_WHITESPACE_FLAGS
DECL|macro|XDIFF_H
DECL|macro|XDL_BDOP_CPY
DECL|macro|XDL_BDOP_INS
DECL|macro|XDL_BDOP_INSB
DECL|macro|XDL_EMIT_COMMON
DECL|macro|XDL_EMIT_FUNCNAMES
DECL|macro|XDL_MERGE_EAGER
DECL|macro|XDL_MERGE_MINIMAL
DECL|macro|XDL_MERGE_ZEALOUS
DECL|macro|XDL_MERGE_ZEALOUS_ALNUM
DECL|macro|XDL_MMB_READONLY
DECL|macro|XDL_MMF_ATOMIC
DECL|macro|XDL_PATCH_IGNOREBSPACE
DECL|macro|XDL_PATCH_MODEMASK
DECL|macro|XDL_PATCH_NORMAL
DECL|macro|XDL_PATCH_REVERSE
DECL|macro|xdl_free
DECL|macro|xdl_malloc
DECL|macro|xdl_realloc
DECL|member|bsize
DECL|member|ctxlen
DECL|member|find_func
DECL|member|find_func_priv
DECL|member|flags
DECL|member|flags
DECL|member|outf
DECL|member|priv
DECL|member|ptr
DECL|member|ptr
DECL|member|size
DECL|member|size
DECL|struct|s_bdiffparam
DECL|struct|s_mmbuffer
DECL|struct|s_mmfile
DECL|struct|s_xdemitcb
DECL|struct|s_xdemitconf
DECL|struct|s_xpparam
DECL|typedef|bdiffparam_t
DECL|typedef|find_func_t
DECL|typedef|mmbuffer_t
DECL|typedef|mmfile_t
DECL|typedef|xdemitcb_t
DECL|typedef|xdemitconf_t
DECL|typedef|xpparam_t
