DECL|function|def_ff
DECL|function|get_func_line
DECL|function|xdl_emit_common
DECL|function|xdl_emit_diff
DECL|function|xdl_emit_record
DECL|function|xdl_get_hunk
DECL|function|xdl_get_rec
DECL|member|buf
DECL|member|len
DECL|struct|func_line
