DECL|function|cmp_recs
DECL|function|fall_back_to_classic_diff
DECL|function|find_lcs
DECL|function|histogram_diff
DECL|function|reduce_common_start_end
DECL|function|scanA
DECL|function|try_lcs
DECL|function|xdl_do_histogram_diff
DECL|macro|CMP
DECL|macro|CMP_ENV
DECL|macro|CNT
DECL|macro|LINE_END
DECL|macro|LINE_END_PTR
DECL|macro|LINE_MAP
DECL|macro|MAX_CNT
DECL|macro|MAX_PTR
DECL|macro|NEXT_PTR
DECL|macro|REC
DECL|macro|TABLE_HASH
DECL|member|begin1
DECL|member|begin2
DECL|member|cnt
DECL|member|cnt
DECL|member|end1
DECL|member|end2
DECL|member|env
DECL|member|has_common
DECL|member|key_shift
DECL|member|line_map
DECL|member|line_map_size
DECL|member|max_chain_length
DECL|member|next
DECL|member|next_ptrs
DECL|member|ptr
DECL|member|ptr_shift
DECL|member|rcha
DECL|member|records
DECL|member|records_size
DECL|member|table_bits
DECL|member|xpp
DECL|struct|histindex
DECL|struct|record
DECL|struct|region
