DECL|function|binary_search
DECL|function|fall_back_to_classic_diff
DECL|function|fill_hashmap
DECL|function|find_longest_common_sequence
DECL|function|insert_record
DECL|function|match
DECL|function|patience_diff
DECL|function|walk_common_sequence
DECL|function|xdl_do_patience_diff
DECL|macro|NON_UNIQUE
DECL|member|alloc
DECL|member|entries
DECL|member|env
DECL|member|file1
DECL|member|file2
DECL|member|first
DECL|member|has_matches
DECL|member|hash
DECL|member|last
DECL|member|line1
DECL|member|line2
DECL|member|next
DECL|member|nr
DECL|member|previous
DECL|member|xpp
DECL|struct|entry
DECL|struct|hashmap
