DECL|function|xdl_classify_record
DECL|function|xdl_clean_mmatch
DECL|function|xdl_cleanup_records
DECL|function|xdl_free_classifier
DECL|function|xdl_free_ctx
DECL|function|xdl_free_env
DECL|function|xdl_init_classifier
DECL|function|xdl_optimize_ctxs
DECL|function|xdl_prepare_ctx
DECL|function|xdl_prepare_env
DECL|function|xdl_trim_ends
DECL|macro|XDL_GUESS_NLINES1
DECL|macro|XDL_GUESS_NLINES2
DECL|macro|XDL_KPDIS_RUN
DECL|macro|XDL_MAX_EQLIMIT
DECL|macro|XDL_SIMSCAN_WINDOW
DECL|member|alloc
DECL|member|count
DECL|member|flags
DECL|member|ha
DECL|member|hbits
DECL|member|hsize
DECL|member|idx
DECL|member|len1
DECL|member|len2
DECL|member|line
DECL|member|ncha
DECL|member|next
DECL|member|rchash
DECL|member|rcrecs
DECL|member|size
DECL|struct|s_xdlclass
DECL|struct|s_xdlclassifier
DECL|typedef|xdlclass_t
DECL|typedef|xdlclassifier_t
