DECL|macro|XTYPES_H
DECL|member|ancur
DECL|member|dend
DECL|member|dstart
DECL|member|ha
DECL|member|ha
DECL|member|hbits
DECL|member|head
DECL|member|icurr
DECL|member|isize
DECL|member|next
DECL|member|next
DECL|member|nrec
DECL|member|nreff
DECL|member|nsize
DECL|member|ptr
DECL|member|rcha
DECL|member|rchg
DECL|member|recs
DECL|member|rhash
DECL|member|rindex
DECL|member|scurr
DECL|member|size
DECL|member|sncur
DECL|member|tail
DECL|member|xdf1
DECL|member|xdf2
DECL|struct|s_chanode
DECL|struct|s_chastore
DECL|struct|s_xdfenv
DECL|struct|s_xdfile
DECL|struct|s_xrecord
DECL|typedef|chanode_t
DECL|typedef|chastore_t
DECL|typedef|xdfenv_t
DECL|typedef|xdfile_t
DECL|typedef|xrecord_t
