DECL|function|analyze
DECL|function|btowc
DECL|function|build_charclass
DECL|function|build_charclass_op
DECL|function|build_collating_symbol
DECL|function|build_equiv_class
DECL|function|build_range_exp
DECL|function|calc_eclosure
DECL|function|calc_eclosure_iter
DECL|function|calc_first
DECL|function|calc_inveclosure
DECL|function|calc_next
DECL|function|create_initial_state
DECL|function|create_token_tree
DECL|function|create_tree
DECL|function|duplicate_node
DECL|function|duplicate_node_closure
DECL|function|duplicate_tree
DECL|function|fetch_number
DECL|function|fetch_token
DECL|function|free_charset
DECL|function|free_dfa_content
DECL|function|free_token
DECL|function|free_tree
DECL|function|free_workarea_compile
DECL|function|init_dfa
DECL|function|init_word_char
DECL|function|libc_freeres_fn
DECL|function|link_nfa_nodes
DECL|function|lower_subexp
DECL|function|lower_subexps
DECL|function|mark_opt_subexp
DECL|function|optimize_subexps
DECL|function|optimize_utf8
DECL|function|parse
DECL|function|parse_bracket_element
DECL|function|parse_bracket_exp
DECL|function|parse_bracket_symbol
DECL|function|parse_branch
DECL|function|parse_dup_op
DECL|function|parse_expression
DECL|function|parse_reg_exp
DECL|function|parse_sub_exp
DECL|function|peek_token
DECL|function|peek_token_bracket
DECL|function|postorder
DECL|function|preorder
DECL|function|re_comp
DECL|function|re_compile_fastmap_iter
DECL|function|re_compile_internal
DECL|function|re_compile_pattern
DECL|function|re_set_fastmap
DECL|function|regcomp
DECL|function|regfree
DECL|function|search_duplicated_node
DECL|function|weak_alias
DECL|function|weak_alias
DECL|function|weak_alias
DECL|macro|BRACKET_NAME_BUF_SIZE
DECL|macro|BUILD_CHARCLASS_LOOP
DECL|macro|REG_BADBR_IDX
DECL|macro|REG_BADPAT_IDX
DECL|macro|REG_BADRPT_IDX
DECL|macro|REG_EBRACE_IDX
DECL|macro|REG_EBRACK_IDX
DECL|macro|REG_ECOLLATE_IDX
DECL|macro|REG_ECTYPE_IDX
DECL|macro|REG_EEND_IDX
DECL|macro|REG_EESCAPE_IDX
DECL|macro|REG_EPAREN_IDX
DECL|macro|REG_ERANGE_IDX
DECL|macro|REG_ERPAREN_IDX
DECL|macro|REG_ESIZE_IDX
DECL|macro|REG_ESPACE_IDX
DECL|macro|REG_ESUBREG_IDX
DECL|macro|REG_NOERROR_IDX
DECL|macro|REG_NOMATCH_IDX
DECL|variable|attribute_hidden
DECL|variable|attribute_hidden
DECL|variable|re_comp_buf
DECL|variable|utf8_sb_map
