DECL|macro|alloca
DECL|macro|alloca
DECL|macro|bool
DECL|macro|false
DECL|macro|re_compile_fastmap
DECL|macro|re_compile_pattern
DECL|macro|re_match
DECL|macro|re_match_2
DECL|macro|re_search
DECL|macro|re_search_2
DECL|macro|re_set_registers
DECL|macro|re_set_syntax
DECL|macro|regcomp
DECL|macro|regerror
DECL|macro|regexec
DECL|macro|regfree
DECL|macro|true
DECL|variable|re_max_failures
