DECL|function|add_empty_word
DECL|function|add_empty_words
DECL|function|add_literal
DECL|function|buffer_grow
DECL|function|buffer_push
DECL|function|buffer_push_rlw
DECL|function|ewah_add
DECL|function|ewah_add_dirty_words
DECL|function|ewah_add_empty_words
DECL|function|ewah_and
DECL|function|ewah_and_not
DECL|function|ewah_checksum
DECL|function|ewah_clear
DECL|function|ewah_each_bit
DECL|function|ewah_free
DECL|function|ewah_iterator_init
DECL|function|ewah_iterator_next
DECL|function|ewah_new
DECL|function|ewah_not
DECL|function|ewah_or
DECL|function|ewah_pool_free
DECL|function|ewah_pool_new
DECL|function|ewah_set
DECL|function|ewah_xor
DECL|function|max_size
DECL|function|min_size
DECL|function|read_new_rlw
DECL|macro|BITMAP_POOL_MAX
DECL|variable|bitmap_pool
DECL|variable|bitmap_pool_size
