DECL|function|rlw_get_literal_words
DECL|function|rlw_get_run_bit
DECL|function|rlw_get_running_len
DECL|function|rlw_set_literal_words
DECL|function|rlw_set_run_bit
DECL|function|rlw_set_running_len
DECL|function|rlw_size
DECL|function|rlw_xor_run_bit
DECL|function|rlwit_literal_words
DECL|function|rlwit_word_size
DECL|macro|RLW_LARGEST_LITERAL_COUNT
DECL|macro|RLW_LARGEST_RUNNING_COUNT
DECL|macro|RLW_LARGEST_RUNNING_COUNT_SHIFT
DECL|macro|RLW_LITERAL_BITS
DECL|macro|RLW_RUNNING_BITS
DECL|macro|RLW_RUNNING_LEN_PLUS_BIT
DECL|macro|__EWOK_RLW_H__
DECL|member|buffer
DECL|member|literal_word_offset
DECL|member|literal_word_start
DECL|member|literal_words
DECL|member|pointer
DECL|member|rlw
DECL|member|running_bit
DECL|member|running_len
DECL|member|size
DECL|member|word
DECL|struct|rlw_iterator
