DECL|function|ewah_bit_ctz64
DECL|function|ewah_bit_popcount64
DECL|macro|BITS_IN_WORD
DECL|macro|__EWOK_BITMAP_H__
DECL|macro|ewah_bit_ctz64
DECL|macro|ewah_calloc
DECL|macro|ewah_malloc
DECL|macro|ewah_realloc
DECL|member|alloc_size
DECL|member|b
DECL|member|bit_size
DECL|member|buffer
DECL|member|buffer
DECL|member|buffer_size
DECL|member|buffer_size
DECL|member|compressed
DECL|member|literals
DECL|member|lw
DECL|member|pointer
DECL|member|rl
DECL|member|rlw
DECL|member|word_alloc
DECL|member|words
DECL|struct|bitmap
DECL|struct|ewah_bitmap
DECL|struct|ewah_iterator
DECL|typedef|ewah_callback
DECL|typedef|eword_t
