DECL|enumerator|FilePipeLocalInformation
DECL|enum|_FILE_INFORMATION_CLASS
DECL|function|IsSocketHandle
DECL|function|compute_revents
DECL|function|poll
DECL|function|win32_compute_revents
DECL|function|win32_compute_revents_socket
DECL|macro|INFTIM
DECL|macro|IsConsoleHandle
DECL|macro|MSG_PEEK
DECL|macro|PIPE_BUF
DECL|macro|WIN32_NATIVE
DECL|macro|_WIN32_WINNT
DECL|member|CurrentInstances
DECL|member|InboundQuota
DECL|member|Information
DECL|member|MaximumInstances
DECL|member|NamedPipeConfiguration
DECL|member|NamedPipeEnd
DECL|member|NamedPipeState
DECL|member|NamedPipeType
DECL|member|OutboundQuota
DECL|member|Pointer
DECL|member|ReadDataAvailable
DECL|member|Status
DECL|member|WriteQuotaAvailable
DECL|member|u
DECL|struct|_FILE_PIPE_LOCAL_INFORMATION
DECL|struct|_IO_STATUS_BLOCK
DECL|typedef|FILE_INFORMATION_CLASS
DECL|typedef|FILE_PIPE_LOCAL_INFORMATION
DECL|typedef|IO_STATUS_BLOCK
DECL|typedef|PFILE_INFORMATION_CLASS
DECL|typedef|PFILE_PIPE_LOCAL_INFORMATION
DECL|typedef|PIO_STATUS_BLOCK
DECL|typedef|PNtQueryInformationFile
